### ISSUE TITLE
Stops working when authentication servers have a hiccup

### ISSUE THREAD

**Issue by DennisGarvey** [mrlt8/docker-wyze-bridge#10]
`2021/07/05 11:10:43 [cam] requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://auth-prod.api.wyze.com/user/login`
It would be nice if it auto-retries every certain amount of time. So I wouldn't have to restart the container.

**Comment by mrlt8** [comment]
should be fixed now.
