### ISSUE TITLE
wyze-bridge don't start in portainer

### ISSUE THREAD

**Issue by CzechSebastian** [mrlt8/docker-wyze-bridge#100]
Hi , 
I use Home assistant with portainer and my stack don't start
![image](https://user-images.githubusercontent.com/46093860/131707299-907acb71-5d92-4792-a2bc-fce994c4f846.png)

So this is my code in the stack 

And this is what I have in logs

![image](https://user-images.githubusercontent.com/46093860/131707120-51d577a2-3dc6-4516-83d5-4de38928df4f.png)
 How can I fix this ?

Thanks

**Comment by mrlt8** [comment]
Arm 32-bit OS?

Try this: https://github.com/mrlt8/docker-wyze-bridge/discussions/97#discussioncomment-1248099

**Comment by CzechSebastian** [comment]
I thing it's a 32 bit but how I can be sure?

**Comment by CzechSebastian** [comment]
I use home assistant in a docker container

**Comment by CzechSebastian** [comment]
> Arm 32-bit OS?
> 
> Try this: [#97 (reply in thread)](https://github.com/mrlt8/docker-wyze-bridge/discussions/97#discussioncomment-1248099)

How can I do that with portainer ?

**Comment by CzechSebastian** [comment]
> Arm 32-bit OS?
> 
> Try this: [#97 (reply in thread)](https://github.com/mrlt8/docker-wyze-bridge/discussions/97#discussioncomment-1248099)

Yes that's work !

**Comment by CzechSebastian** [comment]
So now how I can acces to video stream in vlc?

**Comment by mrlt8** [comment]
Try `http://<your server ip>:8888/jardin`
You can see the other uri's here:
https://github.com/mrlt8/docker-wyze-bridge#uris
