### ISSUE TITLE
WebRTC no longer an option in the UI

### ISSUE THREAD

**Issue by kasperb2** [mrlt8/docker-wyze-bridge#1001]
Since the last update, I no longer see WebRTC as an option in the Web UI. Additionally, the feed appears to be null.

I've rebooted HA (running on a dedicated RPi3), power cycled the camera, etc. Nothing else changed on my end.

**Comment by mrlt8** [comment]
Are you running the bridge as an add-on in Home Assistant? Can you post the version number so I can try to replicate the issue?

**Comment by kasperb2** [comment]
Yes, it's an add-on within Home Assistant. v2.3.17

**Comment by kasperb2** [comment]
Thanks, that fixed it.
