### ISSUE TITLE
Memory leak on docker using docker desktop on arm64 / Mac M2

### ISSUE THREAD

**Issue by seangphoto** [mrlt8/docker-wyze-bridge#1004]
Installing the docker image using docker run command:
docker run --restart always -p 8554:8554 -p 8888:8888 -p 5000:5000 mrlt8/wyze-bridge

image launches successfully and works wonderfully, but eventually crashes the docker container, memory leaks up to 9GB, takes about 10-15 mins to reach 1GB, 4 cameras including 1- 2k camera.

what might be causing this behavior? running docker on a M2 Mac Mini (arm64, I guess)

Thank you for any help! (screenshots attached)

<img width="1624" alt="Screen Shot 2023-09-19 at 7 40 14 PM" src="https://github.com/mrlt8/docker-wyze-bridge/assets/103555111/20fd12de-ad88-4317-be9f-df44e6dd178b">
<img width="1629" alt="Screen Shot 2023-09-19 at 7 39 04 PM" src="https://github.com/mrlt8/docker-wyze-bridge/assets/103555111/e935db49-09e3-4594-8b97-da66bdd70408">

**Comment by seangphoto** [comment]
Hello, 

Yes it is 2.3.17, just upgraded. 2.3.16 did the same.

There are no docker-compose.yml options.

**Comment by mrlt8** [comment]
Is this with just the WebUI open or are you streaming from the cameras via RTSP and/or HLS?

**Comment by seangphoto** [comment]
Streaming via RTSP to a scrypted server. Web UI was open also, but closing did not appear to change memory usage. 4 cameras total, including one 2k camera.
