### ISSUE TITLE
New Feature Request: Audio!

### ISSUE THREAD

**Issue by smarthousetips** [mrlt8/docker-wyze-bridge#101]
Not sure if this is possible but it would be awesome to get audio from these cameras!

**Comment by AdiAbuAli** [comment]
Following you for this hope

**Comment by chimcanhcut1112** [comment]
yes, hope will support audio soon

**Comment by esenterre** [comment]
Me too! :)

**Comment by AdiAbuAli** [comment]
I would like to buy @mrlt8 a cup or 2 of coffee, as seems Audio code interleave with video is complocated one and need a shot of caffeine...but coildnt see that option in the page unfortunately

Thanks,
________________________________

**Comment by SimplySynced** [comment]
Please let me know how I can help get this accomplished.  This would be amazing.  I have this paired with Shinobi right now and the ability to have audio will make this the best setup.
