### ISSUE TITLE
Bridge disconnects from all cameras after 5 to 6 hours and doesn't reconnect without intervention.

### ISSUE THREAD

**Issue by diggity801** [mrlt8/docker-wyze-bridge#1010]
Hello,

I have an issue where the bridge works fine while it is connected to the cameras, but after some time - maybe even up to 12 hours - the camera feeds all go offline and I have to click the refresh button in the top right of all of them to get them to reconnect. Or select the reconnect to all cameras option.

Today all feeds went offline at 2:34 in the morning. It was up since around 7 PM the previous day so 7 hours or so seems correct and then all cameras go down.

Thank you for your assistance!

![image](https://github.com/mrlt8/docker-wyze-bridge/assets/4187168/0567725c-22da-422f-9adc-9c7e5df94776)

**Comment by diggity801** [comment]
Actually, to get the cameras to reconnect, I just have to load the web UI, and then they start reconnecting. Do I have to permanently leave a webpage open to the web UI of the docker bridge to keep the cameras connected?

**Comment by mrlt8** [comment]
The streams should reconnect on-demand, but can you see if setting `ON_DEMAND=False` helps keep them alive?

**Comment by diggity801** [comment]
Would that go into the docker compose config file? Thank you!

**Comment by mrlt8** [comment]
Yes, it should go under `environment:` like this:


```
environment:
    - ON_DEMAND=False

```

**Comment by diggity801** [comment]
That fixed it! Thank you!
