### ISSUE TITLE
Login Page loops on credentials

### ISSUE THREAD

**Issue by praveenvj1979** [mrlt8/docker-wyze-bridge#1012]
I installed this as a container on my QNAP NAS. The container loads successfully, detects the Wyze camera as well. But when I try to open the browser on http://IP Address:5000, it prompts for the login name and password and that goes on in a loop. I tried both my NAS Admin credentials, WYZE credentials, but nothing works.

**Comment by mrlt8** [comment]
hmm, that's strange. Are you passing the credentials at startup via docker-compose.yml or docker run?

Can you post an warnings or errors from the logs?

**Comment by praveenvj1979** [comment]
Finally figured it. Found that QNAP was using port 5000 for WebDav. I disabled that and then got it working fine. Thanks a lot for your prompt response.

**Comment by sblea88** [comment]
> I installed this as a container on my QNAP NAS. The container loads successfully, detects the Wyze camera as well. But when I try to open the browser on http://IP Address:5000, it prompts for the login name and password and that goes on in a loop. I tried both my NAS Admin credentials, WYZE credentials, but nothing works.

Is there an article that you used to do this? Trying to figure it out for myself.
