### ISSUE TITLE
Container shuts down if there are no previously defined cameras in a valid cloud account.

### ISSUE THREAD

**Issue by xanderphillips** [mrlt8/docker-wyze-bridge#1031]
**Expected behaviour:** Log into empty account and have ability to add camera, or at least see interface with no camera to interact with.

**Actual behaviour:** Log into empty account and container exits immediately.

Fresh install via portainer.
Documented ports forwarded to host.
Enter username and password on port 5000 website, add multifactor key from email.
Website refreshes immediately to ERR_CONNECTION_REFUSED
Container immediately drops from running to exited state.

**portainer logs for the container after fresh install and one run through the initialization process:**

🚀 DOCKER-WYZE-BRIDGE v2.4.0 

[WyzeBridge] [WARN] Credentials are NOT set
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] Credentials required to complete login!
[WyzeBridge] Please visit the WebUI to enter your credentials.
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.3:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:14] "GET / HTTP/1.1" 302 -
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:14] "GET /login HTTP/1.1" 200 -
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:14] "GET /static/site.css HTTP/1.1" 304 -
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:35] "POST /login HTTP/1.1" 200 -
[WyzeBridge] 🔐 MFA Code Required [Email]
[WyzeBridge] ✉️ e-mail code requested
[WyzeBridge] 📝 Enter verification code in the WebUI or add it to /tokens/mfa_token.txt
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:40] "GET / HTTP/1.1" 200 -
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:40] "GET /static/site.css HTTP/1.1" 304 -
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:40] "GET /static/site.js HTTP/1.1" 304 -
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:40] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 🔑 Using 188435 for authentication
[WyzeBridge] 10.1.1.108 - - [01/Nov/2023 20:48:46] "GET /mfa/188435 HTTP/1.1" 200 -
[WyzeBridge] ✅ Verification code accepted!
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [0] cameras
[WyzeBridge] Stopping 0 streams
[WyzeBridge] 👋 goodbye!

**Comment by mrlt8** [comment]
Unfortunately, the bridge doesn't really do anything without any cameras, so it will just shut down.

The bridge doesn't support adding or removing cameras from an account since it's a very niche action that is probably only done once and would be easier and quicker to do within the Wyze app.
