### ISSUE TITLE
Doesn't run on Raspberry Pi 5 using Rasbian Bookworm 64 Bit

### ISSUE THREAD

**Issue by fjrichman** [mrlt8/docker-wyze-bridge#1057]
Every time I try to run this on my Pi5 using the 64 bit version of Bookworm it just exits with code 139. 

When I've tried to run it on the 32 bit version it worked just fine. 

I suspect the reason is because the Pi5 uses armv8 instead of v7.

**Comment by mrlt8** [comment]
Working on a proper arm64v8. Should be up in the next release.

**Comment by mrlt8** [comment]
@fjrichman could you try using the `mrlt8/wyze-bridge:dev` image? I don't have a pi5, but seems to be working on my pi4.

**Comment by fjrichman** [comment]
mrlt8/wyze-bridge:dev is working on my pi5 now
