### ISSUE TITLE
2.7.0 pan v3 streams drop in 1-8h, stream sometimes 1h delayed somehow, flawless on 2.6.0

### ISSUE THREAD

**Issue by joshuamckay** [mrlt8/docker-wyze-bridge#1088]
Again, 2.6.0 was no issue and my network is fully stable (Aruba enterprise APs). Only change is 2.7.0 upgrade. 

Cameras seem to die off the bridge randomly, one at a time. 

Wyze app still functions for all cameras. 

Firmware didn't change, at 4.50.4.7252

Also I tried disabling audio and just noticed the live stream seems to somehow be about 1h delayed right now? in this instance cams have survived for ~8h, so perhaps longer lived without audio, but becomes delayed. 

Addon log:

[WyzeBridge] 📖 New client reading from dining-room-cam
[WyzeBridge] 📖 New client reading from dining-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from living-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from office-cam
[WyzeBridge] 📕 Client stopped reading from dining-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from office-cam-sub
[WyzeBridge] 📕 Client stopped reading from living-room-cam
[WyzeBridge] 📕 Client stopped reading from kitchen-cam-sub
[WyzeBridge] 📕 Client stopped reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from kitchen-cam
[WyzeBridge] 📖 New client reading from office-cam-sub
[WyzeBridge] 📖 New client reading from office-cam
[WyzeBridge] 📖 New client reading from living-room-cam-sub
[WyzeBridge] 📖 New client reading from living-room-cam
[WyzeBridge] 📖 New client reading from kitchen-cam
[WyzeBridge] 📖 New client reading from dining-room-cam-sub
[WyzeBridge] 📖 New client reading from kitchen-cam-sub
[WyzeBridge] 📖 New client reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from kitchen-cam-sub
[WyzeBridge] 📕 Client stopped reading from dining-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from kitchen-cam
[WyzeBridge] 📕 Client stopped reading from living-room-cam
[WyzeBridge] 📕 Client stopped reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from office-cam-sub
[WyzeBridge] 📕 Client stopped reading from living-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from office-cam
[WyzeBridge] 📖 New client reading from office-cam-sub
[WyzeBridge] 📖 New client reading from office-cam
[WyzeBridge] 📖 New client reading from living-room-cam
[WyzeBridge] 📖 New client reading from living-room-cam-sub
[WyzeBridge] 📖 New client reading from kitchen-cam-sub
[WyzeBridge] 📖 New client reading from kitchen-cam
[WyzeBridge] 📖 New client reading from dining-room-cam-sub
[WyzeBridge] 📖 New client reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from living-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from kitchen-cam-sub
[WyzeBridge] 📕 Client stopped reading from office-cam
[WyzeBridge] 📕 Client stopped reading from kitchen-cam
[WyzeBridge] 📕 Client stopped reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from dining-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from living-room-cam
[WyzeBridge] 📕 Client stopped reading from office-cam-sub
[WyzeBridge] 📖 New client reading from office-cam
[WyzeBridge] 📖 New client reading from office-cam-sub
[WyzeBridge] 📖 New client reading from living-room-cam-sub
[WyzeBridge] 📖 New client reading from living-room-cam
[WyzeBridge] 📖 New client reading from kitchen-cam
[WyzeBridge] 📖 New client reading from kitchen-cam-sub
[WyzeBridge] 📖 New client reading from dining-room-cam-sub
[WyzeBridge] 📖 New client reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from living-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from kitchen-cam-sub
[WyzeBridge] 📕 Client stopped reading from office-cam
[WyzeBridge] 📕 Client stopped reading from kitchen-cam
[WyzeBridge] 📕 Client stopped reading from living-room-cam
[WyzeBridge] 📕 Client stopped reading from dining-room-cam
[WyzeBridge] 📕 Client stopped reading from dining-room-cam-sub
[WyzeBridge] 📕 Client stopped reading from office-cam-sub
[WyzeBridge] 📕 Client stopped reading from living-room-cam
[office-cam-sub] [video] super slow
[office-cam-sub] WARNING: clear buffer
[office-cam-sub] [audio] out of sync gap=11.616177082061768
[living-room-cam-sub] [video] super slow
[living-room-cam-sub] WARNING: clear buffer
[living-room-cam-sub] [audio] out of sync gap=11.789022207260132
[dining-room-cam-sub] [video] super slow
[dining-room-cam-sub] WARNING: clear buffer
[WyzeBridge] 📕 Client stopped reading from dining-room-cam
[dining-room-cam-sub] [audio] out of sync gap=12.083404064178467
[office-cam-sub] WARNING: AV_ER_CLEANBUF_ALREADY_CALLED
[office-cam-sub] WARNING: Audio pipe closed
[WyzeBridge] 📕 Client stopped reading from office-cam-sub
[living-room-cam-sub] WARNING: AV_ER_CLEANBUF_ALREADY_CALLED
[living-room-cam-sub] WARNING: Audio pipe closed
[dining-room-cam-sub] WARNING: AV_ER_CLEANBUF_ALREADY_CALLED
[dining-room-cam-sub] WARNING: Audio pipe closed
[office-cam-sub] Stream stopped
[WyzeBridge] ❌ '/office-cam-sub' stream is down
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V3 - Office Cam on 172.30.101.114
[living-room-cam-sub] Stream stopped
[dining-room-cam-sub] Stream stopped
[office-cam-sub] 📡 Getting 30kb/s SD stream (H264/20fps) via LAN mode (WiFi: 59%) FW: 4.50.4.7252 🔒
[office-cam-sub] Re-encoding audio for compatibility with WebRTC in MTX
[office-cam-sub] 🔊 Audio Enabled - ALAW > LIBOPUS/16,000Hz
[office-cam] WARNING: Audio pipe closed
[kitchen-cam-sub] [audio] out of sync gap=13.497750043869019
[kitchen-cam-sub] WARNING: clear buffer
[kitchen-cam] [audio] out of sync gap=11.11358904838562
[kitchen-cam] WARNING: clear buffer
[office-cam] [Exception] Did not receive a frame for 20s
[kitchen-cam] WARNING: Audio pipe closed
[kitchen-cam] [Exception] Did not receive a frame for 22s
[kitchen-cam-sub] WARNING: Audio pipe closed
[kitchen-cam-sub] [Exception] Did not receive a frame for 25s
[office-cam-sub] WARNING: Audio pipe closed
[office-cam-sub] [Exception] Did not receive a frame for 79s
[living-room-cam] WARNING: Audio pipe closed
[living-room-cam] [Exception] Did not receive a frame for 22s
[dining-room-cam] WARNING: Audio pipe closed
[dining-room-cam] [Exception] Did not receive a frame for 20s

**Comment by calimansi** [comment]
I'm seeing this with normal v3 cams too.  Also, the tag on the bottom is still 2.6.0 even though it is 2.7.0.  Switched back to 2.6.0 for now.

**Comment by thehijacker** [comment]
Same issue here. RTSP goes way off the sync. Sometime even more then 5 minutes. Now on 2.6.0 and it is the same. So something changed.

**Comment by joshuamckay** [comment]
downgraded to 2.6.0 and it seems to be losing streams too. was stable for months at at a time until 2.7.0, but I'm confused why a 2.6.0 downgrade would also now present issues, definitely no firmware change or network change either. the only thing that i can come up with is some kind of new wyze phone-home failing for 2.6.0 and 2.7.0 that just happened to begin when 2.7.0 upgrade hit.

**Comment by Scope666** [comment]
I agree with @joshuamckay ... I reverted to 2.6 and even 2.5 and still had FREQUENT drops, in a very consistent rhythm.  I believe Wyze changed the behavior somehow.  For now I've flashed all 3 cameras back to the old RTSP firmware.

**Comment by paulcusick3** [comment]
+1

**Comment by joshuamckay** [comment]
fwiw I enabled debug logging on 2.6.0 and I've been stable ever since. I don't know if wyze fixed something or the nature of debug logging fixes the issue. I also haven't dared go back to 2.7.0.

**Comment by malik0505** [comment]
Similar boat in that 2.7.0 resulted in my entire setup to stop working. 

Can anyone help me understand how I can downgrade to 2.6.0? Or rather install 2.6.0 (I can just uninstall 2.7.0)? I can then try @joshuamckay method of enabling debug logging

**Comment by joshuamckay** [comment]
just go to github, select 2.6.0 tag, download zip file, and put "app" directory in haos addons directory, then refresh haos addons and it'll show up as a "local addons" and you can install.

**Comment by AngusNB** [comment]
I am having this issue but only with one V3. The longer it's up the further behind it gets.

**Comment by k-w-1** [comment]
Datapoint: also experiencing the video lag issue. DWB 2.7.0, v3 Pro FW: 4.58.11.4679 . 

Looks like #1079 and #1084 may be related.

**Comment by malik0505** [comment]
> just go to github, select 2.6.0 tag, download zip file, and put the zip file's "app" directory in haos addons directory, then refresh haos addons and it'll show up as a "local addons" and you can install.
> 
> fwiw I'm like 48h stable now with 2.6.0 and debug logging on.

total n00b but I cannot seem to locate the haos addons directory. I'm looking via File Editor.

**Comment by joshuamckay** [comment]
I think you can upload zip via file editor, but you're going to need a terminal / shell to see the full directory structure, try "advanced ssh & web terminal" - then you can unzip and mv (move) the directory to the right spot.

**Comment by AngusNB** [comment]
> just go to github, select 2.6.0 tag, ...

Thanks, that did the trick, sort of. I [downloaded 2.6.0](https://github.com/mrlt8/docker-wyze-bridge/archive/refs/tags/v2.6.0.zip) but it's showing as 2.5.3. in HA. Ah well. Still works better than 2.7.0.

**Comment by malik0505** [comment]
Dang still no luck. Was not able to locate the directory let alone upload the zip. I'll just hang tight until a fix I suppose.

**Comment by AngusNB** [comment]
I use the Samba Share addon then access the HA folders through windows Network Shares using the HA IP address.

**Comment by KaneHart** [comment]
Also having major desyncing over time. I thought it was just me. Sadly my Camera's not easy to get to and -20 outside :(

**Comment by xcellentavi** [comment]
> just go to github, select 2.6.0 tag, download zip file, and put the zip file's "app" directory in haos addons directory, then refresh haos addons and it'll show up as a "local addons" and you can install.
> 
> fwiw I'm like 48h stable now with 2.6.0 and debug logging on.

How did you enable or which option(s) did you add from here: https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#debugging-options

Thanks!

**Comment by joshuamckay** [comment]
> > just go to github, select 2.6.0 tag, download zip file, and put the zip file's "app" directory in haos addons directory, then refresh haos addons and it'll show up as a "local addons" and you can install.
> > fwiw I'm like 48h stable now with 2.6.0 and debug logging on.
> 
> How did you enable or which option(s) did you add from here: https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#debugging-options
> 
> Thanks!

log level: debug
log file: true/on
log time: true/on
ffmpeg log level: fatal

**Comment by xcellentavi** [comment]
> > > just go to github, select 2.6.0 tag, download zip file, and put the zip file's "app" directory in haos addons directory, then refresh haos addons and it'll show up as a "local addons" and you can install.
> > > fwiw I'm like 48h stable now with 2.6.0 and debug logging on.
> > 
> > 
> > How did you enable or which option(s) did you add from here: https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#debugging-options
> > Thanks!
> 
> log level: debug log file: true/on log time: true/on ffmpeg log level: fatal
> 
> Stable for many days now on 2.6.0 with above debugging enabled

I downgraded to 2.6.0, definitely less errors than before.  I am seeing only a few of these now and then:

[CONTROL] ERROR - error=TutkError(-20018), cmd=('param_info', '1,2,3,4,5,6,7,21,22,27,50')

I could set up the debug logging, but when you say stable, are you still getting warnings and errors or everything is solid?

**Comment by joshuamckay** [comment]
> > > > just go to github, select 2.6.0 tag, download zip file, and put the zip file's "app" directory in haos addons directory, then refresh haos addons and it'll show up as a "local addons" and you can install.
> > > > fwiw I'm like 48h stable now with 2.6.0 and debug logging on.
> > > 
> > > 
> > > How did you enable or which option(s) did you add from here: https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#debugging-options
> > > Thanks!
> > 
> > 
> > log level: debug log file: true/on log time: true/on ffmpeg log level: fatal
> > Stable for many days now on 2.6.0 with above debugging enabled
> 
> I downgraded to 2.6.0, definitely less errors than before. I am seeing only a few of these now and then:
> 
> [CONTROL] ERROR - error=TutkError(-20018), cmd=('param_info', '1,2,3,4,5,6,7,21,22,27,50')
> 
> I could set up the debug logging, but when you say stable, are you still getting warnings and errors or everything is solid?

definitely still errors, logs at that level are rarely clean. I do experience ~5 second delays currently, but compared to the 2.7.0, I consider it solid.

**Comment by malik0505** [comment]
Finally downgraded (although showing 2.5.3), but still unable to connect. Here's the log 
```

🚀 DOCKER-WYZE-BRIDGE v2.5.3 

13:21:12 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
13:21:12 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
13:21:12 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
 * Serving Flask app 'frontend'
 * Debug mode: off
13:21:12 [INFO][WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.33.1:5000
13:21:12 [INFO][WyzeBridge] Press CTRL+C to quit
13:21:13 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /v3/user/login HTTP/1.1" 200 None
13:21:13 [WARNING][WyzeBridge] 🔐 MFA Code Required [TotpVerificationCode]
13:21:13 [WARNING][WyzeBridge] 📝 Enter verification code in the WebUI or add it to /config/wyze-bridge/mfa_token.txt
13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET / HTTP/1.1" 200 -
13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/bulma.css HTTP/1.1" 200 -
13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/site.css HTTP/1.1" 200 -
13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/bulma-toast.js HTTP/1.1" 304 -
13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/site.js HTTP/1.1" 304 -
13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /api/sse_status HTTP/1.1" 200 -
13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET / HTTP/1.1" 200 -
13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/bulma.css HTTP/1.1" 304 -
13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/site.css HTTP/1.1" 304 -
13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/bulma-toast.js HTTP/1.1" 304 -
13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/site.js HTTP/1.1" 304 -
13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /api/sse_status HTTP/1.1" 200 -
13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET / HTTP/1.1" 200 -
13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/bulma.css HTTP/1.1" 200 -
13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/site.css HTTP/1.1" 304 -
13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/bulma-toast.js HTTP/1.1" 304 -
13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/site.js HTTP/1.1" 304 -
13:24:09 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:09] "GET /api/sse_status HTTP/1.1" 200 -
13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET / HTTP/1.1" 200 -
13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/bulma.css HTTP/1.1" 304 -
13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/site.css HTTP/1.1" 304 -
13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/site.js HTTP/1.1" 304 -
13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/bulma-toast.js HTTP/1.1" 304 -
13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /api/sse_status HTTP/1.1" 200 -
```

**Comment by xcellentavi** [comment]
> Finally downgraded (although showing 2.5.3), but still unable to connect. Here's the log
> 
> ```
> 
> 🚀 DOCKER-WYZE-BRIDGE v2.5.3 
> 
> 13:21:12 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
> 13:21:12 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
> 13:21:12 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
>  * Serving Flask app 'frontend'
>  * Debug mode: off
> 13:21:12 [INFO][WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on all addresses (0.0.0.0)
>  * Running on http://127.0.0.1:5000
>  * Running on http://172.30.33.1:5000
> 13:21:12 [INFO][WyzeBridge] Press CTRL+C to quit
> 13:21:13 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /v3/user/login HTTP/1.1" 200 None
> 13:21:13 [WARNING][WyzeBridge] 🔐 MFA Code Required [TotpVerificationCode]
> 13:21:13 [WARNING][WyzeBridge] 📝 Enter verification code in the WebUI or add it to /config/wyze-bridge/mfa_token.txt
> 13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET / HTTP/1.1" 200 -
> 13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/bulma.css HTTP/1.1" 200 -
> 13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/site.css HTTP/1.1" 200 -
> 13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/bulma-toast.js HTTP/1.1" 304 -
> 13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /static/site.js HTTP/1.1" 304 -
> 13:23:00 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:00] "GET /api/sse_status HTTP/1.1" 200 -
> 13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET / HTTP/1.1" 200 -
> 13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/bulma.css HTTP/1.1" 304 -
> 13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/site.css HTTP/1.1" 304 -
> 13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/bulma-toast.js HTTP/1.1" 304 -
> 13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /static/site.js HTTP/1.1" 304 -
> 13:23:06 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:23:06] "GET /api/sse_status HTTP/1.1" 200 -
> 13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET / HTTP/1.1" 200 -
> 13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/bulma.css HTTP/1.1" 200 -
> 13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/site.css HTTP/1.1" 304 -
> 13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/bulma-toast.js HTTP/1.1" 304 -
> 13:24:07 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:07] "GET /static/site.js HTTP/1.1" 304 -
> 13:24:09 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:09] "GET /api/sse_status HTTP/1.1" 200 -
> 13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET / HTTP/1.1" 200 -
> 13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/bulma.css HTTP/1.1" 304 -
> 13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/site.css HTTP/1.1" 304 -
> 13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/site.js HTTP/1.1" 304 -
> 13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /static/bulma-toast.js HTTP/1.1" 304 -
> 13:24:32 [INFO][WyzeBridge] 172.30.32.2 - - [26/Jan/2024 13:24:32] "GET /api/sse_status HTTP/1.1" 200 -
> ```

You have 2FA set up but you are not providing the TOTP_KEY or the value is incorrect.  Check your settings.

**Comment by malik0505** [comment]
I usually input the MFA code in the mfa_token.txt and it's worked.....not this time though

The TOTP_KEY field has usually been empty iirc

**Comment by KaneHart** [comment]
So no news on the issues?

**Comment by joshuamckay** [comment]
I haven't heard anything, but I just updated to new firmware yesterday and went back to 2.7.0 (still debug logging) and I've kept streams for over 24h now.

**Comment by xcellentavi** [comment]
> I usually input the MFA code in the mfa_token.txt and it's worked.....not this time though
> 
> The TOTP_KEY field has usually been empty iirc

Hmm, not sure then as mine is used in a docker container with the TOTP_KEY instead of the mfa_token.txt.  Perhaps [this](https://github.com/mrlt8/docker-wyze-bridge/issues/889) relates to your issue?

**Comment by malik0505** [comment]
I used the API Key method and it worked...Now I can join the others when they say things aren't perfect, but at least there's something heh

**Comment by joshuamckay** [comment]
just an update, new firmware and 2.7.0 still loses stream, but can last up to 2 days, usually failing within 1 though.

**Comment by Scope666** [comment]
Still on RTSP firmware for now, waiting to see if a new version will be released that can work with the newer firmware versions Wyze has been pushing out.

**Comment by Hassansaleh22** [comment]
I'm also having the same issue, it get out of sync slowly. I'm on 2.7.0 firmware. Restarting it will get it back in sync but sometimes each 12 hours you losses 5 mins. Waiting to see if there is any solution.

**Comment by Raul-7-7** [comment]
Hey @Scope666 , curious, why would you want to use the bridge if you are on RTSP? I am thinking of switching to RTSP as the bridge no longer works (delayed) however wondering what is the disadvantage? Cheers

**Comment by Scope666** [comment]
The only reason I switched to this bridge awhile back was because I thought the RTSP firmware was a bit buggy, and also because they stopped updating it.  I have an extra outdoor Wi-Fi plug and I have both Wyze cams plugged into it, so if they act up, I can remotely reboot them.   :) 

When it was good, this bridge was like a ROCK for me for many many months.  It's a shame Wyze messed it up.  (I'm assuming with official firmware updates)

**Comment by Scope666** [comment]
When I was still running stock firmware, I tried multiple versions and the symptoms were always the same.   LOTS of disconnects / reconnects shown in the Blue Iris log.  On the Wyze RTSP firmware it's been much better.  Before the recent Wyze stock firmware updates, they would stay connected for a LONG time.

**Comment by KaneHart** [comment]
So on the RTSP Firmware if you do disconnect, etc does it try again or am I having to manually reboot the bloody thing?

**Comment by Raul-7-7** [comment]
Thx @Scope666 . I am going to switch then. Is there any issue with switching back and forth from RTSP to official f/w?

**Comment by Scope666** [comment]
No, not that I'm aware of... I've flipped back and forth a couple times.

**Comment by fjrichman** [comment]
Did the delay get worse the longer it was running? I've been noticing an issue with my cameras where the longer they're rubbing the more delayed they become. At one point they were delayed by several days.

**Comment by Raul-7-7** [comment]
I restarted about 12 hours ago and so far no delay! not sure if the issue resolved itself or delay is going to show up soon, anyone else?

**Comment by KaneHart** [comment]
It's 100% up and down for me. Normally if I reboot it all I have issues and the longer I leave it were talking days it seems to self correct itself lol

**Comment by joshuamckay** [comment]
4 weeks later and not a word from the dev on the onslaught of issues. I've tried so many things myself to fix, all temporary remedies at best. it seems relying on this software was a bad idea. wyze pan v3 were the coolest cams I could find, but wyze itself is terrible with no rtsp and this bridge feels effectively abandoned if it's this bad and ignored. I didn't think much at a week or two since it's open source, but now it's just getting ridiculous.

**Comment by Raul-7-7** [comment]
> 4 weeks later and not a word from the dev on the onslaught of issues. I've tried so many things myself to fix, all temporary remedies at best. it seems relying on this software was a bad idea. wyze pan v3 were the coolest cams I could find, but wyze itself is terrible with no rtsp and this bridge feels effectively abandoned if it's this bad and ignored. I didn't think much at a week or two since it's open source, but now it's just getting ridiculous.

What is getting ridiculous? The person who has been spending their time on a volunteer basis? 
FYI WYZE does have RTSP firmware, you can google it and install it. 
Also, for the future, unless you are paying for something then never count on it for production basis. I for one, really appreciate all the work Dev has put on this, if he has abandoned it, then so be it! he has every right! his time, his choice how to spend it.

**Comment by joshuamckay** [comment]
oh I fully accept it's open source and volunteer and appreciate all open source efforts and devs. I just didn't expect a big rewrite to drop and/or wyze updates to render it this broken and the project to not respond for a month. it's just not typical, even in open source/volunteer world. at this point I'm kinda worried something happened to the dev. 

FYI wyze rtsp firmware doesn't work on pan v3 nor does mini hacks.

**Comment by Raul-7-7** [comment]
> oh I fully accept it's open source and volunteer and appreciate all open source efforts and devs. I just didn't expect a big rewrite to drop and/or wyze updates to render it this broken and the project to not respond for a month. it's just not typical, even in open source/volunteer world. at this point I'm kinda worried something happened to the dev.
> 
> FYI wyze rtsp firmware doesn't work on pan v3 nor does mini hacks.

I understand your frustration, we all are, and I really hope the Dev is ok as well. 
With regards to WYZE, you can do what many of us are in the process of ! moving to another vendor. It is clear WYZE has no intention of supporting RTSP. 
Whenever I see a sale, I buy Reolink, until I completely get rid of my WYZE.

**Comment by KaneHart** [comment]
I mentioned mrlt8 vanishing, but I no way at all hold him accountable at all. It's bloody open source project haha. But with mrlt8 MIA a bit, I'm a bit worried, but then again maybe it's time for me to check our direct RTSP firmware and see how it goes. No matter what big thanks to mrlt8 and everyone else who contributed even if they took the time to help someone or report a bug or even told someone about the software.

I think it's time for me in the long run to find a better Camera setup either 5ghz or wired, but I want something that has a decent night time sensor the same or better. I honestly just can't see myself going back to greyscale haha.

**Comment by AngusNB** [comment]
@mrlt8 will get to it when he has time. Meanwhile use 2.6.0. I've no real issues with it.

The .zip and .tar downloads seem to be messed up. If you want 2.6.0 then download 2.7.0 and install it manually. The 2.6.0 download seems to be 2.5.3.

**Comment by calimansi** [comment]
@mrlt8 - Have you seen this thread?  For some of us, the time get way out of sync from 2.7.0 on.  I really love this software and would like to keep using it.

**Comment by joshuamckay** [comment]
bought different cameras, giving up and closing this issue.

**Comment by KaneHart** [comment]
That's not how GitHub works just because you've given up doesn't mean the issue is still not there. Unsubscribe. You don't just close one of the biggest issues on here just because you had a tantrum.

**Comment by xcellentavi** [comment]
> That's not how GitHub works just because you've given up doesn't mean the issue is still not there. Unsubscribe. You don't just close one of the biggest issues on here just because you had a tantrum.

You could start a new issue and mention this closed one to keep it open if you want.  There was also a lack of helpful information here (not OP's fault) but would be useful to the developers to get additional technical details. Here's a sample outline for reporting bugs:

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Anything else that you think could be an issue.

### Evidence

- How was this tested?
