### ISSUE TITLE
Cannot get 2.7.0

### ISSUE THREAD

**Issue by jplwoodward** [mrlt8/docker-wyze-bridge#1091]
I start my docker container with --pull=always mrlt8/wyze-bridge, but do not get 2.7.0.  I have 2.6.0 and it says it is current when I start it.

**Comment by jjyu420** [comment]
Seems like a flaw in 2.70. You are likely on 2.7 although it shows 2.6. I have the same issue and it’s already opened as an issue.

**Comment by jplwoodward** [comment]
Thanks!
