### ISSUE TITLE
After reboot, problems!

### ISSUE THREAD

**Issue by JA16122000** [mrlt8/docker-wyze-bridge#1123]
[WyzeBridge] ⚠️ 504 Server Error: Gateway Time-out for url: https://auth-prod.api.wyze.com/api/user/login
 
 Don't know what to do?

**Comment by dp0100** [comment]
Yep...getting the same here

**Comment by thehijacker** [comment]
Must be Wyze servers issue. Even online is not working:

https://my.wyze.com/live

**There was a problem with the server. Please try again later or contact us for assistance.**

**Comment by carldanley** [comment]
It seems like a server issue - I can't use the app at all (cell connection or wifi).

**Comment by itworksdontaskquestions** [comment]
Same here.

**Comment by KaneHart** [comment]
Wyze Servers once again fracking up. Nothing to do with this.

**Comment by cheme75** [comment]
FWIW, only got my original doorbell connected at present but it's streaming just fine.

**Comment by java007md** [comment]
Wyze Service Status:

https://support.wyze.com/hc/en-us/articles/360015979872-Service-Status-Known-Issues

All my camera's are having connection issues (v3's).

**Comment by cheme75** [comment]
> Wyze Service Status:
> 
> 
> 
> https://support.wyze.com/hc/en-us/articles/360015979872-Service-Status-Known-Issues
> 
> 
> 
> All my camera's are having connection issues (v3's).

Yup, see that. Maybe since I'm home on same subnet it's still streaming.

**Comment by jshg46** [comment]
Could be, I just wished it was possible atleast on in network cameras.

**Comment by cheme75** [comment]
> Could be, I just wished it was possible atleast on in network cameras.

I doubt it will ever work offline, only locally. It has to get the authorization from the wyze servers. Their servers go down then auth fails. If wyze blocks access then this bridge will be a dead end. 

Doubt Wyze will do that since this is a viable option for them to avoid alienating a large subset of users who they no longer support with a native RTSP stream option.

**Comment by itworksdontaskquestions** [comment]
@JA16122000 Issue seems to have resolved, you should close this issue.
