### ISSUE TITLE
No stream to mobile device on latest release

### ISSUE THREAD

**Issue by ragenhe** [mrlt8/docker-wyze-bridge#113]
Starting yesterday, my V3 disappeared from my home assistance _mobile_ app, it was fine when viewing on anything browser based.  I didn't mess with it much, it was getting late.

This morning I dug through the logs, nothing catastrophic.

I did see where my V2 was pulling 30 kb/s stream, not the normal 120 kb/s.

So here is the summary.

No errors on wyze-bridge container.
No errors in frigate container.
No errors in HA container (different host)

Stream is present on frigate via browser and mobile.
Stream is present on HA via browser but _not on mobile_.

I rolled back to 0.6.0 and all is good again.

Reporting just in case it helps on other issues, or could be a clue on something unexplained up to this point.

**Comment by mrlt8** [comment]
Thanks for the report. When you say mobile, do you mean the 8888 stream?

**Comment by ragenhe** [comment]
No. It would be rtmp pretty much from end to end. It’s very weird!!!

**Comment by mrlt8** [comment]
Should be fixed in v0.6.4!

For some reason it seems like the cams will randomly change the resolution which causes issues with the RTMP and HLS streams.

The update should raise an exception if the resolution doesn't match for more than 30 consecutive frames which will then restart the connection.

**Comment by ragenhe** [comment]
On the first container startup all seemed to be back to normal.  Then my V2 disappeared and even after a container restart, it didn't return.  Looking at the logs for both, the rtsp server had a minor update difference between 0.6.0 and the latest.  Maybe something is weird there.

**Comment by ragenhe** [comment]
This is from the 0.6.0 container.  But the stream is still available.
```
2021/09/09 12:20:54 [Mia-cam] WARNING: Lost frame,
2021/09/09 12:24:09 [Mia-cam] WARNING: Received incomplete frame ```

**Comment by ragenhe** [comment]
Running on 0.6.4, I'll watch it and report back what happens throughout the day.

**Comment by ragenhe** [comment]
Still no issues.

Thanks!
