### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by vednolacni** [mrlt8/docker-wyze-bridge#1137]
![Screenshot_1](https://github.com/mrlt8/docker-wyze-bridge/assets/123391433/71765769-fb82-4204-8e56-b02b8fa46749)
![Screenshot_2](https://github.com/mrlt8/docker-wyze-bridge/assets/123391433/44c93f8f-245e-4555-9aaf-48f7a90fe9ed)

I updated the home assistant add-on, but when i run it its not updated.

**Comment by Raul-7-7** [comment]
This is a known issue, the tag is not updating, the code is updated. BTW if you have issues with video sync, best to stick with 2.6

**Comment by superdong69** [comment]
Does ANYONE know where @mrlt8 is? It's been a minute and he's not responding. This entire project is broken since the 2.7 update. Works for about 10 mins before it fails all cameras. And there's no way to roll back in Home Assistant to get back to 2.6

**Comment by JA16122000** [comment]
> Does ANYONE know where @mrlt8 is? It's been a minute and he's not responding. This entire project is broken since the 2.7 update. Works for about 10 mins before it fails all cameras. And there's no way to roll back in Home Assistant to get back to 2.6

https://github.com/mrlt8/docker-wyze-bridge/discussions/1128

**Comment by swarshah** [comment]
I wondered this myself, and then I discovered that the version bump commit was not a part of the 2.7 release.

**Comment by mrlt8** [comment]
This should be fixed with v2.8.1 - there was an issue with our GitHub action.
