### ISSUE TITLE
Any New Forks active now the project is dead?

### ISSUE THREAD

**Issue by KaneHart** [mrlt8/docker-wyze-bridge#1139]
I assume since there was no message, or explanation about the dev going MIA, they have perished in this world. Just wondering if anyone has forked the project and continued on?

**Comment by letrain02** [comment]
i don't think @mrlt8 is MIA. this is a project, by donations. not apple or google that dumps an update every 3 weeks. patience. people do have lives outside supporting free applications. looking at docker hub he obviously still exists. nightly's are still being dropped there. 

https://hub.docker.com/r/mrlt8/wyze-bridge/tags

**Comment by KaneHart** [comment]
Love the hate. Over 2 Months now almost 3 lmao. I'm happy for what they did and created. All I'm interested is in an active fork where it's going to continue on.

**Comment by warmon6** [comment]
https://github.com/mrlt8/docker-wyze-bridge/branches

Not sure why you think he's MIA, His branches are still getting updates. One of the branches was updated a week before your first post and the other branch just a few days ago.

Once he's satisfied with those changes, that's when he update the main branch.

**Comment by Raul-7-7** [comment]
I really hope @mrlt8 is doing fine and enjoying life. However, I think @KaneHart is right, @mrlt8 las contribution was back in Jan (https://github.com/mrlt8) so I think this project is pretty much dead unless @mrlt8 himself posts! 

As for what to do, I honestly think the best is to slowly move away from WYZE, there are other brands that do have RTSP natively which I am slowly switching to, (I am switching to Reolink) however there are many other brands cheaper/more expensive out there.

**Comment by PerpSearch** [comment]
Looks active to me
https://github.com/mrlt8/docker-wyze-bridge/pull/1005
