### ISSUE TITLE
Please define a license for this project

### ISSUE THREAD

**Issue by DAcodedBEAT** [mrlt8/docker-wyze-bridge#1142]
I was looking through the Github issues for ways that I can help contribute to this project and noticed https://github.com/mrlt8/docker-wyze-bridge/issues/1118 , which made me look into what this project was licensed under (also previously brought up in https://github.com/mrlt8/docker-wyze-bridge/issues/441#issuecomment-1162617610 but it might've been missed since the issue was closed).

_from https://choosealicense.com/no-permission/_
>[Since there isn't any clear licensing for this project,] the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

If this project is intended to be open source, a license should be added so that users can run, modify, study, distribute, and use the code.

**Comment by DAcodedBEAT** [comment]
@mrlt8 What is your verdict on this? Should I submit an PR for the MIT license in the interim?

**Comment by DAcodedBEAT** [comment]
@mrlt8 (since I saw that you recently became active) Can you please look into this?

**Comment by mrlt8** [comment]
I'll look into this when I have a chance, but we are using some methods from the tutk SDK so not sure how that would work for the license.

**Comment by DAcodedBEAT** [comment]
If you are referring to https://github.com/kroo/wyzecam , I believe you should be fine as long as proper attribution is put in place (since it's using the MIT license https://choosealicense.com/licenses/mit/)

**Comment by DAcodedBEAT** [comment]
@mrlt8 _polite nudge_. Would you like for me to suggest a license and contribute a pull request for it?

**Comment by mrlt8** [comment]
@DAcodedBEAT thank you for your suggestions, I went ahead and added an AGPL-3 license. Please let me know if there's anything else i can do.

**Comment by DAcodedBEAT** [comment]
no, this is great! thanks for doing this!! closing this since it's done.
