### ISSUE TITLE
Not Auto updating in Home Assistant still

### ISSUE THREAD

**Issue by almoney** [mrlt8/docker-wyze-bridge#1147]
### Discussed in https://github.com/mrlt8/docker-wyze-bridge/discussions/1032

<div type='discussions-op-text'>

<sup>Originally posted by **AngusNB** November  2, 2023</sup>
I have Docker-Wyze-Bridge running in Home Assistant on a RPi3. Overall it works great.
I noticed that it hasn't updated to v2.4.0. It's still at v2.3.17. Auto update is on.
Can I manually update it? If so, how?</div>

Anyone working on this so that updates work in the Home Assistant deployment?  The check for updates says there is a new version available 2.7 when I am running 2.6.  Maybe this is an error in the HA deployment since I just turned this on in my instance yesterday?

Docker Wyze Bridge
Current version: 2.7.0 (Changelog)

is reported in the Add-ons display as well.

**Comment by drewkeller** [comment]
Auto update is enabled in Home Asistant configuration forDocker Wyze Bridge. The bridge page in Home Assistant accessed from the sidebar says "Update available" for 2.7 when I click the circle/arrow icon. But there is no indication of how to update. I tried uninstalling and installing again but still at 2.6.

**Comment by tadcrazio** [comment]
FWIW, i was on version 2.3.7 or something, saw this issue and wanted to try an update. I'm not sure what i did completely but went to go re-add docker-wyze-bridge and I ended up with 2 instances of it installed. new and old. 

What i notice is: 
In the web-UI for docker wyze bridge in my HA, at the bottom i see:  docker-wyze-bridge v2.6.0 
BUT on the main page before clicking into the web-ui i see 2.7

Perhaps the same for you, and it's a bug that just shows 2.6 in the UI? Or perhaps it's not actually 2.7  ¯\_(ツ)_/¯

**Comment by drewkeller** [comment]
This is what the log shows when I start the bridge. Seeing that the 2.7 was released on Jan 10, I imagine I must really have 2.7, although the bridge page shows 2.6.
```
[WyzeBridge] 🏠 Home Assistant Mode
[WyzeBridge] WARNING: invalid escape sequence '\:'
🚀 DOCKER-WYZE-BRIDGE v2.6.0 AARCH64 2.7.0 BUILD [2024-01-11t04:20:13.342z] bbacb0f

```

**Comment by krusej23** [comment]
I had the same issue and had to go install the new version separately and then uninstall the old version.

**Comment by mrlt8** [comment]
Yes, you may need to re-add the repo. 


https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmrlt8%2Fdocker-wyze-bridge

I had to restructured the repo so that we could add additional builds like the dev branch.
