### ISSUE TITLE
FORCE_FPS doesn't appear to be working

### ISSUE THREAD

**Issue by jarrah31** [mrlt8/docker-wyze-bridge#1161]
Hello,

I have Wyze-bridge 2.8.1 running as a Docker container. It connects to the following three Wyze cams:

Wyze Cam v3 - v4.36.11.8391
Wyze Cam v3 Pro - v4.58.11.8391
Wyze Cam Pan v3 - v4.50.4.9222

In my Docker environment variables I have the following set:

```
    environment:
      # [REQUIRED] Fill the following two lines:
      - WYZE_EMAIL=$WYZE_EMAIL
      - WYZE_PASSWORD=$WYZE_PASSWORD
      - RTSP_PATHS_ALL_READUSER=$WYZE_RTSP_USER
      - RTSP_PATHS_ALL_READPASS=$WYZE_RTSP_PASS
      - FORCE_FPS_FRONTCAMTOP=10
      - FORCE_FPS_GARAGECAM=10
      - FORCE_FPS_KITCHENCAMPAN=10
      - TOTP_KEY=$WYZE_TOTP
      - NET_MODE=LAN
      - ENABLE_AUDIO_GARAGECAM=True
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_AUTH=${MQTTAUTH}
      - MQTT_TOPIC=wyzebridge
      - MQTT_DTOPIC=homeassistant
      # - FRESH_DATA=true
      # - AUDIO_CODEC=AAC
      - WB_IP=${DOCKER_HOST_IP}
      - DEBUG_FFMPEG=true
 ```

I use the RTSP streams to feed into SecuritySpy which is reporting 20fps for all three cameras.

Looking at the docker logs, on startup it says the following:

```
[WyzeBridge] [CONTROL] Connecting to kitchencampan
[kitchencampan] Attempting to force fps=10
[kitchencampan] Requesting frame_size=0, bitrate=180, fps=10
[kitchencampan] 📡 Getting 180kb/s HD stream (H264/10fps) via LAN mode (WiFi: 56%) FW: 4.50.4.9222 🔒
[kitchencampan] [CONTROL] Attempting to SET: rotary_degree=up
[kitchencampan] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/kitchencampan stream is UP! (3/3)
[kitchencampan] [CONTROL] response=None
[WyzeBridge] [CONTROL] Disconnecting from kitchencampan
[WyzeBridge] ❌ '/kitchencampan' stream is down
[kitchencampan] Attempting to force fps=10
[kitchencampan] Requesting frame_size=0, bitrate=180, fps=10
[kitchencampan] 📡 Getting 180kb/s HD stream (H264/10fps) via LAN mode (WiFi: 48%) FW: 4.50.4.9222 🔒
[kitchencampan] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[kitchencampan] [video] super slow
[kitchencampan] WARNING: clear buffer
[WyzeBridge] ✅ '/kitchencampan stream is UP! (3/3)
[WyzeBridge] 📖 New client reading from kitchencampan
[WyzeBridge] 📖 New client reading from kitchencampan
[WyzeBridge] 📕 Client stopped reading from kitchencampan

[frontcamtop] Attempting to force fps=10
[frontcamtop] Requesting frame_size=3, bitrate=180, fps=10
[frontcamtop] 📡 Getting 180kb/s 2K stream (H264/10fps) via LAN mode (WiFi: 56%) FW: 4.58.11.8391 🔒
[frontcamtop] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[frontcamtop] [video] super slow
[frontcamtop] WARNING: clear buffer

[garagecam] Attempting to force fps=10
[garagecam] Requesting frame_size=0, bitrate=180, fps=10
[garagecam] 📡 Getting 180kb/s HD stream (H264/10fps) via LAN mode (WiFi: 63%) FW: 4.36.11.8391 🔒
[garagecam] Re-encoding audio for compatibility with WebRTC in MTX
[garagecam] 🔊 Audio Enabled - ALAW > LIBOPUS/16,000Hz
[garagecam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
```

As you can see here it tries for force 10fps, however when I look at the Wyze-Bridge web GUI and select the 'I' icon on each camera, it says fps = 20:
```
videoParm	{ "bitRate": "30", "fps": "20", "horizontalFlip": "1", "logo": "2", "resolution": "2", "time": "1", "type": "H264", "verticalFlip": "1" }
```

This is also backed up in the SecuritySpy app:

<img width="594" alt="Capto_Annotation" src="https://github.com/mrlt8/docker-wyze-bridge/assets/3072303/44e24847-984f-4ca7-ad97-9e99f91de335">

Trying other versions seems to work better:

v2.6.0 is close to 10fps

 ![Capto_Capture 2024-04-25_07-36-09_PM](https://github.com/mrlt8/docker-wyze-bridge/assets/3072303/3da5ad4b-1310-4664-861a-d2488832823f)

v2.7.0 does 20fps with one of the cams

![Capto_Capture 2024-04-25_07-38-41_PM](https://github.com/mrlt8/docker-wyze-bridge/assets/3072303/728f904f-0df1-44e3-b300-1ce052e403e8)

The main reason for reporting this is because it helps reduce my wifi bandwidth, especially for the Pan Cam because that is further away from the router. (or does it? I guess the camera always sends 20fps and wyze bridge just re-encodes as 10fps?)

**Comment by mrlt8** [comment]
hmm I'll have to look into this.

**Comment by jarrah31** [comment]
Thank you, hopefully it’s not just me seeing this difference.

**Comment by mrlt8** [comment]
Could you try the latest dev build to see if that helps?

**Comment by jarrah31** [comment]
Thanks for the update, I should be able to try this on Monday when back home.

**Comment by mrlt8** [comment]
@jarrah31 could you try the dev branch to see if that helps?

**Comment by jarrah31** [comment]
Very sorry @mrlt8 it's been a busy week at work and I clean forgot to test the dev branch. I've now just installed 2.9.0 and can confirm FROCE_FPS now works great. Thank you very much!

**Comment by jdeath** [comment]
how set force_fps in home assistant mode? Tried 
FORCE_FPS_KITCHENCAMPAN: 10
and 
FORCE_FPS:10 under cam_options

neither seems to work (do not see it trying to request lower fps in log).

I am trying to reduce memory usage. High usage of the bridge appears to crash my system.

**Comment by mrlt8** [comment]
hmm, I think we're missing the fps options for HA. will have to look into that!

**Comment by jdeath** [comment]
2.9.2 works great for fps in HA. Lowered my memory usage by using 5fps. Hopefully no more crashes.
