### ISSUE TITLE
Wyze Doorbell video slowly lags

### ISSUE THREAD

**Issue by 392media** [mrlt8/docker-wyze-bridge#1165]
I am feeding a doorbell (model WYZEDB3) to Frigate without transcoding (rotation). In the past 5 months I start noticing the time of the clock on the doorbell video falls behind other cameras (TP-Links) in rate of a couple seconds per day. If left untouched the gap can widen to 10+seconds.

I turned on verbose logging and notice that ffmpeg is reporting a speed slower than 1.0

```
fra[WyzeBridge] 📖 New client reading from doorbell3.20 bitrate=N/A speed=0.87x     
[WyzeBridge] 📕 Client stopped reading from doorbell
Requesting frame_size=0, bitrate=120, fps=027:50:10.75 bitrate=N/A speed=0.86x     
frame=2084819 fps= 17 q=-1.0 size=N/A time=28:57:22.00 bitrate=N/A speed=0.852x    
```

Restarting wyze bridge docker with bring the speed back to 1.0 at the beginning, but if will slow down gradually again. However, restarting the bridge doesn't make the clock watermark in video stream catch up. It feels like that the video stream output from the camera has been buffered or slowed down.

The only thing that'd fix the displayed clock is to view the camera in Wyze app. It seems the app will notice the time drift and reset the video stream in some way.

I am wondering what the real cause of this issue is, and if the bridge can use the trick that the Wyze app use to detect and fix the slowdown in video.

**Comment by mrlt8** [comment]
Hmm, seems like the camera's clock is slowly drifting. Are you on the latest version of the bridge which is currently v2.8.1? 

Does this API option help?

```
localhost:5000/api/<cam-name>/camera_time/set
```

**Comment by 392media** [comment]
How exactly the API call should be with 'curl'?

**Comment by mrlt8** [comment]
something like this should work:
```
curl http://localhost:5000/api/doorbell/camera_time/set
```

We're using the system time to sync the clock, so you don't need to pass any parameters.

**Comment by 392media** [comment]
I have been running an hourly cronjob calling the camera time sync API. which keeps the clock from drifting behind too much. Thanks
