### ISSUE TITLE
2.8.1 version with super slow issue

### ISSUE THREAD

**Issue by 34t614t1254y** [mrlt8/docker-wyze-bridge#1167]
Hi there,

I use Wyze Bridge 2.8.1 on Home Assistant. (wyze v3 4.36.11.8391)

It has an issue that the frame has been broken. (or skipped)

The log shows up that the stream is super slow.

It really suddenly happens so can't figure out what's wrong.

Everything is fine when I downgrade the version.

**Comment by mrlt8** [comment]
The `super slow` warning can usually be ignored as the bridge is just trying to compensate for the late frames.

Is the actual video showing any significant frame drops?

**Comment by 34t614t1254y** [comment]
https://github.com/mrlt8/docker-wyze-bridge/assets/69705603/58a50921-01ce-415b-812a-f2f539b52233


https://github.com/mrlt8/docker-wyze-bridge/assets/69705603/b4ac39be-3f4e-4162-8ddb-a1ad6ba7f304

The bicycle is by wyze bridge docker and the person is by wyze bridge on Home Assistant.

It's especially serious when the video comes with the night vision.

**Comment by mrlt8** [comment]
@34t614t1254y could you try the dev branch to see if that helps?

**Comment by 34t614t1254y** [comment]
@34t614t1254y Thank you for your reply.

Just installed DEV version on Home Assistant add-on.

Let you know when there is the same issue again!
