### ISSUE TITLE
Addon no longer runs 

### ISSUE THREAD

**Issue by McMoobud** [mrlt8/docker-wyze-bridge#1171]
Hey mrlt8, love your work and your addon very much! 

Unfortunately after the latest update (2.8.3) the add-on no longer starts and I get the following error in the logs: 

[WyzeBridge] Stopping 1 stream
[WyzeBridge] 📕 Client stopped reading from driveway-cam
[WyzeBridge] ❌ '/driveway-cam' stream is down
[WyzeBridge] Stopping MediaMTX...
ice ERROR: 2024/05/02 16:43:22 Failed to read UDP packet: read udp [::]:8189: use of closed network connection
[WyzeBridge] 👋 goodbye!
[WyzeBridge] Stream monitoring stopped

Nothing has changed in the config, and I've tried restarting following the update with no luck. 

Anything I can try to resolve? Any help greatly appreciated :)

**Comment by gdgeist** [comment]
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/13734613/9a09ec9e-2dc7-4f03-bf31-de5a47df6554)
Appears that the config now requires a developer API Key and wont start without it.

**Comment by McMoobud** [comment]
Just found that in the Github Instructions, My apologies for not finding it before I raised this. 

Back up and running with API and Key ID :)
