### ISSUE TITLE
Missing required option 'API_ID' in Docker Wyze Bridge 

### ISSUE THREAD

**Issue by bengthu** [mrlt8/docker-wyze-bridge#1173]
After the last update today, the Wyze Bridge doesn't find my cameras and the UI is stopped and won't start. 
I restarted my HA unit (long restart) and still get the error when I attempt to Start Wyze Bridge:

**Go to configuration:**
Missing required option 'API_ID' in Docker Wyze Bridge (7094bb28_docker_wyze_bridge).

My configuration didn't have the "optional" API Keys before the update. 
I went to Wyze developer and created the ID and Key and added them.
I keep getting the same error. And the API keys aren't saved.

Here's the top few from the logs:
[frontdoor] 📡 Getting 180kb/s HD stream (H264/15fps) via LAN mode (WiFi: 99%) FW: 4.9.9.3006 🔒
[WyzeBridge] ✅ '/frontdoor stream is UP! (3/3)
[WyzeBridge] 📖 New client reading from frontdoor
[WyzeBridge] 🎉 Connecting to WyzeCam V2 - Backyard  on 192.168.1.142
[backyard] 📡 Getting 180kb/s HD stream (H264/15fps) via LAN mode (WiFi: 91%) FW: 4.9.9.3006 🔒
[backyard] [video] super slow
[backyard] WARNING: clear buffer
[WyzeBridge] ✅ '/backyard stream is UP! (3/3)
[WyzeBridge] 📖 New client reading from backyarda
[WyzeBridge] 📕 Client stopped reading from backyard
[backyard] Stream stopped

**Comment by rspierenburg** [comment]
I'm having a similar issue.  Add-on won't start for me with this error popping up.

"Missing required option 'API_ID' in Docker Wyze Bridge (7094bb28_docker_wyze_bridge)"

**Comment by rspierenburg** [comment]
So I went to https://developer-api-console.wyze.com/#/apikey/view and logged in and created an API which I then copied into the Config for the addon.  Was able to start the addon after that.

**Comment by paulseverson3244** [comment]
> So I went to https://developer-api-console.wyze.com/#/apikey/view and logged in and created an API which I then copied into the Config for the addon. Was able to start the addon after that.

This is a solid solution if you have Wyze Cloud. Sadly I do not and as such I cant get a API key. 

Looks to be a issue with the package as I updated as well this morning to the new version and getting the same error as others have noted.

**Comment by mrlt8** [comment]
@paulseverson3244 I believe the wyze developer key should be open to everyone.

Unfortunately wyze has shutdown the v2 and v3 authentication endpoints that we were previously using #1163, so our only options going forward would be an extremely hacky option or using the developer API keys which is the easier option for most.

**Comment by paulseverson3244** [comment]
> @paulseverson3244 I believe the wyze developer key should be open to everyone.
> 
> Unfortunately wyze has shutdown the v2 and v3 authentication endpoints that we were previously using #1163, so our only options going forward would be an extremely hacky option or using the developer API keys which is the easier option for most.

That makes sense, after setting up 2FA and then generating the keys I was able to get it working once again within my HA VM. 
Thanks for the prompt response and app. 

2FA has to be setup within the mobile app. 
https://support.wyze.com/hc/en-us/articles/360024402052-Two-Factor-Authentication

Link to how to setup API keys for anyone else: 
https://support.wyze.com/hc/en-us/articles/16129834216731-Creating-an-API-Key

**Comment by jehlybean** [comment]
> @paulseverson3244 I believe the wyze developer key should be open to everyone.
> 
> Unfortunately wyze has shutdown the v2 and v3 authentication endpoints that we were previously using #1163, so our only options going forward would be an extremely hacky option or using the developer API keys which is the easier option for most.

Is there a way to implement this in the Unraid docker?  I'm not seeing any config other than Login/Pass?

**Comment by Happydish** [comment]
> > @paulseverson3244 I believe the wyze developer key should be open to everyone.
> > Unfortunately wyze has shutdown the v2 and v3 authentication endpoints that we were previously using #1163, so our only options going forward would be an extremely hacky option or using the developer API keys which is the easier option for most.
> 
> Is there a way to implement this in the Unraid docker? I'm not seeing any config other than Login/Pass?

Edit the container,  "Add another Path, Port, Variable, Label or Device" at the bottom, do config type variable, name API_ID, key API_ID, value as your key ID, then do the same for another variable, API_KEY, and your api key

**Comment by jehlybean** [comment]
> > > @paulseverson3244 I believe the wyze developer key should be open to everyone.
> > > Unfortunately wyze has shutdown the v2 and v3 authentication endpoints that we were previously using #1163, so our only options going forward would be an extremely hacky option or using the developer API keys which is the easier option for most.
> > 
> > 
> > Is there a way to implement this in the Unraid docker? I'm not seeing any config other than Login/Pass?
> 
> Edit the container, "Add another Path, Port, Variable, Label or Device" at the bottom, do config type variable, name API_ID, key API_ID, value as your key ID, then do the same for another variable, API_KEY, and your api key

This worked perfectly, thank you for the response.

**Comment by bengthu** [comment]
I was able to get it to accept my Key ID and Api Key by editing the YAML. Note there are 2 save buttons - make sure you click the Save button on the Options section of the YAML editor. Once it took the keys, I was able to start the UI and it works. Thanks!
