### ISSUE TITLE
mtx_event.py breaks for non-root user

### ISSUE THREAD

**Issue by GiZZoR** [mrlt8/docker-wyze-bridge#1174]
I was trying to deploy wyze-bridge manually to a LXC container in proxmox, and noticed that when I tried to run the app as a non-root user I kept getting this error:
`May 03 15:41:49 wyze-bridge gunicorn[3695]:   File "/app/wyzebridge/mtx_event.py", line 56, in open_pipe`
`May 03 15:41:49 wyze-bridge gunicorn[3695]:     self.pipe_fd = os.open(self.FIFO, os.O_RDWR | os.O_NONBLOCK)`
`May 03 15:41:49 wyze-bridge gunicorn[3695]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`May 03 15:41:49 wyze-bridge gunicorn[3695]: PermissionError: [Errno 13] Permission denied: '/tmp/mtx_event'`

I might be wrong, but I think the usage of os.mkfifo [here](https://github.com/mrlt8/docker-wyze-bridge/blob/main/app/wyzebridge/mtx_event.py#L52) seems incorrect. As far as I can tell, os.mkfifo expects a "mode" and not the "flags" from os.open.

Is there some reason for not changing `os.mkfifo(self.FIFO, os.O_RDWR | os.O_NONBLOCK)` to  simply `os.mkfifo(self.FIFO)`?

**Comment by mrlt8** [comment]
hmmm, I think you're right. could you try the latest dev branch?

**Comment by GiZZoR** [comment]
Cloned dev branch this morning. Can confirm that it's working. Thanks!
