### ISSUE TITLE
2.8.3 "Lost connection to the bridge..."

### ISSUE THREAD

**Issue by jplwoodward** [mrlt8/docker-wyze-bridge#1179]
I restarted my 2.7 Docker installation because the CPU started running to hot.  I restarted with 2.8.3, which cannot run...it just say "Lost connection to the bridge..."

Is this a known bug? How can I start 2.7, which worked?

**Comment by mrlt8** [comment]
anything in the logs?

Wyze recently retired some of the authentication endpoints we were using, so you may need to set an API key/ID.

**Comment by jplwoodward** [comment]
YES!  That was the problem.  Thank you.  - John
