### ISSUE TITLE
Potential Remote Access Due to Network Misconfiguration

### ISSUE THREAD

**Issue by ramirezrick** [mrlt8/docker-wyze-bridge#1181]
A simple Shodan search shows all the camera feeds being exposed out to the internet. smh.

**Comment by mrlt8** [comment]
Thanks for the bringing this up. 


This project does not open ports to the outside network.

It seems some users may have inadvertently enabled port forwarding or DMZ to the server hosting the bridge, exposing streams unintentionally.

Although this project is intended for local access only, I'll try implementing an opt-out for the web authentication to prevent users from making the same mistake.

Again, users should NOT enable port forwarding to the bridge from the external network unless they know what they're doing!
