### ISSUE TITLE
ver 2.9.0 - error when using quality > 255

### ISSUE THREAD

**Issue by Anc0dia** [mrlt8/docker-wyze-bridge#1185]
With version 2.9.0 does the higher bitrate setting work with the Wyze firmware for v3/v3 pro?  Anything above 255 gives me an error :

here I tried HD10000: 

[WyzeBridge] 🎬 3 streams enabled
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - back on 192.168.200.105
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - front2k on 192.168.200.107
[front2k] 📡 Getting 10000kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 61%) FW: 4.58.11.8391 🔒
[front2k] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/front2k stream is UP! (3/3)
[back] 📡 Getting 10000kb/s HD stream (H264/20fps) via LAN mode (WiFi: 92%) FW: 4.36.11.8391 🔒
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - side on 192.168.200.106
[back] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/back stream is UP! (3/3)
[side] 📡 Getting 10000kb/s HD stream (H264/20fps) via LAN mode (WiFi: 97%) FW: 4.36.11.8391 🔒
[side] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/side stream is UP! (3/3)
[back] bitrate=16 does not match 10000
[back] Requesting frame_size=0, bitrate=10000, fps=0
[front2k] bitrate=16 does not match 10000
[front2k] Requesting frame_size=3, bitrate=10000, fps=0
[side] bitrate=16 does not match 10000
[side] Requesting frame_size=0, bitrate=10000, fps=0

**Comment by mrlt8** [comment]
whoops, can you try the dev branch?

**Comment by Anc0dia** [comment]
that fixed it.   I also get the correct bitrate when I check via the API:

http://192.168.200.15:5001/api/front2k/bitrate

{"command":"bitrate","payload":null,"response":10000,"status":"success","value":10000}
