### ISSUE TITLE
Refresh/access tokens changing on Wyze end breaks streams/webui

### ISSUE THREAD

**Issue by mgrimace** [mrlt8/docker-wyze-bridge#1208]
## Describe the bug
It appears at least from my end that the access/refresh token provided via `https://my.wyze.com` and visiting `https://services.wyze.com/api/v2/santa/refresh?tag=webview` is changing/rotating today with no specific action taken on my part. When the token changes, it breaks access to feeds and DWB UI is unreachable. I have a API ID+KEY, but it does seem that the cameras require the access token now as well to work properly. Inputting the fresh key fixes the issue until it rotates.

As far as I know I'm not doing anything that would regenerate or rotate the refresh tokens. 

## Environment  (if applicable)
- Affected Camera(s):
- Affected Camera Firmware:
- Affected Bridge Version:
- Bridge type:
  - [ x ] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

**Comment by mrlt8** [comment]
Please use the API Key/ID if you have them, as that is the officially approved method for authenticating with Wyze.

The token-based method is primarily for testing or if you haven't generated an API Key/ID yet.

**Comment by mgrimace** [comment]
> Please use the API Key/ID if you have them, as that is the officially approved method for authenticating with Wyze.
> 
> The token-based method is primarily for testing or if you haven't generated an API Key/ID yet.

Makes sense. 

Testing: when I remove the access/refresh token and only use API Key/ID on 2.9.1, then I get frequent camera disconnects (original doorbell + v1 floodlight), which makes the video lag/disconnect in Scrypted+Homekit. I tried adding `ON_DEMAND=false` but no change. Temporary workaround is back to 2.6.0.

**Comment by mrlt8** [comment]
That's a known issue. some potential fixes for that in the dev branch currently under testing.
