### ISSUE TITLE
Wyze Bridge in Unraid shows cams, but now RTSP needs auth? Cams disappeared in Spy DVR. 

### ISSUE THREAD

**Issue by dev464** [mrlt8/docker-wyze-bridge#1211]
![RTSP locked](https://github.com/mrlt8/docker-wyze-bridge/assets/80529329/4551af43-e7d4-4579-8444-6139da625f8e)
![401 Unauth](https://github.com/mrlt8/docker-wyze-bridge/assets/80529329/03afebf7-7d8d-40bc-b7f2-d29bcd2d9e69)
## Describe the bug

Noticed Cams weren't displaying in Agent-DVR unraid docker. Looks like a username password is now needed to open RTSP streams? 
I had updated my API key a couple months ago and everything was working fine. Tried opening the RTSP stream in VLC player and was also prompted for a username and password, tried my Wyze credentials which didn't work. 

## Environment  (if applicable)
- Affected Camera(s): All Cameras
- Affected Camera Firmware: All Firmware
- Affected Bridge Version: v2.9.2
- Bridge type: Unraid docker

**Comment by mrlt8** [comment]
The username for the stream is `wb` and the password should be unique API Key displayed at the bottom of your WebUI like this:

<img width="447" alt="random key" src="https://github.com/mrlt8/docker-wyze-bridge/assets/67088095/256f64e7-64e2-451a-8308-aeba66cb8e29">

You can change the API key by setting the `WB_API` ENV variable.

If you're running the bridge 100% local, then you can probably set `WB_AUTH=False` to disable authentication and run it like it was before.

Please see the release log for more info:
https://github.com/mrlt8/docker-wyze-bridge/releases/tag/v2.9.0
