### ISSUE TITLE
2.9.3 : RTSP stream not working RTMP is ok

### ISSUE THREAD

**Issue by danny66900** [mrlt8/docker-wyze-bridge#1226]
## Describe the bug
Hi,

I can't get the RTSP feed to work on 2.9.3. RTMP stream works well and HLS too.

Things I tried: 

ON_DEMAND=FALSE
WEB_AUTH=FALSE
ENABLE_AUDIO=FALSE

Nothing looks wrong in the logs 
```

🚀 DOCKER-WYZE-BRIDGE v2.9.3 X86_64 DEV BUILD [2024-05-22t13:46:48.748z] 9af5763

 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] 📚 Using 'auth' from local cache...
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.3:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 📚 Using 'user' from local cache...
[WyzeBridge] 📚 Using 'cameras' from local cache...
[WyzeBridge] 🪄 FILTER ALLOWING: 1 of 4 cams
[WyzeBridge] [+] Adding frontdoor [WYZEDB3]
[WyzeBridge] starting MediaMTX 1.8.2
[WyzeBridge] 🎬 1 stream enabled
[WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - frontdoor on 10.0.0.26
[WyzeBridge] 10.0.0.29 - - [23/May/2024 19:16:38] "GET /api/sse_status HTTP/1.1" 200 -
[frontdoor] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 92%) FW: 4.25.1.333 🔒
[frontdoor] Re-encoding using libx264 [transpose='clock']
[frontdoor] WARNING: Skipping wrong frame_size at start of stream [frame_size=4]
[WyzeBridge] ✅ '/frontdoor stream is UP! (3/3)
[WyzeBridge] 📖 New client reading from frontdoor
[WyzeBridge] 📖 New client reading from frontdoor
[WyzeBridge] 📕 Client stopped reading from frontdoor
[WyzeBridge] 10.0.0.29 - - [23/May/2024 19:17:09] "GET /img/frontdoor.jpg HTTP/1.1" 304 -
[WyzeBridge] 10.0.0.29 - - [23/May/2024 19:17:10] "GET /img/frontdoor.jpg HTTP/1.1" 304 -
```
Any idea what to try to fix this? Thanks alot!

## Environment  (if applicable)
- Affected Camera(s): Wyze cam v2 and Wyze doorbell
- Affected Camera Firmware:
- Affected Bridge Version:
- Bridge type:
  - [ ] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [X] Other : Unraid docker

**Comment by mrlt8** [comment]
are you forwarding the RTSP port? If not, the default should be 8554 like this:
```
rtsp://localhost:8554/frontdoor.jpg
```

**Comment by danny66900** [comment]
> are you forwarding the RTSP port? If not, the default should be 8554 like this:
> 
> ```
> rtsp://localhost:8554/frontdoor.jpg
> ```

I use the following url on my phone/tablet on VLC/Shinobi server :

 rtsp://10.0.0.53:8554/frontdoor

10.0.0.53 is my server static IP.

That url works : rtmp://10.0.0.53:1935/frontdoor

So something looks wrong with the rtsp. 

![Screenshot_20240524-002921](https://github.com/mrlt8/docker-wyze-bridge/assets/157429417/c9ad8560-0c7c-4094-b81f-159679499771)

Any more info/logs I can provide? Thanks

**Comment by delmlund** [comment]
I had the same issue. Racked my brain for a few hours. I use UNRAID and install via apps. The v2.9.3 app has the ports configured wrong in the docker config. 

If memory serves correct the docker had RTSP Host port as 8544. But since the container port was 8554 it would show up in wyze bridge as correct. But the docker port config was wrong so RTSP wouldn't work. Updated the docker config and all is working perfect.

**Comment by danny66900** [comment]
> I had the same issue. Racked my brain for a few hours. I use UNRAID and install via apps. The v2.9.3 app has the ports configured wrong in the docker config.
> 
> If memory serves correct the docker had RTSP Host port as 8544. But since the container port was 8554 it would show up in wyze bridge as correct. But the docker port config was wrong so RTSP wouldn't work. Updated the docker config and all is working perfect.

You're a true hero! Thanks alot!

**Comment by danny66900** [comment]
Fixed
