### ISSUE TITLE
Unable to disable MQTT using MQTT_HOST: false

### ISSUE THREAD

**Issue by cmgenius** [mrlt8/docker-wyze-bridge#1232]
Using the HA addon, I am attempting to disable MQTT functionality. Setting MQTT_HOST to false as instructed in the documentation results in an error as pictured below. Is this a bug or am I doing something incorrectly? 

<img width="1038" alt="Screenshot 2024-05-26 at 21 59 12" src="https://github.com/mrlt8/docker-wyze-bridge/assets/140793955/36521021-be51-411b-b5a8-a953b40c21f2">

**Comment by mrlt8** [comment]
@cmgenius you should be able to disable MQTT by setting `MQTT_DTOPIC` to something other than `homeassistant` in the latest update.

**Comment by jhansche** [comment]
Minor clarification here: that doesn't disable mqtt, right? That just changes the discovery topic, to something that HA isn't listening to? And looking at the commit, it also now disables the auto discovery of the mqtt add-on host.

In other words, if you had previously changed your HA discovery topic to something other than the default, it also wouldn't auto-discover, unless you set the bridge dtopic to match? But now doing so means it also wouldn't auto discover the host, so you'll have to manually configure that as well? 

I guess my point is that it seems to be catering to a default case, and for someone who has changed their HA discovery topic, it means they also have to configure the host explicitly as well. I think it would just be more clear to have an explicit setting for these
* MQTT: on/off
* MQTT Discovery topic: default homeassistant, but can be customized
* MQTT endpoint: host/port, can auto detect HA if running as an add-on

This way you don't have to assign double-meaning to either the host (disable) or the dtopic (homeassistant)

**Comment by mrlt8** [comment]
hmm, I personally don't use HA so I wasn't aware that the discovery topic was configurable. 

Will have to look into it again.

I _really_ wish HA was more like Homebridge as the current config is getting extremely large!
