### ISSUE TITLE
Docker Wyze Brige Ver 2.9.5 with audio enabled not working with Wyze V4 Cams

### ISSUE THREAD

**Issue by rspierenburg** [mrlt8/docker-wyze-bridge#1241]
## Describe the bug
Every since updating from 2.9.4 to 2.9.5 my two Wyze V4s will not stream if Audio is enabled. 

## Environment  (if applicable)
- Affected Camera(s): Frontyard Cam (V4), Backyard Cam (V4)
- Affected Camera Firmware: 4.52.4.9887
- Affected Bridge Version: 2.9.5
- Bridge type:
  - [ ] Docker Compose/Docker Run
  - [X] Home Assistant
  - [ ] Other

Here is the log.

🚀 DOCKER-WYZE-BRIDGE v2.9.5 X86_64

[WyzeBridge] 📚 Using 'auth' from local cache...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] 📚 Using 'user' from local cache...
[WyzeBridge] 📚 Using 'cameras' from local cache...
[WyzeBridge] [+] Adding Fountain Cam [WYZE_CAKP2JFUS]
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://xxx.xxx.xxx.xxx:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] [API] Fetched [6] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Frontyard Cam [HL_CAM4]
[WyzeBridge] ☁️ Pulling "frontyard-cam" thumbnail to /media/wyze/img/frontyard-cam.jpg
[WyzeBridge] [+] Adding Backyard Cam [HL_CAM4]
[WyzeBridge] ☁️ Pulling "backyard-cam" thumbnail to /media/wyze/img/backyard-cam.jpg
[WyzeBridge] [+] Adding Bambu Cam [WYZEC1-JZ]
[WyzeBridge] [+] Adding Storm Cam [GW_GC1]
[WyzeBridge] [GW_GC1] Storm Cam not supported
[WyzeBridge] [+] Adding Playroom Cam [WYZECP1_JEF]
[WyzeBridge] starting MediaMTX 1.1.1
[WyzeBridge] 🎬 6 streams enabled
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Fountain Cam on 192.168.1.xxx
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Backyard Cam on 192.168.1.xxx
[backyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 57%) FW: 4.52.4.9887 🔒
[backyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[backyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[backyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[backyard-cam] WARNING: Audio pipe closed
[backyard-cam] FFMPEG stopped
[fountain-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 53%) FW: 4.36.11.8391 🔒
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Frontyard Cam on 192.168.1.xxx
[fountain-cam] 🔊 Audio Enabled [Source=ALAW/16,000Hz]
[fountain-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[fountain-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/fountain-cam stream is UP! (3/3)
[frontyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.52.4.9887 🔒
[frontyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[frontyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[frontyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[frontyard-cam] WARNING: Audio pipe closed
[frontyard-cam] FFMPEG stopped
[WyzeBridge] 📖 New client reading from fountain-cam
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Backyard Cam on 192.168.1.xxx
[backyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 55%) FW: 4.52.4.9887 🔒
[backyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[backyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[backyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[backyard-cam] WARNING: Audio pipe closed
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Frontyard Cam on 192.168.1.xxx
[backyard-cam] FFMPEG stopped
[frontyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.52.4.9887 🔒
[frontyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[frontyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[frontyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[frontyard-cam] AV_ER_INVALID_ARG
[frontyard-cam] WARNING: AV_ER_INVALID_ARG
[frontyard-cam] WARNING: Audio pipe closed
[frontyard-cam] FFMPEG stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Backyard Cam on 192.168.1.xxx
[backyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 55%) FW: 4.52.4.9887 🔒
[backyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[backyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[backyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[backyard-cam] WARNING: Audio pipe closed
[backyard-cam] FFMPEG stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Frontyard Cam on 192.168.1.xxx
[frontyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.52.4.9887 🔒
[frontyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[frontyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[frontyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[frontyard-cam] AV_ER_INVALID_ARG
[frontyard-cam] WARNING: AV_ER_INVALID_ARG
[frontyard-cam] WARNING: Audio pipe closed
[frontyard-cam] FFMPEG stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Backyard Cam on 192.168.1.xxx
[backyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 55%) FW: 4.52.4.9887 🔒
[backyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[backyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[backyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[backyard-cam] WARNING: Audio pipe closed
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Frontyard Cam on 192.168.1.xxx
[backyard-cam] FFMPEG stopped
[frontyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.52.4.9887 🔒
[frontyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[frontyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[frontyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[frontyard-cam] WARNING: Audio pipe closed
[frontyard-cam] FFMPEG stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Backyard Cam on 192.168.1.xxx
[backyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 57%) FW: 4.52.4.9887 🔒
[WyzeBridge] 🎉 Connecting to WyzeCam V4 - Frontyard Cam on 192.168.1.xxx
[backyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[backyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[backyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[backyard-cam] WARNING: Audio pipe closed
[backyard-cam] FFMPEG stopped
[frontyard-cam] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.52.4.9887 🔒
[frontyard-cam] 🔊 Audio Enabled [Source=AAC/16,000Hz]
[frontyard-cam] [AUDIO] Re-Encode Enabled [AUDIO_CODEC=libopus]
[frontyard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
Option sample_rate not found.
[frontyard-cam] WARNING: Audio pipe closed
[fountain-cam] [video] super slow
[fountain-cam] WARNING: clear buffer
[frontyard-cam] FFMPEG stopped

**Comment by mrlt8** [comment]
Thank you @rspierenburg! Could you try the edge build?

**Comment by rspierenburg** [comment]
Sorry I'm not sure how to get the edge build.

**Comment by airbornetrooper82573** [comment]
> Sorry I'm not sure how to get the edge build.

In your docker compose, change from latest or dev to edge. 

image: mrlt8/wyze-bridge:edge

I can now use audio and view on home app again!

**Comment by rspierenburg** [comment]
And where would I find the Docker compose file in Home Assistant?
