### ISSUE TITLE
Version 2.9.5 breaks MQTT  in Home Assistant.

### ISSUE THREAD

**Issue by DdraigX** [mrlt8/docker-wyze-bridge#1247]
## Describe the bug
Been doing some testing this morning after my motion activation stopped working. It appears that docker wyze bridge version 2.9.5 breaks something with the MQTT Broker.  I'm using the Mosquito Broker and it reports the entities as unavailable after re-discovering them. Attempted restarts of the broker etc, but the  only thing that works is to revert to prior docker version 2.9.4. 

## Environment  (if applicable)
- Affected Camera(s): Wyze Cam V3
- Affected Camera Firmware:  4.36.11.8391
- Affected Bridge Version: 2.9.5
- Bridge type:
  - [ ] Docker Compose/Docker Run
  - [x] Home Assistant
  - [ ] Other

**Comment by spuggy1968** [comment]
I was about to ask a similar question in this regard, since the last update I can no longer control my PAN Cameras.   They do not respond or move.

**Comment by mrlt8** [comment]
Do you have a custom `MQTT_DTOPIC`? Potentially related to #1232.

**Comment by DdraigX** [comment]
> Do you have a custom `MQTT_DTOPIC`? Potentially related to #1232.

I do not believe I do. I'm brand new to HA in the last two weeks, and did a fresh install. After the upgrade I noticed I wasn't getting  any alerts and discovered it uses the MQTT for that. Looking at the MQTT entity's they were all "unavailable" for  the wyze bridge. I restored from a backup and realized what was happening this morning. I'm on 2.9.4 at the moment and works as intended.

**Comment by spuggy1968** [comment]
I should have opened my own Topic, but I feel it is all related, and I just reinstalled version 2.9.4, and the MQTT commands to control Pan Cam V2 work as well, but not in Version 2.9.5.   Do disrespect to DdraigX if you feel I have hijacked your post, but I think it is all related to the same MQTT functionality.   I too have the standard Mosquito Broker running and nothing had changed to it's settings.

**Comment by DdraigX** [comment]
> I should have opened my own Topic.....

No I think it's related also.

**Comment by blockarchitech** [comment]
Just set this up and MQTT entities would not be added to HA. Possibly related? I can share my logs if need be. Mosquito does say there is a new client connecting

**Comment by mrlt8** [comment]
This should be fixed in v2.9.6.

We were trying to read the MQTT settings from the environment before they were loaded from home assistant.

**Comment by blockarchitech** [comment]
Can confirm this is fixed in the latest update. Thanks!
