### ISSUE TITLE
Bitrate Overflow Issue

### ISSUE THREAD

**Issue by prodemydotcom** [mrlt8/docker-wyze-bridge#1250]
## Describe the Bug

When the bitrate is set to a value up to 255, the API response is correct:
REST API URL: `http://127.0.0.1:5000/api/v4/bitrate`
```json
{
  "command": "bitrate",
  "payload": null,
  "response": 255,
  "status": "success",
  "value": 255
}
```

However, setting the bitrate to any value over 255 causes an overflow:
REST API URL: `http://127.0.0.1:5000/api/v4/bitrate/288`
```json
{
  "command": "bitrate",
  "payload": "288",
  "status": "success",
  "value": 288
}
```

The API reports success, but querying the current bitrate shows an incorrect value due to overflow:
REST API URL: `http://127.0.0.1:5000/api/v4/bitrate`
```json
{
  "command": "bitrate",
  "payload": null,
  "response": 32,
  "status": "success",
  "value": 32
}
```

The value 32 is the result of overflow, as 288 wraps around within an 8-bit limit (255 + 32 + 1 = 288).

This overflow causes wyze-bridge to repeatedly attempt to correct the bitrate:
```
wyze-bridge  | [v4] bitrate=32 does not match 288
wyze-bridge  | [v4] Requesting frame_size=3, bitrate=288, fps=0
```

## Expected Behavior

Wyze-bridge should handle the overflow correctly and not attempt to correct the bitrate if the issue is due to overflow.

## Environment

- Affected Camera(s): V4
- Affected Camera Firmware: 4.52.4.9887
- Affected Bridge Version: v2.9.0 X86_64
- Bridge type:
  - [x] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

Thank you for looking into this issue!

**Comment by mrlt8** [comment]
Sorry, I'm unable to replicate. 
Please ensure you're running the latest version of the bridge.

**Comment by prodemydotcom** [comment]
Can confirm latest version does not have this issue. Thank you!
