### ISSUE TITLE
Invalid Leading Whitespace in API ID docker v2.9.6

### ISSUE THREAD

**Issue by hellboyfishman** [mrlt8/docker-wyze-bridge#1252]
When updating to 2.9.6 I see the below error in the logs and the webUI asks for the login information/API ID and KEY.  The space is visible between the opening apostrophe and the API ID.   If I pin the version back to 2.9.5 the docker container starts as expected.   

 [WyzeBridge] [API] Invalid leading whitespace, reserved character(s), or return character(s) in header value: ' XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

- Affected Camera(s): ALL
- Affected Camera Firmware: n/a
- Affected Bridge Version: 2.9.6
- Bridge type:
  - [X] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

**Comment by mrlt8** [comment]
I believe you need to remove the whitespace.

**Comment by hellboyfishman** [comment]
I don't have whitespace in my .env file and I'm using a variable in my docker-compose.yml to reference that value.  It works great in 2.9.5 but not in 2.9.6.   

API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX is what is in my .env file.

**Comment by hellboyfishman** [comment]
@mrlt8  I'm closing this, for some reason it was pruning the space in the compose file prior to 2.9.6.   I think, based on previous testing, that it was just using the value in the .env if it was there without looking to the compose variable.  Perhaps 2.9.6 resolved that issue so it caused mine.   Thanks for the quick response.
