### ISSUE TITLE
Deleted Cams in Wyze App still in Wyze Bridge

### ISSUE THREAD

**Issue by bobster316** [mrlt8/docker-wyze-bridge#1255]
I have deleted some cameras from the wyze app thinking they will be removed from wyze bridge however when running in docker portainer the camera still show up in wyze bridge.. how can i remove them.
Thanks

**Comment by mrlt8** [comment]
Does restarting the container remove them? you may need to set `FRESH_DATA=true` in your docker-compose.yml.

**Comment by bobster316** [comment]
Thanks this is now resolved.
