### ISSUE TITLE
High CPU usage with v2.9.8

### ISSUE THREAD

**Issue by Dleewee** [mrlt8/docker-wyze-bridge#1268]
## Describe the bug
After updating from 2.9.7 to 2.9.8 I am seeing an increase of 15% CPU usage on the host ( going from 10% avg CPU usage up to 25% avg CPU usage). I tracked this increase to docker-wyze-bridge. Rolling back to 2.9.7 indeed dropped CPU usage back to previously expected values. 

## Environment  (if applicable)
- Affected Camera(s): Cam V3 (x2)
- Affected Camera Firmware: 4.36.11.8391
- Affected Bridge Version: 2.9.8
- Bridge type:
  - [X ] Home Assistant

Below are the start-up logs for both versions. I notice there seems to be motion detection enabled in 2.9.8 which didn't seem to be present in the 2.9.7 log. 

> 🚀 DOCKER-WYZE-BRIDGE v2.9.8 X86_64
> 
> [WyzeBridge] [WARN] Credentials are NOT set
>  * Serving Flask app 'frontend'
>  * Debug mode: off
> [WyzeBridge] 📚 Using 'auth' from local cache...
> [WyzeBridge] 📚 Using 'user' from local cache...
> [WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on all addresses (0.0.0.0)
>  * Running on http://127.0.0.1:5000
>  * Running on http://172.30.33.2:5000
> [WyzeBridge] Press CTRL+C to quit
> [WyzeBridge] 📚 Using 'cameras' from local cache...
> [WyzeBridge] [+] Adding Back Yard Cam [WYZE_CAKP2JFUS]
> [WyzeBridge] [+] Adding Front Yard Cam [WYZE_CAKP2JFUS]
> [WyzeBridge] starting MediaMTX 1.1.1
> [WyzeBridge] 🎬 2 streams enabled
> [WyzeBridge] API Motion Events Enabled [interval=1.5]
> [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Yard Cam on 192.168.10.XXX
> [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Front Yard Cam on 192.168.10.X
> [back-yard-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 94%) FW: 4.36.11.8391 🔒
> [back-yard-cam] 🔊 Audio Enabled [Source=ALAW/16,000Hz]
> [back-yard-cam] [AUDIO] Re-Encode for RTSP compatibility [codec_out='pcm_mulaw']
> [front-yard-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 63%) FW: 4.36.11.8391 🔒
> [front-yard-cam] 🔊 Audio Enabled [Source=ALAW/16,000Hz]
> [front-yard-cam] [AUDIO] Re-Encode for RTSP compatibility [codec_out='pcm_mulaw']
> [back-yard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
> [WyzeBridge] ✅ '/back-yard-cam stream is UP! (3/3)
> [WyzeBridge] 📖 New client reading from back-yard-cam
> [front-yard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
> [WyzeBridge] ✅ '/front-yard-cam stream is UP! (3/3)
> [WyzeBridge] 📖 New client reading from front-yard-cam
> [WyzeBridge] 📕 Client stopped reading from back-yard-cam
> [WyzeBridge] 📖 New client reading from back-yard-cam
> [WyzeBridge] 📕 Client stopped reading from front-yard-cam
> [WyzeBridge] 📖 New client reading from front-yard-cam
> [front-yard-cam] [video] super slow
> [front-yard-cam] WARNING: clear buffer
> [WyzeBridge] [MOTION] Motion detected on front-yard-cam at  12:41:13
> [WyzeBridge] Stopping 2 streams
> [back-yard-cam] WARNING: Audio pipe closed
> [WyzeBridge] Stream monitoring stopped
> [back-yard-cam] Stream stopped
> [front-yard-cam] WARNING: Audio pipe closed
> [front-yard-cam] Stream stopped
> [WyzeBridge] Stopping MediaMTX...
> [WyzeBridge] 👋 goodbye!
> [WyzeBridge] 🏠 Home Assistant Mode
> 
> 🚀 DOCKER-WYZE-BRIDGE v2.9.7 X86_64
> 
> [WyzeBridge] [WARN] Credentials are NOT set
>  * Serving Flask app 'frontend'
>  * Debug mode: off
> [WyzeBridge] 📚 Using 'auth' from local cache...
> [WyzeBridge] 📚 Using 'user' from local cache...
> [WyzeBridge] 📚 Using 'cameras' from local cache...
> [WyzeBridge] [+] Adding Back Yard Cam [WYZE_CAKP2JFUS]
> [WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on all addresses (0.0.0.0)
>  * Running on http://127.0.0.1:5000
>  * Running on http://172.30.33.2:5000
> [WyzeBridge] Press CTRL+C to quit
> [WyzeBridge] [+] Adding Front Yard Cam [WYZE_CAKP2JFUS]
> [WyzeBridge] starting MediaMTX 1.1.1
> [WyzeBridge] 🎬 2 streams enabled
> [WyzeBridge] API Motion Events Enabled [interval=1.5]
> [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Front Yard Cam on 192.168.10.XXX
> [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Yard Cam on 192.168.10.XXX
> [back-yard-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 98%) FW: 4.36.11.8391 🔒
> [back-yard-cam] 🔊 Audio Enabled [Source=ALAW/16,000Hz]
> [back-yard-cam] [AUDIO] Re-Encode for RTSP compatibility [codec_out='pcm_mulaw']
> [front-yard-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 54%) FW: 4.36.11.8391 🔒
> [front-yard-cam] 🔊 Audio Enabled [Source=ALAW/16,000Hz]
> [front-yard-cam] [AUDIO] Re-Encode for RTSP compatibility [codec_out='pcm_mulaw']
> [front-yard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
> [WyzeBridge] ✅ '/front-yard-cam stream is UP! (3/3)
> [WyzeBridge] 📖 New client reading from front-yard-cam
> [back-yard-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
> [WyzeBridge] ✅ '/back-yard-cam stream is UP! (3/3)
> [WyzeBridge] 📖 New client reading from back-yard-cam
> [WyzeBridge] 📕 Client stopped reading from front-yard-cam
> [WyzeBridge] 📖 New client reading from front-yard-cam

**Comment by dcw88** [comment]
I have the same issue.  CPU usage went up to 70% after updating to v2.9.8.  I have revert back to v2.9.7.

**Comment by mrlt8** [comment]
Are you by any chance using the HLS streams?

**Comment by Dleewee** [comment]
Afraid not, only using rtsp.

Possibly noteworthy: I do not have GPU acceleration on the host, so perhaps
something changed causing transcoding?

**Comment by dcw88** [comment]
> This should be fixed in v2.9.9.

Yes, I can confirm that v2.9.9 resolved the CPU high usage issue.  Thanks!
