### ISSUE TITLE
unraid RSTP port is 8554 not 8544. thanks

### ISSUE THREAD

**Issue by jjone** [mrlt8/docker-wyze-bridge#1277]
## Describe the bug
Provide a clear and concise description of the issue and include logs if applicable.

## Environment  (if applicable)
- Affected Camera(s):
- Affected Camera Firmware:
- Affected Bridge Version:
- Bridge type:
  - [ ] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

**Comment by mrlt8** [comment]
Thanks. I made a pull request to update the template.
