### ISSUE TITLE
Incorrect credentials in 'dev' branche ?

### ISSUE THREAD

**Issue by JA16122000** [mrlt8/docker-wyze-bridge#1279]
## incorrect credentials?
Provide a clear and concise description of the issue and include logs if applicable.

## Environment  (if applicable)
- Affected Camera(s):
- Affected Camera Firmware:
- Affected Bridge Version:
- Bridge type:
  - [x ] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

---------------------------------

[WyzeBridge] [AUTH] Using wb_api from /tokens/wb_api
🚀 DOCKER-WYZE-BRIDGE v2.9.10 ARMV7L DEV BUILD [2024-07-03t07:00:14.465z] f2a8495
[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] [AUTH] WB_AUTH=True
[WyzeBridge] [AUTH] Clearing local auth data [file_path='/tokens/wb_api']
[WyzeBridge] [AUTH] WB_USERNAME=Mulderij
[WyzeBridge] [AUTH] WB_PASSWORD=j********                                                                     <<==== incorrect
[WyzeBridge] [AUTH] WB_API=blob
[WyzeBridge] [MTX] Custom stream auth enabled
[WyzeBridge] [MTX] Auth [blob:blob] paths='all'
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [2] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Voortuin [HL_CAM3P]
[WyzeBridge] [MTX] 📹 Will record 1800s clips to /Record/voortuin/voortuin_%Y_%m_%d_%H_%M_%S.mp4
[WyzeBridge] [+] Adding Achtertuin [HL_CAM3P]
[WyzeBridge] [MTX] 📹 Will record 1800s clips to /Record/achtertuin/achtertuin_%Y_%m_%d_%H_%M_%S.mp4
[WyzeBridge] [MTX] starting MediaMTX 1.8.3
[WyzeBridge] 🎬 2 streams enabled
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Voortuin on 192.168.178.70
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Achtertuin on 192.168.178.69
[voortuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 46%) FW: 4.58.12.9751 🔒
[achtertuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.58.12.9751 🔒
[voortuin] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[achtertuin] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/voortuin stream is UP! (3/3)
[WyzeBridge] ✅ '/achtertuin stream is UP! (3/3)
[WyzeBridge] 195.240.59.44 - - [03/Jul/2024 10:45:03] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 195.240.59.44 - - [03/Jul/2024 10:45:06] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 195.240.59.44 - - [03/Jul/2024 10:45:08] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 195.240.59.44 - - [03/Jul/2024 10:45:10] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 195.240.59.44 - - [03/Jul/2024 10:45:11] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:57:13] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:57:15] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:57:16] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:57:18] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:59:35] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:59:38] "GET /favicon.ico HTTP/1.1" 404 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:59:45] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:59:47] "GET /?video HTTP/1.1" 401 -
[WyzeBridge] 173.239.217.163 - - [03/Jul/2024 10:59:54] "GET /?video HTTP/1.1" 401 -

**Comment by GiZZoR** [comment]
Have you tried deleting the wb_api token file, and letting the app recreate it?
From the 1st log line you posted: `[WyzeBridge] [AUTH] Using wb_api from /tokens/wb_api`
