### ISSUE TITLE
BUG: Doorbell WYZEDB3 Stopped Working

### ISSUE THREAD

**Issue by jdeath** [mrlt8/docker-wyze-bridge#1294]
### Describe the bug

Doorbells (Firmware 4.25.1.333, model WYZEDB3 ) do not connect and get timeout errors. Only noticed as had a power outage. Rolled back to 2.9.10 worked (edit, figured this out later)

Doorbells work in the app, however the ON with a circle around it does not show for my two doorbells. 

[WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Side Door on 192.168.1.XXX
[WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.1.XXX
[WyzeBridge] ⏰ Timed out connecting to Front door.
[WyzeBridge] ⏰ Timed out connecting to Side Door.

### Affected Bridge Version

2.9.11 

### Bridge type

Home Assistant

### Affected Camera(s)

WYZEDB3 

### Affected Camera Firmware

4.25.1.333

**Comment by tdashmike** [comment]
I have the same problem. It was working fine until right before 2 PM (EST) today. Times out but works fine in app, IP it's trying to connect to also seems correct.

**Comment by mrlt8** [comment]
Can you try **Restart** > **reload camera data** in the WebUI?

**Comment by jdeath** [comment]
[WyzeBridge] [CONTROL] ☁️ Sending restart to side-door via Wyze API
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:27:28] "GET /api/side-door/power/restart HTTP/1.1" 200 -
[WyzeBridge] ⏰ Timed out connecting to Side Door.

**Comment by tdashmike** [comment]
> Can you try **Restart** > **reload camera data** in the WebUI?

`
[WyzeBridge] [API] Fetched [8] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET / HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /img/doorbell.png HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /img/crawl-space-cam.png HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /img/doorbell.png HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /img/crawl-space-cam.png HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /img/doorbell.png HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [13/Jul/2024 21:34:53] "GET /img/crawl-space-cam.png HTTP/1.1" 304 -
[WyzeBridge] Stopping MediaMTX...
[WyzeBridge] Stopping 2 streams
[crawl-space-cam] WARNING: Audio pipe closed
[crawl-space-cam] Stream stopped
[WyzeBridge] Stream monitoring stopped
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [8] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🪄 FILTER BLOCKING: 6 of 8 cams
[WyzeBridge] [+] Adding Crawl Space Cam [WYZE_CAKP2JFUS]
[WyzeBridge] [+] Adding Doorbell [WYZEDB3]
[WyzeBridge] starting MediaMTX 1.1.1
[WyzeBridge] 🎬 2 streams enabled
[WyzeBridge] API Motion Events Enabled [interval=1.5]
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Crawl Space Cam on 192.168.7.202
[WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Doorbell on 192.168.7.221
[crawl-space-cam] 📡 Getting 180kb/s HD stream (H264/15fps) via LAN mode (WiFi: 100%) FW: 4.36.11.8391 🔒
[crawl-space-cam] 🔊 Audio Enabled [Source=ALAW/16,000Hz]
[crawl-space-cam] [AUDIO] Re-Encode for RTSP compatibility [codec_out='pcm_mulaw']
[crawl-space-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅ '/crawl-space-cam stream is UP! (3/3)
[WyzeBridge] 📖 New client reading from crawl-space-cam
[WyzeBridge] 📕 Client stopped reading from crawl-space-cam
[WyzeBridge] ⏰ Timed out connecting to Doorbell.
`

**Comment by automiketic** [comment]
I'm having this exact same issue except mine started after updating from v2.7 of wyze-bridge to the latest

**Comment by cheme75** [comment]
Although disappointing to hear of a potential new bug, I'm relieved to know it's not just me. My db3 stopped working after updating to the latest 2.9.11 - tried same things as mentioned by others and still getting same problem - connection timed out. No changes to email, pw, api ID or api key. Re-pulled, restarted, retried up -d - nothing is working. Baffling to me since it's my only cam at present and it was working normally in the bridge.

**Comment by cheme75** [comment]
> I'm having this exact same issue except mine started after updating from v2.8.1 of wyze-bridge to the latest version. Reverting back to 2.8.1 resolved the issue. 

How does one revert? I use the .yml and docker-compose in windows.

**Comment by jdeath** [comment]
> Reverting back to 2.8.1 resolved the issue.

Thanks. 2.8.1 worked for me. Strange, since 2.9.10 worked before (but does not now). I revert in home assistant, so cannot help with other methods.

**Comment by tdashmike** [comment]
> > Reverting back to 2.8.1 resolved the issue.
> 
> Thanks. 2.8.1 worked for me. Strange, since 2.9.10 worked before (but does not now). I revert in home assistant, so cannot help with other methods.

How did you revert in HA?

**Comment by automiketic** [comment]
> > I'm having this exact same issue except mine started after updating from v2.8.1 of wyze-bridge to the latest version. Reverting back to 2.8.1 resolved the issue.
> 
> How does one revert? I use the .yml and docker-compose in windows.

To revert I ran docker compose rm -f then modified the docker-compose.yml file. The image line went from:
 image: mrlt8/wyze-bridge:latest to  image: mrlt8/wyze-bridge:2.8.1
 Then ran docker compose pull then started the container again as normal.

**Comment by tdashmike** [comment]
> > > Reverting back to 2.8.1 resolved the issue.
> > 
> > 
> > Thanks. 2.8.1 worked for me. Strange, since 2.9.10 worked before (but does not now). I revert in home assistant, so cannot help with other methods.
> 
> How did you revert in HA?

I figured it out. Thanks.

https://www.youtube.com/watch?v=yxbZAv0oYcE

**Comment by jdeath** [comment]
> How did you revert in HA?

Download the raw files (readme, config.json), in this directory: https://github.com/mrlt8/docker-wyze-bridge/tree/main/home_assistant

Place them in /addons/dockerwyzebridge/

edit config.json for the version you want to run. Go to addon store, under local addons, you should have an entry. Install that.

**Comment by cheme75** [comment]
> > > I'm having this exact same issue except mine started after updating from v2.8.1 of wyze-bridge to the latest version. Reverting back to 2.8.1 resolved the issue.
> > 
> > 
> > How does one revert? I use the .yml and docker-compose in windows.
> 
> To revert stop the container then run docker compose rm -f. Next modify the docker-compose.yml file. Change the image line from: image: mrlt8/wyze-bridge:latest to: image: mrlt8/wyze-bridge:2.8.1 Then run docker compose pull and start the container again as normal.

Ok. Thx. Will try in morning.

**Comment by cheme75** [comment]
> Can you try **Restart** > **reload camera data** in the WebUI?

Web ui control shows stream enable, result is state:success in a green popup, trying stream start, result is state:error in red popup

**Comment by mrlt8** [comment]
This should be fixed in v2.9.12. Autocomplete typo was using the `model_name` instead of `product_model` when setting the bitrate on connection causing some cameras like the doorbell to get stuck.

**Comment by tdashmike** [comment]
@mrlt8 Confirmed fixed on 2.9.12. Thank you.

**Comment by cheme75** [comment]
Also confirming fixed for my db3 cam. Thx for the quick fix!

**Comment by jdeath** [comment]
Fixed. Thank you. Closing
