### ISSUE TITLE
BUG: v2.10.0 - Authentication problem - it's asking for username/password.

### ISSUE THREAD

**Issue by bengthu** [mrlt8/docker-wyze-bridge#1304]
### Describe the bug

Unable to stream videos after update. I'm using the API with web auth FALSE.

ENABLE_AUDIO: false
ON_DEMAND: true
WB_AUTH: false
MOTION_API: false
MQTT: true
CAM_OPTIONS: []
MQTT_DTOPIC: homeassistant
WYZE_EMAIL: mywyzEmail@gmail.com
WYZE_PASSWORD: mySecretWyzePassword
API_ID: theAPIid...-aa7755569ca4
API_KEY: theAPIkey...2pixQ5ccC
NET_MODE: ANY
SNAPSHOT: Disable
SUBSTREAM: false
FRESH_DATA: true

**I can see the streams in the web UI**, but when I attempt to view them using VLC, it asks for username/password.

rtsp://homeassistant.local:8554/blackalpha

"RSTP authentication: Please enter a valid login name and a password."

These don't work:
WYZE_EMAIL: mywyzEmail@gmail.com
WYZE_PASSWORD: mySecretWyzePassword

Of course they also fail to stream via Home Assistant.

From the log:
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] [AUTH] WB_AUTH=False
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [5] cameras

### Affected Bridge Version

2.10.0 

### Bridge type

Home Assistant

### Affected Camera(s)

All

**Comment by grinddking** [comment]
same issue here, reverted back to old version until correction.

**Comment by mrlt8** [comment]
Thanks for the report. 

Temporary fix is to select **Restart** > **clear cache and reconnect** from the bridge's webUI.

**Comment by bengthu** [comment]
Thanks for the quick fix! And thanks for all your work on this integration!

**Comment by ez2kal** [comment]
I am using the latest version, of docker wyze bridge but I have not been able to pass authentication step even once. I am using the correct email, password, key Id and API key ( using wyze portal) but each time after submitting, it refreshes  back to blank log in page with no error. I don't know what else I can do.
