### ISSUE TITLE
BUG: Login screen asking for Email, Password, Key ID and API key

### ISSUE THREAD

**Issue by dobage** [mrlt8/docker-wyze-bridge#1318]
### Describe the bug

![Screenshot 2024-08-10 063806](https://github.com/user-attachments/assets/aec3e9eb-dc68-49ad-95cf-ea02ac913b72)

This is the screen I get when going to 192.168.2.5:5000

I have tried the wbadmin, and my  real email for "Email" I have tried to set it with the WB_USERNAME

I have tried the first part of my email before the @, I have tried to set it with the WB_PASSWORD, I have tried my combination Wyze web site login and password, I have tried my Wyze developer web page login and password.

I do have the correct Key ID and API key.  I even deleted them and tried them again.  If feels like I am getting the wrong login screen and I should be adding the Key ID and API key on a security page with in the WebUI.

Any help would be great thanks

### Affected Bridge Version

2.10..1

### Bridge type

Docker Run/Compose

### Affected Camera(s)

all

### Affected Camera Firmware

all

**Comment by mrlt8** [comment]
Sorry for the confusion. You'll need to provide your wyze credentials and the API ID and API Key for the bridge to fetch the relevant p2p information for each of the cameras tied to the account.

The `wbadmin` and email password are to access the bridge after it authenticates withe wyze.

**Comment by dobage** [comment]
I have used the email I use for Wyze both the web app and the [wyze service ](https://developer-api-console.wyze.com/) site and both passwords and still can not log in.  It appears like it is trying but then brings me back to the login screen with no errors?

**Comment by mrlt8** [comment]
Can you see if there are any error in your docker container? The wyze authentication server seems to block some commercial IP addresses and/or VPN providers.

**Comment by dobage** [comment]
Ahh very good call Surfshark VPN wan routing traffic for Docker.  Thank you.
