### ISSUE TITLE
Video stream ports connection failed

### ISSUE THREAD

**Issue by User8395** [mrlt8/docker-wyze-bridge#1323]
### Describe the bug

I cannot access any video stream. If I go to the port directly, it says failed to connect.

### Affected Bridge Version

2.10.1

### Bridge type

Home Assistant

### Affected Camera(s)

Everything 

### Affected Camera Firmware

Latest

**Comment by mrlt8** [comment]
Is the bridge starting up correctly? can you check the logs?

**Comment by User8395** [comment]
It might be because i didn't forward the ports, Ill try that and get back to you

**Comment by User8395** [comment]
Ok everything's fine now!

I never forwarded the ports
