### ISSUE TITLE
FEATURE REQUEST: Add "loop" recording option

### ISSUE THREAD

**Issue by puterboy** [mrlt8/docker-wyze-bridge#1359]
Would be great to have the ability to do "loop recording"
i.e. specify max time of loop (say 24 hours) and then bridge will continuously record  and save last 24 hours, overwriting anything older.

This ensures that you don't run out of space as otherwise presumably recordings would grow forever...

**Comment by mrlt8** [comment]
Have you tired:

```yaml
- RECORD_KEEP=24h
```

**Comment by puterboy** [comment]
My sincere apologies, I somehow didn't see the full manual.
I now see that feature under advanced and will try that out.
I am closing the issue -- again sorry for wasting your time.
