### ISSUE TITLE
Difference between V3 Pro and V4

### ISSUE THREAD

**Issue by JA16122000** [mrlt8/docker-wyze-bridge#1364]
I notice a difference between the V3 Pro and the V4.
The V3 Pro works perfectly, stably, and right on time.
However, the V4 lags behind by about 20 seconds.

In the Wyze app, there is no apparent difference between the V3 Pro and the V4.

**Comment by JA16122000** [comment]
nvm.

It has to do with the audio.

- ENABLE_AUDIO=False 

is the solution.

**Comment by mrlt8** [comment]
@JA16122000 Can you try another audio codec to see if that helps?
