### ISSUE TITLE
cam nickname is not pulled correctly

### ISSUE THREAD

**Issue by SgtBatten** [mrlt8/docker-wyze-bridge#139]
My cam is available at the url ending in /wyze-cam-v3 instead of /entry.

In the Wyze app the camera is called "Entry"

Running the latest bridge version as a HA addon. 
Wyze cam v3 is on firmware 4.36.2.5

**Comment by mrlt8** [comment]
Weird. Did you rename the cam after starting the bridge or is "Entry" the name of a group instead of the camera?
 
Either day, you should be able to flush the cache by turning on FRESH_DATA. (API_THUMB should also pull a fresh list of cams).

**Comment by SgtBatten** [comment]
That must have been the cause. I deleted cameras.pickle and restarted the add-on and now I can see in the pickle it says Entry.
