### ISSUE TITLE
v0.3.0 doesn't like FILTER_NAMES

### ISSUE THREAD

**Issue by terryhonn** [mrlt8/docker-wyze-bridge#14]
Blew away my old install this morning and started fresh. If I leave FILTER_NAMES out of the wyze-bridge envs, it starts fine and tries to publish to the rtsp-server.... 

But, if I include the FILTER_NAMES option, it does this:

Starting wyze-bridge ... done
Starting rtsp-server ... done
Attaching to wyze-bridge, rtsp-server
rtsp-server       | 2021/07/08 16:37:42 I [0/0] rtsp-simple-server v0.16.4
rtsp-server       | 2021/07/08 16:37:42 I [0/0] [RTSP] TCP listener opened on :8554
rtsp-server       | 2021/07/08 16:37:42 I [0/0] [RTMP] listener opened on :1935
rtsp-server       | 2021/07/08 16:37:42 I [0/0] [HLS] listener opened on :8888
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
rtsp-server       | 2021/07/08 16:37:43 I [0/0] [RTSP] [conn 192.168.1.109:56636] opened
rtsp-server       | 2021/07/08 16:37:43 I [0/0] [RTSP] [conn 192.168.1.109:56636] ERR: no one is publishing to path 'front-porch-cam'
rtsp-server       | 2021/07/08 16:37:43 I [0/0] [RTSP] [conn 192.168.1.109:56636] closed
rtsp-server       | 2021/07/08 16:37:44 I [0/0] [RTSP] [conn 192.168.1.109:56637] opened
rtsp-server       | 2021/07/08 16:37:44 I [0/0] [RTSP] [conn 192.168.1.109:56637] ERR: no one is publishing to path 'gate-cam'
rtsp-server       | 2021/07/08 16:37:44 I [0/0] [RTSP] [conn 192.168.1.109:56637] closed
rtsp-server       | 2021/07/08 16:37:44 I [0/0] [RTSP] [conn 192.168.1.109:56633] opened
rtsp-server       | 2021/07/08 16:37:44 I [0/0] [RTSP] [conn 192.168.1.109:56633] ERR: no one is publishing to path 'drive-cam'
rtsp-server       | 2021/07/08 16:37:44 I [0/0] [RTSP] [conn 192.168.1.109:56633] closed
wyze-bridge exited with code 1
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching auth data from local cache...
wyze-bridge       | Fetching auth data from wyze...
wyze-bridge       | Fetching user data from wyze...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Fetching cameras data from wyze...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given
wyze-bridge       | STARTING DOCKER-WYZE-BRIDGE v0.3.0
wyze-bridge       | Fetching user data from local cache...
wyze-bridge       | Fetching cameras data from local cache...
wyze-bridge       | Traceback (most recent call last):
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 115, in <module>
wyze-bridge       |     wyze_bridge().run()
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 111, in run
wyze-bridge       |     for camera in self.filtered_cameras():
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 50, in filtered_cameras
wyze-bridge       |     filtered = list(filter(self.env_filter,cams))
wyze-bridge       |   File "/opt/wyzecam/cameras.py", line 16, in env_filter
wyze-bridge       |     return True if cam.nickname.upper() in self.get_env('FILTER_NAMES') or cam.mac in self.get_env('FILTER_MACS') or cam.product_model in self.get_env('FILTER_MODEL') or self.model_names.get(cam.product_model) in self.get_env('FILTER_MODEL') else False
wyze-bridge       | TypeError: get_env() takes 1 positional argument but 2 were given

Until I stop it. Thoughts?

**Comment by mrlt8** [comment]
Good catch! Should be fixed v0.3.1! 
Please test it out and let me know!

**Comment by terryhonn** [comment]
v0.3.1 is filtering by name correctly now, thank you!
