### ISSUE TITLE
ERROR: Invalid interpolation format for "environment" option

### ISSUE THREAD

**Issue by mudi-il** [mrlt8/docker-wyze-bridge#140]
I'm getting errors for both the email & password when running <docker-compose up --build >
1. I assume the curly brackets are part of the value?
2.  I have a + sign within my email address and a $ sign in the middle of my password.  is this an issue?

thanks

**Comment by mrlt8** [comment]
Curly brackets are not required - they're there for Portainer compatibility, so you can just ignore that.

`+` should not be an issue, but `$` will cause issues with docker and need to be escaped with an extra `$`. e.g., pa$$word should be entered as `pa$$$$word`

Sorry about the confusion! I should probably add something about that in the readme.

**Comment by mudi-il** [comment]
Thanks for the prompt reply!
I decided after asking the question to reset my email address and password so now they don't contain any 'problematic' characters.
yet,  I still get an error. 
I replaced my email and password  with * in this reply:

WYZE_EMAIL=$*******@gmail.com # Replace with wyze email
WYZE_PASSWORD=$*********** # Replace with wyze password**

WARNING: The ***i variable is not set. Defaulting to a blank string.
WARNING: The ***** variable is not set. Defaulting to a blank string.
Recreating wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 2021/09/22 13:35:08 I [0/0] rtsp-simple-server v0.17.3
wyze-bridge    | 2021/09/22 13:35:08 I [0/0] [RTSP] TCP listener opened on :8554
wyze-bridge    | 2021/09/22 13:35:08 I [0/0] [RTMP] listener opened on :1935
wyze-bridge    | 2021/09/22 13:35:08 I [0/0] [HLS] listener opened on :8888
wyze-bridge    | 2021/09/22 13:35:08 I [0/0] [API] listener opened on 127.0.0.1:9997
wyze-bridge    | Set your WYZE_PASSWORD credentials and restart the container.

**Comment by mrlt8** [comment]
The extra `$` can also be removed (again only there for Portainer compatibility)

**Comment by mudi-il** [comment]
Perfect, it's working! thanks again
