### ISSUE TITLE
connecting to wyze with multifactor authentication enabled

### ISSUE THREAD

**Issue by nijhawank** [mrlt8/docker-wyze-bridge#15]
I have multi factor authentication enabled with my wyze account, how do we login. I see only email and password as the two values for login.

**Comment by mrlt8** [comment]
The upstream [wyzecam library](https://github.com/kroo/wyzecam) we're using doesn't support 2fa.

I'll still take a look and see if there's anything we might be able to do.

**Comment by mrlt8** [comment]
Quick update - I was able to get two-factor working!
Now I just need to figure out a way to allow user interaction with the docker container to input the verification code..
