### ISSUE TITLE
Syntax for ROTATE_DOOR

### ISSUE THREAD

**Issue by nwhistler** [mrlt8/docker-wyze-bridge#150]
What is the syntax for the `ROTATE_DOOR` env variable? I tried =true and even = camera name but couldn't get it.

Thank you for adding this feature, I am excited to use it.

**Comment by mrlt8** [comment]
It *should* work with `ROTATE_DOOR=true` when the camera is reporting the product_model as `WYZEDB3`. 
are you on a newer firmware?

**Comment by nwhistler** [comment]
hmmm, I am on Firmware version 4.25.0.267. I tried again with a lowercase `true` and still didn't work. I can get it to work with `- FFMPEG_CMD_FRONTDOORBELL= -i - -vcodec libx264 -vf transpose=1 -f rtsp rtsp://0.0.0.0:8554/` but that defeats your code.

**Comment by nwhistler** [comment]
I turned on debugging, captured the output, and redacted IP addresses if that helps
[debug.txt](https://github.com/mrlt8/docker-wyze-bridge/files/7249623/debug.txt)
s.

**Comment by mrlt8** [comment]
Looks like you're still running v0.6.10 and `ROTATE_DOOR` was added in v0.7.0+.

**Comment by nwhistler** [comment]
Ah yes, you are correct. One last question, now that I have v0.7.0 and `ROTATE_DOOR` enabled I am getting `[FFMPEG] Wrong resolution: 4` for the Doorbell. What's the best way to resolve or ignore that?

**Comment by nwhistler** [comment]
The rest of my issues are tracked in: https://github.com/mrlt8/docker-wyze-bridge/issues/133
