### ISSUE TITLE
Official RTSP support for Wyze Cam v3

### ISSUE THREAD

**Issue by lanrat** [mrlt8/docker-wyze-bridge#154]
Official RTSP support for Wyze Cam v3 was finally released.

https://support.wyze.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP

Would it be worthwhile to add support for the new RTSP endpoints be added to this bridge?

**Comment by mrlt8** [comment]
Interesting idea. The API returns the IPs of the cameras, so we could ping them at startup to see if an RTSP stream is available and use those in rtsp-simple-server. This could potentially also work with the raw h264 streams from the [FiveLeavesLeft](https://github.com/FiveLeavesLeft/WyzeCameraLiveStream) firmware.
Will look into this.

**Comment by AdiAbuAli** [comment]
But we'll loose the non RTSP FW, which Wyze maintain better than RTSP FW....at leaset for me, the main value of mrlt8 project, that it keep the robustness of non RTSP wyze FW, and bridge the gap with RTSP  (sure still waiting for Audio and DTLS).

below is their statement about new RTSP FW:
"We don't have the resources to keep developing two branches of firmware for Wyze Cam v2, Wyze Cam v3, and Wyze Cam Pan. At this time, we are not committing to ongoing maintenance for RTSP firmware. We will deliver security updates as needed"
"Please note that features and functions added after the version will not be available. AI and other Cam Plus-related features may be unstable for cameras using this firmware so it is recommended to only use it if you plan to use RTSP full-time."
https://support.wyze.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP
