### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by MRliqiang91** [mrlt8/docker-wyze-bridge#155]
Hi, my RTSP stream seems to drop after around 10minutes or so. managed to catch this timeout error before all the stream drops.

Is this a setting on the router that needs to be changed? any help will be very much appreciated!

wyze-bridge    | 2021/09/29 02:43:44 I [3/3] [RTSP] [conn 127.0.0.1:48520] ERR: read tcp 127.0.0.1:8554->127.0.0.1:48520: i/o timeout
wyze-bridge    | 2021/09/29 02:43:44 I [3/3] [RTSP] [conn 127.0.0.1:48520] closed
wyze-bridge    | 2021/09/29 02:43:44 I [2/2] [path patio-outdoor-cam] destroyed
wyze-bridge    | 2021/09/29 02:43:44 I [2/2] [RTSP] [session 584178824] closed
wyze-bridge    | 2021/09/29 02:43:44 I [2/2] [RTSP] [conn 172.16.57.1:52524] closed
wyze-bridge    | 2021/09/29 02:43:44 I [2/2] [RTSP] [session 850022658] closed
wyze-bridge    | 2021/09/29 02:43:45 I [2/2] [RTSP] [conn 172.16.57.1:52556] opened
wyze-bridge    | 2021/09/29 02:43:45 I [2/2] [path patio-outdoor-cam] created
wyze-bridge    | 2021/09/29 02:43:45 I [2/2] [RTSP] [conn 172.16.57.1:52556] ERR: no one is publishing to path 'patio-outdoor-cam'
wyze-bridge    | 2021/09/29 02:43:45 I [2/2] [RTSP] [conn 172.16.57.1:52556] closed
wyze-bridge    | 2021/09/29 02:43:46 I [2/2] [RTSP] [conn 172.16.57.1:52558] opened

**Comment by MRliqiang91** [comment]
Just an update. The errors changed once I updated to the latest 0.7v.

wyze-bridge    | 🎬 STARTING ALL 3 CAMERAS
wyze-bridge    | 2021/09/30 10:41:12 [WyzeBridge] Starting rtsp-simple-server v0.17.3
wyze-bridge    | 2021/09/30 10:41:15 [sitting area] 🎉 Starting HD 60kb/s Stream for WyzeCam V3 in "LAN mode" FW: 4.36.3.18 IP: 192.168.1.122 WiFi: 96%
wyze-bridge    | 2021/09/30 10:41:16 [Interior Cam] 🎉 Starting HD 60kb/s Stream for WyzeCam V3 in "LAN mode" FW: 4.36.3.18 IP: 192.168.1.125 WiFi: 100%
wyze-bridge    | 2021/09/30 10:41:16 [Patio Outdoor Cam] 🎉 Starting HD 60kb/s Stream for WyzeCam V3 in "LAN mode" FW: 4.36.3.18 IP: 192.168.1.121 WiFi: 100%
wyze-bridge    | 2021/09/30 10:41:27 [RTSP][SITTING-AREA] ✅ '/sitting-area' stream is UP!
wyze-bridge    | 2021/09/30 10:41:27 [RTSP][SITTING-AREA] 📖 New client reading
wyze-bridge    | 2021/09/30 10:41:28 [RTSP][INTERIOR-CAM] ✅ '/interior-cam' stream is UP!
wyze-bridge    | 2021/09/30 10:41:29 [RTSP][INTERIOR-CAM] 📖 New client reading
wyze-bridge    | 2021/09/30 10:41:30 [RTSP][PATIO-OUTDOOR-CAM] ✅ '/patio-outdoor-cam' stream is UP!
wyze-bridge    | 2021/09/30 10:41:30 [RTSP][PATIO-OUTDOOR-CAM] 📖 New client reading
wyze-bridge    | 2021/09/30 10:41:44 [RTSP][SITTING-AREA] 📖 New client reading
wyze-bridge    | 2021/09/30 10:46:38 [Patio Outdoor Cam] WARNING: Received incomplete frame
wyze-bridge    | 2021/09/30 10:47:07 [sitting area] WARNING: Lost frame
wyze-bridge    | 2021/09/30 10:48:07 [RTSP][SITTING-AREA] 📕 Client stopped reading
wyze-bridge    | 2021/09/30 10:48:20 [RTSP][SITTING-AREA] 📖 New client reading
wyze-bridge    | 2021/09/30 10:48:30 [RTSP][SITTING-AREA] 📕 Client stopped reading
wyze-bridge    | 2021/09/30 10:48:34 [RTSP][SITTING-AREA] 📖 New client reading
wyze-bridge    | 2021/09/30 10:48:44 [RTSP][SITTING-AREA] 📕 Client stopped reading
wyze-bridge    | 2021/09/30 10:48:52 [RTSP][PATIO-OUTDOOR-CAM] ❌ '/patio-outdoor-cam' stream is down
wyze-bridge    | 2021/09/30 10:48:52 [RTSP][PATIO-OUTDOOR-CAM] 📕 Client stopped reading
wyze-bridge    | 2021/09/30 10:48:53 [RTSP][INTERIOR-CAM] ❌ '/interior-cam' stream is down
wyze-bridge    | 2021/09/30 10:48:53 [RTSP][INTERIOR-CAM] 📕 Client stopped reading
wyze-bridge    | 2021/09/30 10:48:57 [RTSP][SITTING-AREA] ❌ '/sitting-area' stream is down
wyze-bridge    | 2021/09/30 10:48:57 [RTSP][SITTING-AREA] 📕 Client stopped reading

**Comment by mrlt8** [comment]
That is strange. Do the streams come back up?
Try checking your router for something like [Airtime Fairness](https://support.wyze.com/hc/en-us/articles/360031479211-ASUS-Routers-and-Airtime-Fairness).

Any chance you can view the channel utilization on your wifi? It could be some neighboring wifi causing interference on your channel.

**Comment by MRliqiang91** [comment]
I'll check on that, will come back with some updates

But to answer your question, it does not seem to come back up. It just remained down until I restart the container.
