### ISSUE TITLE
Timestamp oddness, frames out of order?

### ISSUE THREAD

**Issue by Alfiegerner** [mrlt8/docker-wyze-bridge#16]
I've been trying to work why my timestamps (and I guess frames) are getting out of order, see video [here](https://photos.app.goo.gl/skDjfB7Q8WQZVzz28).

Anybody else seeing this? I don't get it with my wyze rtsp feeds or in wyze app.

Maybe pipe to stdin doesn't gaurantee order?

**Comment by mrlt8** [comment]
I've noticed that sometimes. 
Wonder if we might be able to do something with FFMpeg?

**Comment by Alfiegerner** [comment]
I've just tried adding:

                                                '-fflags', 'nobuffer',

to FFMPEG params and it's been better for me.  But that might just happen to be a one off .  I'll keep on trying with that.

**Comment by Alfiegerner** [comment]
I think recordings from Frigate are fine, so I tried using the input and output parameters from the Frigate config, but no luck, still getting odd frame order when viewing live.

**Comment by mrlt8** [comment]
Have you tried `-err_detect ignore_err` or  some other fflags like `+flush_packets` `+genpts` or `+discardcorrupt`

I wonder if moving to something like gstreamer or an alternative would help..? Open to suggestions!

**Comment by Alfiegerner** [comment]
Yep, I've tried those, here's one one tried (both commented out ones too, this just my file as is).

-hide_banner',
       # '-stats' if 'DEBUG_FFMPEG' in os.environ else '-nostats',                        #'-nostats',
       '-avoid_negative_ts', 'make_zero',                                                 '-fflags', '+genpts+discardcorrupt',
       '-use_wallclock_as_timestamps', '1',
       #'-err_detect', 'ignore_err'                                                       '-loglevel','info', ## if 'DEBUG_FFMPEG' in os.environ else 'fatal',
       '-f', sess.camera.camera_info['videoParm']['type'].lower(),
       '-framerate', sess.camera.camera_info['videoParm']['fps'],                         '-i', '-',                                                                         # '-b:v', str(bitrate)+'k',                                                        #'-reset_timestamps' , '1',                                                        '-strftime', '1',
       '-vcodec', 'copy',
       '-f','rtsp',

**Comment by mrlt8** [comment]
Does enabling `PYTHONUNBUFFERED=1` in your docker-compose help?
Also, could you give the arm version a try? For some reason it seems to be more stable.

**Comment by Alfiegerner** [comment]
I'll try the PYTHONUNBUFFERED=1 - on using the arm version, I'm on ubuntu on an intel i7 - do you still want me to try it?

**Comment by mrlt8** [comment]
Are the frames out of order on all streams or just hls?

**Comment by Alfiegerner** [comment]
I've only looked at rtsp.

**Comment by mrlt8** [comment]
Does adjusting the popen `bufsize` help?

https://github.com/mrlt8/docker-wyze-bridge/blob/cf7c5cf42f22638d83629af88d1a43476476a432/app/cameras.py#L122

**Comment by Alfiegerner** [comment]
No joy on that either - fiddled around with settings but bufsize=1024*100 seemed to work in, the sense of getting a steady stream, but still jumbled timestamp.

**Comment by mrlt8** [comment]
Is this still an issue with v0.5.0?

**Comment by Alfiegerner** [comment]
Looks good now - jumping back on board after returning to wyze RTSP, now looks stable and no timestamp issues, thanks for your efforts @mrlt8 .
