### ISSUE TITLE
Audio IN works on non RTSP FW!!

### ISSUE THREAD

**Issue by AdiAbuAli** [mrlt8/docker-wyze-bridge#160]
Hi,
Its juat to whom interest...
I loaded RTSP FW for V3 and as expected Ausio In works, then I loaded the non RTSP FW (3.36.3.19) back, but as non expected,  Audio IN still works!!

Am not sure what that kicked in in V3 camera!

**Comment by mckochan** [comment]
Can you clarify? 
Do you mean the RTSP feed is still active after loading NON-RTSP FW? Or are you using the docker-wyze-bridge?

**Comment by AdiAbuAli** [comment]
No, after rollling back to non RTSP FW in wyze V3, and start to use that cam via doxker-wyze-bridge (not direct streaming), still voice Out works....hope its clear.
Am using Synology NAS, and I configured that camera via local host via Wyze-bridge after rolling back, and redefined the camera to take the stream from that beidge and yes Voice out is still there....

Thanks,
________________________________

**Comment by AdiAbuAli** [comment]
I just checked now again, and no Voice out anymore....not sure what restarted since then to cause it to get back with no Audio....forget about it.....i think it was a stuck stream

Thanks,
________________________________
