### ISSUE TITLE
Frigate NVR not working using Wyze Bridge

### ISSUE THREAD

**Issue by mgsnell** [mrlt8/docker-wyze-bridge#175]
After installing Wyze Bridge, I have verified thru VLC and Web browser that all 4 feeds work. However when I use the rtsp feed of the bridge in my  frigate.yml (rtsp://homeassistant.local:8554/front-door-cam) frigate complains with the following:

front_door_cam:  ffmpeg sent a broken frame. memoryview assigment: lvalue and rvalue have different structues resulting in a green display in frigate nvr.

![frigate log using wyze bridge rtsp](https://user-images.githubusercontent.com/49707336/137629712-8bb32b35-53b7-4ff5-a1b6-3d89c988b46d.jpg)

![frigate yml wyze bridge](https://user-images.githubusercontent.com/49707336/137629721-dfd43c1b-e2f4-484e-9db2-8dc7faa11b20.jpg)

![wyze bridge log](https://user-images.githubusercontent.com/49707336/137629724-8f4d0989-b348-46d1-9f17-1e15729c8ee8.jpg)

**Comment by mrlt8** [comment]
Seems like it might be a Frigate config issue since you're able to stream via VLC?

IIRC, you need to specify the heigh/width of the video in your frigate yaml and might also want to try replacing homeassistant.local with the actual IP to see if that helps?

**Comment by mrlt8** [comment]
Marking this as resolved.
Please feel free to open a new topic if you need additional assistance.
