### ISSUE TITLE
OS and System compatibility

### ISSUE THREAD

**Issue by mrlt8** [mrlt8/docker-wyze-bridge#18]
Curious to see what OS and system specs people are using to get at least one stream up.

Would appreciate if you could post the OS and cpu/ram of the system you're using to run the container, as well as the number of cams you're able to get up.
thanks!

**Comment by helio58** [comment]
Hi
Using docker iMac 
3 streams. 
Load Avg: 1.73, 1.80, 1.73  CPU usage: 1.68% user, 8.20% sys, 90.10% idle.

**Comment by mckochan** [comment]
Using docker on Unraid with 2 streams
Intel i5-2500t with 16gb RAM
wyze-bridge uses 10 to 13% CPU usage and 215MB RAM
RTSP server users 1 to 3% and 12MB RAM

**Comment by mrlt8** [comment]
Raspberry Pi 4 Model B Rev 1.2 (4GB) on Ubuntu 21.04 with 5 cameras:
```
CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
f91057431aa3   wyze-bridge   290.68%   81.76MiB / 3.703GiB   2.16%     389MB / 291MB    54.3MB / 0B       26
294078e84ec0   rtsp-server   8.84%     18.87MiB / 3.703GiB   0.50%     293MB / 62.5MB   7.86MB / 0B       8

**Comment by SomebodySysop** [comment]
> Raspberry Pi 4 Model B Rev 1.2 (4GB) on Ubuntu 21.04 with 5 cameras:
> 
> ```
> CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
> f91057431aa3   wyze-bridge   290.68%   81.76MiB / 3.703GiB   2.16%     389MB / 291MB    54.3MB / 0B       26
> 294078e84ec0   rtsp-server   8.84%     18.87MiB / 3.703GiB   0.50%     293MB / 62.5MB   7.86MB / 0B       8
> ```

What command did you use to get this output?

**Comment by mrlt8** [comment]
@SomebodySysop `docker stats`
https://docs.docker.com/engine/reference/commandline/stats/

**Comment by milkplus27** [comment]
Raspberry Pi 2 Model B Rev 1.1 with 2 cameras

```
CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O   PIDS
9137dc4e8bce   wyze-bridge     166.23%   0B / 0B             0.00%     22.8MB / 16.3MB   0B / 0B     11
8684875a19e4   rtsp-server     21.66%    0B / 0B             0.00%     17.1MB / 20.1MB   0B / 0B     9
```

**Comment by ricksdunn** [comment]
Ubuntu 18.04.5 LTS  i7-8700  one cam stream

CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %     
6baf56e03f2b        wyze-bridge           6.05%               50.25MiB / 31.26GiB       0.16%    
e8e164c7c26c        rtsp-server            1.43%               11.94MiB / 31.26GiB       0.04%
