### ISSUE TITLE
AV_ER_BUFPARA_MAXSIZE_INSUFF

### ISSUE THREAD

**Issue by michaelrobgrove** [mrlt8/docker-wyze-bridge#181]
On the Dev version with Wyze V3 on latest firmware and getting this message:

2021/10/21 13:06:16 [Front Porch Cam] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 in "P2P mode" FW: 4.36.6.17 IP: 192.168.1.39 WiFi: 46%
2021/10/21 13:06:16 [Front Porch Cam] AV_ER_BUFPARA_MAXSIZE_INSUFF
2021/10/21 13:06:16 [Front Porch Cam] 🧹 Cleaning up FFMPEG...

Just repeats over and over. Won't connect. It did connect 1 time for less than 30 seconds. Rebooted device and nothing. Also 1 of my v2 won't reliably stay connected. But the other does. Both cams with issues are closer to the router than one without, all have latest firmware. Allow work on Wyze app. Not sure what the cause is.

**Comment by mrlt8** [comment]
The dev branch is experimental and still a work in progress.

I pushed some tweaks which should help with the buffer.

**Comment by mrlt8** [comment]
Thanks! Feedback is always appreciated!
