### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by bbobrian** [mrlt8/docker-wyze-bridge#197]
- OS: Unraid 6.9.2
- Using latest docker image (v1.0.1)
- Single v3 cam, latest official firmware (4.36.3.19, not RTSP beta)
- Accessing through latest Frigate docker (0.9.4)

On start/restart of container:
CPU: < 1%
Ram: ~50MB

After about 2 hours:
CPU: > 6%
Ram: ~250MB

And continues to climb. This is a recent development.

**Comment by mrlt8** [comment]
So I think this is most likely a video buffer issue. 
Could you try running the edge image to see if it helps?

**Comment by bbobrian** [comment]
Switched. I will monitor and report results later this afternoon.

**Comment by bbobrian** [comment]
7 hours in and currently:
CPU: < 1%
Ram: 68MB

**Comment by mrlt8** [comment]
Marking this as resolved.
Please feel free to open a new topic if you need additional assistance.
