### ISSUE TITLE
1 working out of 2 cameras.

### ISSUE THREAD

**Issue by balajeek** [mrlt8/docker-wyze-bridge#20]
Just installed the docker-wyze-bridge, no errors all seem to run fine.
I have 3 cameras on wyze app, 1 is offline for now, two are working.
from vlc i can open the rtsp and it works fine for 1 camera, but not for the second one, it throws error "unable to open MRL" from vlc.

camera 'v3-outdoor' works fine, camera 'front-door-cam' not working and its wyzecam pan with rtsp firmware on it.

Thanks.

Here is the log from wyze-bridge:
----------------------------------
STARTING DOCKER-WYZE-BRIDGE v0.3.2.1
Could not find local cache for user
Could not find local cache for auth
Fetching auth from wyze api...
Saving auth to local cache...
Fetching user from wyze api...
Saving user to local cache...
Could not find local cache for cameras
Fetching cameras from wyze api...
Saving cameras to local cache...
STARTING ALL 3 CAMERAS
2021/07/15 21:24:10 [V3 outdoor] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.1.4 from 192.168.99.140 (WiFi Quality: 88%)...
2021/07/15 21:24:11 [Reef] IOTC_ER_CAN_NOT_FIND_DEVICE
2021/07/15 21:24:11 [Reef] Camera offline? Sleeping for 10s.
2021/07/15 21:24:11 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 62%)...
2021/07/15 21:24:11 [Front Door Cam] 'type'
2021/07/15 21:24:23 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 67%)...
2021/07/15 21:24:23 [Front Door Cam] 'type'

... the last two lines keep repeating every 10s. don't know why

HERE IS THE LOG FROM rtsp-server:
--------------------------------------

2021/07/15 21:29:24 I [0/0] rtsp-simple-server v0.16.4
2021/07/15 21:29:24 I [0/0] [RTSP] TCP listener opened on :8554
2021/07/15 21:29:24 I [0/0] [RTMP] listener opened on :1935
2021/07/15 21:29:24 I [0/0] [HLS] listener opened on :8888
2021/07/15 21:29:43 I [0/0] [RTSP] [conn 172.19.0.3:60462] opened
2021/07/15 21:29:43 I [0/0] [RTSP] [session 2226935621] opened by 172.19.0.3:60462
2021/07/15 21:29:43 I [1/0] [RTSP] [session 2226935621] is publishing to path 'v3-outdoor', 1 track with TCP

... i see publishing for v3-outdoor, but not for 'front-door-cam'

**Comment by balajeek** [comment]
just an update, after i restart all the cameas and restart the docker containers.
This is the log, as you can see two cameras seem work but the third one says 'type'


STARTING ALL 3 CAMERAS

2021/07/15 22:04:56 [Reef] Starting HD 120kb/s Stream for WyzeCam V2 (WYZEC1-JZ) running FW: 4.28.4.49 from 192.168.99.41 (WiFi Quality: 60%)...
2021/07/15 22:04:57 [V3 outdoor] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.1.4 from 192.168.99.140 (WiFi Quality: 83%)...
2021/07/15 22:04:59 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 76%)...
2021/07/15 22:04:59 [Front Door Cam] 'type'
2021/07/15 22:05:12 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 94%)...
2021/07/15 22:05:12 [Front Door Cam] 'type'
2021/07/15 22:05:24 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 88%)...
2021/07/15 22:05:24 [Front Door Cam] 'type'

**Comment by mrlt8** [comment]
Interesting. 'type' seems to be an exception coming from the tutk library. I wonder if the upstream https://github.com/kroo/wyzecam is compatible with the wyzecam pan?

Could you try adding `- DEBUG_FFMPEG=True` to your docker-compose.yml and see if that prints any additional info:
```yaml
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - DEBUG_FFMPEG=True
```

**Comment by balajeek** [comment]
after adding the debug as you said, here is the log:

2021/07/16 13:37:57 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 97%)...
2021/07/16 13:37:57 [Front Door Cam] 'type'
Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 1200k tbn, 40 tbc
Output #0, rtsp, to 'rtsp://rtsp-server:8554/v3-outdoor':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 20 fps, 20 tbr, 90k tbn, 20 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
[rtsp @ 0x55a062776140] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly

**Comment by balajeek** [comment]
some more log that appeared immediately after the restart of the service:

2021/07/16 13:37:40 [V3 outdoor] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.1.4 from 192.168.99.140 (WiFi Quality: 98%)...
2021/07/16 13:37:41 [Front Door Cam] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 (WiFi Quality: 90%)...
2021/07/16 13:37:41 [Front Door Cam] 'type'
[h264 @ 0x55a06276f180] sps_id 0 out of range
[h264 @ 0x55a06276f180] non-existing PPS 0 referenced
    Last message repeated 2 times
[h264 @ 0x55a06276f180] sps_id 0 out of range
[h264 @ 0x55a06276f180] non-existing PPS 0 referenced
[h264 @ 0x55a06276f180] decode_slice_header error
[h264 @ 0x55a06276f180] no frame!
[h264 @ 0x55a06276f180] non-existing PPS 0 referenced
[h264 @ 0x55a06276f180] decode_slice_header error
[h264 @ 0x55a06276f180] no frame!
[h264 @ 0x55a06276f180] non-existing PPS 0 re

**Comment by balajeek** [comment]
Just wanted to update with the issue:

Hope someone can figure out from log what i should be doing so it fixes my issue.
since i installed and started the rtsp and wyze services, i was having trouble getting the stream on wyze app, it freezes and and sometime says "retry or re-power".  so i stopped rtsp and wyze containers (i have portainer) and restarted the wyzecam pan and it came back up and worked fine, I let it like this for couple hours, then i started the rtsp and wyze services and the wyzecam pan started with the same issue again, same errors in the log and i am unable to connect or freezes from wyze iphone app.  I do have other v2 camera on wyze and that seem to work.

Also I thought why not i just add FILTER_NAME and have only the two cameras i want, so hoping it will exlude my wyzecam pan, but filter seem not work, it gives only one camera instead of two.

**Comment by mrlt8** [comment]
Could you post your `- FILTER_NAMES` line?

**Comment by k-rock** [comment]
i updated my V2 firmware from 'rtsp' to 'non-rtsp' version and am not able to view the V2 stream (my V3 works fine...)

**(w/ '- DEBUG_FFMPEG=True' )**
`
kyle@monster:~/wyze-bridge/docker-wyze-bridge$ sudo systemctl status wyzebridge.service 
● wyzebridge.service - Wyze bridge
   Loaded: loaded (/lib/systemd/system/wyzebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-07-16 18:12:09 EDT; 17s ago
  Process: 26882 ExecStartPre=/usr/bin/docker-compose stop (code=exited, status=0/SUCCESS)
  Process: 26889 ExecStartPre=/usr/bin/docker-compose pull (code=exited, status=0/SUCCESS)
 Main PID: 26898 (docker-compose)
    Tasks: 7 (limit: 4915)
   Memory: 40.1M
   CGroup: /system.slice/wyzebridge.service
           └─26898 /usr/bin/python3 /usr/bin/docker-compose up

Jul 16 18:12:26 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] decode_slice_header error
Jul 16 18:12:26 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] no frame!
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] non-existing PPS 0 referenced
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    |     Last message repeated 1 times
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] decode_slice_header error
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] no frame!
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] non-existing PPS 0 referenced
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    |     Last message repeated 1 times
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] decode_slice_header error
Jul 16 18:12:27 monster docker-compose[26898]: wyze-bridge    | [h264 @ 0x561cba5f31c0] no frame!
kyle@monster:~/wyze-bridge/docker-wyze-bridge$         
`

**(w/out debug option)**

`kyle@monster:~$ sudo systemctl status wyzebridge.service 
● wyzebridge.service - Wyze bridge
   Loaded: loaded (/lib/systemd/system/wyzebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-07-16 18:01:08 EDT; 3min 47s ago
  Process: 25947 ExecStartPre=/usr/bin/docker-compose stop (code=exited, status=0/SUCCESS)
  Process: 25954 ExecStartPre=/usr/bin/docker-compose pull (code=exited, status=0/SUCCESS)
 Main PID: 25963 (docker-compose)
    Tasks: 7 (limit: 4915)
   Memory: 37.6M
   CGroup: /system.slice/wyzebridge.service
           └─25963 /usr/bin/python3 /usr/bin/docker-compose up

Jul 16 18:04:30 monster docker-compose[25963]: rtsp-server    | 2021/07/16 22:04:30 I [3/4] [RTSP] [session 780208820] closed
Jul 16 18:04:31 monster docker-compose[25963]: rtsp-server    | 2021/07/16 22:04:31 I [3/4] [RTSP] [conn 192.168.86.50:43966] closed
Jul 16 18:04:31 monster docker-compose[25963]: rtsp-server    | 2021/07/16 22:04:31 I [3/3] [RTSP] [session 765708677] closed
Jul 16 18:04:31 monster docker-compose[25963]: rtsp-server    | 2021/07/16 22:04:31 I [3/3] [RTSP] [session 4098141551] closed
Jul 16 18:04:33 monster docker-compose[25963]: wyze-bridge    | Connection closed by remote. Closing connection.
Jul 16 18:04:33 monster docker-compose[25963]: wyze-bridge    | 2021/07/16 22:04:33 [garage] Authentication did not succeed! {'connectionRes': '2'}
Jul 16 18:04:42 monster docker-compose[25963]: wyze-bridge    | Connection closed by remote. Closing connection.
Jul 16 18:04:42 monster docker-compose[25963]: wyze-bridge    | 2021/07/16 22:04:42 [garage] Authentication did not succeed! {'connectionRes': '2'}
Jul 16 18:04:51 monster docker-compose[25963]: wyze-bridge    | Connection closed by remote. Closing connection.
Jul 16 18:04:52 monster docker-compose[25963]: wyze-bridge    | 2021/07/16 22:04:52 [garage] Authentication did not succeed! {'connectionRes': '2'}
kyle@monster:~$ `

**Comment by balajeek** [comment]
> Could you post your `- FILTER_NAMES` line?

My there wyze camera names are 1) Front Door Cam  2) reef  3) v3-outdoor
1=WyzeCam Pan, 2 is v2, 3 is v3

This is what i have currently, hoping that it will eliminate camera 1, which it did becaz i don't see any log for camera 1, but it keep saying "[V3 outdoor] Killing FFmpeg...",  "[V3 outdoor] Starting HD 120kb/s Stream for WyzeCam V3", just repeating for both v3 and v2

- FILTER_MODEL=Pan
- FILTER_MODE=BLOCK

I had tried this before
- FILTER_NAMES=v3-outdoor, reef

**Comment by mrlt8** [comment]
Killing ffmpeg is basically just cleanup after some other issue. It *should* print the exception somewhere above that..

> - FILTER_NAMES=v3-outdoor, reef

I think it should be 
```yaml
- FILTER_NAMES=v3 outdoor, reef
```
The hyphens are only used for the URIs.

**Comment by balajeek** [comment]
I did as you said, and it seem to work. 
but few min later v3 outdoor, did not show up, looking at the logs shows:


2021/07/19 01:05:25 [V3 outdoor] Killing FFmpeg...
Connection closed by remote. Closing connection.
2021/07/19 01:05:35 [V3 outdoor] Authentication did not succeed! {'connectionRes': '2'}
2021/07/19 01:05:35 [V3 outdoor] Killing FFmpeg...

**Comment by balajeek** [comment]
today wyze app prompted me for update of v3 outdoor camera and i did the update.
now the wyze bridge docker shows in the log:

2021/07/20 14:58:32 [V3 outdoor] Authentication did not succeed! {'connectionRes': '2'}

what happen?

**Comment by balajeek** [comment]
after restarting the wyze container, it seem to work at for last 30 min. will keep posted.
Just noticed v0.4, its mentioned i need new docker-comple.yaml, what does that mean, some extra parameteres!

**Comment by jmacul2** [comment]
I am having the 'type' bug as well.  All my cameras are V2 cameras with the RTSP firmware.  Is the RTSP firmware unsupported?  Seems like it should be if the feed is coming from the relay servers.  I enabled FFmpeg debugging and I don't get any more detailed errors.

**Comment by jmacul2** [comment]
The reason for the 'type' error is because of this FFMPEG argument:

`'-f', sess.camera.camera_info['videoParm']['type'].lower(),`

type does not exist on thr RTSP firmware and/or others??

In any cause isn't the type always "h264"?  I just hard coded it and now it works fine.

**Comment by mrlt8** [comment]
Good catch @jmacul2! 

Not sure if any cameras currently use it, but I believe the upstream wyzecam library has references to hevc.

Could you see if this works on your pan before I merge:
https://github.com/mrlt8/docker-wyze-bridge/blob/e3e1dd959d8f4f7d89b34cbccb220858c64c6f12/app/wyze_bridge.py#L124

**Comment by balajeek** [comment]
at work right now, but will try in 2 hr or so.
So i have to open this file and update this line as you had given and build?

**Comment by balajeek** [comment]
okay i did that, replaced the line 124 with the one you provided and did docker-compose up --build and i don't see the type error anymore and able to see the feeds.

Here is the log for your info:
`STARTING DOCKER-WYZE-BRIDGE v0.4.1.5
**Could not find local cache for user
Could not find local cache for auth**
Fetching auth from wyze api...
Saving auth to local cache...
Fetching user from wyze api...
Saving user to local cache...
**Could not find local cache for cameras**
Fetching cameras from wyze api...
Saving cameras to local cache...
STARTING ALL 3 CAMERAS
2021/07/29 19:11:18 [Reef] Starting HD 120kb/s Stream for WyzeCam V2 (WYZEC1-JZ) running FW: 4.28.4.49 from 192.168.1.4 "LAN mode" (WiFi Quality: 56%)...
2021/07/29 19:11:19 [V3 outdoor] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.2.5 from 192.168.1.5 "LAN mode" (WiFi Quality: 100%)...
2021/07/29 19:11:19 I [0/0] [RTSP] [conn 172.19.0.2:55020] opened
2021/07/29 19:11:19 I [0/0] [RTSP] [conn 172.19.0.2:55020] **ERR: no one is publishing to path 'reef'**
2021/07/29 19:11:19 I [0/0] [RTSP] [conn 172.19.0.2:55020] closed
2021/07/29 19:11:19 I [0/0] [RTSP] [conn 172.19.0.2:55022] opened
2021/07/29 19:11:19 I [0/0] [RTSP] [conn 172.19.0.2:55022] **ERR: no one is publishing to path 'v3-outdoor'**
2021/07/29 19:11:19 I [0/0] [RTSP] [conn 172.19.0.2:55022] closed
2021/07/29 19:11:20 [FrontDoor] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.1.6 "LAN mode" (WiFi Quality: 67%)...
2021/07/29 19:11:24 I [0/0] [RTSP] [conn 127.0.0.1:38176] opened
2021/07/29 19:11:24 I [0/0] [RTSP] [session 1141098288] opened by 127.0.0.1:38176
2021/07/29 19:11:24 I [1/0] [RTSP] [session 1141098288] is publishing to path 'v3-outdoor', 1 track with UDP
2021/07/29 19:11:25 I [1/0] [RTSP] [conn 127.0.0.1:38236] opened
2021/07/29 19:11:25 I [1/0] [RTSP] [session 3356804433] opened by 127.0.0.1:38236
2021/07/29 19:11:25 I [2/0] [RTSP] [session 3356804433] is publishing to path 'reef', 1 track with UDP
2021/07/29 19:11:27 I [2/0] [RTSP] [conn 127.0.0.1:38238] opened
2021/07/29 19:11:27 I [2/0] [RTSP] [session 3578086531] opened by 127.0.0.1:38238
2021/07/29 19:11:27 I [3/0] [RTSP] [session 3578086531] is publishing to path 'frontdoor', 1 track with UDP
2021/07/29 19:11:29 I [3/0] [RTSP] [conn 172.19.0.2:55220] opened
2021/07/29 19:11:29 I [3/0] [RTSP] [session 465063226] opened by 172.19.0.2:55220
2021/07/29 19:11:29 I [3/1] [RTSP] [session 465063226] is reading from path 'reef', 1 track with TCP
2021/07/29 19:11:29 I [3/1] [RTSP] [conn 172.19.0.2:55222] opened
2021/07/29 19:11:29 I [3/1] [RTSP] [session 4093739722] opened by 172.19.0.2:55222
2021/07/29 19:11:29 I [3/2] [RTSP] [session 4093739722] is reading from path 'v3-outdoor', 1 track with TCP
2021/07/29 19:12:35 I [3/2] [RTSP] [conn 192.168.99.31:60046] opened
2021/07/29 19:12:35 I [3/2] [RTSP] [session 3253244011] opened by 192.168.99.31:60046
2021/07/29 19:12:35 I [3/3] [RTSP] [session 3253244011] is reading from path 'frontdoor', 1 track with UDP
2021/07/29 19:12:42 I [3/2] [RTSP] [session 3253244011] closed
2021/07/29 19:12:42 I [3/2] [RTSP] [conn 192.168.99.31:60046] closed

`

Can you tell if me if this all looks okay, specially the bold one should i be concerned, and so many [RTSP] Session and [conn] closed.

Thank you.

**Comment by balajeek** [comment]
After it started working, i left it alone, but noticed few days later that even though when i first start wyze-bridge, it finds all 3 cameras and starts publishing and i am able to stream thru vlc, specially the pan camera, but few hours later i get error message that repeats continuously (see below log) and the camera feed stops working.  I didn't know about this until yesterday.

When wyze-bridge stop working I go to Wyze iphone app and it streams fine on the pan camera.

**log of first few lines when started:**
STARTING DOCKER-WYZE-BRIDGE v0.4.1.5
Fetching user from local cache...
Fetching cameras from local cache...
STARTING ALL 3 CAMERAS 
2021/08/06 11:42:08 [Reef] Starting HD 120kb/s Stream for WyzeCam V2 (WYZEC1-JZ) running FW: 4.28.4.49 from 192.168.941 "LAN mode" (WiFi Quality: 66%)...
2021/08/06 11:42:08 [V3 outdoor] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.2.5 from 192.168.99.140 "LAN mode" (WiFi Quality: 92%)...
2021/08/06 11:42:09 [FrontDoor] Starting HD 120kb/s Stream for WyzeCam PAN (WYZECP1_JEF) running FW: 4.29.4.41 from 192.168.99.40 "LAN mode" (WiFi Quality: 100%)...
2021/08/06 11:42:12 I [0/0] [RTSP] [conn 127.0.0.1:46306] opened
2021/08/06 11:42:12 I [0/0] [RTSP] [session 2513896010] opened by 127.0.0.1:46306
2021/08/06 11:42:12 I [1/0] [RTSP] [session 2513896010] is publishing to path 'v3-outdoor', 1 track with UDP
22021/08/06 11:42:14 I [1/0] [RTSP] [session 3150652883] opened by 127.0.0.1:46402
2021/08/06 11:42:14 I [2/0] [RTSP] [session 3150652883] is publishing to path 'reef', 1 track with UDP
2021/08/06 11:42:18 I [2/2] [RTSP] [session 263614689] opened by 127.0.0.1:46420
2021/08/06 11:42:18 I [3/2] [RTSP] [session 263614689] is publishing to path 'frontdoor', 1 track with UDP



then  later I get  this  t3 essage repeatlivly

2021/08/06 13:27:59 I [3/3] [RTMP] [conn 192.168.99.13:59958] opened
2021/08/06 13:27:59 I [3/3] [RTMP] [conn 192.168.99.13:59958] ERR: no one is publishing to path 'live/front'
2021/08/06 13:27:59 I [3/3] [RTMP] [conn 192.168.99.13:59958] closed

**Comment by mrlt8** [comment]
does this help? 
```yaml
- RTSP_PROTOCOLS=tcp
```

**Comment by balajeek** [comment]
first, thanks for the superfast response. 👍 

I added this variable as you mentioned in the docker-compose,  so far good, the log shows "is reading from path 'frontdoor', 1 track with TCP". 

will keep monitoring and let you know if something changes.


Also i noticed 0.5 is published, even though my docker-comple says :latest it does not pull 
I also tried docker-compose pull wyze-bridge and still won't pull the latest build.

I am afraid i would not want to do docker pull, becaz last time i did, it pulled some other container images too which i did not wanted it.

**Comment by mrlt8** [comment]
Are you building the image? if so:
```
git pull
docker-compose up --build
```
otherwise make sure your image is set correctly:
`image: mrlt8/wyze-bridge:latest`

**Comment by balajeek** [comment]
yes i have the image with latest, but still it won't pull the latest, i still see 0.4 in the log

**Comment by mrlt8** [comment]
Have you tried running
```
docker-compose down
docker-compose rm -f
```

**Comment by balajeek** [comment]
> Have you tried running
> 
> ```
> docker-compose down
> docker-compose rm -f
> ```

i will try this bit later

**Comment by balajeek** [comment]
> does this help?
> 
> ```yaml
> - RTSP_PROTOCOLS=tcp
> ```

so i thought this helped, now i checked again and see the error keep coming every min. Again i opened the wyze iphone app and camera seem fine and streaming.

[RTSP] [conn 172.18.0.20:54820] ERR: no one is publishing to path 'frontdoor'

What does this actually mean, is wyze-bridge trying to connect or some other service try to access the url and get this error?
Trying to understand.

**Comment by mrlt8** [comment]
It means you or some other service you configured is trying to access the `/frontdoor` RTSP stream but the stream is not available.

In your log from above, `[3/3]` means that you have '3' streams active and '3' clients are reading:
2021/08/06 13:27:59 I **[3/3]** [RTMP] [conn 192.168.99.13:59958] ERR: no one is publishing to path 'live/front'

**Comment by balajeek** [comment]
> It means you or some other service you configured is trying to access the `/frontdoor` RTSP stream but the stream is not available.
> 
> In your log from above, `[3/3]` means that you have '3' streams active and '3' clients are reading:
> 2021/08/06 13:27:59 I **[3/3]** [RTMP] [conn 192.168.99.13:59958] ERR: no one is publishing to path 'live/front'

got it thanks for the clarification.  since the pan camera did not work for, may be i will try flashing to a non-rtsp firmware and see if it makes any difference, if not i will have to replace the camera i think.
