### ISSUE TITLE
Not Streaming to HomeKit

### ISSUE THREAD

**Issue by airbornetrooper82573** [mrlt8/docker-wyze-bridge#209]
It was working but since upgrading to v1 and higher, I can no longer get the streams to play in HomeKit. Works fine in the Wyze app and streams in VLC using RTSP. 

Homebridge FFmpeg Config:
`       
 {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Front Yard Cam",
                    "manufacturer": "Wyze",
                    "model": "WYZE_CAKP2JFUS",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://123:asd@172.16.1.48:8554/front-yard-cam",
                        "vcodec": "copy",
                        "audio": false
                    }
                },
                {
                    "name": "Back Yard Cam",
                    "manufacturer": "Wyze",
                    "model": "WYZE_CAKP2JFUS",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://123:asd@172.16.1.48:8554/back-yard-cam",
                        "vcodec": "copy",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
`

docker-compose.yml
`
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: always
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:
            - WYZE_EMAIL=email@gmail.com # Replace with wyze email
            - WYZE_PASSWORD=mypass # Replace with wyze password
            - FRESH_DATA=true
            - RTSP_LOGLEVEL=debug
            - DEBUG_FFMPEG=true
            - NET_MODE=LAN
            - RTSP_PATHS_ALL_READUSER=123
            - RTSP_PATHS_ALL_READPASS=asd
            - RTSP_READTIMEOUT=60s
            `

docker-compose log
`
root@raspberrypi:/home/pi/docker-wyze-bridge# docker-compose up
Starting wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v1.0.2
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:13 [WyzeBridge] ♻️ FORCED REFRESH - Removing local 'user' data
wyze-bridge    | 2021/10/28 21:06:13 [WyzeBridge] ♻️ FORCED REFRESH - Removing local 'auth' data
wyze-bridge    | 2021/10/28 21:06:13 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/10/28 21:06:13 [WyzeBridge] 💾 Saving 'auth' to local cache...
wyze-bridge    | 2021/10/28 21:06:13 [WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
wyze-bridge    | 2021/10/28 21:06:14 [WyzeBridge] 💾 Saving 'user' to local cache...
wyze-bridge    | 2021/10/28 21:06:14 [WyzeBridge] ♻️ FORCED REFRESH - Removing local 'cameras' data
wyze-bridge    | 2021/10/28 21:06:14 [WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
wyze-bridge    | 2021/10/28 21:06:15 [WyzeBridge] 💾 Saving 'cameras' to local cache...
wyze-bridge    | 
wyze-bridge    | 🎬 STARTING ALL 2 CAMERAS
wyze-bridge    | 2021/10/28 21:06:15 [WyzeBridge] Starting rtsp-simple-server v0.17.7
wyze-bridge    | 2021/10/28 21:06:15 INF [0/0] rtsp-simple-server v0.17.7
wyze-bridge    | 2021/10/28 21:06:15 INF [0/0] [path back-yard-cam] created
wyze-bridge    | 2021/10/28 21:06:15 INF [0/0] [path front-yard-cam] created
wyze-bridge    | 2021/10/28 21:06:15 INF [0/0] [RTSP] TCP listener opened on :8554
wyze-bridge    | 2021/10/28 21:06:15 INF [0/0] [RTMP] listener opened on :1935
wyze-bridge    | 2021/10/28 21:06:15 INF [0/0] [HLS] listener opened on :8888
wyze-bridge    | 2021/10/28 21:06:17 [Back Yard Cam] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 172.16.1.57 WiFi: 98%
wyze-bridge    | 2021/10/28 21:06:17 [Back Yard Cam] [FFMPEG_CMD] ffmpeg -loglevel verbose -fflags +flush_packets+genpts+discardcorrupt+nobuffer -i - -vcodec copy -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554
wyze-bridge    | ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
wyze-bridge    |   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
wyze-bridge    |   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
wyze-bridge    |   libavutil      56. 51.100 / 56. 51.100
wyze-bridge    |   libavcodec     58. 91.100 / 58. 91.100
wyze-bridge    |   libavformat    58. 45.100 / 58. 45.100
wyze-bridge    |   libavdevice    58. 10.100 / 58. 10.100
wyze-bridge    |   libavfilter     7. 85.100 /  7. 85.100
wyze-bridge    |   libswscale      5.  7.100 /  5.  7.100
wyze-bridge    |   libswresample   3.  7.100 /  3.  7.100
wyze-bridge    |   libpostproc    55.  7.100 / 55.  7.100
wyze-bridge    | [h264 @ 0x4230780] Reinit context to 1920x1088, pix_fmt: yuv420p
wyze-bridge    | 2021/10/28 21:06:18 [Front Yard Cam] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 172.16.1.167 WiFi: 93%
wyze-bridge    | 2021/10/28 21:06:18 [Front Yard Cam] [FFMPEG_CMD] ffmpeg -loglevel verbose -fflags +flush_packets+genpts+discardcorrupt+nobuffer -i - -vcodec copy -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554
wyze-bridge    | ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
wyze-bridge    |   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
wyze-bridge    |   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
wyze-bridge    |   libavutil      56. 51.100 / 56. 51.100
wyze-bridge    |   libavcodec     58. 91.100 / 58. 91.100
wyze-bridge    |   libavformat    58. 45.100 / 58. 45.100
wyze-bridge    |   libavdevice    58. 10.100 / 58. 10.100
wyze-bridge    |   libavfilter     7. 85.100 /  7. 85.100
wyze-bridge    |   libswscale      5.  7.100 /  5.  7.100
wyze-bridge    |   libswresample   3.  7.100 /  3.  7.100
wyze-bridge    |   libpostproc    55.  7.100 / 55.  7.100
wyze-bridge    | [h264 @ 0x30f8780] Reinit context to 1920x1088, pix_fmt: yuv420p
wyze-bridge    | [h264 @ 0x422f410] max_analyze_duration 5000000 reached at 5030000 microseconds st:0
wyze-bridge    | Input #0, h264, from 'pipe:':
wyze-bridge    |   Duration: N/A, bitrate: N/A
wyze-bridge    |     Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (1920x1088), 20.25 fps, 20 tbr, 1200k tbn, 40 tbc
wyze-bridge    | [tcp @ 0x427a220] Starting connection attempt to 0.0.0.0 port 8554
wyze-bridge    | [tcp @ 0x427a220] Successfully connected to 0.0.0.0 port 8554
wyze-bridge    | 2021/10/28 21:06:22 INF [0/0] [RTSP] [conn 127.0.0.1:51372] opened
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [c->s] OPTIONS rtsp://0.0.0.0:8554/back-yard-cam RTSP/1.0
wyze-bridge    | CSeq: 1
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 1
wyze-bridge    | Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
wyze-bridge    | Server: gortsplib
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | [rtsp @ 0x4279b20] SDP:
wyze-bridge    | v=0
wyze-bridge    | o=- 0 0 IN IP4 127.0.0.1
wyze-bridge    | s=No Name
wyze-bridge    | c=IN IP4 127.0.0.1
wyze-bridge    | t=0 0
wyze-bridge    | a=tool:libavformat 58.45.100
wyze-bridge    | m=video 0 RTP/AVP 96
wyze-bridge    | a=rtpmap:96 H264/90000
wyze-bridge    | a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J00AKedAPAET8s1AQEB8AAADAAQAAAMAoNGADqYAFfl//wKA,KO48gAA=; profile-level-id=4D0029
wyze-bridge    | a=control:streamid=0
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [c->s] ANNOUNCE rtsp://0.0.0.0:8554/back-yard-cam RTSP/1.0
wyze-bridge    | CSeq: 2
wyze-bridge    | Content-Length: 304
wyze-bridge    | Content-Type: application/sdp
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | v=0
wyze-bridge    | o=- 0 0 IN IP4 127.0.0.1
wyze-bridge    | s=No Name
wyze-bridge    | c=IN IP4 127.0.0.1
wyze-bridge    | t=0 0
wyze-bridge    | a=tool:libavformat 58.45.100
wyze-bridge    | m=video 0 RTP/AVP 96
wyze-bridge    | a=rtpmap:96 H264/90000
wyze-bridge    | a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J00AKedAPAET8s1AQEB8AAADAAQAAAMAoNGADqYAFfl//wKA,KO48gAA=; profile-level-id=4D0029
wyze-bridge    | a=control:streamid=0
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 INF [0/0] [RTSP] [session 869534373] opened by 127.0.0.1:51372
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 2
wyze-bridge    | Server: gortsplib
wyze-bridge    | Session: 3294479050
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [c->s] SETUP rtsp://0.0.0.0:8554/back-yard-cam/streamid=0 RTSP/1.0
wyze-bridge    | CSeq: 3
wyze-bridge    | Session: 3294479050
wyze-bridge    | Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=record
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 3
wyze-bridge    | Server: gortsplib
wyze-bridge    | Session: 3294479050
wyze-bridge    | Transport: RTP/AVP/TCP;unicast;interleaved=0-1
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 DEB [0/0] [RTSP] [conn 127.0.0.1:51372] [c->s] RECORD rtsp://0.0.0.0:8554/back-yard-cam RTSP/1.0
wyze-bridge    | CSeq: 4
wyze-bridge    | Range: npt=0.000-
wyze-bridge    | Session: 3294479050
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:22 INF [1/0] [RTSP] [session 869534373] is publishing to path 'back-yard-cam', 1 track with TCP
wyze-bridge    | 2021/10/28 21:06:22 INF [1/0] [path back-yard-cam] runOnPublish command started
wyze-bridge    | 2021/10/28 21:06:22 DEB [1/0] [RTSP] [conn 127.0.0.1:51372] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 4
wyze-bridge    | Server: gortsplib
wyze-bridge    | Session: 3294479050
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | Output #0, rtsp, to 'rtsp://0.0.0.0:8554/back-yard-cam':
wyze-bridge    |   Metadata:
wyze-bridge    |     encoder         : Lavf58.45.100
wyze-bridge    |     Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (0x0), q=2-31, 20.25 fps, 20 tbr, 90k tbn, 20 tbc
wyze-bridge    | Stream mapping:
wyze-bridge    |   Stream #0:0 -> #0:0 (copy)
wyze-bridge    | 2021/10/28 21:06:23 [RTSP][BACK-YARD-CAM] ✅ '/back-yard-cam' stream is UP!
wyze-bridge    | [rtsp @ 0x4279b20] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[h264 @ 0x30f7410] max_analyze_duration 5000000 reached at 5020000 microseconds st:0eed=0.484x    
wyze-bridge    | Input #0, h264, from 'pipe:':
wyze-bridge    |   Duration: N/A, bitrate: N/A
wyze-bridge    |     Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (1920x1088), 20.33 fps, 20 tbr, 1200k tbn, 40 tbc
wyze-bridge    | [tcp @ 0x3124d80] Starting connection attempt to 0.0.0.0 port 8554
wyze-bridge    | [tcp @ 0x3124d80] Successfully connected to 0.0.0.0 port 8554
wyze-bridge    | 2021/10/28 21:06:26 INF [1/0] [RTSP] [conn 127.0.0.1:51374] opened
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [c->s] OPTIONS rtsp://0.0.0.0:8554/front-yard-cam RTSP/1.0
wyze-bridge    | CSeq: 1
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 1
wyze-bridge    | Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
wyze-bridge    | Server: gortsplib
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | [rtsp @ 0x3163dc0] SDP:
wyze-bridge    | v=0
wyze-bridge    | o=- 0 0 IN IP4 127.0.0.1
wyze-bridge    | s=No Name
wyze-bridge    | c=IN IP4 127.0.0.1
wyze-bridge    | t=0 0
wyze-bridge    | a=tool:libavformat 58.45.100
wyze-bridge    | m=video 0 RTP/AVP 96
wyze-bridge    | a=rtpmap:96 H264/90000
wyze-bridge    | a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J00AKedAPAET8s1AQEB8AAADAAQAAAMAoNGADqYAFfl//wKA,KO48gAA=; profile-level-id=4D0029
wyze-bridge    | a=control:streamid=0
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [c->s] ANNOUNCE rtsp://0.0.0.0:8554/front-yard-cam RTSP/1.0
wyze-bridge    | CSeq: 2
wyze-bridge    | Content-Length: 304
wyze-bridge    | Content-Type: application/sdp
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | v=0
wyze-bridge    | o=- 0 0 IN IP4 127.0.0.1
wyze-bridge    | s=No Name
wyze-bridge    | c=IN IP4 127.0.0.1
wyze-bridge    | t=0 0
wyze-bridge    | a=tool:libavformat 58.45.100
wyze-bridge    | m=video 0 RTP/AVP 96
wyze-bridge    | a=rtpmap:96 H264/90000
wyze-bridge    | a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J00AKedAPAET8s1AQEB8AAADAAQAAAMAoNGADqYAFfl//wKA,KO48gAA=; profile-level-id=4D0029
wyze-bridge    | a=control:streamid=0
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 INF [1/0] [RTSP] [session 118603342] opened by 127.0.0.1:51374
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 2
wyze-bridge    | Server: gortsplib
wyze-bridge    | Session: 2356598957
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [c->s] SETUP rtsp://0.0.0.0:8554/front-yard-cam/streamid=0 RTSP/1.0
wyze-bridge    | CSeq: 3
wyze-bridge    | Session: 2356598957
wyze-bridge    | Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=record
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 3
wyze-bridge    | Server: gortsplib
wyze-bridge    | Session: 2356598957
wyze-bridge    | Transport: RTP/AVP/TCP;unicast;interleaved=0-1
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 DEB [1/0] [RTSP] [conn 127.0.0.1:51374] [c->s] RECORD rtsp://0.0.0.0:8554/front-yard-cam RTSP/1.0
wyze-bridge    | CSeq: 4
wyze-bridge    | Range: npt=0.000-
wyze-bridge    | Session: 2356598957
wyze-bridge    | User-Agent: Lavf58.45.100
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | 2021/10/28 21:06:26 INF [2/0] [RTSP] [session 118603342] is publishing to path 'front-yard-cam', 1 track with TCP
wyze-bridge    | 2021/10/28 21:06:26 INF [2/0] [path front-yard-cam] runOnPublish command started
wyze-bridge    | 2021/10/28 21:06:26 DEB [2/0] [RTSP] [conn 127.0.0.1:51374] [s->c] RTSP/1.0 200 OK
wyze-bridge    | CSeq: 4
wyze-bridge    | Server: gortsplib
wyze-bridge    | Session: 2356598957
wyze-bridge    | 
wyze-bridge    | 
wyze-bridge    | Output #0, rtsp, to 'rtsp://0.0.0.0:8554/front-yard-cam':
wyze-bridge    |   Metadata:
wyze-bridge    |     encoder         : Lavf58.45.100
wyze-bridge    |     Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (0x0), q=2-31, 20.33 fps, 20 tbr, 90k tbn, 20 tbc
wyze-bridge    | Stream mapping:
wyze-bridge    |   Stream #0:0 -> #0:0 (copy)
2021/10/28 21:06:27 [RTSP][FRONT-YARD-CAM] ✅ '/front-yard-cam' stream is UP!e=N/A speed=0.917x    
wyze-bridge    | [rtsp @ 0x3163dc0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
`

**Comment by airbornetrooper82573** [comment]
What is the command used to downgrade back to 0.7.6?

**Comment by airbornetrooper82573** [comment]
> Any errors in homebridge?
> 
> You may also want to check out [Scrypted](https://github.com/mrlt8/docker-wyze-bridge/wiki/HomeKit-Secure-Video)

It's working in Scrypted. Can you tell me more about it? It is essentially a HomeBridge alternative? I'd like to get this working with my original setup but this will have to do for the time being.

**Comment by mrlt8** [comment]
You can downgrade by using `mrlt8/wyze-bridge:0.7.6` instead of `mrlt8/wyze-bridge:latest`

I'm guessing something is wrong with your homebridge setup since it works in VLC and Scrypted..?

**Comment by airbornetrooper82573** [comment]
Strangely enough, my Pi 3b crapped the bed so I had to swap it with a pi 4. I have pi-hole and wyze-bridge running in docker now and so far everything is working fine. I'll leave this open for a day and if all is still will, I will close.

**Comment by airbornetrooper82573** [comment]
Meant to close this but life happens. All is working fine using docker on the pi 4. I have had 0 drops. Thanks to this project I learned how to use docker and portainer so kudos.
