### ISSUE TITLE
Add WebRTC Support

### ISSUE THREAD

**Issue by mrlt8** [mrlt8/docker-wyze-bridge#213]
Since wyze has native WebRTC, it's probably a good idea to switch over to the kinesis WebRTC as backup and/or in addition to tutk.

**Comment by tonesto7** [comment]
Are there any performance hits or benefits?  Is WebRTC more stable?

**Comment by mrlt8** [comment]
I was able to access the stream which also supports audio, but haven't been able to do much testing as ffmpeg and rtsp-simple-server don't seem to support webrtc natively.

**Comment by mckochan** [comment]
Don't know if you've seen it, but home assistant has native WebRTC support now that someone implemented it for the nest cams that use it.
https://github.com/home-assistant/core/pull/57034

**Comment by tonesto7** [comment]
I hope it works better than RTSP now.  I can't use them at all since updating to DTLS firmware.  

I've even split my 8 cameras into 2 bridges and they still won't stay streaming

**Comment by mrlt8** [comment]
It would still use RTSP. What would change is the backend - replace tutk with webRTC.

**Comment by tonesto7** [comment]
Are you close to allowing access in edge release?

**Comment by parthmodi** [comment]
Has Webrtc been implemented in the main branch? I added the environment variable WEBRTC, but I’m not seeing anything in the log indicating it’s using Webrtc.

**Comment by mrlt8** [comment]
Not yet. We can pull the signaling URL, token, etc, but not really sure where to go from there as there.

Home Assistant has support for WebRTC, but I was not able to figure out how to get it working with the wyze stream.
