### ISSUE TITLE
Several Python Traceback printout

### ISSUE THREAD

**Issue by AdiAbuAli** [mrlt8/docker-wyze-bridge#214]
Hi, 
In latest release, I start see several Python tracebacks (some are fatal, and with several modules)...Attached for today..
![1](https://user-images.githubusercontent.com/89463853/139922546-c6d850e8-2586-435c-bff3-26f085b0d852.JPG)
![2](https://user-images.githubusercontent.com/89463853/139922550-d7a6c6eb-8410-4c6b-b746-35d56d605459.JPG)
![4](https://user-images.githubusercontent.com/89463853/139922552-5fe039a9-6463-4dcb-a3fb-67a833ef8a6b.JPG)
![6](https://user-images.githubusercontent.com/89463853/139922555-940ef2fd-9342-4434-b9ba-f6a44fad7d82.JPG)
![7](https://user-images.githubusercontent.com/89463853/139922556-8e49ef71-0a77-4f1a-ac2f-f2d13d14d20c.JPG)
![5](https://user-images.githubusercontent.com/89463853/139922558-5ebd7318-8dd6-463f-8386-644668bbfa61.JPG)
..

**Comment by AdiAbuAli** [comment]
another one just after restart....
![Capture](https://user-images.githubusercontent.com/89463853/139957336-2f3008fe-caec-46f8-bc8a-610aa9a9f32d.JPG)

**Comment by mrlt8** [comment]
Does this help? https://github.com/mrlt8/docker-wyze-bridge/commit/a5e88942e8b27d282a7483c0842433390683f84b

**Comment by AdiAbuAli** [comment]
No....

Seems each of the below 6 tracback, have different root cause...maybe?

**Comment by AdiAbuAli** [comment]
or maybe it wasn't pushed to docker, since I can see latest image in Docker is 7 days old, while a5e8894 is 5 days back...

![image](https://user-images.githubusercontent.com/89463853/140319959-29445aa9-da9a-476e-a1e5-8709c9004745.png)

**Comment by mrlt8** [comment]
It hasn't been pushed as a release. Please try the nightly or edge image.

**Comment by AdiAbuAli** [comment]
I run it under Nightly and will observe and keep you updated.

**Comment by AdiAbuAli** [comment]
Quick update ...python tracebacks seems to be solved (except one incident. when PC shutdown improperly, and run it again)..

**Comment by AdiAbuAli** [comment]
using nightly released yesterday (https://registry.hub.docker.com/layers/mrlt8/wyze-bridge/nightly/images/sha256-15dd5586e81d944bb63d7ed2f71bb4cc8c0f3c67ab367d80341f4a6c883a29da?context=explore), released 13 hours back.

below pythons tracebacks observed after stop-start:
![Capture](https://user-images.githubusercontent.com/89463853/140504268-a66bc39f-5b04-4962-a565-2cc37090e240.JPG)

**Comment by AdiAbuAli** [comment]
@mrlt8 Still there is Python Traceback printouts, on both Nightly and Edge...

**Comment by AdiAbuAli** [comment]
Still in 1.03, below MQTT tracebacks (FYI...MQTT=FALSE in env)...it doesn't impact the stream anyway...

Traceback (most recent call last):                                                                                                                        
  File "/app/rtsp_event.py", line 8, in <module>                                                                                                          
    import paho.mqtt.client as mqtt                                                                                                                       
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                      
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked                                                                              
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked                                                                                       
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module                                                                                 
  File "<frozen importlib._bootstrap_external>", line 978, in get_code                                                                                    
  File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode                                                                           
KeyboardInterrupt                                                                                                                                         
2021/11/13 13:18:28 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP!                                                                                     
[rtsp @ 0x55d7c3406ac0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the ti
mestamps properly                                                                                                                                         
2021/11/13 13:18:29 [RTSP][GARAGE] ✅ '/garage' stream is UP!                                                                                             
2021/11/13 13:18:29 [RTSP][GARAGE] Ὅ6 New client reading                                                                                                 
2021/11/13 13:18:29 [RTSP][FRONT-DOOR] Ὅ6 New client reading                                                                                             
2021/11/13 13:18:29 [RTSP][FRONT-DOOR] Ὅ6 New client reading                                                                                             
2021/11/13 13:18:29 [RTSP][FRONT-DOOR] Ὅ5 Client stopped reading                                                                                         
Traceback (most recent call last):                                                                                                                        
  File "/app/rtsp_event.py", line 8, in <module>                                                                                                          
    import paho.mqtt.client as mqtt                                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 57, in <module>                                                                 
    from urllib import request as urllib_dot_request                                                                                                      
  File "/usr/local/lib/python3.9/urllib/request.py", line 88, in <module>                                                                                 
    import http.client                                                                                                                                    
  File "/usr/local/lib/python3.9/http/client.py", line 1459, in <module>                                                                                  
    class HTTPException(Exception):                                                                                                                       
  File "/usr/local/lib/python3.9/http/client.py", line 1459, in HTTPException                                                                             
    class HTTPException(Exception):                                                                                                                       
KeyboardInterrupt                                                                                                                                         
2021/11/13 13:18:30 [RTSP][GARAGE] Ὅ6 New client reading

**Comment by mrlt8** [comment]
hmm, not sure why you seem to be getting so many errors from rtsp_event.py

Also, mqtt _should_ should be disabled by default unless you're running in home assistant..

**Comment by AdiAbuAli** [comment]
Seems only ones using docker over Synology NAS?...below was another case from another user...

https://github.com/mrlt8/docker-wyze-bridge/issues/228

**Comment by AdiAbuAli** [comment]
Hi,
Still the issue not solved in lastest release, just only after restarting the synology NAS.
Am not sure, maybe its related to docker version or synology, but why just recently I have no idea.

**Comment by mrlt8** [comment]
Can you post the error that you see?

**Comment by AdiAbuAli** [comment]
Below is an example....it's not always failed to import signal, but sometimes other mdoules (e.g. OS....it's random), and some times keep logging tracbacks and never connect...
it's random bhaviour, whenever I stop and restart the container...and hang in that behaviour till I restart the synology NAS (not only Docker).

Docker version is 20.10.3.-1239 in Synology.

Ἲc STARTING ALL 3 CAMERAS                                                                                                                                                                                  
2021/12/02 13:48:14 [WyzeBridge] Starting rtsp-simple-server v0.17.10                                                                                                                                       
2021/12/02 13:48:17 [Front Door] Ἰ9 Starting HD 120kB/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 ὑ2 (DTLS) IP: 10.0.0.16 WiFi: 96%                                                                  
2021/12/02 13:48:17 [Front Door] WARNING: [First run] Wrong resolution: 1                                                                                                                                   
2021/12/02 13:48:17 [Back Door] Ἰ9 Starting HD 120kB/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 ὑ2 (DTLS) IP: 10.0.0.2 WiFi: 99%                                                                    
2021/12/02 13:48:17 [Back Door] WARNING: [First run] Wrong resolution: 1                                                                                                                                    
2021/12/02 13:48:17 [Front Door] WARNING: Frame not available                                                                                                                                               
2021/12/02 13:48:17 [Back Door] WARNING: Frame not available                                                                                                                                                
2021/12/02 13:48:18 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP!                                                                                                                                       
2021/12/02 13:48:18 [Garage] Ἰ9 Starting HD 120kB/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 ὑ2 (DTLS) IP: 10.0.0.23 WiFi: 99%                                                                      
2021/12/02 13:48:18 [Garage] WARNING: [First run] Wrong resolution: 1                                                                                                                                       
2021/12/02 13:48:18 [Garage] WARNING: Frame not available                                                                                                                                                   
2021/12/02 13:48:18 [RTSP][FRONT-DOOR] Ὅ6 New client reading                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                          
  File "/app/rtsp_event.py", line 6, in <module>                                                                                                                                                            
    import signal                                                                                                                                                                                           
  File "/usr/local/lib/python3.9/signal.py", line 3, in <module>                                                                                                                                            
    from functools import wraps as _wraps                                                                                                                                                                   
  File "/usr/local/lib/python3.9/functools.py", line 18, in <module>                                                                                                                                        
    from collections import namedtuple                                                                                                                                                                      
  File "/usr/local/lib/python3.9/collections/__init__.py", line 911, in <module>                                                                                                                            
    class ChainMap(_collections_abc.MutableMapping):                                                                                                                                                        
  File "/usr/local/lib/python3.9/abc.py", line 106, in __new__                                                                                                                                              
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)                                                                                                                                           
KeyboardInterrupt                                                                                                                                                                                           
2021/12/02 13:48:19 [RTSP][BACK-DOOR] ✅ '/back-door' stream is UP!                                                                                                                                         
2021/12/02 13:48:20 [RTSP][BACK-DOOR] Ὅ6 New client reading                                                                                                                                                
2021/12/02 13:48:20 [RTSP][GARAGE] ✅ '/garage' stream is UP!                                                                                                                                               
2021/12/02 13:48:20 [RTSP][GARAGE] Ὅ6 New client reading                                                                                                                                                   
2021/12/02 13:48:20 [RTSP][BACK-DOOR] Ὅ6 New client reading                                                                                                                                                
2021/12/02 13:48:21 [RTSP][BACK-DOOR] Ὅ5 Client stopped reading

**Comment by mrlt8** [comment]
I believe what's happening is that your client stops reading the stream almost immediately which causes rtsp-simple-server to kill the runOnRead command with SIGINT (KeyboardInterrupt) before rtsp_event.py even has a chance to start up.

**Comment by AdiAbuAli** [comment]
maybe becuase it happen only (traceback and import error) at that same stage always.

what is the proposed change will do in that case?
also can I re-pull latest image now to test?

**Comment by mrlt8** [comment]
Adjust your client so it doesn't stop immediately..?

Changes should be in the edge branch, but probably won't make a difference if your client is dropping the connection immediately.

**Comment by AdiAbuAli** [comment]
I see...that why the other complain also in synology, we are using same SW...there is no such option.
anyways, we may disable the cameras from NVR, and enable it after enabling the bridge....not before

**Comment by mrlt8** [comment]
Do you know why it starts and stops reading? Is it attempting to ping the stream for availability? Maybe rtsp-simple-server could add an option to ignore runOnRead for pings?

**Comment by AdiAbuAli** [comment]
You mean in normal scenario (despite the import error)?
If yes, so I need to do tcpdump during setup phase to check.
But its always tries to to open 2 reads, one of them get down and one get up...maybe tries to get one with high quality and another with low qualoty stream, so I can have option to record on low quality and one for motion detection use high quality....
Anyways, the setup from the bridge is only one stream, either HD or SD.
Will confirm via trace.

Thanks,
________________________________

**Comment by mrlt8** [comment]
Marking this as resolved.
Please feel free to open a new topic if you need additional assistance.
