### ISSUE TITLE
WyzeApp updated firmware to 4.36.6.17 & issues

### ISSUE THREAD

**Issue by capncybo** [mrlt8/docker-wyze-bridge#217]
Last-night I let my phone's Android WyzeApp upgrade two of my v3 cameras firmware to 4.36.6.17
This morning I'm unable to view the rtsp streams...
Not sure if it's a coincidence?
(Note: I already tried stopping & rebuilding the docker container & I've toggled the cameras ON / OFF / & ON...)
No luck so far, Any advise?

EDITED: **RESOLVED** it myself by adding the IP of the Server into my... "docker-compose.yml" file:
            - DOCKER_HOST=192.168.1.116
Note: for my usage case... I'm going through OPENVPN between (Home <---> Work)
+ There have been A LOT of Linux Security Upgrades Lately so ???
But I swear... it was working without the DOCKER_HOST being specified before.

When Broken... it simply displayed the following...
Starting wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v1.0.2
wyze-bridge    | 
wyze-bridge    | 2021/11/04 15:57:42 [WyzeBridge] 📚 Using 'user' from local cache...
wyze-bridge    | 2021/11/04 15:57:42 [WyzeBridge] 📚 Using 'cameras' from local cache...
wyze-bridge    | 
wyze-bridge    | 🎬 STARTING ALL 2 CAMERAS
wyze-bridge    | 2021/11/04 15:57:42 [WyzeBridge] Starting rtsp-simple-server v0.17.6
wyze-bridge    | 2021/11/04 15:57:43 [Front Yard] IOTC_ER_DEVICE_OFFLINE
wyze-bridge    | 2021/11/04 15:57:43 [Front Yard] 👻 Camera offline. WILL retry in 10s.
wyze-bridge    | 2021/11/04 15:57:43 [Front Door] IOTC_ER_DEVICE_OFFLINE
wyze-bridge    | 2021/11/04 15:57:43 [Front Door] 👻 Camera offline. WILL retry in 10s.
wyze-bridge    | 2021/11/04 15:57:54 [Front Door] IOTC_ER_DEVICE_OFFLINE
wyze-bridge    | 2021/11/04 15:57:54 [Front Door] 👻 Camera offline. WILL retry in 20s.
wyze-bridge    | 2021/11/04 15:57:54 [Front Yard] IOTC_ER_DEVICE_OFFLINE
wyze-bridge    | 2021/11/04 15:57:54 [Front Yard] 👻 Camera offline. WILL retry in 20s.
wyze-bridge    | 2021/11/04 15:58:14 [Front Yard] IOTC_ER_DEVICE_OFFLINE
wyze-bridge    | 2021/11/04 15:58:14 [Front Yard] 👻 Camera offline. WILL retry in 30s.

**Comment by xconverge** [comment]
Yea I dont know what I was thinking updating the FW without checking here first. I recreated my container with DOCKER_HOST set as well and it works...

**Comment by oParoxysm** [comment]
Hello all,

I too faced this issue after updating. I was able to get it resolved by deleting the container and creating it again, all is working as expected now.

**Comment by mrlt8** [comment]
Hmm, I wonder if it might be enough to set the fresh data env.

**Comment by yeahme49** [comment]
> Hmm, I wonder if it might be enough to set the fresh data env.

That's all I had to do after I upgraded to 4.36.6.17, didn't need to delete the container.

**Comment by RUHavingFun** [comment]
> > Hmm, I wonder if it might be enough to set the fresh data env.
> 
> That's all I had to do after I upgraded to 4.36.6.17, didn't need to delete the container.

Fixed for me too.

**Comment by robhammett** [comment]
No joy with the DOCKER_HOST fix.  Getting the following:

wyze-bridge_1  | 2021/11/16 22:44:18 I [0/0] rtsp-simple-server v0.16.4
wyze-bridge_1  | 2021/11/16 22:44:18 I [0/0] [RTSP] UDP/RTP listener opened on :8000
wyze-bridge_1  | 2021/11/16 22:44:18 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
wyze-bridge_1  | 2021/11/16 22:44:18 I [0/0] [RTSP] TCP listener opened on :8554
wyze-bridge_1  | 2021/11/16 22:44:18 I [0/0] [RTMP] listener opened on :1935
wyze-bridge_1  | 2021/11/16 22:44:18 I [0/0] [HLS] listener opened on :8888
wyze-bridge_1  | STARTING DOCKER-WYZE-BRIDGE v0.4.0
wyze-bridge_1  | Could not find local cache for user
wyze-bridge_1  | Could not find local cache for auth
wyze-bridge_1  | Fetching auth from wyze api...
wyze-bridge_1  | Saving auth to local cache...
wyze-bridge_1  | Fetching user from wyze api...
wyze-bridge_1  | Saving user to local cache...
wyze-bridge_1  | Could not find local cache for cameras
wyze-bridge_1  | Fetching cameras from wyze api...
wyze-bridge_1  | Saving cameras to local cache...
wyze-bridge_1  | STARTING ALL 2 CAMERAS
wyze-bridge_1  | 2021/11/16 22:44:32 [spare01] IOTC_ER_CAN_NOT_FIND_DEVICE
wyze-bridge_1  | 2021/11/16 22:44:32 [spare01] Camera offline? Sleeping for 10s.
wyze-bridge_1  | 2021/11/16 22:44:32 [driveway01] IOTC_ER_CAN_NOT_FIND_DEVICE
wyze-bridge_1  | 2021/11/16 22:44:32 [driveway01] Camera offline? Sleeping for 10s.

**Comment by RUHavingFun** [comment]
> No joy with the DOCKER_HOST fix. Getting the following:
> 
> FIX: Blow out everything, pull new image from dockerhub and it all worked like a charm!
> 
> wyze-bridge_1 | 2021/11/16 22:44:18 I [0/0] rtsp-simple-server v0.16.4 wyze-bridge_1 | 2021/11/16 22:44:18 I [0/0] [RTSP] UDP/RTP listener opened on :8000 wyze-bridge_1 | 2021/11/16 22:44:18 I [0/0] [RTSP] UDP/RTCP listener opened on :8001 wyze-bridge_1 | 2021/11/16 22:44:18 I [0/0] [RTSP] TCP listener opened on :8554 wyze-bridge_1 | 2021/11/16 22:44:18 I [0/0] [RTMP] listener opened on :1935 wyze-bridge_1 | 2021/11/16 22:44:18 I [0/0] [HLS] listener opened on :8888 wyze-bridge_1 | STARTING DOCKER-WYZE-BRIDGE v0.4.0 wyze-bridge_1 | Could not find local cache for user wyze-bridge_1 | Could not find local cache for auth wyze-bridge_1 | Fetching auth from wyze api... wyze-bridge_1 | Saving auth to local cache... wyze-bridge_1 | Fetching user from wyze api... wyze-bridge_1 | Saving user to local cache... wyze-bridge_1 | Could not find local cache for cameras wyze-bridge_1 | Fetching cameras from wyze api... wyze-bridge_1 | Saving cameras to local cache... wyze-bridge_1 | STARTING ALL 2 CAMERAS wyze-bridge_1 | 2021/11/16 22:44:32 [spare01] IOTC_ER_CAN_NOT_FIND_DEVICE wyze-bridge_1 | 2021/11/16 22:44:32 [spare01] Camera offline? Sleeping for 10s. wyze-bridge_1 | 2021/11/16 22:44:32 [driveway01] IOTC_ER_CAN_NOT_FIND_DEVICE wyze-bridge_1 | 2021/11/16 22:44:32 [driveway01] Camera offline? Sleeping for 10s.

Did you try the fresh data option?  It has worked for many of us.

- FRESH_DATA=True

**Comment by mrlt8** [comment]
Marking this as resolved.
Please feel free to open a new topic if you need additional assistance.
