### ISSUE TITLE
V3 show up but not V2 (w/ RTSP firmware)

### ISSUE THREAD

**Issue by k-rock** [mrlt8/docker-wyze-bridge#22]
I am able to view my V3 but not V2 camera streams.

My V2 camera is named 'garage' but I cannot view that particular stream.
Any suggestions?

`
kyle@monster:~$ sudo systemctl status wyzebridge.service
● wyzebridge.service - Wyze bridge
   Loaded: loaded (/lib/systemd/system/wyzebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-07-16 14:15:55 EDT; 18min ago
  Process: 17173 ExecStartPre=/usr/bin/docker-compose stop (code=exited, status=0/SUCCESS)
  Process: 17180 ExecStartPre=/usr/bin/docker-compose pull (code=exited, status=0/SUCCESS)
 Main PID: 17189 (docker-compose)
    Tasks: 7 (limit: 4915)
   Memory: 37.5M
   CGroup: /system.slice/wyzebridge.service
           └─17189 /usr/bin/python3 /usr/bin/docker-compose up

Jul 16 14:33:39 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:33:39 [garage] 'type'
Jul 16 14:33:50 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:33:50 [garage] Starting HD 120kb/s Stream for WyzeCam V2 (WYZEC1-JZ) running FW: 4.
Jul 16 14:33:50 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:33:50 [garage] 'type'
Jul 16 14:34:02 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:34:02 [garage] Starting HD 120kb/s Stream for WyzeCam V2 (WYZEC1-JZ) running FW: 4.
Jul 16 14:34:02 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:34:02 [garage] 'type'
Jul 16 14:34:07 monster docker-compose[17189]: rtsp-server    | 2021/07/16 18:34:07 I [3/2] [RTSP] [conn 192.168.86.50:60088] opened
Jul 16 14:34:07 monster docker-compose[17189]: rtsp-server    | 2021/07/16 18:34:07 I [3/2] [RTSP] [conn 192.168.86.50:60088] ERR: no one is publishing to path '
Jul 16 14:34:07 monster docker-compose[17189]: rtsp-server    | 2021/07/16 18:34:07 I [3/2] [RTSP] [conn 192.168.86.50:60088] closed
Jul 16 14:34:14 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:34:14 [garage] Starting HD 120kb/s Stream for WyzeCam V2 (WYZEC1-JZ) running FW: 4.
Jul 16 14:34:14 monster docker-compose[17189]: wyze-bridge    | 2021/07/16 18:34:14 [garage] 'type'
`

**Comment by mrlt8** [comment]
Seems to be related to #20, who is also getting the same ‘type’ error on the rtsp firmware.
