### ISSUE TITLE
Unable to re-install docker-wyze-bridge

### ISSUE THREAD

**Issue by SomebodySysop** [mrlt8/docker-wyze-bridge#222]
Been running for months without issue.  Updated firmware on all cams tonight and bridge stopped working.  So, decided to just re-install.

git clone https://github.com/mrlt8/docker-wyze-bridge.git

root@ToshibaWin7-Ubuntu:/home/ron/docker# cd docker-wyze-bridge
root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge# docker-compose up
Removing rtsp-server
Starting 112dc2f54235_rtsp-server ... 
Starting 112dc2f54235_rtsp-server ... error

ERROR: for 112dc2f54235_rtsp-server  Cannot start service rtsp-server: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/ron/docker/docker-wyze-bridge/app/rtsp-simple-server.yml" to rootfs at "/rtsp-simple-server.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for rtsp-server  Cannot start service rtsp-server: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/ron/docker/docker-wyze-bridge/app/rtsp-simple-server.yml" to rootfs at "/rtsp-simple-server.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge# ls -la app
total 8760
drwxr-xr-x 3 root root    4096 Nov  8 21:54 .
drwxr-xr-x 5 root root    4096 Nov  8 21:54 ..
-rwxr-xr-x 1 root root 4818376 Nov  8 21:53 amd.lib
-rw-r--r-- 1 root root 4073452 Nov  8 21:53 arm.lib
-rwxr-xr-x 1 root root     992 Nov  8 21:53 CHANGELOG.md
-rw-r--r-- 1 root root    1894 Nov  8 21:53 config.json
-rw-r--r-- 1 root root    1637 Nov  8 21:53 Dockerfile
-rw-r--r-- 1 root root    1639 Nov  8 21:53 Dockerfile.arm
-rwxr-xr-x 1 root root     656 Nov  8 21:53 DOCS.md
-rw-r--r-- 1 root root    1711 Nov  8 21:53 multi-arch.Dockerfile
-rwxr-xr-x 1 root root    2543 Nov  8 21:53 README.md
-rw-r--r-- 1 root root    4626 Nov  8 21:53 rtsp_event.py
drwxr-xr-x 2 root root    4096 Nov  8 21:54 rtsp-simple-server.yml
-rw-r--r-- 1 root root   21875 Nov  8 21:53 wyze_bridge.py
root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge# 

The install keeps creating rtsp-simple-server.yml as a directory, then consequently fails to start.  How do I fix this?

**Comment by SomebodySysop** [comment]
As a follow up.  I removed the wyze-bridge and rtsp-bridge containers as well as docker-wyze-bridge directory and started from scratch.  Same results.

root@ToshibaWin7-Ubuntu:/home/ron/docker# rm -r docker-wyze-bridge
root@ToshibaWin7-Ubuntu:/home/ron/docker# git clone https://github.com/mrlt8/docker-wyze-bridge.git
Cloning into 'docker-wyze-bridge'...
remote: Enumerating objects: 911, done.
remote: Counting objects: 100% (911/911), done.
remote: Compressing objects: 100% (624/624), done.
remote: Total 911 (delta 518), reused 587 (delta 251), pack-reused 0
Receiving objects: 100% (911/911), 3.78 MiB | 9.16 MiB/s, done.
Resolving deltas: 100% (518/518), done.
root@ToshibaWin7-Ubuntu:/home/ron/docker# cp docker-compose.yml docker-wyze-bridge
root@ToshibaWin7-Ubuntu:/home/ron/docker# cd docker-wyze-bridge
root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge# docker-compose up
Creating rtsp-server ... error
Creating wyze-bridge ... 

ERROR: for rtsp-server  Cannot start service rtsp-server: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/ron/docker/docker-wyze-bridge/app/rtsp-simple-server.yml" to rootfs at "/rtsp-simple-server.yml" caused: mount through procfd: not a directory: unknown: Are youCreating wyze-bridge ... done

ERROR: for rtsp-server  Cannot start service rtsp-server: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/ron/docker/docker-wyze-bridge/app/rtsp-simple-server.yml" to rootfs at "/rtsp-simple-server.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge#

**Comment by mrlt8** [comment]
There have been several structural changes and deprecation to the bridge over the past few versions that may require an updated docker-compose. 
See the latest example [docker-compose](https://github.com/mrlt8/docker-wyze-bridge/blob/main/docker-compose.sample.yml). 
You may also need to run `docker-compose pull`

**Comment by SomebodySysop** [comment]
Is this:


version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888

in addition to the below, or it replaces it (no "rtsp-server" directive)?

version: '3'
services:
    rtsp-server:
        container_name: rtsp-server
        image: aler9/rtsp-simple-server
        restart: always
        environment: 
            - RTSP_PROTOCOLS=tcp
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        volumes:
            - ./app/rtsp-simple-server.yml:/rtsp-simple-server.yml

    wyzecam-bridge:
        container_name: wyze-bridge
        build: 
            context: ./app
            dockerfile: Dockerfile.arm
        restart: always

**Comment by mrlt8** [comment]
It should replace it. You can remove the rtsp-server related stuff as it's handled from within the bridge.

**Comment by SomebodySysop** [comment]
Got it!  Made changes and rtsp and wyze-bridge come up.  But, stuck in this loop:

root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge# docker-compose pull
Pulling wyze-bridge ... done
root@ToshibaWin7-Ubuntu:/home/ron/docker/docker-wyze-bridge# docker-compose up --build --force-recreate --remove-orphans
Removing orphan container "rtsp-server"
Removing orphan container "wyze-bridge"
Creating wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v1.0.2
wyze-bridge    | 
wyze-bridge    | 2021/11/09 06:46:34 [WyzeBridge] 🔍 Could not find local cache for 'user'
wyze-bridge    | 2021/11/09 06:46:34 [WyzeBridge] 🔍 Could not find local cache for 'auth'
wyze-bridge    | 2021/11/09 06:46:34 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:46:35 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/loginwyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:46:45 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:46:45 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/loginwyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:46:55 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:46:55 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/loginwyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:47:05 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:47:05 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/loginwyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:47:15 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:47:15 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/loginwyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:47:25 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:47:25 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/loginwyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:47:35 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:47:35 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
wyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:47:45 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:47:45 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
wyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:47:55 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:47:55 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
wyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:48:05 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:48:05 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
wyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2021/11/09 06:48:15 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/09 06:48:16 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
wyze-bridge    | Sleeping for 10s...

Anything I can do about it?

**Comment by mrlt8** [comment]
Looks like you're getting rate limited from the Wyze servers for some reason..

One quick way around would be to request a new IP on your modem.

**Comment by SomebodySysop** [comment]
> Looks like you're getting rate limited from the Wyze servers for some reason..
> 
> One quick way around would be to request a new IP on your modem.

Probably because I kept restarting the bridge when it stopped working after the update -- unless it was the update when this started happening.  Sheesh!

**Comment by SomebodySysop** [comment]
Final question. Why am I getting this error?:

root@Raspberry-Ubuntu:/home/ron/docker/docker-wyze-bridge# **docker-compose pull**
_ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.wyze-bridge: 'dockerfile'_


version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:

**Comment by SomebodySysop** [comment]
I commented out the "dockerfile" command on raspberry and it came up without issue.

Also waited a bit and restarted bridge on toshiba and it came up also without issue.

For the record, the docker-wyze-bridge has worked like a charm for months now in my application which has grown to 7 wyze cameras.  I prefer this over using the new RTSP firmware which I'm sure will be quite limited and poorly supported.

Thank you @mrlt8 for your continued work on this.
