### ISSUE TITLE
Missing camera

### ISSUE THREAD

**Issue by rbflurry** [mrlt8/docker-wyze-bridge#227]
The bridge will only loads 6 cameras for me. I have another V3 named "sheds" that has never worked.

On startup it only says starting all 6 cameras, I tried fresh data and deleting the pickle and deleting and recreating the container.

Pickle file only shows the 6 cameras.

Any other ideas?

**Comment by mrlt8** [comment]
> I have another V3 named "sheds" that has never worked.

Do you have two cameras named "sheds"? The bridge uses the names as the ID, so there's a chance one of the cameras is getting ignored if they have the same name.

**Comment by rbflurry** [comment]
Sorry wrong choice of words. All cameras have unique names. Is there any other filtering going on?

**Comment by mrlt8** [comment]
The bridge did filter out DTLS enabled cameras on previous versions, but there shouldn't be any filtering if you're on v1.0+.

**Comment by rbflurry** [comment]
Running the latest versions so that should not be it. Thank you for your suggestions so far.

**Comment by rbflurry** [comment]
Nevermind, I figured this out, My mistake thank you.
