### ISSUE TITLE
container keeps crashing

### ISSUE THREAD

**Issue by frankie1984** [mrlt8/docker-wyze-bridge#228]
Hi There,

I recently deployed the latest version(102) on my synology NAS and the container keeps crashing with this error:
Is there something i missed?

**11/11**
2021/11/11 13:10:07 [RTSP][VOORDEUR] 📕 Client stopped reading
2021/11/11 13:10:07 [RTSP][VOORDEUR] 📖 New client reading 
2021/11/11 13:10:12 [RTSP][VOORDEUR] 📕 Client stopped reading
2021/11/11 13:10:13 [RTSP][VOORDEUR] 📖 New client reading 
2021/11/11 13:10:17 [RTSP][VOORDEUR] 📕 Client stopped reading
2021/11/11 13:10:17 [RTSP][VOORDEUR] ❌ '/voordeur' stream is down
2021/11/11 13:10:51 [Voordeur] AV_ER_REMOTE_TIMEOUT_DISCONNECT
--- Logging error ---
Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 315, in start_stream
    with wyzecam.iotc.WyzeIOTCSession(*iotc) as sess:
  File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 313, in __enter__
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 670, in _connect
    raise tutk.TutkError(session_id)
wyzecam.tutk.tutk.TutkError: <unprintable TutkError object>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 365, in getMessage
    msg = str(self.msg)
TypeError: __str__ returned non-string (type int)
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/wyze_bridge.py", line 375, in start_stream
    log.info(ex)
Message: TutkError(-67)
Arguments: ()
Exception in thread Voordeur:
Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 315, in start_stream
    with wyzecam.iotc.WyzeIOTCSession(*iotc) as sess:
  File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 313, in __enter__
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 670, in _connect
    raise tutk.TutkError(session_id)
wyzecam.tutk.tutk.TutkError: <exception str() failed>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/wyze_bridge.py", line 376, in start_stream
    if str(ex) in "Authentication did not succeed! {'connectionRes': '2'}":
TypeError: __str__ returned non-string (type

**This was from the 11/10**
2021/11/10 16:34:38 [WyzeBridge] Starting rtsp-simple-server v0.17.7
2021/11/10 16:34:40 [Achtertuin poort] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.186 WiFi: 52%
2021/11/10 16:34:40 [Voordeur] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.17 WiFi: 63%
2021/11/10 16:34:40 [Semm] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.18 WiFi: 67%
2021/11/10 16:34:40 [Jipp] 🎉 Starting HD 120kb/s Stream for WyzeCam Pan "LAN mode" FW: 4.10.7.1068 🔒 (DTLS) IP: 192.168.1.19 WiFi: 44%
2021/11/10 16:34:41 [Tijs] 🎉 Starting HD 120kb/s Stream for WyzeCam Pan "LAN mode" FW: 4.10.7.1068 🔒 (DTLS) IP: 192.168.1.16 WiFi: 76%
2021/11/10 16:34:44 [RTSP][VOORDEUR] ✅ '/voordeur' stream is UP!
2021/11/10 16:34:45 [RTSP][ACHTERTUIN-POORT] ✅ '/achtertuin-poort' stream is UP!
2021/11/10 16:34:45 [RTSP][VOORDEUR] 📖 New client reading 
2021/11/10 16:34:45 [RTSP][JIPP] ✅ '/jipp' stream is UP!
2021/11/10 16:34:45 [RTSP][VOORDEUR] 📖 New client reading 
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 4, in <module>
    import paho.mqtt.client
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 57, in <module>
    from urllib import request as urllib_dot_request
  File "/usr/local/lib/python3.9/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/local/lib/python3.9/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/local/lib/python3.9/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/local/lib/python3.9/email/feedparser.py", line 37, in <module>
    headerRE = re.compile(r'^(From |[\041-\071\073-\176]*:|[\t ])')
  File "/usr/local/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.9/sre_parse.py", line 958, in parse
    p.state.flags = fix_flags(str, p.state.flags)
  File "/usr/local/lib/python3.9/sre_parse.py", line 924, in fix_flags
    if flags & SRE_FLAG_LOCALE:
KeyboardInterrupt
2021/11/10 16:34:46 [RTSP][ACHTERTUIN-POORT] 📖 New client reading 
2021/11/10 16:34:46 [RTSP][ACHTERTUIN-POORT] 📖 New client reading 
2021/11/10 16:34:46 [RTSP][ACHTERTUIN-POORT] 📕 Client stopped reading
2021/11/10 16:34:46 [RTSP][TIJS] ✅ '/tijs' stream is UP!
2021/11/10 16:34:47 [RTSP][SEMM] ✅ '/semm' stream is UP!
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 4, in <module>
    import paho.mqtt.client
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 18, in <module>
    import logging
  File "/usr/local/lib/python3.9/logging/__init__.py", line 439, in <module>
    class StrFormatStyle(PercentStyle):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 444, in StrFormatStyle
    fmt_spec = re.compile(r'^(.?[<>=^])?[+ -]?#?0?(\d+|{\w+})?[,_]?(\.(\d+|{\w+}))?[bcdefgnosx%]?$', re.I)
  File "/usr/local/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 156, in _compile
    _compile(code, av[2], flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 168, in _compile
    _compile(code, p, _combine_flags(flags, add_flags, del_flags))
  File "/usr/local/lib/python3.9/sre_compile.py", line 75, in _compile
    LITERAL_CODES = _LITERAL_CODES
KeyboardInterrupt
2021/11/10 16:34:47 [RTSP][ACHTERTUIN-POORT] 📖 New client reading 
2021/11/10 16:34:48 [RTSP][ACHTERTUIN-POORT] 📕 Client stopped reading
2021/11/10 16:34:50 [RTSP][VOORDEUR] 📕 Client stopped reading

**Comment by kingb2019** [comment]
Same issue here. Happened after I updated the HA add-on. Used the FRESH_DATA and still happens. Uninstalled, restarted and resinstalled, same issue.

**Comment by frankie1984** [comment]
Nice. I'll try to run the latest version and give you some feedback. 
Very nice 💪

**Comment by cayco** [comment]
I'm on the latest and container is still crashing. With or without MQTT enabled. For now I ended up with restarting it every hour...

**Comment by kingb2019** [comment]
So I've tried this on Hass, Docker on Ubuntu and Docker for Windows, same results for each instance. Is there a platform this is currently stable on?

**Comment by SomebodySysop** [comment]
I've reported this in another thread, just joining this one.  I don't think it's signal strength because ALL my cameras die after a few minutes to a few hours.  And it only started after the most recent firmware update.  Is Wyze intentionally trying to kill this RTSP alternative?

**Comment by frankie1984** [comment]
is reverting wyze firmware an option? I use a few v3 as smart doorbell/garden security so i rather have them working with my NAS on an older firmware.

**Comment by kingb2019** [comment]
> I've reported this in another thread, just joining this one. I don't think it's signal strength because ALL my cameras die after a few minutes to a few hours. And it only started after the most recent firmware update. Is Wyze intentionally trying to kill this RTSP alternative?

All mine were dying as well. It seems if one stream drops all the cameras drop. I started filtering as a test and they have been stable since as long as I leave the one with a weak signal off.

**Comment by SomebodySysop** [comment]
> All mine were dying as well. It seems if one stream drops all the cameras drop. I started filtering as a test and they have been stable since as long as I leave the one with a weak signal off.

When you say "filtering", what do you mean?

**Comment by SomebodySysop** [comment]
> All mine were dying as well. It seems if one stream drops all the cameras drop. I started filtering as a test and they have been stable since as long as I leave the one with a weak signal off.

Never mind.  I thought by "filtering" you were doing something different from what I'm doing.  But I use:
            - FILTER_NAMES=WyzeCam302, WyzeCam303, WyzeCam308, WyzeCam307, WyzeCam306, WyzeCam305, WyzeCam304
So I'm filtering too -- with the same adverse results.

**Comment by kingb2019** [comment]
> > All mine were dying as well. It seems if one stream drops all the cameras drop. I started filtering as a test and they have been stable since as long as I leave the one with a weak signal off.
> 
> Never mind. I thought by "filtering" you were doing something different from what I'm doing. But I use: - FILTER_NAMES=WyzeCam302, WyzeCam303, WyzeCam308, WyzeCam307, WyzeCam306, WyzeCam305, WyzeCam304 So I'm filtering too -- with the same adverse results.

Try filtering to 1 camera and add 1 at a time to see if one is causing the issue. I've done this and I have been stable ever since I found the problem child. I am going to add an AP and see if that keeps the problem at bay.

**Comment by SomebodySysop** [comment]
> > Never mind. I thought by "filtering" you were doing something different from what I'm doing. But I use: - FILTER_NAMES=WyzeCam302, WyzeCam303, WyzeCam308, WyzeCam307, WyzeCam306, WyzeCam305, WyzeCam304 So I'm filtering too -- with the same adverse results.
> 
> Try filtering to 1 camera and add 1 at a time to see if one is causing the issue. I've done this and I have been stable ever since I found the problem child. I am going to add an AP and see if that keeps the problem at bay.

Rebooted earlier today with these environmental variables:

            - RTSP_READTIMEOUT=120s
            - RTSP_APIADDRESS=0.0.0.0:9997
            - RTSP_API=yes            
            - DOCKER_HOST=192.168.1.197
            - FILTER_NAMES=WyzeCam302, WyzeCam303, WyzeCam308, WyzeCam307, WyzeCam306, WyzeCam305, WyzeCam304
            - FRESH_DATA=True

All the cameras have come up and stayed up, 

wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v1.0.2
wyze-bridge    | 
wyze-bridge    | 2021/11/19 02:53:03 [WyzeBridge] ♻️ FORCED REFRESH - Removing local 'user' data
wyze-bridge    | 2021/11/19 02:53:03 [WyzeBridge] ♻️ FORCED REFRESH - Removing local 'auth' data
wyze-bridge    | 2021/11/19 02:53:03 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2021/11/19 02:53:04 [WyzeBridge] 💾 Saving 'auth' to local cache...
wyze-bridge    | 2021/11/19 02:53:04 [WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
wyze-bridge    | 2021/11/19 02:53:05 [WyzeBridge] 💾 Saving 'user' to local cache...
wyze-bridge    | 2021/11/19 02:53:05 [WyzeBridge] ♻️ FORCED REFRESH - Removing local 'cameras' data
wyze-bridge    | 2021/11/19 02:53:05 [WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
wyze-bridge    | 2021/11/19 02:53:05 [WyzeBridge] 💾 Saving 'cameras' to local cache...
wyze-bridge    | 🪄 WHITELIST MODE ON
wyze-bridge    | 
wyze-bridge    | 🎬 STARTING 7 OF 9 CAMERAS
wyze-bridge    | 2021/11/19 02:53:05 [WyzeBridge] Starting rtsp-simple-server v0.17.7
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam305] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.73 WiFi: 97%
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam304] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.194 WiFi: 97%
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam303] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.220 WiFi: 96%
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam306] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.75 WiFi: 97%
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam302] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.177 WiFi: 96%
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam307] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.240 WiFi: 84%
wyze-bridge    | 2021/11/19 02:53:07 [WyzeCam308] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.196 WiFi: 70%
wyze-bridge    | 2021/11/19 02:53:12 [RTSP][WYZECAM303] ✅ '/wyzecam303' stream is UP!
wyze-bridge    | 2021/11/19 02:53:12 [RTSP][WYZECAM304] ✅ '/wyzecam304' stream is UP!
wyze-bridge    | 2021/11/19 02:53:12 [RTSP][WYZECAM306] ✅ '/wyzecam306' stream is UP!
wyze-bridge    | 2021/11/19 02:53:12 [RTSP][WYZECAM302] ✅ '/wyzecam302' stream is UP!
wyze-bridge    | 2021/11/19 02:53:13 [RTSP][WYZECAM308] ✅ '/wyzecam308' stream is UP!
wyze-bridge    | 2021/11/19 02:53:13 [RTSP][WYZECAM307] ✅ '/wyzecam307' stream is UP!
wyze-bridge    | 2021/11/19 02:53:17 [RTSP][WYZECAM305] ✅ '/wyzecam305' stream is UP!

The camera I seem to have the most problems with is 303 -- which is at 96% signal strength.  When I unplug it then plug it back:

 2021/11/19 03:07:01 [WyzeCam303] AV_ER_REMOTE_TIMEOUT_DISCONNECT
wyze-bridge    | --- Logging error ---
wyze-bridge    | Traceback (most recent call last):
wyze-bridge    |   File "/app/wyze_bridge.py", line 315, in start_stream
wyze-bridge    |     with wyzecam.iotc.WyzeIOTCSession(*iotc) as sess:
wyze-bridge    |   File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 313, in __enter__
wyze-bridge    |     self._connect()
wyze-bridge    |   File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 670, in _connect
wyze-bridge    |     raise tutk.TutkError(session_id)
wyze-bridge    | wyzecam.tutk.tutk.TutkError: <unprintable TutkError object>
wyze-bridge    | 
wyze-bridge    | During handling of the above exception, another exception occurred:
wyze-bridge    | 
wyze-bridge    | Traceback (most recent call last):
wyze-bridge    |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
wyze-bridge    |     msg = self.format(record)
wyze-bridge    |   File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
wyze-bridge    |     return fmt.format(record)
wyze-bridge    |   File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
wyze-bridge    |     record.message = record.getMessage()
wyze-bridge    |   File "/usr/local/lib/python3.9/logging/__init__.py", line 365, in getMessage
wyze-bridge    |     msg = str(self.msg)
wyze-bridge    | TypeError: __str__ returned non-string (type int)
wyze-bridge    | Call stack:
wyze-bridge    |   File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
wyze-bridge    |     self._bootstrap_inner()
wyze-bridge    |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
wyze-bridge    |     self.run()
wyze-bridge    |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
wyze-bridge    |     self._target(*self._args, **self._kwargs)
wyze-bridge    |   File "/app/wyze_bridge.py", line 375, in start_stream
wyze-bridge    |     log.info(ex)
wyze-bridge    | Message: TutkError(-67)
wyze-bridge    | Arguments: ()
wyze-bridge    | Exception in thread WyzeCam303:
wyze-bridge    | Traceback (most recent call last):
wyze-bridge    |   File "/app/wyze_bridge.py", line 315, in start_stream
wyze-bridge    |     with wyzecam.iotc.WyzeIOTCSession(*iotc) as sess:
wyze-bridge    |   File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 313, in __enter__
wyze-bridge    |     self._connect()
wyze-bridge    |   File "/usr/local/lib/python3.9/site-packages/wyzecam/iotc.py", line 670, in _connect
wyze-bridge    |     raise tutk.TutkError(session_id)
wyze-bridge    | wyzecam.tutk.tutk.TutkError: <exception str() failed>
wyze-bridge    | 
wyze-bridge    | During handling of the above exception, another exception occurred:
wyze-bridge    | 
wyze-bridge    | Traceback (most recent call last):
wyze-bridge    |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
wyze-bridge    |     self.run()
wyze-bridge    |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
wyze-bridge    |     self._target(*self._args, **self._kwargs)
wyze-bridge    |   File "/app/wyze_bridge.py", line 376, in start_stream
wyze-bridge    |     if str(ex) in "Authentication did not succeed! {'connectionRes': '2'}":
wyze-bridge    | TypeError: __str__ returned non-string (type int)

Stopped and restarted the container and they are all back up -- for now.

**Comment by mrlt8** [comment]
Marking this as resolved.
Please feel free to open a new topic if you need additional assistance.
