### ISSUE TITLE
Issues on Pi 4

### ISSUE THREAD

**Issue by michaelrobgrove** [mrlt8/docker-wyze-bridge#229]
I have this installed on my Pi 4 with Home Assistant. I used the HA version but after about 10 minutes, it seems to stop working. Showing running in HA but no log activity and HLS shows 404 error. RTSP just fails to load. 

So i removed from HA and tried the docker command. It downloads but says the credentials are missing. I have tried multiple times and still an issue. Credentials are in the command, works fine on AWS server. Not sure what I am missing. 

![issue](https://user-images.githubusercontent.com/63489982/141606112-6b8e066d-db26-4e1c-846e-6e21c3e4fabe.png)

**Comment by mrlt8** [comment]
Seems like it might be related to #211 

As for the credentials, are you including the key as well?
`docker run -p 8888:8888 -e WYZE_EMAIL=myemail@email.com -e WYZE_PASSWORD=mypassword  mrlt8/wyze-bridge:latest`

**Comment by RyanHope** [comment]
i am also getting this issue now

**Comment by mrlt8** [comment]
@RyanHope Missing credentials error?

**Comment by michaelrobgrove** [comment]
Sorry, this issue is resolved I didnt see your reply. 

It was a case of I should have went to bed instead of setting up another server. lol
