### ISSUE TITLE
Invalid credentials?

### ISSUE THREAD

**Issue by Swap-File** [mrlt8/docker-wyze-bridge#25]
I had a randomly generated Wyze account password with a $ in it.  It didn't seem to work with the bridge, when trying to connect I just got generic "Invalid credentials?" errors.

I generated a new random account password without special characters and it worked fine.

Are there special requirements for passwords with special characters to work with this program?

**Comment by mrlt8** [comment]
I think you can escape `$` with an extra `$`.  

e.g. use `pa$$$$word` to get `pa$$word`

**Comment by Swap-File** [comment]
Might be useful to add a warning that special characters need to be escaped. As this program gets popular less techy people will be trying to use it.  Thanks!

**Comment by cybersholt** [comment]
Escaping with a $ wasn't working for me in powershell, turns out you have to escape with \ so pa\$\$word to get pa$$word.

Hopefully helps someone and might be worth adding to the docs.

- Windows 10 Pro 21H1 19043.2075
- WSL 2
- Docker Desktop 4.12.0
