### ISSUE TITLE
[FFMPEG] [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by RyanHope** [mrlt8/docker-wyze-bridge#256]
Since the firmware upgrade that introduced DTLS, this project has been essentially unusable.  If I run the docker container from cmdline I see constant "Client stopped reading" "New client reading" messages until eventually a stream goes down, get a broken pipe error and then the rest of the streams stop working. I have to constantly kill the container and restart it.

**Comment by mrlt8** [comment]
Related to #211? Is this still an issue in v1.0.4?
