### ISSUE TITLE
Can this be used without a Wyze account (e.g. by manually specifying local IP addresses of cameras on LAN)?

### ISSUE THREAD

**Issue by diamondavocado** [mrlt8/docker-wyze-bridge#268]
I would like to remove the reliance on Wyze (or any remote service) entirely and run cameras in a purely local-only mode.

I understand from Issue #167 that you can connect to Wyze just once and then use the locally-stored tokens directory to stream cameras locally in LAN mode, however for future-proofing purposes I would prefer to never contact Wyze's servers at all.

Is there a way to do this, for example by specifying the MAC or IP addresses of your local cameras?

**Comment by mrlt8** [comment]
At this point, no it is not possible.

If you want to go fully offline and avoid the wyze cloud/app, I'd suggest trying to run a third-party firmware.

There is a actually a method to [search the LAN](http://www.sunipcam.com/sdk/UserManual/APIRefGuide/structst___lan_search_info.html) for devices in the tutk library, but the problem would be keeping the cams up without WAN access. The cameras will stay up if you disconnect them from the internet, but will have trouble booting up if they can't ping the wyze servers.

**Comment by diamondavocado** [comment]
> I'd suggest trying to run a third-party firmware.

Thank you for the reply.

Do you have any recommendations for firmware which supports the Wyze Cam v3? I was using `dafang-hacks` firmware on my v2 cameras but the v3 is not supported by that as far as I know.

**Comment by mrlt8** [comment]
Might be able to run [HclX/WyzeHacks](https://github.com/HclX/WyzeHacks) and/or [FiveLeavesLeft/WyzeCameraLiveStream](https://github.com/FiveLeavesLeft/WyzeCameraLiveStream) to see if you can disable some of the phone homes on the camera itself.
