### ISSUE TITLE
V3 cam gives error [SOLVED]

### ISSUE THREAD

**Issue by svanimpelen** [mrlt8/docker-wyze-bridge#27]
Got 2 cameras, the V2 works good, the V3 keeps giving me the error " [FFMPEG] [Errno 32] Broken pipe", these are the logs:

`today at 09:06:33 2021/07/22 07:06:33 I [1/1] [HLS] [conn 192.168.1.179:62596] GET /lieke/
today at 09:06:33 2021/07/22 07:06:33 I [1/1] [HLS] [converter lieke] opened
today at 09:06:33 2021/07/22 07:06:33 I [1/1] [HLS] [converter lieke] ERR: no one is publishing to path 'lieke'
today at 09:06:33 2021/07/22 07:06:33 I [1/1] [HLS] [converter lieke] closed
today at 09:06:39 2021/07/22 07:06:39 AV Client Start: chan_id=0 expected_chan=0
today at 09:06:39 2021/07/22 07:06:39 Now listening on channel id 0
today at 09:06:41 2021/07/22 07:06:41 No longer listening on channel id 0
today at 09:06:41 2021/07/22 07:06:41 [Lieke] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.2.5 from 192.168.3.83 "Relay mode" (WiFi Quality: 77%)...
today at 09:06:52 2021/07/22 07:06:52 [Lieke] [FFMPEG] [Errno 32] Broken pipe
today at 09:06:52 2021/07/22 07:06:52 [Lieke] Cleaning up FFmpeg...
today at 09:07:01 2021/07/22 07:07:01 AV Client Start: chan_id=0 expected_chan=0
today at 09:07:01 2021/07/22 07:07:01 Now listening on channel id 0
today at 09:07:04 2021/07/22 07:07:04 No longer listening on channel id 0
today at 09:07:04 2021/07/22 07:07:04 [Lieke] Starting HD 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) running FW: 4.36.2.5 from 192.168.3.83 "Relay mode" (WiFi Quality: 78%)...
today at 09:07:15 2021/07/22 07:07:15 [Lieke] [FFMPEG] [Errno 32] Broken pipe
today at 09:07:15 2021/07/22 07:07:15 [Lieke] Cleaning up FFmpeg...`

**Comment by svanimpelen** [comment]
I had the V2 cam on my normal WIFI and the V3 on my IoT network.

**Comment by backslashV** [comment]
how did you solve this? I am facing the same issue.

**Comment by svanimpelen** [comment]
I moved my v3 cam to my normal wifi.. Not ideal. Maybe can have the IP of the home server be reachable for the other vlan
