### ISSUE TITLE
Invalid credentials after docker restart

### ISSUE THREAD

**Issue by thehijacker** [mrlt8/docker-wyze-bridge#273]
Hello,

I made some changes to docker-compose.yml for wyze cotainer and restarted with docker-compose up -d. Since container was recreated I started to receive following in log:

```
🚀 STARTING DOCKER-WYZE-BRIDGE v1.0.4

2021/12/29 20:23:45 [wyze_bridge][INFO][WyzeBridge] 🔍 Could not find local cache for 'user'
2021/12/29 20:23:45 [wyze_bridge][INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
2021/12/29 20:23:45 [wyze_bridge][INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2021/12/29 20:23:45 [urllib3.connectionpool][DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
2021/12/29 20:23:46 [urllib3.connectionpool][DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
2021/12/29 20:23:46 [wyze_bridge][WARNING][WyzeBridge] 🚷 Invalid credentials?
2021/12/29 20:23:46 [wyze_bridge][WARNING][WyzeBridge] 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
Sleeping for 10s...
```

Password did not change. I have tried to login on web and it says user was locked. I have reset the password and recreated a new one. It works fine in Wyze app but still not working in wyze-bridge. I have also enabled two step verification but still same error in log.

Any idea?

**Comment by mrlt8** [comment]
Does `FRESH_DATA=true` help?

**Comment by AmGarera** [comment]
I'm experience the same issue

**Comment by AmGarera** [comment]
@mrlt8 I'm using FRESH_DATA=true already

**Comment by mrlt8** [comment]
I had a look, but it doesn't seem like much has changed in the api to break anything.
I also tried both sms and the time based codes, but unable to replicate..

Could this have been another AWS issue?

**Comment by AmGarera** [comment]
Mine was resolved # special character was in the pass and a + in my email/username
