### ISSUE TITLE
HEAD is now at 1a7e660 Add MAX_NOREADY env

### ISSUE THREAD

**Issue by SomebodySysop** [mrlt8/docker-wyze-bridge#274]
Trying to get the latest update using: git reset --hard HEAD

It fails with this message: HEAD is now at 1a7e660 Add MAX_NOREADY env

What am I doing wrong now!

**Comment by mrlt8** [comment]
```
docker-compose pull # Pull new image
docker-compose up -d # Restart container in detached mode
docker image prune # Remove old images
```

**Comment by SomebodySysop** [comment]
> ```
> docker-compose pull # Pull new image
> docker-compose up -d # Restart container in detached mode
> docker image prune # Remove old images
> ```

Exactly what I needed.  Thank you!
