### ISSUE TITLE
What is DTLS and can I disable it?

### ISSUE THREAD

**Issue by SomebodySysop** [mrlt8/docker-wyze-bridge#275]
I have had a world of woe with choppy | stuttering | hesitating video from my WyzeCam v3 cameras.  I've tried moving the access points around, getting cameras as close to APs as possible, finding the best channels and bandwidths, upgrading APs, and nothing seems to work.  Every Wyze camera I have deployed has jumpy video -- except for one.  I just installed it today, and it is also the only camera that does not come up with DTLS:

wyze-bridge    | 🎬 STARTING 7 OF 8 CAMERAS
wyze-bridge    | 2021/12/31 23:51:03 [WyzeBridge] Starting rtsp-simple-server v0.17.7
wyze-bridge    | 2021/12/31 23:51:05 [WyzeCam305] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.73 WiFi: 100%
**wyze-bridge    | 2021/12/31 23:51:05 [WyzeCam308] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.3.19 IP: 192.168.1.247 WiFi: 98%**
wyze-bridge    | 2021/12/31 23:51:05 [WyzeCam306] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 🔒 (DTLS) IP: 192.168.1.75 WiFi: 100%
wyze-bridge    | 2021/12/31 23:51:05 [WyzeCam302] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 🔒 (DTLS) IP: 192.168.1.177 WiFi: 100%
wyze-bridge    | 2021/12/31 23:51:05 [WyzeCam303] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 🔒 (DTLS) IP: 192.168.1.220 WiFi: 100%
wyze-bridge    | 2021/12/31 23:51:05 [WyzeCam307] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.6.17 🔒 (DTLS) IP: 192.168.1.240 WiFi: 97%
wyze-bridge    | 2021/12/31 23:51:06 [WyzeCam304] 🎉 Starting HD 120kb/s Stream for WyzeCam V3 "LAN mode" FW: 4.36.8.15 🔒 (DTLS) IP: 192.168.1.194 WiFi: 89%

The WyzeCam308 is a v3 camera that replaced another v3 camera in the exact same position.  The previous camera came up with 70% signal strength.  The replacement camera comes up with 98% signal strength.  Nothing else changed, except the cameras.  And as you can see, the newer one does not have DTLS.  So I'm wondering, what exactly is DTLS, and can I turn it off?

Or, can I revert to previous version of firmware?  4.36.3.19

**Comment by mrlt8** [comment]
There was a [vulnerability](https://www.throughtek.com/about-throughteks-kalay-platform-security-mechanism/) in the tutk platform that was patched by enabling DTLS on the cameras.

Wyze firmware updates tend to be buggy, so might be worth reinstalling the firmware before downgrading to see if that helps?

**Comment by SomebodySysop** [comment]
Someone on the Wyze forums mentioned this:

_So apparently that’s an SSL (TLS) tunnel using UDP instead of TCP. The cameras should negotiate it the same way though (for a given firmware)? Perhaps your router/firewall is throttling things somewhat randomly?_

Where would the throttle be?  The access point, the router, the linux box running docker-wyze-bridge?  Or is this just nonsense?

**Comment by danlo315** [comment]
I had the same issue with my V3 and stuttering.  I went through the downgrade all the way back to 4.36.0.280 and I can attest that the stuttering is severely reduced (but not gone).

**Comment by SomebodySysop** [comment]
> I had the same issue with my V3 and stuttering. I went through the downgrade all the way back to 4.36.0.280 and I can attest that the stuttering is severely reduced (but not gone).

Have flashed firmware version 4.36.3.19 onto 3 Wyze V3 cameras and the choppiness has been reduced dramatically on each.  I believe in my case, because of the density of wifi usage in my area, the only way I will completely eliminate choppiness | stuttering is to switch to wired cameras.  I've got 8 v3 cams on my docker-wyze-bridge, but seriously considering replacing at least 3 of them -- not only for less frame loss but for better image resolution as well.

Anyway, apparently no way to disable DTLS, so closing this topic.
