### ISSUE TITLE
Lan Mode - RTSP Stream

### ISSUE THREAD

**Issue by cdn4lf** [mrlt8/docker-wyze-bridge#28]
I tried to enable LAN mode on a Synology DSM.  The container started up and all the streams were published, however I was unable to connect to the streams with motioneye.

What should the RTSP stream be when in LAN mode as all the ports are being commented out?

**Comment by mrlt8** [comment]
[URIs](https://github.com/mrlt8/docker-wyze-bridge#uris) should remain the same.

**Comment by cdn4lf** [comment]
`rtsp://localhost:8554/kitchen-cam` no longer shows an image in motioneye with 
`services:
    wyze-bridge:
        restart: always
        network_mode: host
      #  ports:
      #      - 1935:1935
      #      - 8554:8554
      #      - 8888:8888
        build: 
            context: ./app
            # dockerfile: Dockerfile.arm`
in the yml.

**Comment by mrlt8** [comment]
can you open the stream in vlc?

**Comment by cdn4lf** [comment]
Got it going.  The cameras went offline at the same time.
