### ISSUE TITLE
429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login

### ISSUE THREAD

**Issue by mitchross** [mrlt8/docker-wyze-bridge#280]
Seeing lot of 2022/01/26 14:11:03 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login

Takes a day of the container off before it works.

**Comment by mrlt8** [comment]
Is the login failing for some reason? I haven't seen this on my end.

**Comment by mikenabhan** [comment]
I get the same but can't get past it.  


```mike@docker:~/wyze-bridge$ docker-compose up
Starting wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v1.1.1
wyze-bridge    |
wyze-bridge    | 2022/02/23 03:13:43 [WyzeBridge] 🔍 Could not find local cache for 'user'
wyze-bridge    | 2022/02/23 03:13:43 [WyzeBridge] 🔍 Could not find local cache for 'auth'
wyze-bridge    | 2022/02/23 03:13:43 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2022/02/23 03:13:43 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login```

Interestingly, I noticed that my dns server was returning a different set of records for the host: `auth-prod.api.wyze.com` and when I changed it to the one I was able to resolve within my aws account I got a different authentication failure.  I am sure the credentials are correct, as I just reset them prior to this.

**Comment by mrlt8** [comment]
Are you trying to run the bridge in the cloud or through a VPS?

**Comment by mikenabhan** [comment]
I am running the bridge in docker in an ubuntu 20.04 VM running on a standard residential connection.  No funny business with dns like pi-hole or adguard either.  

From my house (where I run the bridge)

```
user@docker:~/wyze-bridge$ dig +short auth-prod.api.wyze.com @9.9.9.9
65.8.181.87
65.8.181.37
65.8.181.65
65.8.181.67
user@docker:~/wyze-bridge$ dig +short auth-prod.api.wyze.com @8.8.8.8
143.204.32.62
143.204.32.114
143.204.32.75
143.204.32.108
```

**Comment by mrlt8** [comment]
hmm, not sure why you're IP is being rate limited..?

Can you curl the login endpoint?

```shell
curl --request POST \
  --url https://auth-prod.api.wyze.com/user/login \
  --header 'Content-Type: application/json' \
  --header 'user-agent: wyze_ios_2.28.0' \
  --data '{
	"email": "me@email.com",
	"password": "mypassword"
}'
```
That should give an "Invalid User Name or Password." error with those credentials.

**Comment by mikenabhan** [comment]
I get nothing returned back from curl.  When I run with a -i I am getting 

```
HTTP/2 429
content-length: 0
date: Wed, 23 Feb 2022 05:07:26 GMT
x-ratelimit-remaining: 0
x-ratelimit-reset-by: Wed Feb 23 05:13:55 GMT 2022
x-cache: Error from cloudfront
via: 1.1 48a6ccbb0ddb052ab512a3422295bd38.cloudfront.net (CloudFront)
x-amz-cf-pop: DEN50-C2
x-amz-cf-id: tRzCk3vViSMC9RW_CRiufP8QnhzLseTwOE0Kj117WWM2mSJ5Xvjyzw==
```

**Comment by mikenabhan** [comment]
I found the source of the rate limit on my end I think.  It looks like I had another device on my network trying to auth to the wyze API.  Not an easy find, had to see all the devices trying to resolve `auth-prod.api.wyze.com`.  So this does not appear to be an issue with your code in my case, but I am not the one who opened the ticket.

**Comment by mrlt8** [comment]
Are you still having this issue @mitchross?

**Comment by mitchross** [comment]
> Are you still having this issue @mitchross?

I have it when fresh data is true.

Thought I haven't seen in in a while, you can close issue for now.
