### ISSUE TITLE
Using coral dev board VPU for hardware accelerated decoding

### ISSUE THREAD

**Issue by gszakacs** [mrlt8/docker-wyze-bridge#283]
Does anyone know how to use the on board VPU (coral dev board) for hw accelerated video decoding with ffmpeg ?
Are there any ffmpeg experts who may be able to help figure out how to add install/utilize the https://github.com/Freescale/libimxvpuapi to the frigate config.yml file as a "hwaccel" option ?

**Comment by ril3y** [comment]
I am no ffmpeg expert but it looks like you would need to do some work to get this done:
https://unix.stackexchange.com/questions/356056/hardware-accelerated-h-264-transcoding-on-i-mx6

Perhaps ask the ffmpeg devs/forums about supporting this hardware accelerator?
