### ISSUE TITLE
Feature request: substream option

### ISSUE THREAD

**Issue by gszakacs** [mrlt8/docker-wyze-bridge#287]
Hi, The SD (30kB) stream works well with frigate and the coral dev board for offline object detection/tracking.  However, when I use the HD stream the coral dev board cpu usage goes crazy, so I am wondering how difficult would it be for the developers to leave a main stream (HD60 or HD120) for high quality event recording but also add a re-encoded substream (SD30) for realtime object detection.

**Comment by mrlt8** [comment]
I don't think this is possible without some additional protocols, as there seems to be only one tutk stream per camera.

You could try running the the bridge in addition to the rtsp firmware or custom firmware like [FiveLeavesLeft](https://github.com/FiveLeavesLeft/WyzeCameraLiveStream) and use one of those streams as the HD and grab the SD stream from the bridge.

Most of the cams also have a WebRTC server running in the background for alexa/google integration, so if we could grab that, that would give us an option for a second stream.
