### ISSUE TITLE
Feature Request:  On demand camera snapshots

### ISSUE THREAD

**Issue by Gerk** [mrlt8/docker-wyze-bridge#291]
Would be amazing to be able to pull snapshots on demand.  I'm using this to monitor prints with OctoPrint and would love to be able to use with the timelapse (built in or with OctoSnap) but both require an endpoint to pull a snapshot on demand and as best as I can tell this is not currently possible.

**Comment by mrlt8** [comment]
While not ideal, you might be able to use something like [SNAPSHOT=RTSP30](https://github.com/mrlt8/docker-wyze-bridge#snapshotstill-images) with [nginx](https://github.com/mrlt8/docker-wyze-bridge/discussions/266) to expose the image locally.

I'd like to eventually let the camera do the snapshots and pull those from the camera as those are much higher quality than what we can grab from the over-compressed streams.

**Comment by Gerk** [comment]
Ya for the time lapse stuff that probably won't work as intended as it does the snapshot at a pretty specific time so that the build head is always in the same place.  Is the camera snapshots not exposed in the reverse engineered API?  I haven't had the time to dig into it much yet.

**Comment by mrlt8** [comment]
There's not much documentation on the wyze commands, but I did stumble across the snapshot command by trial and error. IIRC, it saves the image to the img dir on the sd card and I had to use the boa server to pull it.

**Comment by Gerk** [comment]
Ok interesting.  Yes that seems to be the behaviour I'm seeing as well.  Was looking at the original charles session from way back when but didn't see anything of use really, also it seems like they have changed that up now from the quick capture I just did.
