### ISSUE TITLE
V3 camera - getting error IOTC_ER_DEVICE_REJECT_BY_WRONG_AUTH_KEY

### ISSUE THREAD

**Issue by balajeek** [mrlt8/docker-wyze-bridge#292]
I have the wyze bridge running for quite some time which my frigate uses it to manage my recordings, just noticed today on frigate one of the camera was not showing, upon trouble shooting i found error in the wyze bridge log

[V3 outdoor] IOTC_ER_DEVICE_REJECT_BY_WRONG_AUTH_KEY

this error repeats every min.

I haven't opened my wyze iphone app for many months, and I opened today to check and on the app the camera streams fine.

what else i can check?

FYI: After checking the recordings, it looks it stopped recording after 4am this morning.

**Comment by mrlt8** [comment]
Did the firmware version on the camera change? Sounds like it could be a forced firmware update..

Does setting `FRESH_DATA=true` help?

**Comment by balajeek** [comment]
I not sure if it would force update, as i mentioned i haven't opened the wyze app for a very long time.
When i opened wyze today it prompted to update the v3 and pan cam firmware update, I haven't done it yet 

Its says on v3 camera
Current version: 4.36.8.15
Latest version: 4.36.8.26

Should i update it? or should i flash with some older version?

**Comment by mrlt8** [comment]
They started pushing forced updates without any user interaction even on modded firmware like [WyzeHacks](https://github.com/HclX/WyzeHacks/issues/145).

The bridge should continue to work with all firmware versions for now, so an update isn't necessary unless there's a fix in the newer firmware.

Were you able to get it to work with `FRESH_DATA=true` or v1.1.1?

**Comment by balajeek** [comment]
Yes i just added FRESH_DATA=true to the env and it seem work.  What does this setting do ?

The log now shows:
2022/02/18 15:58:50 [RTSP][V3-OUTDOOR] ✅ '/v3-outdoor' stream is UP!
2022/02/18 15:58:50 [RTSP][V3-OUTDOOR] 📖 New client reading 

So should i ignore the firmware update then?

As always, thank you so much for your super fast support.

**Comment by mrlt8** [comment]
The bridge will normally cache the data needed to connect to the camera so as to minimize the number of hits to the wyze servers. When `FRESH_DATA` is set, it will ignore the local cache and pull "fresh data" from the wyze api before connecting to the cameras.

You can try to ignore the firmware updates, but it seems like wyze will push the update whenever they want now.

**Comment by balajeek** [comment]
oh wait, all along i thought the camera streams are directly coming from the camera locally on the lan and nothing to do with wyze server at all.  Please clarify if i am mistaken.

If its still using wyze servers that would be the first thing i want to get rid off.
I was actually wanted to not using their wyze app or their servers for anything and planning to block from my router.

**Comment by balajeek** [comment]
Thanks for the clarification.  I will have to use it for now until i find a replacement.

**Comment by virmaior** [comment]
> Unfortunately, other users have attempted to block the cams from the wyze servers and have failed as the cams refuse to start up if they can't phone home at boot.

1. The cameras continue to record to the SD even without phoning home as far as I can tell.
2. One of my cameras that I took offline has the wrong timestamp from not connecting to the internet.

**Comment by mrlt8** [comment]
Marking this issue as resolved for now since the original issue seems to be resolved. 

@balajeek For the time being, you should be able to block the cameras from the WAN once they are up.

@virmaior That makes sense. From what I can tell, all the wyzecams are just white-label cams that run the wyze services on top of the default software (neos, atom, etc do the same). It seems like the low level stuff like recording to SD continue to work while the tutk and rtsp streams get stuck until they can phone home.
