### ISSUE TITLE
Constant "Client stopped reading" | "New client reading" 

### ISSUE THREAD

**Issue by terryhonn** [mrlt8/docker-wyze-bridge#299]
I've got just one v3 configured in a particular instance of the bridge, and the only client is Blue Iris consuming the bridge rtsp feed. In the bridge logs, I have this, the whole time the stream is up:

2022/02/20 17:22:21 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:22:30 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:22:46 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:22:59 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:23:15 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:23:42 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:23:57 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:24:10 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:24:25 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:24:36 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:24:52 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:25:00 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:25:16 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:25:32 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:25:47 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:26:04 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:26:19 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:26:42 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:26:57 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:27:14 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:27:30 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:28:14 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:28:30 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:29:06 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:29:22 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:29:43 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:29:59 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:30:22 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:30:38 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:31:07 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:31:23 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:31:44 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
2022/02/20 17:32:00 [RTSP][SOUTH-SHOP-CAM] 📖 New client reading 
2022/02/20 17:32:21 [RTSP][SOUTH-SHOP-CAM] 📕 Client stopped reading
 
Is this an issue with the way I have BI set up to consume, or something I'm doing wrong in the bridge?

Thanks in advance!

**Comment by mrlt8** [comment]
Do you have SNAPSHOT=RTSP or something else taking snapshots from the stream..?

You may be able get some more info about the client with `RTSP_LOGLEVEL=info`.

**Comment by terryhonn** [comment]
BRILLIANT! :-)  
Removing SNAPSHOT=RTSP15 from the environment variables inexplicably stopped the new client/stopped client messages every 15 seconds.  

Thank you very much for overlooking my idiocy. And thanks again for all your work on this!
