### ISSUE TITLE
IOTC_ER_DEVICE_REJECT_BY_WRONG_AUTH_KEY

### ISSUE THREAD

**Issue by karepiu** [mrlt8/docker-wyze-bridge#304]
Getting IOTC_ER_DEVICE_REJECT_BY_WRONG_AUTH_KEY when trying to connect to doorbell. 
Tried FRESH_DATA=true does not help. Any idea what to do ?

**Comment by mrlt8** [comment]
Is this on the latest version of the bridge? v1.1.1+ should be able to catch that error and generate the a new authkey.

Are you running a beta version of the firmware by any chance?

**Comment by karepiu** [comment]
HI, I was on firmware 4.25.0.302. Seems after upgrading to 4.25.0.313 it started to work.

**Comment by mrlt8** [comment]
Marking this as resolved. 
Please feel free to open a new topic if this error comes up again.
