### ISSUE TITLE
p2p / lan setting per camera and not for whole application

### ISSUE THREAD

**Issue by beankylla** [mrlt8/docker-wyze-bridge#309]
Hi,

I have some cameras at my place and some others at my parents. 

Would like to know if we could shift the lan / p2p setting on a per camera basis.

Thanks!

**Comment by mrlt8** [comment]
This has been added to v1.2.1. You should be able to specify a camera with something like: `NET_MODE_CAM_NAME=P2P`

**Comment by beankylla** [comment]
WOW great thanks!
will give it a try!

**Comment by mrlt8** [comment]
Marking this as resolved.
Please feel free to open a new topic if you need additional assistance.
