### ISSUE TITLE
All cameras constantly going offline

### ISSUE THREAD

**Issue by dnestico** [mrlt8/docker-wyze-bridge#312]
I have no idea what's going on recently but am on the latest update and all my cameras just keep going offline, not in the wyze app they work fine there, but on home assistant.

Let me know if more info is needed but wish this could be resolved as streaming my cameras on HA are a big thing I really liked when I discovered this plugin...

<img width="1126" alt="Screen Shot 2022-03-01 at 2 24 29 AM" src="https://user-images.githubusercontent.com/3034555/156124107-30522f50-5e7d-497d-8351-cd8d3bcef4cc.png">

**Comment by mrlt8** [comment]
Check the logs in the add-on for any messages.

**Comment by dnestico** [comment]
Here is the log:

🚀 STARTING DOCKER-WYZE-BRIDGE v1.2.0
🏠 Home Assistant Mode
2022/03/01 15:49:09 [WyzeBridge] ♻️ FORCED REFRESH - Ignoring local 'user' data
2022/03/01 15:49:09 [WyzeBridge] ♻️ FORCED REFRESH - Ignoring local 'auth' data
2022/03/01 15:49:09 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:49:09 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:50:09 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:50:09 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:51:09 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:51:09 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:52:09 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:52:10 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:53:10 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:53:10 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:54:10 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:54:10 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:55:10 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:55:11 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:56:11 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:56:11 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:57:11 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:57:11 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:58:11 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:58:11 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 15:59:11 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 15:59:12 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:00:12 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:00:12 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:01:12 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:01:12 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:02:13 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:02:13 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:03:13 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:03:13 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:04:13 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:04:13 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:05:13 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:05:14 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:06:14 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:06:14 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login
2022/03/01 16:07:14 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/03/01 16:07:14 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login

**Comment by mrlt8** [comment]
Looks like your ip is getting rate limited.. are you running any other wyze add-ons? The bridge should cache the necessary data, so you can usually leave `fresh_data` off.

**Comment by mrlt8** [comment]
Looks like the rate limiting is probably being caused by that add-on: https://github.com/romedtino/simple-wyze-vac#note-as-of-8202021

**Comment by mrlt8** [comment]
It might be ok if you're on the latest version of that add-on since it seems to have polling disabled..?

**Comment by dnestico** [comment]
I am on the latest version which is why not sure it's having this issue. But I'll still uninstall it probably later or tomorrow just in case.

**Comment by dnestico** [comment]
@mrlt8 UPDATE:

So I've now uninstalled the vacuum problem and gave it some time and... no changes unfortunately :/

<img width="768" alt="Screen Shot 2022-03-03 at 3 32 16 AM" src="https://user-images.githubusercontent.com/3034555/156526769-fff371d2-0e67-4469-9d55-6ac29eae6c04.png">


**ADD-ON LOG:**

🚀 STARTING DOCKER-WYZE-BRIDGE v1.2.0
🏠 Home Assistant Mode
2022/03/03 03:30:50 [WyzeBridge] 📚 Using 'user' from local cache...
2022/03/03 03:30:50 [WyzeBridge] 📚 Using 'cameras' from local cache...
🎬 STARTING ALL 5 CAMERAS
2022/03/03 03:30:50 [WyzeBridge] 📚 Using 'auth' from local cache...
2022/03/03 03:30:50 [WyzeBridge] 
======
WebRTC
======
Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 584, in <module>
    wb.run()
  File "/app/wyze_bridge.py", line 49, in run
    self.get_webrtc()
  File "/app/wyze_bridge.py", line 401, in get_webrtc
    if wss := wyzecam.api.get_cam_webrtc(self.auth, cam.mac):
  File "/app/wyzecam/api.py", line 230, in get_cam_webrtc
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://webrtc.api.wyze.com/signaling/device/2CAA8EF7181F?use_trickle=true

**Comment by mrlt8** [comment]
Try disabling WebRTC. 
It's experimental, and not meant for use in the bridge.

**Comment by dnestico** [comment]
You're a legend bud! It's finally back. Now hopefully the on demand streaming update comes soon.

![Screenshot_20220303-175617.png](https://user-images.githubusercontent.com/3034555/156666841-8c3db909-a1c6-4fb6-8bd9-7164921b636d.png)
