### ISSUE TITLE
Enhancement : Camera Restart

### ISSUE THREAD

**Issue by AdiAbuAli** [mrlt8/docker-wyze-bridge#313]
Hi,
Some times Camera hang, or performance degrade intern of streaming.
Is it possible to add send Camera Restart command after specific numbers of AV_ER_DATA_NOREADY, or time based (e.g. every 3 days)?
Also the same for time Sync Time option (in Wyze application under advanced settings)
BR,

**Comment by AdiAbuAli** [comment]
Thanks...

For the Sync part, yes, but minor deviation, after sync it will not be 100% all showboard cams will be at same time, but reduce deviation.

**Comment by AdiAbuAli** [comment]
Any timline When dev version will push as Latest?

Thanks,
________________________________

**Comment by mrlt8** [comment]
It's stalled because of a timeout issue on some cams related to #306.

**Comment by AdiAbuAli** [comment]
Do you recommend me to try it...?

**Comment by mrlt8** [comment]
Should be fine, as it should fallback on connect if the check times out. 
Feedback would be appreciated.

**Comment by AdiAbuAli** [comment]
Sure..just started using it and will provide feedback soon.
Meanwhile, is it Audio out version?

Thanks,
________________________________

**Comment by mrlt8** [comment]
Audio is not supported at this time. The audio channel is actually disabled in recent versions because it was causing a memory leak.

**Comment by AdiAbuAli** [comment]
I tried the Dev version and it was perfect streaming and reliable

Thanks,
________________________________
