### ISSUE TITLE
Stream bitrate reverted back to original value after AV_ER_SESSION_CLOSE_BY_REMOTE

### ISSUE THREAD

**Issue by tonyzzz321** [mrlt8/docker-wyze-bridge#320]
I would like to constantly record my Wyze Cam, split the video into 3min long mp4 files, and then upload them to some server for archive. To save some bandwidth, I set the stream quality to HD60 in the docker-compose.yml file. I am using FFMPEG to record and split.

```console
ffmpeg -use_wallclock_as_timestamps 1 -rtsp_transport tcp -i rtsp://localhost:8554/back-yard-cam -c copy -f segment -segment_time 180 -segment_atclocktime 1 -segment_format mp4 -reset_timestamps 1 -strftime 1 "Back_Yard_Cam-%Y%m%d%H%M%S%z.mp4"
```

After starting the docker instance, my FFMPEG command starts to generate some mp4 files with size at about 10MB each. But after about half a day or so, the file size becomes 20MB each. If I restart the wyze-bridge docker instance, then the file size goes back to normal. 

I looked at the log and did some correlations. It seems like whenever AV_ER_SESSION_CLOSE_BY_REMOTE occurs in the log and the stream is restarted, the file size becomes 20MB. I suspect that the bitrate of the stream gets reset to HD120 when that error occurs.

Here is the log:

```
Attaching to wyze-bridge
wyze-bridge | 🚀 STARTING DOCKER-WYZE-BRIDGE v1.2.1
wyze-bridge | 
wyze-bridge | 2022/03/09 06:00:58 [WyzeBridge][INFO][WyzeBridge] 📚 Using 'user' from local cache...
wyze-bridge | 2022/03/09 06:00:58 [WyzeBridge][INFO][WyzeBridge] 📚 Using 'cameras' from local cache...
wyze-bridge | 
wyze-bridge | 🎬 STARTING ALL 2 CAMERAS
wyze-bridge | 2022/03/09 06:00:58 [WyzeBridge][INFO][WyzeBridge] Starting rtsp-simple-server v0.17.17
wyze-bridge | 2022/03/09 06:00:58 [WyzeBridge][INFO][WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Yard Cam on 192.168.0.31 (1/3)
wyze-bridge | 2022/03/09 06:00:58 [WyzeBridge][INFO][WyzeBridge] 🎉 Connecting to WyzeCam V2 - Driveway Cam on 192.168.0.32 (1/3)
wyze-bridge | 2022/03/09 06:00:58 [wyzecam.iotc][DEBUG][Driveway Cam] Connect via IOTC_Connect_ByUIDEx
wyze-bridge | 2022/03/09 06:00:58 [wyzecam.iotc][DEBUG][Back Yard Cam] Connect via IOTC_Connect_ByUIDEx
wyze-bridge | 2022/03/09 06:00:59 [wyzecam.iotc][INFO][Back Yard Cam] AV Client Start: chan_id=0 expected_chan=0
wyze-bridge | 2022/03/09 06:00:59 [wyzecam.iotc][INFO][Driveway Cam] AV Client Start: chan_id=0 expected_chan=0
wyze-bridge | 2022/03/09 06:01:00 [WyzeBridge][INFO][Back Yard Cam] [videoParm] {'type': 'H264', 'bitRate': '120', 'resolution': '1', 'fps': '20', 'horizontalFlip': '1', 'verticalFlip': '1', 'logo': '2', 'time': '1'}
wyze-bridge | 2022/03/09 06:01:00 [WyzeBridge][INFO][Back Yard Cam] 📡 Getting 60kb/s HD stream @20fps via LAN mode (WiFi: 65%) FW: 4.36.8.26 🔒 (DTLS) (2/3)
wyze-bridge | 2022/03/09 06:01:00 [py.warnings][WARNING][Back Yard Cam] WARNING: Skipping smaller frame at start of stream (frame_size=1)
wyze-bridge | 2022/03/09 06:01:01 [WyzeBridge][INFO][Driveway Cam] [videoParm] {'type': 'H264', 'bitRate': '60', 'resolution': '1', 'fps': '15', 'horizontalFlip': '1', 'verticalFlip': '1', 'logo': '2', 'time': '1'}
wyze-bridge | 2022/03/09 06:01:01 [WyzeBridge][INFO][Driveway Cam] 📡 Getting 60kb/s HD stream @15fps via LAN mode (WiFi: 98%) FW: 4.9.8.860 🔒 (DTLS) (2/3)
wyze-bridge | 2022/03/09 06:01:05 [RTSP][DRIVEWAY-CAM] ✅ '/driveway-cam' stream is UP! (3/3)
wyze-bridge | 2022/03/09 06:01:06 [RTSP][BACK-YARD-CAM] ✅ '/back-yard-cam' stream is UP! (3/3)
wyze-bridge | 2022/03/09 06:01:07 [RTSP][BACK-YARD-CAM] 📖 New client reading 
wyze-bridge | 2022/03/09 10:55:02 [py.warnings][WARNING][Back Yard Cam] WARNING: Frame not available yet
wyze-bridge | 2022/03/09 15:28:52 [py.warnings][WARNING][Driveway Cam] WARNING: Frame not available yet
wyze-bridge | 2022/03/09 19:48:31 [RTSP][BACK-YARD-CAM] ❌ '/back-yard-cam' stream is down
wyze-bridge | 2022/03/09 19:48:31 [RTSP][BACK-YARD-CAM] 📕 Client stopped reading
wyze-bridge | 2022/03/09 19:48:31 [WyzeBridge][WARNING][Back Yard Cam] AV_ER_SESSION_CLOSE_BY_REMOTE
wyze-bridge | 2022/03/09 19:48:31 [WyzeBridge][INFO][WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Yard Cam on 192.168.0.31 (1/3)
wyze-bridge | 2022/03/09 19:48:31 [wyzecam.iotc][DEBUG][Back Yard Cam] Connect via IOTC_Connect_ByUIDEx
wyze-bridge | 2022/03/09 19:48:42 [wyzecam.iotc][INFO][Back Yard Cam] AV Client Start: chan_id=0 expected_chan=0
wyze-bridge | 2022/03/09 19:48:43 [WyzeBridge][INFO][Back Yard Cam] [videoParm] {'type': 'H264', 'bitRate': '60', 'resolution': '1', 'fps': '20', 'horizontalFlip': '1', 'verticalFlip': '1', 'logo': '2', 'time': '1'}
wyze-bridge | 2022/03/09 19:48:43 [WyzeBridge][INFO][Back Yard Cam] 📡 Getting 60kb/s HD stream @20fps via LAN mode (WiFi: 60%) FW: 4.36.8.26 🔒 (DTLS) (2/3)
wyze-bridge | 2022/03/09 19:48:43 [py.warnings][WARNING][Back Yard Cam] WARNING: Skipping smaller frame at start of stream (frame_size=1)
wyze-bridge | 2022/03/09 19:48:48 [RTSP][BACK-YARD-CAM] ✅ '/back-yard-cam' stream is UP! (3/3)
wyze-bridge | 2022/03/09 19:48:52 [RTSP][BACK-YARD-CAM] 📖 New client reading 
wyze-bridge | 2022/03/09 19:49:53 [py.warnings][WARNING][Back Yard Cam] WARNING: Frame not available yet
```

Thank you for looking into this issue.

**Comment by mrlt8** [comment]
Interesting. Are you running the ffmpeg command in rtsp-simple-server? We could probably integrate something directly into the bridge so that it saves the mp4s as they are received.

As for the change in bitrate, the bridge is puling the same stream as the app so viewing the stream in the app could change the quality of the stream we're receiving. The bridge does check for a change in resolution "frame_size" as swapping the resolution mid stream was causing issues, but we're not checking the bitrate at this time.

Do you happen to know if you opened the app and/or had any cloud-based recordings around the time of the AV_ER_SESSION_CLOSE_BY_REMOTE messages?

**Comment by mrlt8** [comment]
This is a tricky issue as the camera doesn't return the bitrate with the frame data like it does with the frame_size. We can request the bitrate manually and everything works, but this seems to cause a slight pause in the stream that needs to be worked out.

**Comment by AdiAbuAli** [comment]
Recording is a nice feature, specially that it will bypass RSTP_SIMPLE_SERVER (I assume less integration point will result in better integrity)...But also it will be of add value to use this feature in another way:
In Synology Surveillance Station (and assume other NVRs), where the Docker bridge and NVR is integrated in same Synology NAS, there is option to read from file (rather than RTSP), as attached in snap shot, but I assume it will read from a single rotating file for each Cam, and should have timestamp within the MP4 file...is this possible to have single rotating file (another feature in parallels to having multiple MP4 recorded files?
![Capture](https://user-images.githubusercontent.com/89463853/159184686-b7597851-47c6-4f85-8fe8-c1cca1b6dfe8.JPG)

**Comment by mrlt8** [comment]
Changes have been merged into v1.3.0.

Please let me know if this helps.

@AdiAbuAli I personally don't have the time or access to a Synology Surveillance Station to work on that, but would be happy to merge any pull requests.

**Comment by tonyzzz321** [comment]
I've tested the new version the past week and I don't see the issue anymore. The fix seems to be effective. Thank you for addressing this and also adding the record feature.

**Comment by mrlt8** [comment]
Awesome! 
Marking this as resolved for now.
