### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sweichbr** [mrlt8/docker-wyze-bridge#323]
Ever since the most recent update, I have noticed that this add-on is steadily sucking up memory - and today actually caused my HA to reboot.  Currently is is consuming 1.56GB.

Version 1.21

**Comment by mrlt8** [comment]
Thanks! I'll look into this. Were you running v1.2.0 previously?
Any non default settings enabled?

**Comment by sweichbr** [comment]
Yes. I try and keep up to date.

The only thing I did was exclude my outdoor cams because of the battery
drain.

**Comment by mrlt8** [comment]
Hmm, I've been trying to replicate this, but memory usage seems similar to the standard docker install and stays in the 100s after a couple of hours with 5 cams.

Are you still getting a memory leak? If so how long is it taking to go over 1GB?

**Comment by sweichbr** [comment]
Yup. I created an automation to restart the add-on whenever memory hits 80%
and it still happens multiple times a day.

Maybe an Uninstall reinstall should be the next step.

**Comment by melbnz** [comment]
I also have this issue with 4 active RTSP camera on v1.2.1.  It is creeping up about 10% add-on RAM per hour then HA OS is out of memory (2GB) kills some python process and freezes and i have to manually restart OS. I'm a VM on Synology. It had been stable for 2 + months.  The add-on was set to auto-start however i've disabled this for today.  I am on 7.2 as i had to rollback to a feb release as my HA crapped itself big time and that was my last full backup. It seems that wyze is my only non OS python user.
<img width="590" alt="py3" src="https://user-images.githubusercontent.com/77428234/158693356-84677c88-9497-448c-8255-c665429ceeff.png">

**Comment by melbnz** [comment]
I will stop wyze add-on shortly and report.  Current climb attached
![Mem usage](https://user-images.githubusercontent.com/77428234/158693979-c5cd381b-1d02-4b06-9c9d-8332df65dc9f.jpg)

**Comment by sweichbr** [comment]
Reinstall did not help.

@melbnz this is my automation to auto restart the add-on
alias: HA Memory Alert
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.memory_use_percent
    above: '80'
condition: []
action:
  - service: notify.mobile_app_sm_n975u1
    data:
      message: '{{ now().strftime(''%I:%M%p  %A  %x'') }}'
      title: Memory Use above 80%
  - service: hassio.addon_restart
    data:
      addon: 7094bb28_docker-wyze-bridge
mode: single

>

**Comment by melbnz** [comment]
Memory has remained static since wyze add-on stopped
![stable mem](https://user-images.githubusercontent.com/77428234/158705731-f046a090-c1b5-4025-b63e-8bc684c6169e.jpg)

**Comment by mrlt8** [comment]
Thanks for the info! It's probably the audio buffer leaking again. v1.2.1 was supposed to disable the audio channel for the session, but we'll probably need to clear it manually like we were doing in v1.2.0.

**Comment by mrlt8** [comment]
Potential fix in the dev branch. May need to add the edge-repo to access: https://github.com/mrlt8/edge-repo

**Comment by mrlt8** [comment]
Can anyone confirm if the patches in the dev branch help with the memory leak?

The dev branch can be added to HA by adding the [edge repo]( https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmrlt8%2Fedge-repo).

**Comment by sweichbr** [comment]
Just installed. Will monitor and report back.

**Comment by mbfrydman** [comment]
Testing now, had a crash of HA right after install. Will see if it's stable now.

**Comment by sweichbr** [comment]
Still hitting high memory usage

**Comment by mbfrydman** [comment]
Still getting crashes after about 2 hours.
I'm guessing it's memory related, not sure how to check logs though as it just crashes and I'm not reading anything specific

**Comment by mrlt8** [comment]
I pushed a new dev build (v1.3.0 DEV 2) which should clear the audio and video buffer which is what v1.2.0 was originally doing.

I'm unable to replicate the memory leak, so feedback would be appreciated!

**Comment by melbnz** [comment]
I’ve added dev branch and started service, cameras running rtsp , initial memory jump just under 10%. .  Will check in the morning (8 hours time)

**Comment by melbnz** [comment]
Reached out of memory in a few hours running dev on latest OS and core.
![90A26659-202B-4B7B-B5BA-1B8EED0DB4ED](https://user-images.githubusercontent.com/77428234/159135771-7de9bcba-62c0-4f5b-bec8-c6896b755a57.png)

**Comment by mrlt8** [comment]
Thanks for testing @melbnz! Could you confirm the version number displayed in the logs at startup?

I made some additional tweaks to rollback to using the frame_index instead of frame_no like we were in v1.2.0.

To update to the latest dev build, you'll need to go to your HA **Add-On Store** (/hassio/store) and check for updates:
<img width="166" alt="check for updates" src="https://user-images.githubusercontent.com/67088095/159149301-af81694f-1639-4b21-8df7-a42574fb88da.png">
 and then uninstall and install the dev branch to use the new dev image.

**Comment by melbnz** [comment]
Log below, will update and advise
🚀 STARTING DOCKER-WYZE-BRIDGE v1.3.0 DEV 2
🏠 Home Assistant Mode
2022/03/20 19:19:35 [WyzeBridge] 📚 Using 'user' from local cache...
2022/03/20 19:19:35 [WyzeBridge] 📚 Using 'cameras' from local cache...
🎬 STARTING ALL 9 CAMERAS
2022/03/20 19:19:35 [WyzeBridge] Starting rtsp-simple-server v0.17.17
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - upstairs  on 10.10.10.108 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - workshop on 192.168.5.70 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - H1 on 192.168.5.78 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam Pan - Office Cam on 192.168.5.228 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.5.69 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - lounge on 192.168.5.67 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - lobby on 192.168.5.66 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Brew room H2 on 192.168.5.113 (1/3)
2022/03/20 19:19:35 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - cat cam on 10.10.10.31 (1/3)

**Comment by melbnz** [comment]
Using beta 1 - memory is racing away!  Maybe too much cpu as well?  Restarted to prove version. All attached 
![8F91DD5B-D4ED-4BC3-A9C1-F57C15107971](https://user-images.githubusercontent.com/77428234/159156146-04586608-fbc5-47bc-b349-c389ec140439.png)
![633F29B6-93E5-43D6-AC64-3CD483B7B78A](https://user-images.githubusercontent.com/77428234/159156151-a55a26b2-3ac6-4809-88a2-960691bd3ff3.png)
![854137A4-F53D-422F-89F4-21963EFE8312](https://user-images.githubusercontent.com/77428234/159156152-8025356d-624c-475d-8a4d-40f6ef1aeae2.png)

**Comment by mbfrydman** [comment]
Same results minus the graphs, I'm guessing being on a RPi3 mine crashes when it tries to swap.

**Comment by mrlt8** [comment]
Whoops, my bad! CPU usage should be fixed in the new dev build.
<img width="416" alt="beta 2" src="https://user-images.githubusercontent.com/67088095/159171239-9a1237ca-9554-4889-bf81-93886bec6412.png">


I still can't figure what's causing the memory issue. I added v1.2.0 as a "previous" build on the edge-repo, so we can try to compare the performance between the two builds.

**Comment by melbnz** [comment]
I have beta 2 loaded, memory is racing off again...if this is 1.20?
![wyze mem beta 2](https://user-images.githubusercontent.com/77428234/159375331-45eb6fdd-c1dd-45f6-9923-9498e15c2758.jpg)

**Comment by mrlt8** [comment]
v1.2.0 should be in the edge-repo as previous https://github.com/mrlt8/edge-repo/blob/main/previous/config.json

**Comment by mrlt8** [comment]
Has anyone been able to confirm if the leak was already in the previous v1.2.0 build?

**Comment by sweichbr** [comment]
I am not sure how to get back to 1.2.0. I ran the edge version and it says
1.2.1

**Comment by mrlt8** [comment]
There should be a "previous" build in the add-on store. May need to "check for updates".

**Comment by sweichbr** [comment]
Found it. Will report back shortly

**Comment by sweichbr** [comment]
So far so good. Mem is around 300-400 but not climbing

**Comment by melbnz** [comment]
![image](https://user-images.githubusercontent.com/77428234/159846414-b9e98607-5fdf-46b8-9b7a-9dad11046e41.png)

**Comment by sweichbr** [comment]
12 hours plus, still running well.

**Comment by mrlt8** [comment]
Thanks! This narrows things down and confirms that 1) it's not a firmware change causing the leak and 2) it's probably not related to the previous audio buffer leak.

Will try to work on it this weekend!

**Comment by melbnz** [comment]
V1.2.0 is stable for me as well  20+ hours
<img width="234" alt="image" src="https://user-images.githubusercontent.com/77428234/160023880-ad94b5a1-62c7-484b-abd8-8f4832b35c8c.png">

**Comment by mrlt8** [comment]
Ok, I think I may have been able to replicate the issue by forcing my cams offline...

By any chance, does enabling `IGNORE_OFFLINE` on the main v1.2.1 work?

I pushed a new beta to the dev branch that should resolve the offline issue which may have been causing the leak.

**Comment by sweichbr** [comment]
Thanks.

 

I am starting with the IGNORE_OFFLINE flag and will report back.

 

From: mrlt8 ***@***.***>
Reply-To: mrlt8/docker-wyze-bridge ***@***.***>
Date: Friday, March 25, 2022 at 10:13 AM
To: mrlt8/docker-wyze-bridge ***@***.***>
Cc: Shimon Weichbrod ***@***.***>, Author ***@***.***>
Subject: Re: [mrlt8/docker-wyze-bridge] Memory Leak (Issue #323)

 

Ok, I think I may have been able to replicate the issue by forcing my cams offline...

By any chance, does enabling IGNORE_OFFLINE on the main v1.2.1 work?

I pushed a new beta to the dev branch that should resolve the offline issue which may have been causing the leak.

**Comment by sweichbr** [comment]
So far looking good.

**Comment by mrlt8** [comment]
I pushed v1.2.2 to the main repo which should work even when IGNORE_OFFLINE is not enabled.

Please let me know if this helps with the memory issue.

**Comment by mbfrydman** [comment]
Works great, thanks for the fix

**Comment by melbnz** [comment]
Tried 1.2.2 with flag set and not set.  Seems stable with both.  Good job, thank you

**Comment by mrlt8** [comment]
Awesome! Marking this issue as resolved for now.

**Comment by sweichbr** [comment]
Thanks for your persistence to get this fixed!
