### ISSUE TITLE
Can't cast to chromecast

### ISSUE THREAD

**Issue by dnestico** [mrlt8/docker-wyze-bridge#327]
I am trying to setup automation that casts my camera to my google nest hub, but for some reason, I can't figure out how to make it play, it just shows this screen:

(this is not my image but it is the same exact screen I see on my nest hub btw)
![8fa1ac6f20ab321346f198284fcc44e0e8fddac6](https://user-images.githubusercontent.com/3034555/159854233-44886742-14d9-4f9b-8a5d-19fa02314c45.jpg)

Here is the simple stream camera automation:

<img width="1047" alt="Screen Shot 2022-03-24 at 2 14 58 AM" src="https://user-images.githubusercontent.com/3034555/159854291-0b28c075-17c0-4229-b81c-27a354117703.png">

It didn't work with HLS checked or not, not sure why as the cameras are working fine and I can ask google to stream them just fine, I can also cast them from other apps like tiny cam pro, so not sure why this is happening.

**Comment by dnestico** [comment]
After further investigation, this appears to be a chromecast / nest hub issue. It only supports HLS and VP9.

https://developers.google.com/cast/docs/media 

STILL for some reason when I cast the HLS stream, it works great on the browser, but the nest hub just won't play it even though it's an HLS stream. I tried using the media extractor and didn't fix it either. 

So for now I have it stream a snapshot when my automation runs, but would be nice if you found a solution to this and maybe do something similar to what the "TinyCam Pro" app does, which that works perfectly for streaming.

**Comment by mrlt8** [comment]
Not very familiar with casting, but have you tried both HLS streams on `server:8888/cam-name` and `server:8888/cam-name/stream.m3u8`?

Specs seem to support h264, so I don't think that's the issue, but you may be able to play around with some of the setting in [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) or tweak the ffmpeg input flags with `FFMPEG_FLAGS`.

**Comment by dnestico** [comment]
I don't have the rtsp-simple-server addon but I am going to try tweaking some of the FFMPEG_FLAGS settings now.  

As you can see I tried both HLS streams and yup same result, will update you soon.

<img width="1118" alt="Screen Shot 2022-03-25 at 1 59 37 AM" src="https://user-images.githubusercontent.com/3034555/160063745-cde030d8-936b-4551-901e-94534c06970b.png">
<img width="1120" alt="Screen Shot 2022-03-25 at 1 58 51 AM" src="https://user-images.githubusercontent.com/3034555/160063748-1a459d90-3462-4e1d-9f5e-18125229c195.png">

**Comment by dnestico** [comment]
Currently trying this new addon I found that I think displays the cams as WebRTC and it works great, but the problem still exists, when I cast them cameras, still nothing :/

Maybe you can explain how the FFMPEG_FLAGS work, please? Thanks.

Addon: https://github.com/AlexxIT/WebRTC

**Comment by mrlt8** [comment]
rtsp-simple-server is what we use internally to create the RTSP/RTMP/HLS streams and could be used to [re-encode or convert](https://github.com/aler9/rtsp-simple-server#remuxing-re-encoding-compression) the stream to a compatible format.

I'm an apple based user, so can't really comment on or test chrome cast compatibility.

**Comment by dnestico** [comment]
Ok so I have your wyze docker addon from the home assistant store, how exactly do I do this?

**Comment by dnestico** [comment]
Another question:

I enabled webrtc and fresh_data and it gave me the URLs this time unlike last time I got an error, but, all cameras went unavailable so I turned it back off.

How exactly do we use these URLs? That WebRTC integration I linked earlier does seem to be working great though, no sound though. Also Im still messing with things to figure out the casting issue. 

I think it might be on the Chromecast/nest-hub side tbh so trying to figure out to maybe change the stream on the HA side that would make it work, not sure what to so far.

**Comment by mrlt8** [comment]
I think you'll have have to **Edit in YAML** on the add-on's configuration page:
<img width="158" alt="settings" src="https://user-images.githubusercontent.com/67088095/160241307-7b00f2de-7ed8-497d-b44b-93467685e3f3.png">


The bridge just takes the raw h264 from the camera and pushes it out as RTSP/RTMP/HLS. There's a chance the nest doesn't like the h264 format that wyze is using, so you might be able to re-encode the raw video before it gets pushed out with ffmpeg:
```yaml
FFMPEG_CMD: ffmpeg -f h264 -i - -vcodec libx264 -preset veryfast -f rtsp rtsp://0.0.0.0:8554/
```
NOTE: Re-encoding the stream will require much more computing resources.

Could also potentially use `libvpx-vp9` to encode directly to vp9, but I couldn't get VLC to recognize the stream.

For tweaking rtsp-simple-server settings, see the readme [for some examples](https://github.com/mrlt8/docker-wyze-bridge#rtsp-simple-server).

As for webrtc, it basically gives you the same webrtc you'd get from the web view.

**Comment by krysiswbk** [comment]
![Screenshot_20220327-172025_Home Assistant](https://user-images.githubusercontent.com/92241867/160301559-44f25639-9a67-4aca-ad6e-dfb1fc1a66bc.jpg)
Give this a try. I too had a hard time. Got it working with this script.. May want to add a mute too - this way there's not connection noise

**Comment by krysiswbk** [comment]
You know what, that's not working for me any more either. Mind you that's what I've been using the past little while. Originally I had to cast the camera twice but that went away.. Not sure now

**Comment by dnestico** [comment]
> I think you'll have have to **Edit in YAML** on the add-on's configuration page: <img alt="settings" width="158" src="https://user-images.githubusercontent.com/67088095/160241307-7b00f2de-7ed8-497d-b44b-93467685e3f3.png">
> 
> The bridge just takes the raw h264 from the camera and pushes it out as RTSP/RTMP/HLS. There's a chance the nest doesn't like the h264 format that wyze is using, so you might be able to re-encode the raw video before it gets pushed out with ffmpeg:
> 
> ```yaml
> FFMPEG_CMD: ffmpeg -f h264 -i - -vcodec libx264 -preset veryfast -f rtsp rtsp://0.0.0.0:8554/
> ```
> 
> NOTE: Re-encoding the stream will require much more computing resources.
> 
> Could also potentially use `libvpx-vp9` to encode directly to vp9, but I couldn't get VLC to recognize the stream.
> 
> For tweaking rtsp-simple-server settings, see the readme [for some examples](https://github.com/mrlt8/docker-wyze-bridge#rtsp-simple-server).
> 
> As for webrtc, it basically gives you the same webrtc you'd get from the web view.

So the FFMpeg command did not work on nest hub or even my dashboard, and CPU usage absolutely skyrocketed, after I put the command my streams actually just turned to snapshots and stopped playing so I had to remove it, also still on "1.1.2" while doing this, and CPU usage is pretty high at 80%+ which is weird because it wasn't before... and I've removed the command already and restarted the addon but my streams are back at least.

The VP9 command now had pretty good low CPU usage, again though but a little different this time I get "ERROR: No Video" on all cams.

Neither worked with the nesthub and in fact, the VP9 command just wouldn't even start the stream.


Back to more investigating!...

**Comment by dnestico** [comment]
@mrlt8  Update: I may have found what's causing the issue, maybe when you figure our webRTC this should not be a problem.

But for now I'm gathering more information on this and gonna try some workarounds soon.

<img width="773" alt="Screen Shot 2022-03-27 at 11 24 08 PM" src="https://user-images.githubusercontent.com/3034555/160321287-c03b4c68-a990-4bfe-adea-c68732f5803c.png">

**Comment by mrlt8** [comment]
hmm, does adding a silent audio track help?

```
ffmpeg -fflags +flush_packets+genpts+discardcorrupt+nobuffer -i - -f lavfi -i anullsrc -c:a aac -vcodec copy -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554
```

**Comment by dnestico** [comment]
Sooo, it looks ike it killed the camera feeds 🤔 

Or did I put it wrong?

<img width="1002" alt="Screen Shot 2022-03-28 at 12 00 07 AM" src="https://user-images.githubusercontent.com/3034555/160324348-ebe403c7-d34b-434b-b0df-2d44f9ac1695.png">

<img width="760" alt="Screen Shot 2022-03-27 at 11 59 48 PM" src="https://user-images.githubusercontent.com/3034555/160324342-f8a9f312-dc4a-4e04-8420-8c129836e8be.png">

**Comment by mrlt8** [comment]
Are the streams going up in the logs? Can you test in VLC or some other player?

**Comment by dnestico** [comment]
Here is the log, it seems like the cameras are going up unless I am reading this wrong which probably am, but, it did not work in VLC or chrome M3U8 plugin I have.

<img width="520" alt="Screen Shot 2022-03-28 at 12 10 58 AM" src="https://user-images.githubusercontent.com/3034555/160325391-21941427-cf9a-466b-95f5-5a0427aa36a2.png">
<img width="522" alt="Screen Shot 2022-03-28 at 12 10 23 AM" src="https://user-images.githubusercontent.com/3034555/160325392-d65e3558-d036-404a-865e-37470b36c0dd.png">
<img width="1201" alt="Screen Shot 2022-03-28 at 12 13 10 AM" src="https://user-images.githubusercontent.com/3034555/160325484-5a89513f-6d62-4c7f-92bf-3bf464b60423.png">


2022/03/28 00:09:23 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:09:23 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 80%) FW: 4.25.1.042 🔒 (DTLS) (2/3)
2022/03/28 00:09:23 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/03/28 00:09:25 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 77%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:09:25 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:09:25 [Porch] [Errno 32] Broken pipe
2022/03/28 00:09:26 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:09:28 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:09:28 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 76%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:09:28 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:09:31 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 78%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:09:38 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:09:38 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:09:40 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 75%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:09:40 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:09:41 [Porch] [Errno 32] Broken pipe
2022/03/28 00:09:41 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:09:42 [Front Doorbell] [Errno 32] Broken pipe
2022/03/28 00:09:43 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:09:43 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.2.104 (1/3)
2022/03/28 00:09:43 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:09:43 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 75%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:09:45 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 78%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:09:45 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 80%) FW: 4.25.1.042 🔒 (DTLS) (2/3)
2022/03/28 00:09:46 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/03/28 00:09:53 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:09:53 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:09:55 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 77%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:09:55 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:09:56 [Porch] [Errno 32] Broken pipe
2022/03/28 00:09:56 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:09:58 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:09:58 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:09:58 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 75%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:01 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 79%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:05 [Front Doorbell] [Errno 32] Broken pipe
2022/03/28 00:10:05 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.2.104 (1/3)
2022/03/28 00:10:08 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 83%) FW: 4.25.1.042 🔒 (DTLS) (2/3)
2022/03/28 00:10:08 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:10:08 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/03/28 00:10:08 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:10:10 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 77%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:10:10 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:10:11 [Porch] [Errno 32] Broken pipe
2022/03/28 00:10:11 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:10:13 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:10:13 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:10:14 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 74%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:16 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 80%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:23 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:10:23 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:10:26 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 79%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:10:26 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:10:26 [Porch] [Errno 32] Broken pipe
2022/03/28 00:10:26 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:10:27 [Front Doorbell] [Errno 32] Broken pipe
2022/03/28 00:10:27 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.2.104 (1/3)
2022/03/28 00:10:28 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:10:28 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:10:29 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 75%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:30 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 82%) FW: 4.25.1.042 🔒 (DTLS) (2/3)
2022/03/28 00:10:30 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/03/28 00:10:31 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 78%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:38 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:10:38 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:10:41 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 78%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:10:41 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:10:41 [Porch] [Errno 32] Broken pipe
2022/03/28 00:10:41 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:10:43 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:10:43 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:10:44 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 76%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:45 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 81%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:49 [Front Doorbell] [Errno 32] Broken pipe
2022/03/28 00:10:49 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.2.104 (1/3)
2022/03/28 00:10:52 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 83%) FW: 4.25.1.042 🔒 (DTLS) (2/3)
2022/03/28 00:10:52 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/03/28 00:10:53 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:10:53 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:10:55 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 76%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:10:56 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:10:56 [Porch] [Errno 32] Broken pipe
2022/03/28 00:10:56 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:10:58 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:10:58 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 73%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:10:58 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:11:00 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 78%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:11:08 [Driveway] [Errno 32] Broken pipe
2022/03/28 00:11:09 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Driveway on 192.168.2.30 (1/3)
2022/03/28 00:11:10 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 77%) FW: 4.36.8.32 🔒 (DTLS) (2/3)
2022/03/28 00:11:11 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/03/28 00:11:11 [Porch] [Errno 32] Broken pipe
2022/03/28 00:11:11 [Front Doorbell] [Errno 32] Broken pipe
2022/03/28 00:11:12 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.2.104 (1/3)
2022/03/28 00:11:12 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Porch on 192.168.2.44 (1/3)
2022/03/28 00:11:13 [Garage Cam] [Errno 32] Broken pipe
2022/03/28 00:11:14 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/03/28 00:11:14 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 83%) FW: 4.25.1.042 🔒 (DTLS) (2/3)
2022/03/28 00:11:14 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 77%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/03/28 00:11:14 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)

**Comment by mrlt8** [comment]
Sorry, that needs to go in `FFMPEG_CMD` not `FFMPEG_FLAGS`:
<img width="552" alt="vlc" src="https://user-images.githubusercontent.com/67088095/160326811-f4d94fbe-17b0-4b13-9f94-b53e7a16f060.png">

**Comment by dnestico** [comment]
So I can definitely see that you added an audio track via VLC, but STILL, it somehow won't show the God damn camera on the nest hub!!

Not gonna lie, I thought this would be the fix and it somehow isn't sadly, so dumb.

<img width="1131" alt="Screen Shot 2022-03-28 at 12 49 43 AM" src="https://user-images.githubusercontent.com/3034555/160328489-1f475a9e-4ec0-4641-b4cc-646476f65763.png">

**Comment by dnestico** [comment]
Wonder if its possible to ping @probot-home-assistant in this and they might have an idea through this thread.

**Comment by dnestico** [comment]
@frenck

**Comment by mrlt8** [comment]
Were you able to get [gihad/streamer](https://github.com/gihad/streamer) to work with your nest?

Looks like they're using [aevalsrc](https://github.com/gihad/streamer/blob/a4c292458b5b3522f192431a1bf9c82ae796781a/create_ffmpeg_cmd.sh#L24) which would be something like this:
```
ffmpeg -loglevel verbose -fflags +flush_packets+genpts+discardcorrupt+nobuffer -i - -f lavfi -i aevalsrc=0 -c:a aac -c:v copy -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554
```

**Comment by dnestico** [comment]
I will try the flag that you just gave me but no because I do not know how to run it, I am running HA OS on an RPI4 and I didn't see an addon download link.

Will report back very soon after I try the ffmpeg thing.

**Comment by mrlt8** [comment]
btw, I noticed you're using `homeassistant.local` but maybe the nest has some weird DNS thing going on? Have you tried using the IP of the HA machine instead?

**Comment by dnestico** [comment]
THIS WORKED!!!!

So it worked with a 50% success rate because it seems to work great, but only my 2/4 cams, one is a V2 other is a V3. It's unfortunately delayed by a minute, unlike the dashboard/app view.

But the good news is now that you know where the success is you can work with this if you choose too, hopefully making all the cameras work eventually. Thanks!

<img width="1137" alt="Screen Shot 2022-03-28 at 1 54 23 AM" src="https://user-images.githubusercontent.com/3034555/160335444-963e883f-4ce5-40d5-8f79-13298c6ce615.png">
<img width="1136" alt="Screen Shot 2022-03-28 at 1 51 47 AM" src="https://user-images.githubusercontent.com/3034555/160335447-06d61ddb-b8f1-41c9-a75c-e209217fa15d.png">

**Comment by mrlt8** [comment]
Out of curiosity, was the audio channel required?

Also see https://github.com/aler9/rtsp-simple-server#decrease-delay

You may be able to play around with the FFMPEG_CMD to see if you might be able to reduce the delay.

**Comment by krysiswbk** [comment]
I am not sure what cameras you are using but casting works fine with V3 and doorbell. I personally cast from wyze bridge daily. I don't use ffmpeg cmds I don't need to run a ghost audio feed. Please don't spend too much time there! I can cast both hls and non hls!

**Comment by dnestico** [comment]
@mrlt8  So it randomly stopped working and now just worked again on my V2, don't think audio was required because I pulled up the dashboard at the same time and audio icon you put wasn't on that camera that was being casted.

Now to figure out why it works sometimes, and sometimes doesn't.

Also is this what you want me to put for reducing the delay?

ffmpeg -i rtsp://original-stream -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -g 30 -f rtsp rtsp://localhost:$RTSP_PORT/compressed

**Comment by dnestico** [comment]
@krysiswbk 

This is good information, thank you.

Would you say it always works anytime you cast your cameras? And so when you go to cast you are using a URL like this right?

`http://192.168.1.242:8888/porch/stream.m3u8`

And I do actually have nabu casa cloud subscription setup on external  URL so maybe I could play around with that...

Just wondering how did you make it work all the time because it wasn't working for me for the longest time until I started using these ffmpeg cmd things I was given by @mrlt8. Even right now I wouldn't say its 100% success rate because sometimes the feed just doesn't load.

Here is what my configuration file looks like btw, if that helps.

`
#stream
stream:

#ffmpeg
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

#camera
camera:
  - platform: ffmpeg
    input: rtsp://127.0.0.1:8554/porch
#    extra_arguments: -pred 1 -q:v 2 -s 1024x600
    name: Porch cam

  - platform: ffmpeg
    input: rtsp://127.0.0.1:8554/garage-cam
#    extra_arguments: -pred 1 -q:v 2 -s 1024x600
    name: Garage cam

  - platform: ffmpeg
    input: rtsp://127.0.0.1:8554/front-doorbell
#    extra_arguments: -pred 1 -q:v 2 -s 1024x600
    name: Doorbell cam

  - platform: ffmpeg
    input: rtsp://127.0.0.1:8554/driveway
#    extra_arguments: -pred 1 -q:v 2 -s 1024x600
    name: Driveway cam

  - platform: generic
    stream_source: rtsp://user:pass@127.0.0.1:8554/porch
    name: GENERIC Porch cam
`

**Comment by krysiswbk** [comment]
@ 

> @krysiswbk
> 
> This is good information, thank you.
> 
> Would you say it always works anytime you cast your cameras? And so when you go to cast you are using a URL like this right?
> 
> `http://192.168.1.242:8888/porch/stream.m3u8`
> 
> And I do actually have nabu casa cloud subscription setup on external URL so maybe I could play around with that...
> 
> Just wondering how did you make it work all the time because it wasn't working for me for the longest time until I started using these ffmpeg cmd things I was given by @mrlt8. Even right now I wouldn't say its 100% success rate because sometimes the feed just doesn't load.
> 
> Here is what my configuration file looks like btw, if that helps.
> 
> ` #stream stream:
> 
> #ffmpeg ffmpeg: ffmpeg_bin: /usr/bin/ffmpeg
> 
> #camera camera:
> 
> * platform: ffmpeg
>   input: rtsp://127.0.0.1:8554/porch
>   name: Porch cam
> * platform: ffmpeg
>   input: rtsp://127.0.0.1:8554/garage-cam
>   name: Garage cam
> * platform: ffmpeg
>   input: rtsp://127.0.0.1:8554/front-doorbell
>   name: Doorbell cam
> * platform: ffmpeg
>   input: rtsp://127.0.0.1:8554/driveway
>   name: Driveway cam
> * platform: generic
>   stream_source: rtsp://user:pass@127.0.0.1:8554/porch
>   name: GENERIC Porch cam
> 
> `

The ffmpeg was way too resource heavy I took them all off with the exception of a back up of my doorbell cam as that one is slow and was hoping to get it closer to other cams in regards to timestamps. ive been playing but no luck. 

my wyzebridge config has no flags or cmds

  - platform: ffmpeg
    input: rtmp://192.168.2.235:1935/front-door
    name: Front Door Cam2

  - platform: generic
    name: Front Door cam
    stream_source: rtmp://192.168.2.235:1935/front-door
  - platform: generic
    stream_source: rtsp://192.168.2.235:8554/sliding-door
    name: Sliding Door Cam
  - platform: generic
    stream_source: rtsp://192.168.2.235:8554/porch-steps
    name: Porch Steps Cam
  - platform: generic
    stream_source: rtsp://192.168.2.235:8554/patio
    name: Patio Cam

its not perfect but it works 95%

**Comment by dnestico** [comment]
@krysiswbk 

Thanks for sharing, I am actually using one "generic" stream and noticed it loads quicker, I am gonna use this info you shared and mess around for my own setup.

I still have that one cmd in my bridge config but will start playing around soon and remove it too.

**Comment by frenck** [comment]
> Hey @frenck, if you have time, could you help out here please, I can't get my camera to stream on my nest hub, as you can see in the thread here the developer has done a lot to try and fix it but still no luck so far.
> 
> (sorry if I shouldn't of @ ed you btw just trying to get this fixed and didn't know how to @ home assistant GitHub page)

Sorry, I have no clue what this project is, what I can do, how I am connected/affiliated with this all, or why I am pulled into this issue.

In general, I cannot appreciate being demanded/summoned. Please don't. I generally wake up to around 200 GitHub notifications each day, this one was really not needed. Thanks 👍

**Comment by krysiswbk** [comment]
@dnestico no worries! I played with ffmpeg for weeks i couldnt see the benefit over generic. The ffmpeg streams take 5-10 seconds to load in the app for me so forget casting... it was almost a full minute delay. Now when someone presses my doorbell its on my display within seconds ;).

Some things to note - i think its important to identify the IP in the config vs calling it locally (127.
0.0.1)  I have also found the need to add a "turn media player off" before the cast. This tweak has added alot of efficiency.. Now I turn media off - mute media - cast - unmute as a script.. pretty slick in action lol

**Comment by dnestico** [comment]
@krysiswbk Sweet thanks. 

Guess this is not technically an issue anymore so can be closed. I'm for sure bookmarking this is as I plan to re-read everything and overhaul my camera set up soon, and it'll be using frigate too for AI detection, I think I'll use frigates card.

Thanks.

**Comment by krysiswbk** [comment]
> @krysiswbk Sweet thanks.
> 
> Guess this is not technically an issue anymore so can be closed. I'm for sure bookmarking this is as I plan to re-read everything and overhaul my camera set up soon, and it'll be using frigate too for AI detection, I think I'll use frigates card.
> 
> Thanks.

Any luck casting for you?

**Comment by dnestico** [comment]
I'm still running the same setup so same results, works sometimes, not always


I plan to change it soon with the changes your suggested then I'll do some more testing.

**Comment by dnestico** [comment]
@mrlt8 

Btw, so after removing the FFMPEG CMD's my streams are pretty much real-time and I say at worst only a 3-5 second delay, so that's dope.

I haven't started changing them yet from FFMPEG to Generic so everything pretty much is the same.

Soon I'll do the changes @krysiswbk recommended and see how that goes and see if they will make casting work good. 👍

**Comment by dnestico** [comment]
I have switched my cameras to "generic" and can confirm streams load near instantly, also the latest update has for wyze docker has brought the delay down for most cameras to 2-5 seconds, I have only been running it for like 5 minutes though so maybe I'll report back in a couple hours on things.

**Comment by krysiswbk** [comment]
> Another update, I've fully switched my cameras to "generic" as well have removed the webRTC addon and my cameras are back in near real-time!
> 
> Eventually, I will have to test the streaming capabilities to the nest hub when I have time but for now, I have a cast snapshot automation for my doorbell which works good.

with the new update you can remove the camera config from your yaml if using generic. The casting feature is even faster now. literally 2 seconds. When  to wyzes native casting ability it blows it out of the water. 30-60 seconds via Wyze. 2 seconds through wyze bridge and HA
