### ISSUE TITLE
Stream progressively falls behind real-time (v1.3.0)

### ISSUE THREAD

**Issue by bbobrian** [mrlt8/docker-wyze-bridge#330]
The video stream slowly falls back in time, witnessed in the timestamp displayed behind the actual time. It get's progressively worse and is eventually several minutes behind. I compared the stream timestamp to the date from inside the docker container. I noticed this today when I received a person detection notification of myself about 5 minutes after it actually happened.

Restarting the docker container brings it back to real-time but then it slowly falls back again.

Also seeing this continually repeating in the log:
2022/03/28 18:33:03 [wyzecam.tutk.tutk_ioctl_mux][INFO][Front Porch] Now listening on channel id 0
2022/03/28 18:33:04 [wyzecam.tutk.tutk_ioctl_mux][INFO][Front Porch] No longer listening on channel id 0
2022/03/28 18:33:29 [wyzecam.tutk.tutk_ioctl_mux][INFO][Front Porch] Now listening on channel id 0
2022/03/28 18:33:29 [wyzecam.tutk.tutk_ioctl_mux][INFO][Front Porch] Now listening on channel id 0
2022/03/28 18:33:30 [wyzecam.tutk.tutk_ioctl_mux][INFO][Front Porch] No longer listening on channel id 0

**Comment by mrlt8** [comment]
Can confirm the delay. It's probably coming from the sleep between the frames.

As for the ioctl messages, that's to monitor the bitrate and FPS every 500 frames as those two values are missing from in frame_info. I don't think it's causing the delay, but I can change it to every 1000 frames to see if it helps.

**Comment by bbobrian** [comment]
Maybe change those messages to DEBUG level if they are going to happen every 20-40 seconds.

**Comment by dnestico** [comment]
Yea can confirm the same, it starts off real time then can go down to more then 10 minutes behind sometimes.

**Comment by tavicu** [comment]
Same problem after updating to the latest version.

Also i've seen an increase of CPU usage from 8% to 22%.

**Comment by mrlt8** [comment]
> Maybe change those messages to DEBUG level if they are going to happen every 20-40 seconds.

That's coming from the [kroo/wyzecam](https://github.com/kroo/wyzecam) library when `DEBUG_LEVEL` is set, but we could turn that off.

> Also i've seen an increase of CPU usage from 8% to 22%.

Is that jump on the DEV or v1.3.0 build? I do see an increase in CPU usage on the DEV build

It also seems like the latest build of ffmpeg might have slipped into the final release of v1.3.0, but I don't think the lag is coming from that.

**Comment by Z1mDMan** [comment]
> Same problem after updating to the latest version.
> 
> Also i've seen an increase of CPU usage from 8% to 22%.
> 
> For now I have reverted to 1.2.2 and it's all good!

Same here. I'm doing the same work-around for now.

**Comment by dnestico** [comment]
So just realized this explains why my camera notification snapshots are wrong. Wow

**Comment by hoveeman** [comment]
Interestingly my v3 camera does not exhibit the time sync issue. It is still correct. However, my v2 cameras exhibit this and continue to drift in time.

**Comment by dnestico** [comment]
I have:

2 v2's
1 v3
1 DB

As you can see in the screenshot they're all behind, which is strange, because I think the last update they were near real time. Hope there's a fix for this.

<img width="168" alt="Screen Shot 2022-03-29 at 8 30 17 PM" src="https://user-images.githubusercontent.com/3034555/160727669-8247ca73-f8b9-41b8-86a5-1fd58451c0ae.png">

<img width="769" alt="Screen Shot 2022-03-29 at 8 30 07 PM" src="https://user-images.githubusercontent.com/3034555/160727662-90b20c69-8d6e-4e8a-b92a-bbb3fc567bf9.png">

**Comment by mrlt8** [comment]
If using docker:
```
mrlt8/wyze-bridge:dev
``` 

Or if using HA:

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmrlt8%2Fedge-repo)

**Comment by dnestico** [comment]
Alright will check this out soon.

**Comment by dreondre** [comment]
I’ve been running dev for about an hour now and so far so good. However, I’ll likely check again in the morning or in the middle of the night.

**Comment by dnestico** [comment]
So should I remove the public one first and replace it with the dev right?

**Comment by dreondre** [comment]
I've been on the dev branch for 12 hours now and it appears to be keeping in time now. This looks a lot better. 👍

**Comment by mrlt8** [comment]
Pushed v1.3.1 which seems to be better (still see the usual 1.5-ish seconds delay compared to the app) without any major CPU spikes.

@tavicu can you see if you're still seeing a major jump in cpu usage?

**Comment by Z1mDMan** [comment]
I grabbed the nightly yesterday and this morning my cameras were lagging again so I went back to 1.2.2

**Comment by tavicu** [comment]
> @tavicu can you see if you're still seeing a major jump in cpu usage?

Updated and with 1.3.1 everything looks ok! The CPU is back to normal and the delay is around 2 seconds :)
Thank you for the quick fix!

**Comment by bbobrian** [comment]
> Pushed v1.3.1 which seems to be better (still see the usual 1.5-ish seconds delay compared to the app) without any major CPU spikes.

Running great for me as well. Thanks!

**Comment by mrlt8** [comment]
Marking this as resolved for now.

**Comment by dnestico** [comment]
So this is defenitley resolved yes but it seems with multiple cameras this still sometimes happens, I have 4 cameras on the hub and sometimes I'll go to look at my doorbell and it will be 2 hours behind while the rest are on time, or sometimes 1 camera will be behind by a couple minutes like 20-30 still...

**Comment by mrlt8** [comment]
Is the actual stream from the bridge behind or is it just the snapshots and/or playback from HA that is delayed?

**Comment by dnestico** [comment]
Yes I do have doorbell rotation set and to answer your question I just checked and both the thumbnail and stream are like 20 minutes behind.

Do you want me to turn doorbell rotation off?

**Comment by mrlt8** [comment]
Is that the doorbell the only camera falling behind?

**Comment by dnestico** [comment]
I just checked and the doorbell was the only stream that was 3 hours behind, while one of my other cams was "unavailable"... Again, not offline in the wyze app though

**Comment by mrlt8** [comment]
3 hours is a huge delay! Any memory or playback issues?

Anyone else still experiencing significant lag on 1.3.1+?

As for the unavailable cam, can you please post logs? there should hopefully be something there showing it go down in the bridge.

**Comment by bbobrian** [comment]
1.3.1 working perfect for me, but I only have a single V3 camera. CPU 0.5% and memory at 59MB.

**Comment by dnestico** [comment]
@mrlt8 

Aii so just restarted HA twice and removed 2 cameras, so down to 4 in HA.

The doorbell was 2 hours behind the rest while 1 is reported as unavailable, but it isn't in the Wyze app!

--------------------------------------------------------------------------------------

I restarted HA for the 3rd time andddd the doorbell is no longer behind the rest, just like normally happens.

Also, the camera that was offline, is now longer offline either.

Just a constant loop it seems.

**Comment by dnestico** [comment]
I am going to keep an eye on it for the next couple of hours, but the doorbell is strange because 5 minutes after checking it, the stream dropped to 1 minute behind the rest.

I am gonna the developer page open in the background for the next hour or couple and every so often check the doorbell stream to see what happens.

**Comment by dnestico** [comment]
I left HA developer page / wyze hub logs open in the background for a couple hours:

**UPDATES:**

20 minutes: doorbell stream fell back 5 mins 

50 minutes: doorbell stream fell back 15 mins 

1 hour 15 minutes later: doorbell stream fell back 20 mins 

1 hour 28 minutes later: garage cam went unavailable, not in wyze app though

LOG FOR THIS EVENT:
2022/04/10 16:37:55 [Garage Cam] WARNING: Skipping smaller frame at start of stream (frame_size=1)
2022/04/10 16:38:02 [RTSP][GARAGE-CAM] 📖 New client reading 
2022/04/10 16:38:04 [RTSP][GARAGE-CAM] 📕 Client stopped reading
2022/04/10 16:38:14 [RTSP][GARAGE-CAM] 📖 New client reading 
2022/04/10 16:38:15 [RTSP][GARAGE-CAM] ❌ '/garage-cam' stream is down
2022/04/10 16:38:15 [RTSP][GARAGE-CAM] 📕 Client stopped reading
2022/04/10 16:38:15 [RTSP][GARAGE-CAM] 📕 Client stopped reading

1 hour 40 mins later: garage cam came back... 
I opened the wyze app to check if it was offline during this time it was on HA and it was not, it was shortly after I checked wyze app it came back online in HA...

LOG FOR THIS EVENT:
2022/04/10 16:48:48 [Garage Cam] WARNING: Waiting for keyframe
2022/04/10 16:48:50 [Garage Cam] [Errno 32] Broken pipe
2022/04/10 16:48:51 [WyzeBridge] 🎉 Connecting to WyzeCam V2 - Garage Cam on 192.168.2.31 (1/3)
2022/04/10 16:48:54 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 75%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)
2022/04/10 16:48:54 [RTSP][GARAGE-CAM] ✅ '/garage-cam' stream is UP! (3/3)
2022/04/10 16:48:54 [RTSP][GARAGE-CAM] 📖 New client reading


2 hours 20 minutes later: the doorbell stream is 1 hour and 18 minutes behind, nothing in the logs

3 hours later: the doorbell stream is now 2 hours behind


This is where I will end this reply, just wanted to try and help you out as much as possible.


Also once again, here is my config:

WYZE_EMAIL: (removed)
WYZE_PASSWORD: (removed)
NET_MODE: ANY
SNAPSHOT: RTSP15
MQTT_DTOPIC: homeassistant
ROTATE_DOOR: true
WEBRTC: false
FRESH_DATA: true
RTSP_READTIMEOUT: 20s
KEEP_BAD_FRAMES: false
FPS_FIX: false
FILTER_BLOCK: true
FILTER_MACS: (removed), (removed)

**Comment by mrlt8** [comment]
From what you posted, it seems to be falling behind at a rate of about 15s every min. So the time stamp should be moving a little slower when viewing the stream live.

The problem with such a large delay is that the frames have to get buffered somewhere, so your memory usage should be skyrocketing.

Since it's only the doorbell that is slowing down, can you disable the rotation to see if that is where the bottleneck is?

**Comment by dnestico** [comment]
Something weird that just happened is the garage camera went offline in HA, not the wyze app... and right as that happened the doorbell streamed jumped right ahead to near real time... weird.

And yes, I will do so.

**Comment by mrlt8** [comment]
@dnestico Is the doorbell staying up to speed with the rest of the cameras when rotation is off?

**Comment by dnestico** [comment]
I think there must be caching issue with my chrome browser because I just loaded the stream and it was 3 hours behind, I then reload the page and it's in sync with every other camera.

Yesterday it only fell back 10 minutes but right now after reloading the browser page its is up to speed with the rest of the cameras.

Also happy about that commit because I definitely want the doorbell rotated lol, but this is fine for now of course since it seems to be performing a lot better.

**Comment by mrlt8** [comment]
Interesting.  I pushed some changes to the dev build that should increase the number of keyframes, so that it should start the rotated video faster. Could you give it a try and see if it helps?

**Comment by dnestico** [comment]
Alright, so I stopped the main branch and started the dev build.

Is there supposed to be duplicate entities? The entities the plugin made give me the Stream URL and the Image URL, so I added them via generic integration and now there are double entities, not a problem but this is normal right?

**Comment by dnestico** [comment]
I will check back later but after adding all my cameras and the doorbell with rotate on it loaded pretty quick and is near real time.

Will have to check again soon but pretty good so far.

**Comment by dnestico** [comment]
Welp now it's 2 hours behind, I might just filter it out tbh

**Comment by mrlt8** [comment]
Is this with chrome or VLC? 
Also, please let the video run for at least 30s to see if it's just a key frame issue.

**Comment by dnestico** [comment]
This is witch chrome, I just checked again and now it's 5 mins behind while the thumbnail is from a couple hours ago.

**Comment by mrlt8** [comment]
Please test in VLC or some other external player as the web viewer may be unreliable.

**Comment by dnestico** [comment]
It actually just jumped ahead on the web player, I guess it needs a couple minutes everytime

**Comment by dnestico** [comment]
<img width="695" alt="Screen Shot 2022-04-12 at 10 05 20 PM" src="https://user-images.githubusercontent.com/3034555/163085242-9fc9da5c-4ec7-4375-89bf-faa2b276f01e.png">


Umm this is... weird, the stream is up on the web player.

**Comment by mrlt8** [comment]
`homeassistant.local`?

**Comment by dnestico** [comment]
That's what I've been using? I'm gonna review the docs again in a couple minutes because I thought that was right as those are the urls the dev branch gave me so I used them.


![Screenshot_20220412-221514.png](https://user-images.githubusercontent.com/3034555/163086371-2b684930-3d57-44a9-ade3-61421fa47c18.png)![Screenshot_20220412-221504.png](https://user-images.githubusercontent.com/3034555/163086375-833a95f1-4ba1-4026-982a-bae3ec7497f5.png)

**Comment by dnestico** [comment]
Oh wait I see my error God damn I am an idiot, I will update you soon.

**Comment by dnestico** [comment]
Ok so that worked and its behind as you can see:

<img width="1393" alt="Screen Shot 2022-04-12 at 10 37 30 PM" src="https://user-images.githubusercontent.com/3034555/163088862-2b602e29-2c7c-4b47-9f0a-0827250fb881.png">

**Comment by mrlt8** [comment]
Thanks for the confirmation. I'll go ahead and split this into a new issue since it only seems to affect the cameras after rotation.

**Comment by dnestico** [comment]
Alright nice, right now the only issue that remains is the thumbnails also aren't updating so I may just switch it to always live rather than auto.

I hope webRTC can keep the cams online because there is one cam that keeps reporting as unavailable on HA when it isn't offline. :/
