### ISSUE TITLE
Corrections to v1.3.0 README.md

### ISSUE THREAD

**Issue by ronald-mendoza** [mrlt8/docker-wyze-bridge#332]
### Discussed in https://github.com/mrlt8/docker-wyze-bridge/discussions/331

<div type='discussions-op-text'>

<sup>Originally posted by **ronald-mendoza** March 30, 2022</sup>
Hello all. I'm pretty new to GitHub, so not sure how to report errors in the v1.3.0 README.md:

Specifically in https://github.com/mrlt8/docker-wyze-bridge#recording-streams-beta

The **Enable recording** example shows `volume` when it should be `volumes`

And in the instructions for the next sample, it says to use _ in place of dashes, which is incorrect. e.g. If the camera name is FRONT-DOOR, the correct syntax is `RECORD_FRONT-DOOR=True`</div>

**Comment by mrlt8** [comment]
Thanks! Will fix!

**Comment by mrlt8** [comment]
Marking this as resolved for now.
