### ISSUE TITLE
Issue with YT Live Streaming with custom FFMPEG_CMD

### ISSUE THREAD

**Issue by haamro** [mrlt8/docker-wyze-bridge#334]
Hello there, 
I am trying to stream my video directly to youtube using custom ffmpeg but it is not working. I am not able to see the log and have no idea why it is not working.  YT needs audio so I am using anullsrc

Following FFMPEG works fine
`ffmpeg -i rtmp://ip:1935/front-door -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key
`

However, when  I run the docker, it is not streaming to YT at all.
my env variable
`- FFMPEG_CMD_FRONT_DOOR=ffmpeg -i - -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key
`

I have tried
`- FFMPEG_CMD_FRONT_DOOR=ffmpeg -i -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key
`

and

`- FFMPEG_CMD_FRONT_DOOR=ffmpeg  -f h264 -i - -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key
`

Do you have any idea what I might be doing wrong or what could be the issue. 

thank you

**Comment by mrlt8** [comment]
The bridge will try to add the camera name to the end of the command to pass the stream to rtsp-simple-server.

Will try to get this patched,  but for now, you could have rtsp-simple-server push the RTMP stream with something like:
```yaml
- RTSP_PATHS_FRONT_DOOR_RUNONPUBLISH=ffmpeg ....
```

**Comment by haamro** [comment]
Thanx for the prompt reply.

I tried this but it didn't work. The ffmpeg command works otherswise
`RTSP_PATHS_FRONT_DOOR_RUNONPUBLISH=ffmpeg -i rtmp://xx:1935/front-door -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key`

Where did _RUNONPUBLISH come from ? I couldn't find any documentation for it on rtsp_simple_server as well.

**Comment by mrlt8** [comment]
whoops, that should be `_RUNONREADY`! I believe they replaced _publish_ with _ready_ a few versions ago.

https://github.com/aler9/rtsp-simple-server#configuration

**Comment by haamro** [comment]
It didn't work either

**Comment by mrlt8** [comment]
Have you tried using `rtsp://0.0.0.0:8554/front-door` as the input?

**Comment by haamro** [comment]
I tried, and it didn't work. I might have to install simple_rtsp_server and publish from there

**Comment by mrlt8** [comment]
v1.3.2 moved the static camera name into a variable, so you should be able to use `FFMPEG_CMD_FRONT_DOOR` to push the stream with the piped input.

**Comment by haamro** [comment]
The following code didn't work. What is the default input video format (after `-i`, I mean why is there an extra `-`  ) ? I tried appending ` -i  rtsp://......`  as well. Also how do I get the detail log for this FFMPEG_CMD, may that will give me a clue, what am I doing wrong.
`FFMPEG_CMD_FRONT_DOOR=ffmpeg -i - -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key`

from documentation:
`- FFMPEG_CMD_CAM_NAME=ffmpeg -f h264 -i - -vcodec copy -f flv rtmp://rtsp-server:1935/{cam_name}`

**Comment by mrlt8** [comment]
The `-i -` is to use stdin as the source so we can push the raw h264 bytes from the camera.

I think `libmp3lame` may be the issue. Can you use aac instead? Something like:
```
- FFMPEG_CMD_CAM_NAME=ffmpeg -f h264 -i - -f lavfi -i anullsrc -acodec aac -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/my_key
```

**Comment by haamro** [comment]
That didn't work either. How do we get the log from FFMPEG_CMD_CAM_NAME ? I don't think its problem with the ffmpeg command, because I can run ffmpeg  and it works fine. I am not sure if FFMPEG_CMD_CAM_NAME is spitting the correct ffmpeg.

**Comment by mrlt8** [comment]
```
- DEBUG_FFMPEG=true
```
Should show the actual command.

You might also want to increase the loglevel on you ffmpeg command to see if it's causing any errors.

**Comment by haamro** [comment]
```

    - DEBUG_LEVEL = debug
    - DEBUG_FFMPEG = true
```
and where do I see the debug log. all I can see is std out from `docker-compose up` . Same thing from `docker logs -f wyze-bridge`

**Comment by mrlt8** [comment]
We're not redirecting stderr, so it should just print the logs, e.g (with `ffmpeg -loglevel debug` since you're replacing the default ffmpeg command):

```
....
wyze-bridge  | Successfully parsed a group of options.
wyze-bridge  | Opening an output file: rtmp://0.0.0.0:999/front-gate.
wyze-bridge  | [rtmp @ 0x555d13fb0700] No default whitelist set
wyze-bridge  | [tcp @ 0x555d14050280] No default whitelist set
wyze-bridge  | [tcp @ 0x555d14050280] Original list of addresses:
wyze-bridge  | [tcp @ 0x555d14050280] Address 0.0.0.0 port 999
wyze-bridge  | [tcp @ 0x555d14050280] Interleaved list of addresses:
wyze-bridge  | [tcp @ 0x555d14050280] Address 0.0.0.0 port 999
wyze-bridge  | [tcp @ 0x555d14050280] Starting connection attempt to 0.0.0.0 port 999
wyze-bridge  | [tcp @ 0x555d14050280] Connection attempt to 0.0.0.0 port 999 failed: Connection refused
wyze-bridge  | [tcp @ 0x555d14050280] Connection to tcp://0.0.0.0:999 failed: Connection refused
wyze-bridge  | [rtmp @ 0x555d13fb0700] Cannot open connection tcp://0.0.0.0:999
wyze-bridge  | rtmp://0.0.0.0:999/front-gate: Connection refused
...
```

**Comment by mrlt8** [comment]
I was able to [stream and view](https://flashphoner.com/testing-of-rtmp-broadcasting-from-a-video-capture-device-or-software-to-browsers/) one of my cams using this:
```yaml
FFMPEG_CMD_FRONT=ffmpeg -loglevel debug -f h264 -i - -f lavfi -i anullsrc -acodec libmp3lame -vcodec copy -f flv rtmp://demo.flashphoner.com:1935/live/live_stream
```

**Comment by haamro** [comment]
Absolutely, the following command works for YouTube. of course there is no audio
`ffmpeg -loglevel debug -f h264 -i - -f lavfi -i anullsrc -a codec libmp3lame  -vcodec copy -f flv rtmp://a.rtmp.youtube.com/live2/your_key`

I am running my docker on Amazon LightSail $5/month plan. I want to see how much bandwidth I will end up using there and how many FFMPEG it can handle. Will start that in couple weeks.

Thank you for your help.

**Comment by mrlt8** [comment]
Hey @haamro, playing around with the idea of adding live-streaming as an option in the bridge so that `- YOUTUBE_FRONT_DOOR=my-youtube-key` would tee the ffmpeg output to rtsp-simple-server and YouTube at the same time. 
We could also include several other predefined live-streaming services as well as a custom rtmp URL with `LIVESTREAM_FRONT_DOOR=rtmp://....`). Let me know what you think or if you have any suggestions!

**Comment by haamro** [comment]
That would be great.  Does  env `QUALITY_FRONT=HD120` works for the `FFMPEG_CMD_FRONT` as well  or do we need to set  camera quality on FFMPEG ? Not sure how to do later. 

ALso, the other issue I am facing right now is the "Not Enough Bitrate", YT recommends 4500K, so we might have to add `-b 4500k` on FFMPEG command

**Comment by mrlt8** [comment]
The `QUALITY` envs are used when requesting the raw frames from the camera, so it shouldn't effect the ffmpeg commands.

Not sure if we can adjust the bitrate as we're just copying the raw h264. Were you able to get the `-b` command to change the output bitrate?

**Comment by mrlt8** [comment]
Marking this issue as resolved for now.

**Comment by bwenger9** [comment]
I just wanted to add my experience here as this issue helped me with what I was trying to achieve. I was attempting to reduce the framerate of the cam to something like 5 or 10fps so my Blue Iris NVR could use less space in continuous recording mode and not have to rely on the SD card for continuous recording. After all was said and done, I realized that the ffmpeg -r option does NOT work alongside the stream copy mode (-vcodec copy) and it gets ignored. This means filtering must be done which causes a re-encode and in my instance rails the CPU and I can't even attach to the stream (homeassistant VM on QNAP NAS).

Also, I had a hell of a time figuring out how to get a successful parameter input without errors. The input -i - is not well documented except for in this thread. Also, the output stream had to be forced to rtsp in my case.

This works but -r 5 is ignored because of stream copy mode, so no real effect of the command from not using it at all.
`ffmpeg -f h264 -i - -r 5 -vcodec copy -f rtsp rtsp://192.168.1.79:8555/{cam_name}`

This works (I think) as it is parsed correctly by ffmpeg but the re-encoding is too much of a burden on my VM.
`ffmpeg -f h264 -i - -vcodec h264 -filter fps=5 -f rtsp rtsp://192.168.1.79:8555/{cam_name}`

Off to try wz_mini_hacks to see what that offers.
