### ISSUE TITLE
Custom snapshot rate

### ISSUE THREAD

**Issue by dnestico** [mrlt8/docker-wyze-bridge#336]
Is it possible to add an option for a custom snapshot rate?

I would like to be able to make the snapshots as low as 5 seconds so that they can be more up to date, thanks.

**Comment by mrlt8** [comment]
This is already a feature with `SNAPSHOT=RTSP(INT)`, so a 5s interval would be `SNAPSHOT=RTSP5`.

FYI, taking a snapshot from the RTSP stream requires the h264 stream to be decoded, so a more frequent snapshots may increase CPU usage.

**Comment by dnestico** [comment]
It doesn't like that, it says it must be 15 and when I did it, it reset back to SNAPSHOT:RTSP15

**Comment by mrlt8** [comment]
It must be the home assistant schema preventing a custom input. I can try to add some more options to the list.

**Comment by dnestico** [comment]
Good point LMAO, I am changing the password now.

**Comment by dnestico** [comment]
Also hopefully next update fixes some cameras showing as unavailable, in the Wyze app they are not offline, but on HA some (1) show(s) as offline sometimes.

**Comment by mrlt8** [comment]
Marking this as resolved for now.
