### ISSUE TITLE
not updating when adding new cams or renaming cams

### ISSUE THREAD

**Issue by pjkix** [mrlt8/docker-wyze-bridge#337]
i'm not sure if this is a know issue or if there is a bug with the api and caching but i've renamed a v3 cam and also added a v3 cam and i'm not seeing them show up in the bridge. i tried doing a restart of both the bridge and all cams but no luck getting the new name or the new cam to show up.

**Comment by mrlt8** [comment]
It's more of a feature to minimize the number of hits to the wyze api, but you can force the bridge to pull new data from the api with `FRESH_DATA` which would look like this in your docker-compose.yml:
```yaml
environment:
    - WYZE_EMAIL=
    - WYZE_PASSWORD=
    - FRESH_DATA=True
```

**Comment by pjkix** [comment]
Cool, thanks for the info, i sorta solved my problem anyway by moving from docker version on NAS to the home assistant version which is working pretty well. Thanks for all the work on this. Cheers!

**Comment by mrlt8** [comment]
Marking this as resolved for now.
