### ISSUE TITLE
Doorbell keeps going offline

### ISSUE THREAD

**Issue by dnestico** [mrlt8/docker-wyze-bridge#338]
On the latest update with the following config settings and the doorbell, stream keeps going offline, I have an automation that notifies me when it happens, and it's basically spamming me about the doorbell, but not the other cameras.

Not sure why this is happening as it's not offline in the Wyze app, but offline on HA a lot of the time, Based off the offline notification it seems to come online then go back offline like every 5 mins or so. On the latest firmware for both wyze docker and doorbell.

My config:

WYZE_EMAIL: -
WYZE_PASSWORD: -
NET_MODE: ANY
SNAPSHOT: RTSP15
MQTT_DTOPIC: homeassistant
ROTATE_DOOR: true
WEBRTC: false
FRESH_DATA: true
RTSP_READTIMEOUT: 10s
KEEP_BAD_FRAMES: true
FPS_FIX: true
FILTER_BLOCK: true
FILTER_MACS: -

The log:

2022/04/07 00:56:09 [RTSP][FRONT-DOORBELL] 📕 Client stopped reading
2022/04/07 00:56:11 [RTSP][FRONT-DOORBELL] ❌ '/front-doorbell' stream is down
2022/04/07 00:56:11 [RTSP][FRONT-DOORBELL] 📕 Client stopped reading

**Comment by mrlt8** [comment]
Anything in the log before that?

You might want to increase `RTSP_READTIMEOUT` to give it a few extra seconds to recover.

**Comment by dnestico** [comment]
That's everything that related to the doorbell, and true, this did start happening after I made it 10s rather than the 30s I had before, will see if that fixes it soon.

**Comment by mrlt8** [comment]
Try to keep an eye on the logs next time it happens to see if you see any other messages around the time:
```
2022/04/05 20:50:52 [RTSP][BACK] ❌ '/back' stream is down
2022/04/05 20:50:52 [RTSP][BACK] 📕 Client stopped reading
2022/04/05 20:50:53 [back] Stream did not receive a frame for over 20s
```

**Comment by dnestico** [comment]
I will definitely do so but gonna have to wait for 2022.4.1 because it seems 2022.4.0 has broken still images (https://github.com/home-assistant/core/issues/69128), but I have made the 'RTSP_READTIMEOUT' 30 seconds now, so will have to see if that changes things.

**Comment by dnestico** [comment]
I managed to get these from the log too, it seems to be affecting all of my cameras and I have no idea why they keep showing as unavailable in HA when they are not offline, because of this my notification snapshots are never accurate, and always hours behind.

**CPU usage also jumps insanely high sometimes all the way from 32% to 88%**

-------------------------------------------------------------------------------------

Here is my config:

WYZE_EMAIL: -
WYZE_PASSWORD: -
NET_MODE: ANY
SNAPSHOT: RTSP15
MQTT_DTOPIC: homeassistant
ROTATE_DOOR: true
WEBRTC: false
FRESH_DATA: false
RTSP_READTIMEOUT: 30s
KEEP_BAD_FRAMES: false
FPS_FIX: false
FILTER_BLOCK: true
FILTER_MACS: -

-------------------------------------------------------------------------------------

2022/04/08 00:13:29 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)

2022/04/08 00:14:31 [Front Doorbell] WARNING: FPS param mismatch (framerate=20)

2022/04/08 00:13:29 [Driveway] WARNING: Skipping smaller frame at start of stream (frame_size=1)

<img width="714" alt="Screen Shot 2022-04-08 at 12 16 55 AM" src="https://user-images.githubusercontent.com/3034555/162361377-af637222-84c0-448e-84fa-c5ab91006e4f.png">

-------------------------------------------------------------------------------------

**And finally, when I was trying to test why the snapshots are old and it wasn't even making a new one when I called the service, this is what the HA log showed:**


Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@127.0.0.1:8554/driveway
12:20:33 AM – (ERROR) Stream - message first occurred at April 7, 2022, 7:14:18 PM and shows up 7 times
Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@127.0.0.1:8554/porch
12:20:03 AM – (ERROR) Stream - message first occurred at April 7, 2022, 7:14:18 PM and shows up 25 times
Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@127.0.0.1:8554/garage-cam
12:20:03 AM – (ERROR) Stream - message first occurred at April 7, 2022, 7:14:18 PM and shows up 25 times
Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@127.0.0.1:8554/front-doorbell
12:20:03 AM – (ERROR) Stream - message first occurred at April 7, 2022, 7:14:18 PM and shows up 64 times

**Comment by dnestico** [comment]
@mrlt8 Yea so this now seems to be effecting more than the doorbell, no idea why the cameras go offline randomly when they work fine in the wyze app. 

I wonder if it's because they are constantly streaming? Maybe on-demand streaming could solve this... With the new HA update, I have the snapshot URL set to 15 seconds, but for some reason, HA doesn't seem to be following that as the snapshots its taking are not every 15 seconds... they are more like hours behind sometimes, it seems to be really effecting my snapshot automations.

**Comment by mrlt8** [comment]
How's the WiFi coverage around those two cameras?
Does limiting the number of cameras improve stability?

**Comment by dnestico** [comment]
So I restarted the bridge, and like usual, that fixed it and they are back online. 

Also, all of my cameras are near my modem, especially the 2 of them are basically beside it.

I just restarted the addon again to get you the wifi info and it really doesn't seem like it should be an issue as you can see here:

2022/04/08 23:41:55 [Luna Cam] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 67%) FW: 4.36.3.19 (2/3)

2022/04/08 23:41:55 [Front Doorbell] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 98%) FW: 4.25.1.042 🔒

2022/04/08 23:41:55 [Porch] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 98%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)

2022/04/08 23:41:55 [Driveway] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 95%) FW: 4.36.9.117 🔒 (DTLS) (2/3)

2022/04/08 23:41:55 [Garage Cam] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 89%) FW: 4.9.8.1002 🔒 (DTLS) (2/3)

**Comment by mrlt8** [comment]
I think we're getting a couple of overlapping issues here.. 

1. Are the cams actually offline or is it just reporting as offline in HA?
2. Do the cameras stay offline or do they eventually come back?
3. Anything in the add-on logs around the `stream is down` messages?
4. Does limiting the number of cameras improve stability? 

The streams do go down every now and then (If you watch closely, you'll notice something similar in the app), but they should be able start back up on their own.

**Comment by dnestico** [comment]
Ok sorry for the confusion, I just didn't want to open 100 issues.

1. No the cameras are not offline, they are just reporting "unavailable" in HA
2. The cameras seem to stay offline until I restart the bridge
3. The log says "Camera is up" but it's reporting "unavailable" in HA and it isn't saying anything about "stream is down" even though its reporting as "unavailable"
4. I haven't tried that yet but maybe will soon, I just restarted the hub again from last night since 2 cameras went unavailable again, 1 came back after 5 minutes, other didn't

**Comment by dnestico** [comment]
Just an update: So the "Porch cam" is staying offline for whatever reason so I am going to filter that out from the bridge, so now it will be 4 cameras instead of 5.

**Comment by pjkix** [comment]
I don't know if this is related or not but i was having issues with safari and Home assistant saying "network stream error" cams not updated live, constantly needing to refresh the page, then i switched browsers to firefox and all my issues magically disappeared, cams are all live now and no error messages. I suspect it has something to do with safari trying to be power efficient or something. Anyway just thought I'd add a note here. Cheers

**Comment by mrlt8** [comment]
Interesting.. this seems like it could be more of a HA issue..? how are you checking the status of the cams, is it from MQTT?

- `Skipping smaller frame at start of stream` is pretty much what it says, the camera is probably set to use the 360p stream, so the bridge requests the HD "frame size" and is waiting for the camera to switch _before starting the stream_. This will keep looping until the HD frame size is received (which may be the CPU spike you see sometimes).

- `Wrong resolution (frame_size=1)` same as above, but this is happening midway through the stream. Can happen if you open the app and it's set to pull the 360p stream, so the bridge attempts change it back to HD: `Requesting frame_size=0 and bitrate=120`

- `Frame not available yet` this means that the bridge hasn't received a frame from the camera in over a second.

- Fetching data from wyze api - you probably have `FRESH_DATA` set. 

- yes, `SNAPSHOT=RTSP` will be pulling the images from the stream itself, so it will show as a client reading.

**Comment by dnestico** [comment]
Ok so with this info I'm taking that "`client reading`" is not an issue, which is good I guess because I have it set to `SNAPSHOT=RTSP15` and soon `SNAPSHOT=RTSP5` when that's released.

The whole resolution thing HAS to be a wyze issue because even in the God damn wyze app I always set the camera resolutions to "HD" but they always load in "SD" for some reason!

And I am not using MQTT, no.

Also, the thumbnails are sometimes behind the actual stream yes but like I said it fixes itself after a couple of hours sometimes, but as of right now my doorbell is still about 30 mins behind the other cameras.

**Comment by mrlt8** [comment]
The resolution thing shouldn't be an issue as the bridge should be able to correct for that within a couple of frames. 

If not via mqtt, where is HA listing the cameras as offline? Can you stream from the RTSP stream via VLC when it is reporting as offline?

**Comment by dnestico** [comment]
So for whatever reason, 2 cameras are once again reporting as "unavailable" in HA, on the Wyze app they are perfectly fine and up and running.

Also nope, cannot access them via VLC, something's up with the bridge for sure.

<img width="531" alt="Screen Shot 2022-04-10 at 2 22 07 PM" src="https://user-images.githubusercontent.com/3034555/162633936-466e8146-808f-43aa-844d-295eef254bf4.png">
<img width="543" alt="Screen Shot 2022-04-10 at 2 22 25 PM" src="https://user-images.githubusercontent.com/3034555/162633938-a43ee9f0-bba6-4a96-b8d3-98c67a8e1739.png">

**Comment by mrlt8** [comment]
Unless you have auth setup in rtsp-simple-server, the stream uri to that in the [readme](https://github.com/mrlt8/docker-wyze-bridge#camera-stream-uris), in your case, assuming HA running on the same machine as VLC:
  ```
  rtsp://localhost:8554/garage-cam
  ```

**Comment by dnestico** [comment]
I will have to try this again if another camera goes offline 👍

**Comment by dnestico** [comment]
@mrlt8 

So I've just been able to test this as the garage cam is showing as "unavailable" in HA, but not the app.... And it isn't accessible through both URLs on VLC.

But I'm watching it live on the wyze app as I'm typing this! haha.

<img width="555" alt="Screen Shot 2022-04-11 at 1 23 43 PM" src="https://user-images.githubusercontent.com/3034555/162795823-f3cabfd6-8f33-4c4d-b698-332c4ab76223.png">
<img width="530" alt="Screen Shot 2022-04-11 at 1 23 32 PM" src="https://user-images.githubusercontent.com/3034555/162795830-cf42632c-52b1-48cc-ac3a-f91aea2c0c10.png">

**Comment by mrlt8** [comment]
I don't think the router is an issue since it starts up correctly.

Unavailable in HA does not mean that the camera is offline.

Again, please view the bridge's logs when it is showing as unavailable, otherwise we have no idea what is going on.

The bridge, just like the app, will lose connection to the camera from time to time, but is supposed to restart the process if the connection is lost. The bridge will show and adjust the connection attempts if the camera is detected as being offline.

**Comment by dnestico** [comment]
Well in other news my "garage cam" has not come back in HA, but checked in the logs it said the camera came back online... so I checked and the thumbnail updated, but the stream was not online so it looks like it came back for like 1 second enough to update thumbnail then went back as unavailable. weird. It actually did this a couple times.

Now regarding the doorbell, I just checked and ever since turning off the doorbell rotation it's only fell back once and by 5 minutes, I will check again tomorrow too see if this stays like that but that seems like positive news.

**Comment by mrlt8** [comment]
Thumbnails from RTSP15? If those are updating then it means the rtsp stream is most likely still up and it's whatever HA is doing to read the stream that is having issues..?

**Comment by mrlt8** [comment]
Have you tried the [ffmpeg platform](https://www.home-assistant.io/integrations/camera.ffmpeg/) instead? I believe that one does it's own snapshots as well.

**Comment by mrlt8** [comment]
I've been running some tests, and believe this is an MQTT bug that's just reporting the camera as offline even though the camera is still up.

Will need to look into it, but you should be able to ignore the status and continue to use the cams as normal.

**Comment by dnestico** [comment]
I'm not even using MQTT but I hope this fixes it because I have one camera that is constantly unavailable in home assistant so no video feed, but it never is offline in the app, getting annoying.

**Comment by mrlt8** [comment]
When you say unavailable, do you mean the RTSP stream is not responding or is it just saying "unavailable" somewhere in home assistant..? 

MQTT is what is sending the entity info in #340 and I'm assuming the camera status that you're referring to. MQTT should set the status to "offline" if the stream is down or "disconnected" if the bridge stop updating the status for some reason.

**Comment by dnestico** [comment]
When I mean "unavailable" I mean the stream doesn't play, sorry.

Here is more info here in this issue. https://github.com/mrlt8/docker-wyze-bridge/issues/340

**Comment by mrlt8** [comment]
This is definitely Home assistant related. I was able to replicate the "unavailable" with generic and ffmpeg even though the actual rtsp stream was still up in VLC. Not sure why HA stop reading the stream though...

**Comment by dnestico** [comment]
Just checked again today and the doorbell is 1 minute behind which is the best it's been so will have to report back if it stays this way.

This is still with all cameras filtered out.

And I am for sure starting to think this is a HA issue too, wonder what I would name the issue to report to them.

**Comment by mrlt8** [comment]
take a look at https://community.home-assistant.io/t/i-tried-all-the-camera-platforms-so-you-dont-have-to/222999

They all seem to have some sort of lag and/or processing issue.

**Comment by krystiancharubin** [comment]
try removing FPS_FIX and setting QUALITY to HD180, this made by doorbell stay up for days with a few short timeout but it always reconnects successfully.

**Comment by dnestico** [comment]
I'm on the dev branch and don't see an option for FPS_FIX but I added the HD180 quality.

**Comment by dnestico** [comment]
I just switched back to the public version and the doorbell started with a 5 min delay.

This is the setup as recommended: 

WYZE_EMAIL: -
WYZE_PASSWORD: -
NET_MODE: ANY
SNAPSHOT: RTSP5
MQTT_DTOPIC: homeassistant
ROTATE_DOOR: true
WEBRTC: false
FRESH_DATA: true
RTSP_READTIMEOUT: 25s
KEEP_BAD_FRAMES: false
FPS_FIX: false
FILTER_BLOCK: true
FILTER_MACS: 2CAA8EB10CD8, 2CAA8E71FC03

**Comment by mrlt8** [comment]
I noticed that the rotation could cause the bitrate to spike, so I limited the bitrate to 3,000 kb/s in dev 4 to see if that might help with the drops.
