### ISSUE TITLE
update HTTP stream hack from FiveLeavesLeft 

### ISSUE THREAD

**Issue by Vendo232** [mrlt8/docker-wyze-bridge#341]
hi, would you be able to update the http stream hack for the new full root mini hack https://github.com/gtxaspec/wz_mini_hacks?

**Comment by mrlt8** [comment]
The bridge should work with the new hack, but if you're looking for a native solution to run on the cam, I believe the [atomcam_tools](https://github.com/mnakada/atomcam_tools), which wz_mini_hacks is based on, already has an rtsp server, so that could probably be ported over.

**Comment by mrlt8** [comment]
Looks like [work](https://github.com/gtxaspec/wz_mini_hacks/issues/8) is being done to address this, so I'll close this issue for now to avoid any overlap.
