### ISSUE TITLE
Stuck at Attaching to Bridge, then get exited with code 139.

### ISSUE THREAD

**Issue by DdraigX** [mrlt8/docker-wyze-bridge#345]
Not sure why I've been struggling with this. I believe I have everything setup correctly. I thought it might be due to the 2 factor authentication I have setup, but I turned that off and I'm still getting the message. 

I'm using a pi zerow and used the armv6 image. 

Any help/suggestions would be appreciated. 

This is my first docker project so I'm pretty much a noob with docker.  Followed mostly this tutorial: https://www.youtube.com/watch?v=NkhFgy0SYJ4

```
pi@xxxxx-piwyze:~ $ sudo cp docker-compose.yml docker-wyze-bridge/
pi@xxxxx-piwyze:~ $ docker-compose up
Pulling wyze-bridge (mrlt8/wyze-bridge:latest)...
latest: Pulling from mrlt8/wyze-bridge
d4bf0b27c669: Pull complete
1a0decfb9deb: Pull complete
bd41b1955e7a: Pull complete
c0d07ae02455: Pull complete
aee6e26ba345: Pull complete
07092ca3b466: Pull complete
Digest: sha256:41eb9cab4531082875db1917accf402fb7540f65c6b1ae2b616c2aa67d00e009
Status: Downloaded newer image for mrlt8/wyze-bridge:latest
Creating wyze-bridge ... done
Attaching to wyze-bridge
pi@xxxxx-piwyze:~ $ docker-compose up
wyze-bridge is up-to-date
Attaching to wyze-bridge
pi@xxxxx-piwyze:~ $ docker-compose up
wyze-bridge is up-to-date
Attaching to wyze-bridge
wyze-bridge exited with code 139
pi@xxxxx-piwyze:~ $

```

**Comment by mrlt8** [comment]
Unfortunately, armv6 isn't supported yet as we've had issues trying to get the the tutk library to run on the alpine base image. 
See #294
