### ISSUE TITLE
Why doesn't this filer line work correctly?

### ISSUE THREAD

**Issue by ragenhe** [mrlt8/docker-wyze-bridge#346]
When using the following in my docker-compose file, my pan camera isn't found.

```- FILTER_MODELS=Pan,V2,V3```

But it is found when I remove the line.

**Comment by mrlt8** [comment]
Thanks for reporting this. Fix will be merged in the next release.

For now, you should be able to use the actual model number `WYZECP1_JEF` in the filter e.g. 
```yaml
- FILTER_MODELS=WYZECP1_JEF,V2,V3
```

**Comment by mrlt8** [comment]
Marking this as resolved. 

Please feel free to open a new topic should you need more assistance!
