### ISSUE TITLE
Repository not showing up in HA

### ISSUE THREAD

**Issue by JochenKlenk** [mrlt8/docker-wyze-bridge#351]
Hi,

I added the Repository to the Addon on Repository List, but it not showing up in the AddOn Store.
Do somone elese have this experience? And if so is there an fix.

![image](https://user-images.githubusercontent.com/67780425/165251083-d1720e0a-80c8-4374-a459-1980fa498f68.png)

core-2022.4.7

Thanks

**Comment by benjani85** [comment]
I've just tried this and getting the exact same issue. Browser refresh makes no difference either.

**Comment by JochenKlenk** [comment]
I tried over cli and get following

bash-5.1# ha addons install docker-wyze-bridge
Processing... Done.

Error: Addon docker-wyze-bridge with version latest does not exist in the store

**Comment by JochenKlenk** [comment]
- maintainer: unknown
  name: docker-wyze-bridge
  slug: 7094bb28
  source: https://github.com/mrlt8/docker-wyze-bridge
  url: https://github.com/mrlt8/docker-wyze-bridge

**Comment by jdeath** [comment]
issue is: expected str for dictionary value @ data['environment']['SKIP_RTSP_LOG']. Got True in app/config.json

**Comment by JochenKlenk** [comment]
all fine I can wait for the next commit. But thanks for the fast support.

**Comment by jdeath** [comment]
I would keep the issue open. I am not the developer.
