### ISSUE TITLE
Wyze Bridge 1.3.6 with hassio 2022.04.7

### ISSUE THREAD

**Issue by cbrightly** [mrlt8/docker-wyze-bridge#355]
I recently updated hassio to core-2022-4.7, supervisor 2022.4 and this package to 1.3.6. When I start the add-on (if it starts at all) I get the following error/ traceback:

```
Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 639, in <module>
    setup_hass()
  File "/app/wyze_bridge.py", line 625, in setup_hass
    os.environ["HOSTNAME"] = info["data"]["hostname"]
  File "/usr/local/lib/python3.10/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```
Is something in my installation just incompatible? Should I roll-back the addon to a previous version? Thanks in advance; I greatly appreciate any thoughts / advice!

**Comment by mrlt8** [comment]
hmm, just did a fresh install on my vm, but not seeing any errors.

I don't think we're using the hostname anyways, so we could probably remove that.
