### ISSUE TITLE
Connection refused and [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by JochenKlenk** [mrlt8/docker-wyze-bridge#356]
Hi guys,

the camera streams are not starting to work. Look slike the port cannot be open. 

All running as an Addon in HomeAssitant wih latest Version 1.36

Any suggestions or ideas?

Thanks 

2022/04/27 11:13:20 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Terrasse on 192.168.178.45 (1/3)
2022/04/27 11:13:20 [Haustüre] [Errno 32] Broken pipe
2022/04/27 11:13:21 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Haustüre on 192.168.178.47 (1/3)
2022/04/27 11:13:22 [Terrasse] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 65%) FW: 4.36.9.131 🔒 (DTLS) (2/3)
2022/04/27 11:13:22 [Terrasse] [FFMPEG_CMD] ffmpeg -loglevel verbose -fflags +genpts+flush_packets+nobuffer -flags +low_delay -analyzeduration 50 -probesize 50 -f h264 -i pipe: -c:v copy -movflags +empty_moov+default_base_moof+frag_keyframe -f tee -map 0:v [select=v:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/terrasse
2022/04/27 11:13:22 [Terrasse] WARNING: Skipping smaller frame at start of stream (frame_size=1)
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[h264 @ 0x25052e0] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 0x24f43a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (1920x1088), 20 tbr, 1200k tbn
**[tcp @ 0x2517a20] Starting connection attempt to 0.0.0.0 port 8554
[tcp @ 0x2517a20] Connection attempt to 0.0.0.0 port 8554 failed: Connection refused
[tcp @ 0x2517a20] Connection to tcp://0.0.0.0:8554?timeout=0 failed: Connection refused
[tee @ 0x2513ce0] Slave '[select=v:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/terrasse': error writing header: Connection refused
[tee @ 0x2513ce0] All tee outputs failed.**
Could not write header for output file #0 (incorrect codec parameters ?): Connection refused
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
[AVIOContext @ 0x2504cb0] Statistics: 98381 bytes read, 0 seeks
2022/04/27 11:13:23 [Haustüre] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 66%) FW: 4.61.0.3 (2/3)
2022/04/27 11:13:23 [Haustüre] [FFMPEG_CMD] ffmpeg -loglevel verbose -fflags +genpts+flush_packets+nobuffer -flags +low_delay -analyzeduration 50 -probesize 50 -f h264 -i pipe: -c:v copy -movflags +empty_moov+default_base_moof+frag_keyframe -f tee -map 0:v [select=v:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/haustüre
2022/04/27 11:13:23 [Haustüre] WARNING: Skipping smaller frame at start of stream (frame_size=1)
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[h264 @ 0x42492e0] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 0x42383a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (1920x1088), 20 tbr, 1200k tbn
[tcp @ 0x42573c0] Starting connection attempt to 0.0.0.0 port 8554
[tcp @ 0x42573c0] Connection attempt to 0.0.0.0 port 8554 failed: Connection refused
[tcp @ 0x42573c0] Connection to tcp://0.0.0.0:8554?timeout=0 failed: Connection refused
[tee @ 0x42585f0] Slave '[select=v:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/haustüre': error writing header: Connection refused
[tee @ 0x42585f0] All tee outputs failed.
Could not write header for output file #0 (incorrect codec parameters ?): Connection refused
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
[AVIOContext @ 0x4248cb0] Statistics: 110653 bytes read, 0 seeks
2022/04/27 11:13:24 [Terrasse] [Errno 32] Broken pipe
2022/04/27 11:13:24 [Haustüre] [Errno 32] Broken pipe
2022/04/27 11:13:24 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Haustüre on 192.168.178.47 (1/3)
2022/04/27 11:13:24 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - Terrasse on 192.168.178.45 (1/3)

**Comment by mrlt8** [comment]
I believe rtsp-simple-server doesn't like the special character in `Haustüre`, so we'll probably have to remove the `ü` when creating the uri for the stream.

**Comment by JochenKlenk** [comment]
yes hat was the issue. Just not thought complete server breaks. But fast fix.

**Comment by mrlt8** [comment]
Unfortunately, it's an issue in the upstream rtsp-simple-server which is beyond my control:

https://github.com/aler9/rtsp-simple-server/blob/b4649ef60b769ca9263c3579a50788d284a1a539/internal/conf/path.go#L30-L32
