### ISSUE TITLE
[audio] custom ffmpeg cmd converts to lowercase mac alphanumeric for /tmp/{cam.mac}.wav

### ISSUE THREAD

**Issue by bittles** [mrlt8/docker-wyze-bridge#358]
Audio branch working well for me with 3 cam v3s with default ffmpeg command, but can't use a custom one.  No variable for cam_mac means if I manually type in the mac for the *.wav the code from before to clean up any stray uppercases converts the mac down to lowercase.  Eg. /tmp/2CAA8EF65D1F.wav in the docker config converts to /tmp/2caa8ef65d1f.wav after startup.  At work now or I'd look at it more to see if adding a mac variable messes anything else up.

**Comment by mrlt8** [comment]
Thanks! Added `{mac}` as a variable.

**Comment by mrlt8** [comment]
Should be able to use `/tmp/{cam_name}.wav` or `{audio_in}` with the new updates.
