### ISSUE TITLE
On demand streaming from cameras

### ISSUE THREAD

**Issue by ofadam** [mrlt8/docker-wyze-bridge#36]
In an effort to not saturate limited Wi-Fi bandwidth, is there a way to trigger wyze-bridge to only pull from a camera on demand via any of the resulting URIs?

**Comment by mrlt8** [comment]
This is something I'd be interested in as well and rtsp-simple-server offers some options for on-demand publishing.

In the meantime, you could also try [reducing the bitrate](https://github.com/mrlt8/docker-wyze-bridge#bitrate-and-resolution).

**Comment by sl33nyc** [comment]
If this is a reasonable enhancement, then could this be applied to outdoor cameras (and therefore make #62 feasible)?

**Comment by GloriamSemper** [comment]
I will also require a feature to have only on-demand connections to the cameras, especially in HA. Wyze bridge is trying to connect to all 30 of my cameras and it fails in hilarious fashion while saturating my server resources. It manages to connect to about half of them for a few seconds each. Tried LAN only mode and lowering bitrate. Enabling on-demand connections to the cams for a snapshot or streaming would resolve this.

**Comment by mrlt8** [comment]
The current snapshot method requires an active rtsp connection, so I was really hoping the boa method could have allowed us to offload the snapshots and motion detection to the camera so we could pull images and alarms without an active video stream, however it seems like boa is missing from the newer firmware versions. 

I've been trying to get RDT working as aa replacement which is what I believe the wyze app is using to transfer the timelapse videos from the camera back to the app.

**Comment by GloriamSemper** [comment]
> The current snapshot method requires an active rtsp connection, so I was really hoping the boa method could have allowed us to offload the snapshots and motion detection to the camera so we could pull images and alarms without an active video stream, however it seems like boa is missing from the newer firmware versions.
> 
> I've been trying to get RDT working as aa replacement which is what I believe the wyze app is using to transfer the timelapse videos from the camera back to the app.

I greatly appreciate your work on this project and also your attention to this issue that prevents my usage of the bridge. Donation incoming.

While having a snapshot to use as a thumbnail is very useful, this seems to be the breaking feature for me. I 100% understand there is currently no way around establishing a full streaming connection to get that snapshot without BOA access. In the meantime, I'd gladly disable that feature for my HA plugin to stay with a "on-demand" stream until you're able to get RDT working. I'm using "SNAPSHOT: Disable" in my HA yaml config but it doesn't seem to stop the thumbnails snapshots from showing? Am I doing something wrong here or is ther just no way to stop that at this time?

Again, you're a friggin god for coding this bridge in the first place. It's the first practical solution to viewing any of the cams outside of the app IMO. Thank you.

**Comment by mrlt8** [comment]
I've started adding some basic support for on-demand streaming, but it does seem to take a couple of seconds for the bridge to connect to the camera and start the stream.
