### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by airbornetrooper82573** [mrlt8/docker-wyze-bridge#367]
I aded ENABLE_AUDIO=True in my env settings but I am still not getting any audio. 

Here are my env settings:

```
WYZE_EMAIL=myemail@gmail.com
WYZE_PASSWORD=******
FRESH_DATA=true
RTSP_LOGLEVEL=debug
DEBUG_FFMPEG=true
ENABLE_AUDIO=True
NET_MODE=P2P
RTSP_PATHS_ALL_READUSER=123
RTSP_PATHS_ALL_READPASS=asd
RTSP_READTIMEOUT=60s
RTSP_APIADDRESS=0.0.0.0:9997
RTSP_API=yes
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=C.UTF-8
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.10.4
PYTHON_PIP_VERSION=22.0.4
PYTHON_SETUPTOOLS_VERSION=58.1.0
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/38e54e5de07c66e875c11a1ebbdb938854625dd8/public/get-pip.py
PYTHON_GET_PIP_SHA256=e235c437e5c7d7524fbce3880ca39b917a73dc565e0c813465b7a7a329bb279a
PYTHONUNBUFFERED=1
RTSP_PROTOCOLS=tcp
SDK_KEY=*****
```

**Comment by mrlt8** [comment]
Is this with v1.4.1? do you see any errors in the log?

**Comment by airbornetrooper82573** [comment]
I use watchtower to keep up to date and I confirmed it is v1.4.1. The only errors I see looking at the log in portainer is 
 
```
[alaw @ 0x2f38920] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)

[tee @ 0x368e410] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```

**Comment by mrlt8** [comment]
Do you should see something like this when the camera connects?
```
[Driveway] 🔊 Audio Enabled - ALAW/16,000Hz
```

**Comment by airbornetrooper82573** [comment]
I’ll check again tomorrow but I did not see that. I have tried doing true and True.

**Comment by jtv7** [comment]
I have the same issue.  It was working ok when I was using the images from the `audio` branch (a few days ago), but now seems broken after switching to the `latest` image.

**Comment by mrlt8** [comment]
@jtv7 do you see the `Audio Enabled` message or is it just ignoring it?

**Comment by jtv7** [comment]
> 

I see` 🔊 Audio Enabled - ALAW/16,000Hz`

**Comment by mrlt8** [comment]
Do you get any audio in VLC? I made some changes so that ffmpeg uses `COPY` by default if the camera is using an RTSP compatible codec like alaw. You can force it to use AAC by adding:
```yaml
- AUDIO_CODEC=aac
```

**Comment by jtv7** [comment]
Thank you, that fixed it!  I am opening the stream in VLC and it works with the config option you mentioned: `-AUDIO_CODEC=aac`

**Comment by mrlt8** [comment]
Awesome! Since the audio is now getting re-encoded, you can [specify](https://github.com/mrlt8/docker-wyze-bridge#audio-filtering) custom audio filters to clean up the audio and/or boost it:
```yaml
 - AUDIO_FILTER=highpass=f=300,lowpass=f=2500,volume=5
```

**Comment by airbornetrooper82573** [comment]
I added the audio codec env and I'm still not getting any audio. Is there a better way to see the logs than through Portainer? It keeps scrolling on me and even searching for audio isn't really working for me.

**Comment by airbornetrooper82573** [comment]
I figured out the log by turning off auto-refresh logs. I've added the custom audio filter too and this is what I see for one of the camera. Still can't hear audio in HomeKit. I turned off silence mode on my iPhone and have volume cranked. Speaker icon doesn't show mute either.

```
2022/05/07 19:38:36 [Front Yard Cam] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 99%) FW: 4.36.9.131 🔒 (DTLS) (2/3)

2022/05/07 19:38:36 [Front Yard Cam] 🔊 Audio Enabled - ALAW/16,000Hz

2022/05/07 19:38:36 [Front Yard Cam] [FFMPEG_CMD] ffmpeg -loglevel verbose -fflags +genpts+flush_packets+nobuffer -flags low_delay -analyzeduration 50 -probesize 50 -f h264 -i pipe: -f alaw -ar 16000 -i /tmp/front-yard-cam.wav -c:v copy -c:a aac -filter:a afftdn=nt=w,highpass=50,lowpass=2500,volume=30 -movflags +empty_moov+default_base_moof+frag_keyframe -f tee -map 0:v -map 1:a -shortest [select=v,a:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/front-yard-cam
```

**Comment by mrlt8** [comment]
What camera is this? Can you hear any audio in another media player like VLC?

**Comment by airbornetrooper82573** [comment]
All my cameras are V3. I am getting audio on VLC

**Comment by mrlt8** [comment]
homebridge? Do you have `"audio": true`?

This is what I have in scrypted with 'no audio'  unchecked:
<img width="439" alt="scrypted" src="https://user-images.githubusercontent.com/67088095/167304129-8747863c-8f60-4e01-91d1-d653191a82fa.png">

**Comment by airbornetrooper82573** [comment]
I forgot about having it set to false when I first set it up. I changed it and restarted. I noticed there was an update so I applied it. Now when I click any of my cameras in HomeKit it just spins and eventually goes to No Response. It still takes the screen grab for my icon and still streams perfectly in VLC though... Here's my Homebridge settings

```
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Front Yard Cam",
                    "manufacturer": "Wyze",
                    "model": "WYZE_CAKP2JFUS",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://123:asd@172.16.1.48:8554/front-yard-cam",
                        "vcodec": "copy",
                        "audio": true,
                        "debug": true
                    }
                },
                {
                    "name": "Back Yard Cam",
                    "manufacturer": "Wyze",
                    "model": "WYZE_CAKP2JFUS",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://123:asd@172.16.1.48:8554/back-yard-cam",
                        "vcodec": "copy",
                        "audio": true,
                        "debug": true,
                        "debugReturn": false
                    }
                },
                {
                    "name": "Drive Way Cam",
                    "manufacturer": "Wyze ",
                    "model": "WYZE_CAKP2JFUS",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://123:asd@172.16.1.48:8554/drive-way-cam",
                        "vcodec": "copy",
                        "audio": true,
                        "debug": true
                    }
                }
```

**Comment by airbornetrooper82573** [comment]
Looks like I'll be moving my cameras over to Scrypted. Wasn't aware of the app but seems to handle cameras a hell of a lot better than Homebridge from 5 minutes of reading!

**Comment by airbornetrooper82573** [comment]
I am following your Scrypted setup via https://github.com/mrlt8/docker-wyze-bridge/wiki/HomeKit-Secure-Video but I left No Audio unchecked. I'm not seeing those options like you showed. I am using the RTSP Camera Plugin. Only thing I've added is the RTSP Stream URL for each of my 3 cameras and have No Audio unchecked. I'm not hearing audio in Scrypted.

**Comment by airbornetrooper82573** [comment]
Disregard, I access Scryted outside noVNC and saw the settings. I can hear audio now. Now I have to figure out how to add it to HomeKit.

**Comment by airbornetrooper82573** [comment]
Got Scrypted added to HomeKit! Wow, it loads much faster than using Homebridge FFMPEG plug-in. This can be marked resolved/closed!
