### ISSUE TITLE
RTSP not working with Scrypted

### ISSUE THREAD

**Issue by lunged** [mrlt8/docker-wyze-bridge#368]
I have a fresh, basic install. I can view the HLS stream in my browser fine, but can not get RTSP working with scrypted.
I also can't stream in VLC, so I am not sure if the issue is RTSP related or not.

Here is the log from Scrypted:

`[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: Camera did not report an audio codec, muting the audio stream and probing the codec.
[Rebroadcast Plugin]: rebroadcast mode: mpegts
rtsp stream url rtsp://192.168.1.XXX:8554/this-cam/
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -rtsp_transport tcp -i rtsp:[REDACTED] -vcodec copy -an -f mpegts pipe:3 -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:4
[Rebroadcast Plugin]: [tcp @ 0x55c00f8e00] Connection to tcp://192.168.1.XXX:8554?timeout=0 failed: Connection refused
[Rebroadcast Plugin]: rtsp://192.168.1.XXX:8554/this-cam/: Connection refused
[Rebroadcast Plugin]: rebroadcast parse error Error: stream ended during read for minimum 8 bytes
[Rebroadcast Plugin]:     at Socket.n (/common/src/read-stream.ts:27:20)
[Rebroadcast Plugin]:     at Socket.emit (node:events:539:35)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:475:12)
[Rebroadcast Plugin]:     at endReadableNT (node:internal/streams/readable:1345:12)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Rebroadcast Plugin]: rebroadcast error Error: killed
[Rebroadcast Plugin]:     at kill (/common/src/ffmpeg-rebroadcast.ts:138:34)
[Rebroadcast Plugin]:     at /common/src/ffmpeg-rebroadcast.ts:287:13
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Rebroadcast Plugin]: prebuffer session ended with error Error: ffmpeg was killed before connecting to the rebroadcast session
[Rebroadcast Plugin]:     at kill (/common/src/ffmpeg-rebroadcast.ts:143:31)
[Rebroadcast Plugin]:     at /common/src/ffmpeg-rebroadcast.ts:287:13
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: ffmpeg exited
`

**Comment by mrlt8** [comment]
Is this the command from the quick start? If so you'd need to publish the port for rtsp by adding `-p 8554:8554` somewhere to the command.

**Comment by lunged** [comment]
This is using docker-compose based on the sample, so I do have 8554:8554 in the ports section already.

**Comment by mrlt8** [comment]
I think you might have an extra forward slash at the end of your rtsp uri:

`rtsp://192.168.1.XXX:8554/this-cam/`

It should be:

`rtsp://192.168.1.XXX:8554/this-cam`

**Comment by lunged** [comment]
Thank you, I did.
However, after removing the trailing slash (rtsp://192.168.1.XXX:8554/this-cam), the results are the same.
VLC also still gives me an error trying to play the stream.

**Comment by lunged** [comment]
After making these changes (and adding ENABLE_AUDIO=True for good measure), I ran docker-compose up to see if there was any info there (peviousy using -d). And it started working.
Good ol' reboots. Thank you for the quick replies.

**Comment by wesbos** [comment]
I had this issue as well, but was missing the port mapping of 8554:8554 in docker. Not sure why that was missing
