### ISSUE TITLE
NameError: name 'uri' is not defined

### ISSUE THREAD

**Issue by JochenKlenk** [mrlt8/docker-wyze-bridge#375]
After Update to 1.4.2 I get follow error.

🎬 STARTING ALL 2 CAMERAS
Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 749, in <module>
    wb.run()
  File "/app/wyze_bridge.py", line 49, in run
    self.get_filtered_cams()
  File "/app/wyze_bridge.py", line 324, in get_filtered_cams
    mqtt_discovery(cam)
  File "/app/wyze_bridge.py", line 664, in mqtt_discovery
    "topic": f"wyzebridge/{uri}/image",
NameError: name 'uri' is not defined

The nam ein Wyze app is of course set. Also without special characters. It works before the update.

Thanks

**Comment by krysiswbk** [comment]
Same issue here

**Comment by mrlt8** [comment]
URI should be fixed in 1.4.3, but my cams are showing as unavailable.

Do we need to use "online/offline" for the availability_topic?

**Comment by krysiswbk** [comment]
Bridge is back online with 1.4.3. Cameras were unavailable at start including after restarting the add on. Rebooting HASS has brought configuration back to previous working state
