### ISSUE TITLE
Upgraded my Raspberry Pi400 from Buster to Bullseye... & Missing Icons

### ISSUE THREAD

**Issue by capncybo** [mrlt8/docker-wyze-bridge#376]
Would you happen to know which package(s) typically contain (What I'll call the "Wingdings") Icons...
After my Raspbian OS update & re-installation of docker, I'm only seeing Question Marks instead of the typical Icons.
It would sure help if I knew what (font/package) I was looking for??? 

Starting wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | ? STARTING DOCKER-WYZE-BRIDGE v1.4.3
wyze-bridge    | 
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ?? FORCED REFRESH - Ignoring local 'user' data
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ?? FORCED REFRESH - Ignoring local 'auth' data
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ?? Fetching 'auth' from the Wyze API...
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ? Saving 'auth' to local cache...
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ?? Fetching 'user' from the Wyze API...
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ? Saving 'user' to local cache...
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ?? FORCED REFRESH - Ignoring local 'cameras' data
wyze-bridge    | 2022/05/10 18:15:50 [WyzeBridge] ?? Fetching 'cameras' from the Wyze API...
wyze-bridge    | 2022/05/10 18:15:51 [WyzeBridge] ? Saving 'cameras' to local cache...
wyze-bridge    | 
wyze-bridge    | ? STARTING ALL 2 CAMERAS
wyze-bridge    | 2022/05/10 18:15:51 [WyzeBridge] Starting rtsp-simple-server v0.18.3
wyze-bridge    | 2022/05/10 18:15:51 [WyzeBridge] ? Connecting to WyzeCam V3 - Front Yard on 192.168.50.22 (1/3)
wyze-bridge    | 2022/05/10 18:15:51 [WyzeBridge] ? Connecting to WyzeCam V3 - Front Door on 192.168.50.21 (1/3)

**Comment by mrlt8** [comment]
The icons are just standard unicode emojis so maybe something like Google’s Noto or emojione?
