### ISSUE TITLE
New Log Error

### ISSUE THREAD

**Issue by cheme75** [mrlt8/docker-wyze-bridge#379]
I stopped bridge over night and see this at end after starting up next morning - seems like all is workin ok though.

[tee @ 0x55e58b891c00] All tee outputs failed.
av_interleaved_write_frame(): Broken pipe
[tee @ 0x5601d7aad9c0] All tee outputs failed.
av_interleaved_write_frame(): Broken pipe

**Comment by mrlt8** [comment]
Just leftovers from the previous logs showing that ffmpeg stopped.

**Comment by cheme75** [comment]
Oh. Ok. Thx!
