### ISSUE TITLE
Getting RTMP stream into frigate

### ISSUE THREAD

**Issue by mckochan** [mrlt8/docker-wyze-bridge#38]
I know this has more to do with Frigate, but figure I might get an answer here:
Has anyone been able to open the RTMP stream within frigate? I can get the RTSP stream working with default settings but can't get the RTMP stream working with either the default RTMP input_args settings or the Reolink settings here:
https://blakeblackshear.github.io/frigate/configuration/cameras/#reolink-410520-possibly-others

I am getting the following errors in Frigate:
frigate.video INFO : Driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : Driveway: ffmpeg process is not running. exiting capture thread...
ffmpeg.Driveway.detect ERROR : [tcp @ 0x5649bd46e540] Connection to tcp://192.168.1.3:1935 failed: No route to host
ffmpeg.Driveway.detect ERROR : [rtmp @ 0x5649bd46dc80] Cannot open connection tcp://192.168.1.3:1935
ffmpeg.Driveway.detect ERROR : rtmp://192.168.1.3:1935/driveway-cam: No route to host

I can open the RTMP stream directly in home assistant

**Comment by mrlt8** [comment]
I don't use frigate, but could you use the rtsp stream instead?

**Comment by mckochan** [comment]
I had thought it had to be RTMP to be able to stream through Frigate, but I think I am wrong on that, Will have to look at the ffprobe and ffmpeg args to figure out why it's not re-streaming the RTSP feed (still images work but stream does not in home assistant).
