### ISSUE TITLE
Unknown audio codec_id=137

### ISSUE THREAD

**Issue by mjb83** [mrlt8/docker-wyze-bridge#385]
2022/05/19 16:32:33 [WyzeBridge] 🎉 Connecting to WyzeCam Pan - baby room on xxx.xxx.x.xxx (1/3)
2022/05/19 16:32:36 [baby room] 
Unknown audio codec_id=137

Hoping this is a simple one. I haven't changed any setup, just started getting this error a few days ago. Anyone seen anything like this or know how to correct?

**Comment by mrlt8** [comment]
Weird how it just changed. Can you try the edge version to see if it fixes it? I believe `codec_id=137` should work with the `mulaw` audio codec.

**Comment by mjb83** [comment]
I spoke to my wife, apparently she applied an update to the can pan (by accident, didn't meant to click it). I guess that was the issue. The Edge build did pickup the mulaw audio codec with no issues tho:

2022/05/19 22:06:15 [baby room] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 73%) FW: x.x.x.x 🔒 (DTLS) (2/3)
2022/05/19 22:06:15 [baby room] 🔊 Audio Enabled - **MULAW**/8,000Hz
2022/05/19 22:06:17 [Front Door] 📡 Getting 120kb/s HD stream (15fps) via LAN mode (WiFi: 67%) FW: x.x.x.x (2/3)
2022/05/19 22:06:17 [Front Door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/05/19 22:06:17 [RTSP][BABY-ROOM] ✅ '/baby-room' stream is UP! (3/3)

**Comment by mrlt8** [comment]
Awesome! I guess wyze switched the audio codec on the Pan for some reason. Pushing this as a new release. Thanks for the heads up!

**Comment by mjb83** [comment]
Hello, I'm not sure if the update pushed properly to live it looks like for home assistant were stuck on 1.4.4. I just tried uninstalling and reinstalling and it's still at 1.4.4 even though the changelog shows 1.4.5? Perhaps I'm doing something wrong but I figured with the uninstall it should have updated to 1.4.5

**Comment by mrlt8** [comment]
Oops, looks like I forgot to bump the version number for Home Assistant.

Thanks for the catch!

**Comment by mjb83** [comment]
No worries. Got the update and switched back to live from edge build, so far so good!
