### ISSUE TITLE
Audio Stream Lagging 

### ISSUE THREAD

**Issue by AdiAbuAli** [mrlt8/docker-wyze-bridge#386]
Hi
Whenever I stream and enable Audio, most of the time stream lag, and/or disconnect, and take time (and sometime need to restart) to get the stream back.
attached are the logs (while DEBUG FFMPEG&FRAME and Debug FFMPEG Only), and while stream lag in descending timeline (different errors there) .

Despite this, will upgrade Debian to Bulleyes, and do apt update & apt upgrade in the code help?

[Debug.zip](https://github.com/mrlt8/docker-wyze-bridge/files/8749304/Debug.zip)

**Comment by mrlt8** [comment]
something strange with the back door cam. can you restart it manually to see if that helps?


> ... will upgrade Debian to Bulleyes, and do apt update & apt upgrade in the code help? ...
 
Are you running the bridge in a container or are you running the python scripts directly?

**Comment by AdiAbuAli** [comment]
I restarted it and will observe.
Am running in a docker container.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdiAbuAli** [comment]
I restarted back door camera, and didn't improve, then, I black listed that cam, and after almost one day, the stream got fine, later it lag again.
attached screenshot, represent the incoming traffic trend, that represent the high download rate when the stream is fine, and then drop when stream lag.
also attached the log, and below is my environment variable:
{
   "CapAdd" : [],
   "CapDrop" : [],
   "cmd" : "python3 /app/wyze_bridge.py",
   "cpu_priority" : 90,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enable_service_portal" : null,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "C.UTF-8"
      },
      {
         "key" : "GPG_KEY",
         "value" : "A035C8C19219BA821ECEA86B64E628F8D684696D"
      },
      {
         "key" : "PYTHON_VERSION",
         "value" : "3.10.4"
      },
      {
         "key" : "PYTHON_PIP_VERSION",
         "value" : "22.0.4"
      },
      {
         "key" : "PYTHON_SETUPTOOLS_VERSION",
         "value" : "58.1.0"
      },
      {
         "key" : "PYTHON_GET_PIP_URL",
         "value" : "https://github.com/pypa/get-pip/raw/38e54e5de07c66e875c11a1ebbdb938854625dd8/public/get-pip.py"
      },
      {
         "key" : "PYTHON_GET_PIP_SHA256",
         "value" : "e235c437e5c7d7524fbce3880ca39b917a73dc565e0c813465b7a7a329bb279a"
      },
      {
         "key" : "PYTHONUNBUFFERED",
         "value" : "1"
      },
      {
         "key" : "RTSP_PROTOCOLS",
         "value" : "tcp"
      },
      {
         "key" : "RTSP_READTIMEOUT",
         "value" : "20s"
      },
      {
         "key" : "RTSP_LOGLEVEL",
         "value" : "warn"
      },
      {
         "key" : "SDK_KEY",
         "value" : "AQAAADQA6XDOFkuqH88f65by3FGpOiz2Dm6VtmRcohNFh/rK6OII97hoGzIJJv/qRjS3EDx17r7hKtmDA/a6oBLGOTC5Gml7PgFGe26VYBaZqQF34BwIwAMQX7BGsONLW8cqQbdI5Nm560hm50N6cYfT2YpE9ctsv5vP5S49Q5gg864IauaY3NuO1e9ZVOvJyLcIJqJRy95r4fMkTAwXZiQuFDAb"
      },
      {
         "key" : "QUALITY",
         "value" : "HD120"
      },
      {
         "key" : "FRESH_DATA",
         "value" : "True"
      },
      {
         "key" : "WYZE_EMAIL",
         "value" : "XXXX@XXXX"
      },
      {
         "key" : "WYZE_PASSWORD",
         "value" : "XXXX"
      },
      {
         "key" : "TZ",
         "value" : "Asia/Amman"
      },
      {
         "key" : "FILTER_BLOCK",
         "value" : "True"
      },
      {
         "key" : "FILTER_NAMES",
         "value" : "Back Door"
      },
      {
         "key" : "ENABLE_AUDIO",
         "value" : "True"
      },
      {
         "key" : "DEBUG_FFMPEG",
         "value" : "True"
      }
   ],
   "exporting" : false,
   "id" : "1f348d1e9469f88710d1f0cc4ae31cd6124b45e907e8bf9a7252ac59db5dee40",
   "image" : "mrlt8/wyze-bridge:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 6442450944,
   "memory_limit_slider" : 6144,
   "name" : "latest",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8554,
         "host_port" : 8554,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : []
}
[latest.zip](https://github.com/mrlt8/docker-wyze-bridge/files/8755283/latest.zip)
![Screenshot_20220523-170950_Active Insight](https://user-images.githubusercontent.com/89463853/169840146-9a1ff0e6-40d8-431a-bb4b-a143907abc4c.jpg)

**Comment by AdiAbuAli** [comment]
Also I just upgraded Debian in the container to Bullseye, and did apt upgrade, and apt auto-remove, and will observe the performance.

**Comment by mrlt8** [comment]
The whole point of the containers is to standardize everything across installs. 

Upgrading random packages, let alone the entire distor, makes it extremely difficult to debug the problem. I'm sorry, but I won't be able to offer any support at this time.

**Comment by AdiAbuAli** [comment]
I can reset back again to default one as it was before 1 hour back

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdiAbuAli** [comment]
Thanks...issue resolved you can close this issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
