### ISSUE TITLE
Feature request: Periodic high quality stills

### ISSUE THREAD

**Issue by tensiondriven** [mrlt8/docker-wyze-bridge#395]
Hello,

I have a need go capture *high quality* jpgs from cameras periodically.   

Since the bridge produces a high quality still on startup, I imagine I could kill/restart to server periodically to force this, but I worry about timing out the Wyze API and it's generally a gruesome solution.

Ideally Docker-Wyze-bridge could provide a URL for each camera that would update live, even if it took 5-10 seconds to return.

Alternately, the RTSP Snapshot feature of periodically capturing a snapshot (with a user definable interval) would be ideal.

As another possible workaround, if the bridge could capture jpg files stored on SD card and sync them locally, or periodically sync the and serve only the most recent, then I could set up internal or time lapse capture on the Wyze app and use the bridge to get the hi-res data.

Currently it appears that there's no way to programmatically get a high quality image from the camera, which is a real shame.

If you happen to know if Wyze exposes an API for this, that would be slick too!

**Comment by mrlt8** [comment]
The problem with the higher quality API snapshots is that they're usually only pushed to the wyze server on a motion event, so even if we were to try to pull a newer images periodically, it is very likely we'd keep getting the same image until the camera pushes a new one. 

There is a potential solution that I've been working on for a while, which is to have the camera to take a high quality pre-compression snapshot on demand  to `/media/mmc/photo/YYYYMMDD/YYYYMMDD_HH_MM_SS.jpg`, then start the boa server on the camera so we can pull those images. 

One of the main problems is that I haven't been able to find a way to remove those files from the camera to prevent the SD card from filling up with all the snapshots.

**Comment by tensiondriven** [comment]
Totally amazing.  I'm having some trouble with the `/photo` endpoint when I have `ENABLE_BOA=true` in my docker-compose.yml, but I'm still poking around with it so maybe I missed something in the config.

I know that it's possible to *format* the card via the app; perhaps a possible solution/workaroud would be to periodically format the card, or format it after pulling each image?  Just thinking out loud.  Thanks again for the amazing, elegant app.  (Even the flask source code is delightfully simple, no needless complexity.  I love it!)

**Comment by mrlt8** [comment]
boa seems to be missing/disabled on recent versions of the firmware #478.

I am trying to use RDT from the TUTK library as an alternative, but have been stuck trying to authenticate with the cams.

**Comment by tensiondriven** [comment]
As far as I know, all of my cameras are still on stock.  I can likely check at some point in the future to confirm (writing on mobile now so can't repro)

If we know which firmware versions support boa, or can interrogate a camera to see if boa is working, two things would help me as a user.  A nice follow-on enhancement might be to either:

- Display camera capabilities in the Web UI, so people could easily see if/which of their camera support boa and why
- Display a log message when a camera starts up or when Bridge tries to use an unavailable feature showing capability information

Just wanted to pass that thought on as some possibly-low hanging fruit.

Also, I know it's probably out of scope and maybe not relevant, but the wyze_mini_hacks project enables some pretty nifty features like high(ish)-quality photo capture.  It probably wouldn't serve very many users for Wyze bridge to add support for cameras with wyze_mini_hacks installed, but again wanted to mention it in case you see a connection and get inspired.

**Comment by mrlt8** [comment]
Hovering/touching the **i** icon next to the camera name should display more info about each camera including the `boa_url` if available.

The logs should also spit out info when starting boa:
<img width="358" alt="boa_start" src="https://user-images.githubusercontent.com/67088095/182987052-52432b70-c76b-4537-b9f3-b48bbe451c63.png">

Taking the higher quality photos isn't really the issue right now.. It's getting them off the camera's SD card.
