### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by KyleStilkey** [mrlt8/docker-wyze-bridge#396]
Been trying to add this to my Home Assistant and each time I go to add a camera I keep getting a Unknown error occurred. I am unaware if I have missed a step somewhere or what but I can't seem to get this to work at all. I did limit it to just show the 1 camera as I have 4 cameras unplugged so the logs would just fill with reconnection attempts, that's the only additional change I have made besides installing and running this. Everything is left at default settings.

![image](https://user-images.githubusercontent.com/6766223/170557629-0b09e1a5-6e6b-4bca-a395-df376eb497d7.png)
![image](https://user-images.githubusercontent.com/6766223/170557660-f40bb0ed-af26-419c-a5a6-a9b818841322.png)

**Comment by cheme75** [comment]
I’m just guessing but don’t you have to select tcp transport?

**Comment by KyleStilkey** [comment]
It defaults to it, not sure if it's a UI thing or what but I never selected it since it's been like that for a bit.

**Comment by cheme75** [comment]
It was a guess since I’m pretty much lost!  I can’t even get lan only on the bridge to function. Normally some decent help here. Hang in or try Reddit.

**Comment by KyleStilkey** [comment]
> It was a guess since I’m pretty much lost! I can’t even get lan only on the bridge to function. Normally some decent help here. Hang in or try Reddit.

Oh for sure, only other thing I can think of is maybe something is wrong with the API as I notice on my HA it's reporting version 1.4.4 when 1.4.5 is listed and it's had the API updated. Not sure if it's just a numbering issue or maybe it the cause and it's not grabbing the latest version?

Just some thoughts, but I am sure someone will respond, as for Reddit is there a sub that works with this docker or is it just the Wyze one I should post to?

**Comment by cheme75** [comment]
I don’t use it often - r/homeassistant maybe - I don’t see a wyze bridge specific Reddit.

**Comment by KyleStilkey** [comment]
Ok sounds good, thanks! I will take a look if I don't get a response here for help and see what others might have to say. Appreciate it!

**Comment by KyleStilkey** [comment]
Figured it out, I changed my IP to my home assistant URL/IP worked out. I was adding it as my routers IP. Simple mistake but will close this and hope this might help anyone else out that makes this simple mistake.
