### ISSUE TITLE
MFA support for Wyze Account

### ISSUE THREAD

**Issue by PDXUser** [mrlt8/docker-wyze-bridge#398]
How do I add my token?

🚀 STARTING DOCKER-WYZE-BRIDGE v1.4.5
2022/05/27 21:41:40 [WyzeBridge] 🔍 Could not find local cache for 'user'
2022/05/27 21:41:40 [WyzeBridge] 🔍 Could not find local cache for 'auth'
2022/05/27 21:41:40 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/05/27 21:41:40 [WyzeBridge] 🔐 MFA Token Required
2022/05/27 21:41:40 [WyzeBridge] 📝 Add verification code to /tokens/mfa_token

I have my account set up with the MFA code.  Is there a specific environment variable I need to setup?

**Comment by mrlt8** [comment]
It depends on how you're running the bridge, but you'll most likely just need to echo the code to `/tokens/mfa_token` with something like:

```sh
docker exec -it wyze-bridge sh -c 'echo "123456" > /tokens/mfa_token'
```
See the readme for additional options: https://github.com/mrlt8/docker-wyze-bridge#multi-factor-authentication

**Comment by PDXUser** [comment]
Thanks!  I got it!  Closing the case!
