### ISSUE TITLE
need a way to reconnect

### ISSUE THREAD

**Issue by SomebodySysop** [mrlt8/docker-wyze-bridge#4]
When a camera disconnects from stream for any reason, the wyze-to-rtmp  (wyze-bridge) also disconnects and prints to screen the message "Reconnect".

How can we develop a method for the bridge to re-connect itself to the stream that disconnected?

**Comment by noelhibbard** [comment]
When it says Reconnect that is exactly what it is doing. It should eventually reconnect. I have my script running as a systemd service which is also setup as a watchdog so if the script crashes then systemd starts it back up. Mine setup has been rock solid. I can have a camera offline for an hour and when I plug it back in the stream picks right back up. camera.py (In the docker version) could be modified to relaunch the script if it were to terminate similar to how systemd does.

**Comment by SomebodySysop** [comment]
> When it says Reconnect that is exactly what it is doing. It should eventually reconnect. I have my script running as a systemd service which is also setup as a watchdog so if the script crashes then systemd starts it back up. Mine setup has been rock solid. I can have a camera offline for an hour and when I plug it back in the stream picks right back up. camera.py (In the docker version) could be modified to relaunch the script if it were to terminate similar to how systemd does.

mrlt8 says he has made the changes.  Going to try and update.

**Comment by mrlt8** [comment]
>.. I have my script running as a systemd service which is also setup as a watchdog so if the script crashes then systemd starts it back up. Mine setup has been rock solid. I can have a camera offline for an hour and when I plug it back in the stream picks right back up. ..

We could try creating a systemd service for each camera on startup and see if that could keep the cameras alive.

**Comment by noelhibbard** [comment]
> >.. I have my script running as a systemd service which is also setup as a watchdog so if the script crashes then systemd starts it back up. Mine setup has been rock solid. I can have a camera offline for an hour and when I plug it back in the stream picks right back up. ..
> 
> 
> 
> We could try creating a systemd service for each camera on startup and see if that could keep the cameras alive. 
> 
> 

That sounds doable. I guess at startup it could stop/disable all existing services and the "enable" all new services. I suspect it will take a different engine than python:3.8-slim though. I'd have to check but I assume that image doesn't have systemd.
