### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by sandersc242** [mrlt8/docker-wyze-bridge#40]
Im stuck trying to figure out MFA
in the logs I can see MFA is required, I set the key using the echo command but I'm unsure of how I add the key into /tokens/
Id assume I have to mount the volume but have no clue how

**Comment by mrlt8** [comment]
There seems to be a problem with the upstream wyze_sdk that is causing issues with MFA.

I've added a temporary patch in v0.5 that I'll be releasing soon!
