### ISSUE TITLE
Home Assistant add-on not loading all cameras

### ISSUE THREAD

**Issue by RickSanchezC136** [mrlt8/docker-wyze-bridge#406]
Hi. I setup my home assistant server, then added the Wyze bridge as an add-on.
It loaded my two cameras, great!
Then I added a third cam, and it didn't pick it up. I've rebooted the HA server, uninstalled and reinstalled the addon, but it still only pics up the first two cams.  When I run the docker script from the install page on my ubuntu test server however it connects to all three cameras fine.  Is there something I need to clear from my HA server for it to pickup my third cam, or is there something else going on?

EDIT: I removed and re-added one of the cameras that was being detected by the HA addon, but after re-adding the camera with a different name, the HA addon log show that it's trying to load the old camera name. It looks like somehow something is cached in the addon and it's not actually finding the current cameras. Is there some way to clear this cache?

**Comment by mrlt8** [comment]
You'll need to set FRESH_DATA to true in the settings for the add-on. This should ignore the local cache.

**Comment by RickSanchezC136** [comment]
You are the man, thank you that worked. 
This rstp bridge, genius. Thank you so much for making this.
