### ISSUE TITLE
Feature Request: Any CAM Rotation

### ISSUE THREAD

**Issue by cheme75** [mrlt8/docker-wyze-bridge#408]
The wyze DB cam rotation works far better and smother for me in this bridge than doing the rotation in scrypted. This DB stream pops open and looks great. The scrypted rotation is slow and blocky looking for quite some time. Would be nice to have options to rotate any cam in the bridge - maybe by name is best option- at least in my case, I only need one cam rotated. Most likely its the processing ability of the scrypted pc vs the bridge pc - but these are all I got available and they generally function ok otherwise.

**Comment by mrlt8** [comment]
Could probably add this. 

The problem with camera specific options is that is that it's a little tricky to support in Home Assistant because of the schema so I want to figure out a format that will be compatible with both.

In the meantime, you could probably do it with a custom ffmpeg command:
```yaml
FFMPEG_CMD_MY_CAM_NAME: ffmpeg -loglevel error -fflags +genpts+flush_packets+nobuffer -flags +low_delay -analyzeduration 50 -probesize 50 -f h264 -i - -c:v libx264 -filter:v transpose=1 -b:v 3000K -tune zerolatency -preset ultrafast -force_key_frames expr:gte(t,n_forced*2) -movflags +empty_moov+default_base_moof+frag_keyframe -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554/{cam_name}
```

**Comment by cheme75** [comment]
I’ll try the code in my yml to see if it works. I’m guessing it’s basically what you are doing in your code for the doorbell. 

As an “optional” env variable maybe? Then only those that require it will use it. There are many optional env variables I’m not using and everything is working fairly well. Possibly a ROTATE_CAM_NAME defaults to false so only those needing it, add it and set it to true. Again, I’m not familiar with coding so got no idea how to do it.

**Comment by mrlt8** [comment]
The problem is that each person has a multiple unique `_CAM_NAME`s so we'd have to specify each in the Home Assistant config, as a temporary solution, I think we'll try to use a dictionary in a list, but this may change as we try to standardize the config for v2.0.

Anyways, I added `ROTATE_CAM_{CAM_NAME}` to the dev branch if you want to try it out.

**Comment by cheme75** [comment]
Ya, not a coder. Not a HA user either. Got no idea the complexity involved. Anyway, sure, I’ll try the dev version - how do I specify in my yml?  I’m not sure I can got to it today but within a day or two I’ll have time.

**Comment by mrlt8** [comment]
something like:
```yaml
- ROTATE_CAM_PORCH=true
or
- ROTATE_CAM_MY_CAM=true
```

**Comment by cheme75** [comment]
Sorry - I got that part ok, it’s the dev branch I got no idea on how to specify?

**Comment by cheme75** [comment]
> something like:
> 
> ```yaml
> - ROTATE_CAM_PORCH=true
> or
> - ROTATE_CAM_MY_CAM=true
> ```

Sorry I didn’t specify - I got that part ok. 

What I don’t know is how do I specify the "dev" branch in yml file or pull command - I got no idea on how to get or load the dev version.

**Comment by mrlt8** [comment]
This should be in v1.5.0 now. 

FYI, you can switch by pulling the `mrlt8/wyze-bridge:dev` images instead of `:latest`.

**Comment by cheme75** [comment]
Getting error:
![C3BD16CE-758C-4954-B0F9-35B24E491D33](https://user-images.githubusercontent.com/16415255/172206029-9f4882c9-d1c6-4f43-848c-69077d1a0ee3.jpeg)

I had the rotate cam line added before actually pulling new image. So maybe it saw the “true” and found the “t” as reason for error. But I deleted that line from yml file and it continues to give me same error.

**Comment by cheme75** [comment]
Apparently something odd in yml - I had a line space before last comment. Anyway, removed old container, edited yml again and it’s up ok now. Will re-add to cam rotate now.

**Comment by cheme75** [comment]
Working well so will close, thanks!
