### ISSUE TITLE
Home Assistant Preview no longer works

### ISSUE THREAD

**Issue by cbrightly** [mrlt8/docker-wyze-bridge#410]
Sometime during the last update or two to either Home Assistant or this plugin, images from cameras no longer appear correctly on my dashboard or when clicking on (what should be) the snapshot on the dashboard to bring up the 'detailed' view modal window.

![image](https://user-images.githubusercontent.com/2245021/172239708-4c5543fc-940a-4e9b-8a46-41cb076dbbe4.jpeg)

![image](https://user-images.githubusercontent.com/2245021/172239871-5e589739-4322-4fec-bbb9-d46011076cb9.jpeg)

**Comment by vhsdream** [comment]
I am having the same issue. Running Home Assistant as a VM in Proxmox VE, as far as I know the stream worked before I updated.

The log now shows a bunch of data that looks like WebRTC data with access tokens and IDs (which is why it is blurred out), when before it would show that it was connecting to the camera.
![wyze-cam-log](https://user-images.githubusercontent.com/67816022/172272994-99d86dfe-5de3-4122-8d69-26b817e8075e.png)

Home Assistant log shows an error related to either a refused connection or invalid data.
![ha-log](https://user-images.githubusercontent.com/67816022/172273026-db2bbc16-9f57-4aa7-8d92-ce14e483d07c.png)

The RTSP server does not appear to be running or streaming anything.
![netstat](https://user-images.githubusercontent.com/67816022/172273308-7cd2e710-db93-4e22-88fb-4d1ba67c427a.png)

**Comment by cbrightly** [comment]
> I am having the same issue. Running Home Assistant as a VM in Proxmox VE, as far as I know the stream worked before I updated.
> 
> 
> 
> The log now shows a bunch of data that looks like WebRTC data with access tokens and IDs (which is why it is blurred out), when before it would show that it was connecting to the camera.
> 
> ![wyze-cam-log](https://user-images.githubusercontent.com/67816022/172272994-99d86dfe-5de3-4122-8d69-26b817e8075e.png)
> 
> 
> 
> Home Assistant log shows an error related to either a refused connection or invalid data.
> 
> ![ha-log](https://user-images.githubusercontent.com/67816022/172273026-db2bbc16-9f57-4aa7-8d92-ce14e483d07c.png)
> 
> 
> 
> The RTSP server does not appear to be running or streaming anything.
> 
> ![netstat](https://user-images.githubusercontent.com/67816022/172273308-7cd2e710-db93-4e22-88fb-4d1ba67c427a.png)
> 
> 
> 
> 

Try removing ```WEB_RTC: false``` from the YAML. It did the same thing to me until I removed mention of it entirely. Then, after removing and running the plug-in I was able to add it back marked false and it worked fine again. 

Still have a broken preview though…

**Comment by vhsdream** [comment]
Well, I updated to the very latest HA Core (that was just released - 2022.6.3), then removed the bridge, reinstalled the bridge, and I can say that the stream works again and for me the previews have come back.

I had messed around with the name of the camera entity in the past (I am using the ffmpeg integration) and that may have had something to do with it. Try completely starting over, perhaps the name of the entity has changed?

**Comment by mrlt8** [comment]
@vhsdream webrtc will just print out the credentials for the KVS stream, but won't do anything else at the moment.

@cbrightly Are the snapshots still getting saved?

**Comment by libby2cm** [comment]
Broke for me too after update.. same symptoms.

**Comment by mrlt8** [comment]
Is it just the preview or are the streams down as well?

**Comment by cbrightly** [comment]
> Is it just the preview or are the streams down as well?

The streams still work okay for me but any preview images normally shown inside of Home Assistant are broken.

**Comment by mrlt8** [comment]
If enabled, snapshots should be saved to `config/www`.

I'll try to replicate this issue in a VM.

**Comment by cbrightly** [comment]
> If enabled, snapshots should be saved to `config/www`.
> 
> 
> 
> I'll try to replicate this issue in a VM.

I do see images in config/www but they are all dated a few days ago (I assume they were pulled the last time the add-on was started)

**Comment by mrlt8** [comment]
Can you restart the bridge? I did noticed some 500 errors when the preview wasn't loading in ffmpeg camera, but was able to get them to come back after restarting the add-on.

**Comment by cbrightly** [comment]
> Can you restart the bridge? I did noticed some 500 errors when the preview wasn't loading in ffmpeg camera, but was able to get them to come back after restarting the add-on.

I have tried restarting the bridge and the HA host several times. The logs for the add-on aren't showing any errors, but the issue persists. I suppose I can try uninstalling and the. reinstalling the bridge, But since this change occurred independently of any other config changes aside from updates to Home Assistant and the bridge I thought it might be directly related. Thoughts?

**Comment by mrlt8** [comment]
Any errors in web inspector? I still see an occasional `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

I'm also seeing a couple of errors pop up now and then in the home assistant core logs:
```
WARNING (MainThread) [haffmpeg.tools] Timeout reading image.

and

ERROR (stream_worker) [homeassistant.components.stream.stream.camera.ffmpeg] Error from stream worker: Stream ended; no additional packets
```

Not sure what's causing it though..

**Comment by PracticalChip** [comment]
im having the same issue.

**Comment by mrlt8** [comment]
Is everyone using the ffmpeg platform in Home Assistant?

This should help speed up the snapshot and is what we use internally for the rtsp-based snapshots:
```yaml
camera:
  - platform: ffmpeg
    input: -threads 1 -analyzeduration 50 -probesize 50 -rtsp_transport tcp -i rtsp://127.0.0.1:8554/cam-name
```

**Comment by libby2cm** [comment]
Quick update on my issue.. since I only had 2 cameras, last night I removed the generic cameras, uninstalled the add-on, and deleted residual files from it from the config directory, then reinstalled the add-on and re-added the cams.. and things are back working again.  Maybe a session token was cached somewhere or something, but at any rate, folks may want to give that a try.  Previously in the log output, it would just show the session header for each device with a final line saying 'goodbye!', but after reinstalling, it's back to normal.  I re-used the same camera device names in HA when i reconfigured it, and I didn't have to re-configure my dashboards or anything, so the entities seemed to have remained intact.

**Comment by mrlt8** [comment]
v1.5.2 should fix the incorrect `WEBRTC` setting. 

@cbrightly do you see any errors related to the preview in http://homeassistant.local:8123/config/logs?

**Comment by cbrightly** [comment]
> v1.5.2 should fix the incorrect `WEBRTC` setting. 
> 
> 
> 
> @cbrightly do you see any errors related to the preview in http://homeassistant.local:8123/config/logs?

I don't see anything as far as errors or warnings in the logs for either HA Core or the add-on. Very strange.

**Comment by mrlt8** [comment]
hmm, I wonder if that's an mqtt issue since those images should get pushed and updated over mqtt with the image from the `SNAPSHOT` config.

As for the FFMPEG camera integration, I believe it's supposed to pull a new image every 10s but ffmpeg can sometimes take awhile.

**Comment by cbrightly** [comment]
> hmm, I wonder if that's an mqtt issue since those images should get pushed and updated over mqtt with the image from the `SNAPSHOT` config.
> 
> 
> 
> As for the FFMPEG camera integration, I believe it's supposed to pull a new image every 10s but ffmpeg can sometimes take awhile.


I do see the MQTT integration sending what should be image data, but it appears that HA isn't digesting it properly for whatever reason. Has anything changed with MQTT in the bridge in the past few updates?
