### ISSUE TITLE
FRESH DATA??

### ISSUE THREAD

**Issue by fbc** [mrlt8/docker-wyze-bridge#418]
I mapped my token directory to the local file system and I run watchtower and it upgrades and restarts my containers when it sees a newer version.

There must have been an update and a restart as when I looked into my logs all I see is this:
```
🚀 STARTING DOCKER-WYZE-BRIDGE v1.5.3

2022/06/13 20:32:52 [WyzeBridge] 📚 Using 'user' from local cache...
2022/06/13 20:32:52 [WyzeBridge] 📚 Using 'cameras' from local cache...

🎬 STARTING ALL 1 CAMERAS


========
Please use:
FRESH_DATA=true

or remove:
cameras.pickle
=======
```
I mapped my directory under the idea that I should not have to 2fa in the event of a restart. I assume that if I use FRESH_DATA that I would have to do that. I don't really know as I can't find any documentation surrounding FRESH_DATA=true.

**Comment by fbc** [comment]
Disreagard i just saw the note.. I will try fresh_data for that one time.. Thanks.

**Comment by mrlt8** [comment]
Another option would be to remove the file `cameras.pickle` from your tokens directory which should keep you logged in.
