### ISSUE TITLE
Possible to get an endpoint with all endpoints?

### ISSUE THREAD

**Issue by wesbos** [mrlt8/docker-wyze-bridge#421]
I'm going a bit loopy trying to reference my camera names, slugify them, and then come up with the URLs for RTSP and images.

Is it possible to just get an endpoint like /cams.json to dump all the info you know about them?

**Comment by mrlt8** [comment]
This should be coming soon. See #420

**Comment by dsheehan** [comment]
The web-ui http://localhost:5000/cameras has a json output you can parse

**Comment by wesbos** [comment]
awesome, looking forward to that!
