### ISSUE TITLE
HA Add-on crashes shortly after starting on v1.6.0

### ISSUE THREAD

**Issue by btehan** [mrlt8/docker-wyze-bridge#424]
I just upgraded from v1.5.4 to v1.6.0 and I'm seeing the following in the logs:

>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> Usage: flask run [OPTIONS]
> Try 'flask run --help' for help.
> Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

I've uninstalled the add-on and rebooted the host machine but it just keeps crashing after I start it.  Anything that I should try?

**Comment by dsheehan** [comment]
PR for fix is here: https://github.com/mrlt8/docker-wyze-bridge/pull/423
Workaround for users on 1.6.0, temporarily add to your docker compose environment:
- FLASK_APP=frontend

**Comment by btehan** [comment]
Thanks dsheehan.
Any workaround for the HA add-on?

**Comment by dsheehan** [comment]
Rollback and use 1.5.4, or however you set environment variables in HA.

**Comment by mrlt8** [comment]
Thanks @dsheehan!
Changes should be rolled out  in v1.6.1 once it builds and pushes the images.

**Comment by dsheehan** [comment]
@mrtl8 I'm not sure what's up. It's working for me when I build the local Dockerfile and run it locally.
But not with the docker pushed to docker hub.
I'm not sure if it's something multi-arch I don't know about.
Sorry 😭

**Comment by btehan** [comment]
Thanks for the quick turnaround dsheehan & mrlt8!

I updated to v1.6.1 but was getting the same log entries after starting it again.  So I tried reinstalling it and now I get the following log entries:

>  * Serving Flask app 'frontend' (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> 2022/06/16 00:18:46 [MainProcess] 🚀 STARTING DOCKER-WYZE-BRIDGE v1.6.1
> 2022/06/16 00:18:46 [MainProcess] 🏠 Home Assistant Mode
> Traceback (most recent call last):
>   File "/usr/local/bin/flask", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 988, in main
>     cli.main()
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 579, in main
>     return super().main(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 850, in run_command
>     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 299, in __init__
>     self._load_unlocked()
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 333, in _load_unlocked
>     self._app = rv = self.loader()
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 389, in load_app
>     app = locate_app(import_name, name)
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 251, in locate_app
>     return find_best_app(module)
>   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 77, in find_best_app
>     app = app_factory()
>   File "/app/frontend.py", line 19, in create_app
>     wb = WyzeBridge()
>   File "/app/wyze_bridge.py", line 30, in __init__
>     setup_hass(self.hass)
>   File "/app/wyze_bridge.py", line 760, in setup_hass
>     if not (cam_name := clean_name(cam.get("CAM_NAME", ""), True, True)):
> TypeError: clean_name() takes 1 positional argument but 3 were given

Thoughts?

**Comment by dsheehan** [comment]
Yep, that's another bug, line 760 needs to drop the ` , True, True`. 😭

**Comment by mrlt8** [comment]
will push a fix

**Comment by mrlt8** [comment]
Changes should be up and CAM_OPTIONS working! Thanks @dsheehan !

**Comment by dsheehan** [comment]
@btehan @mrlt8 hopefully that does it!
