### ISSUE TITLE
HLS Doorbell stream broken when using ROTATE_DOOR=True

### ISSUE THREAD

**Issue by jamescochran** [mrlt8/docker-wyze-bridge#428]
I'm running on unRAID
DOCKER-WYZE-BRIDGE v1.6.2

When I add the environment variable for rotating all doorbell cams the HLS stream no longer works. Other cameras seem unaffected. This also happened when I was just running this container through docker-compose so I don't think it's unique to unraid.

**Comment by mrlt8** [comment]
Will look into this. Any errors in the log when rotation is enabled?

**Comment by jamescochran** [comment]
Relevant entries I see are below. I don't see any errors at all just a couple warnings about smaller frame at startup for my cams:

2022/06/16 13:08:55 [MainProcess] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.1.222 (1/3)
2022/06/16 12:03:17 [Front Doorbell] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 62%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/16 12:03:17 [Front Doorbell] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/16 12:03:17 [Front Doorbell] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/16 13:08:59 [RTSP][FRONT-DOORBELL]  '/front-doorbell' stream is UP! (3/3)

**Comment by mrlt8** [comment]
Can confirm, something weird is going on with HLS when rotation is enabled.
RTSP stream is fine, but accessing `:8888/cam-name/` doesn't load and `:8888/cam-name/stream.m3u8` results in green video for me.
