### ISSUE TITLE
Website links broken

### ISSUE THREAD

**Issue by jamescochran** [mrlt8/docker-wyze-bridge#429]
DOCKER-WYZE-BRIDGE v1.6.2

I'm able to get to the webpage but all of the links point to "localhost" instead of the IP address of the server the container is running on.

**Comment by cbrightly** [comment]
My installation currently shows ```503: Service Unavailable``` when attempting to view the newly added webpage functionality.

**Comment by mrlt8** [comment]
This is a known issue. As a temporary solution, you can try setting your host ip/hostname using the env `DOMAIN=`.

**Comment by jamescochran** [comment]
That worked great. I didn't see it in the documentation but if I get some time maybe I'll try to do a pull request so at least people can know about this workaround if you want me to.

**Comment by dsheehan** [comment]
@jamescochran or just set WB_HLS_URL etc in your compose, for example I am running behind a reverse proxy for all my local site. Where externally it's on port 80, but in container it's still port 5000.
https://github.com/mrlt8/docker-wyze-bridge/blob/cb576d74e39d595b72fecc51d6887b1519b3b50a/app/wyze_bridge.py#L46
