### ISSUE TITLE
MFA No token provided

### ISSUE THREAD

**Issue by sandersc242** [mrlt8/docker-wyze-bridge#43]
Attempting to complete multi-factor authentication but no code is provided in the log
From what I understand it will provide a auth code that needs to be echo'd to tokens

Log:
2021/08/04 00:04:33 I [0/0] rtsp-simple-server v0.16.4
2021/08/04 00:04:33 I [0/0] [RTSP] TCP listener opened on :8554
2021/08/04 00:04:33 I [0/0] [RTMP] listener opened on :1935
2021/08/04 00:04:33 I [0/0] [HLS] listener opened on :8888
STARTING DOCKER-WYZE-BRIDGE v0.5.0
Could not find local cache for user
Could not find local cache for auth
Fetching auth from wyze api...
MFA Token Required
Add token to /tokens/mfa_token

Yaml:
version: '3.8'
services:
    wyze-bridge:
      container_name: wyzebridge
      restart: always
      # network_mode: host
      image: mrlt8/wyze-bridge:latest
      ports:
         - 1935:1935
         - 8554:8554
         - 8555:8555
     # build: 
     #     context: ./app
     #     dockerfile: Dockerfile.arm
      environment:
          - WYZE_EMAIL=*******
          - WYZE_PASSWORD=******
          - LAN_ONLY=True
          - RTSP_PROTOCOLS=tcp

**Comment by sandersc242** [comment]
I've gotten sms 2fa working however I and still unsure how to add the token to wyzebridge.
using "docker volume ls" -----I don't see a tokens volume to mount
using "docker-compose run wyzebridge echo "123456" > /opt/wyzecam/tokens/mfa_token"  ----- It returns No such file or directory

**Comment by mrlt8** [comment]
SMS verification? I'll need to take a second look and workout a fix!

paths have changed in recent versions, so you'll need to add your code to `/tokens/mfa_token`:
```
docker exec -it wyzebridge sh -c 'echo "123456" > /tokens/mfa_token'
```

**Comment by sandersc242** [comment]
> SMS verification? I'll need to take a second look and workout a fix!
> 
> paths have changed in recent versions, so you'll need to add your code to `/tokens/mfa_token`:
> 
> ```
> docker exec -it wyzebridge sh -c 'echo "123456" > /tokens/mfa_token'
> ```

Wyze api attempts to auth by sending a SMS text code. Using the echo path with an invalid token triggers Wyze api to send a code. Entering a correct code for some reason does the same, the logs say the valid code is invalid and attempts again sending a new code-- I'm stuck in a loop.

Using 123456 as token
Enter Wyze SMS 2FA Verification Code: The request to the Wyze API failed.
The server responded with: {'description': 'Invalid Verification Code.', 'requestId': '55f8c0d0-7804-4817-9d8e-1a8fa89e6e87', 'errorCode': 1000}
Please try again!
Using 424889 as token
Enter Wyze SMS 2FA Verification Code: The request to the Wyze API failed.
The server responded with: {'description': 'Invalid Verification Code.', 'requestId': 'ffd6318c-f2ac-4712-8fd1-c9bf60cc2d55', 'errorCode': 1000}
Please try again!

**Comment by mrlt8** [comment]
Should be fixed in the [dev branch](https://github.com/mrlt8/docker-wyze-bridge/tree/dev).
Could you give it try and let me know if it works?

**Comment by sandersc242** [comment]
Unsure how to pull the dev branch, but I did this-
`docker-compose pull && docker-compose up -d`
`docker exec -it wyzebridge sh -c 'echo 123456 > /tokens/mfa_token'` To trigger sms auth code
`docker logs wyzebridge`

`Enter Wyze SMS 2FA Verification Code: The request to the Wyze API failed.
The server responded with: {'description': 'Invalid Verification Code.', 'requestId': '674ee748-f3e4-4157-9c35-b79666b09806', 'errorCode': 1000}
Please try again!
Using 460210 as token
The user account has too many failed login attempts. Please wait a bit and try again.
The server responded with: {'description': 'Too many failed attempts. Please try again later.', 'requestId': 'f914d8bf-0bf4-4a9c-9b85-fc8d9cc69243', 'errorCode': 1000}
Please try again!`

**Comment by mrlt8** [comment]
I merged the dev into the main branch. 
Please let me know if it works!

**Comment by sandersc242** [comment]
> I merged the dev into the main branch.
> Please let me know if it works!

SUCCESS!!!, after pulling I received an auth code, entered with echo and now I have streams. Thank You!
