### ISSUE TITLE
V3 Camera stream becomes many minutes behind.

### ISSUE THREAD

**Issue by Xeddius** [mrlt8/docker-wyze-bridge#434]
I have noticed that upon enabling this feature one of my three camera streams is behind by over 6 minutes, while the other two are behind by only ~2 seconds. (in the wyze app it is behind by only 0.5s) I'm not sure what is going on but it's really frustrating. 

I had intended to use this to monitor my infant while he sleeps, and to see who is at my door, both of which require low latency.
Setting the Low Latency HLS value to true also has the effect of forcing https on all of the stream links (which breaks compatibility with quite a few programs.)

Does anyone have experience with this kind of issue? Without LLHLS enabled all of my streams are behind by about 20 seconds.

And before jumping to conclusions the stream itself is what is behind, I have tried every different player I could, Shinobi, Jellyfin, etc.

**Comment by mrlt8** [comment]
Unfortunately [LL-HLS requires encryption](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis) so there isn't much we can do about that.

Can you post more info on the cam that's 6 min behind? There was/is an FPS bug where some cameras will report the wrong FPS which was causing some cams to fall behind. 

I would suggest trying the RTSP stream and reducing the caching on the media player.

**Comment by Xeddius** [comment]
I just reverted back to 1.6.2 release and disabled LL-HLS, which does not seem to have fixed the issue now. It's a V3 Wyze Cam. I can append more info to this if you can give me a flag or commands I can use to print more information.

**Comment by mrlt8** [comment]
Does that v3 gradually fall behind or is it a constant delay, and does reloading the HLS page bring it closer to realtime?

Anything like `WARNING: FPS param mismatch (avRecv FPS=15)` in the logs? Some of the cams are a little buggy and may report the wrong FPS when switching from day/night mode #340

**Comment by Xeddius** [comment]
It gradually falls behind over time, thus far the HLS page always has the same delay as the other streams, when one is behind by eg 5 minutes they are all behind 5 minutes. It now shows "[###] WARNING: FPS param mismatch (avRecv FPS=15)", however it didn't display that last time I had checked the logs on previous runs.

**Comment by mrlt8** [comment]
Seems like the exact same issue we had with the doorbell. The bridge should continue using the FPS from the camera and ignore the wrong FPS.

Does setting the env `FIX_FPS` help?

**Comment by Xeddius** [comment]
After the latest update of the docker container it seems the issue has disappeared. The V3 camera has stayed in-sync now for almost 3 days straight, all cameras seem to be working. If this comes back I'll try `FIX_FPS` and report the results, for now we can consider this closed.

**Comment by paulcusick3** [comment]
I know this is closed - But I can confirm it is an issue with audio streams and not night vision.  I was experiencing same, did not have night vision.  Shut off audio and no more compounding delayed streams on V3s.  Where would I try FIX_FPS and turn audio back on??

**Comment by mrlt8** [comment]
In your docker-compose or docker command, but I don't think it will help if you only get the delay when audio is enabled.

Is this happening on multiple cameras? Can you post the firmware version they're on?

**Comment by paulcusick3** [comment]
It is one V3 only; other V3 does not.  Firmware is 4.363.9.139.  Shutting off audio three days, no compounding lag.  This camera is also on Cam+ (long story year free, will not renew).  I think it is tied to motion events.  The more events compound the delay.  Just an observation... not scientific.
