### ISSUE TITLE
Preview Not Available (WEB-UI)

### ISSUE THREAD

**Issue by dmkjr** [mrlt8/docker-wyze-bridge#437]
<img width="1486" alt="Screen Shot 2022-06-19 at 7 52 32 PM" src="https://user-images.githubusercontent.com/662675/174504972-3bdfde13-e40e-4490-93e3-1fad2c291acd.png">

All cameras are showing "Preview not Available", however the cameras are confirmed to be working correctly.

Frigate runs on 5000, so I changed to 5001:5000.  

Any ideas?

**Comment by mrlt8** [comment]
Try setting `SNAPSHOT=RTSP` in your docker-compose.yml

**Comment by dmkjr** [comment]
That worked!  How often does it update the snapshots this way?

**Comment by mrlt8** [comment]
`SNAPSHOT=RTSP` will capture a new image every 180 seconds.

You can tweak this by setting your own interval with something like `SNAPSHOT=RTSP30` or any number.

See https://github.com/mrlt8/docker-wyze-bridge#snapshotstill-images

**Comment by cheme75** [comment]
> Thanks. That worked. Any way we can filter out cameras in the interface as well? I have a Wyze Car on my account that I really don't want listed but I don't want to remove it from my Wyze account either.

I believe there is an env variable to set ignore offline to true. Check the read me or wiki.

**Comment by dmkjr** [comment]
I do filter on Frigate side, but it’s showing on the web Ui still.

**Comment by cheme75** [comment]
Not sure what frigate is. I’m using docker on win 10. I just set the env variables in my yml file. This way if ignores my offline cams.
