### ISSUE TITLE
Web-UI doesn't "currently" support remote access via local LAN or VPN

### ISSUE THREAD

**Issue by capncybo** [mrlt8/docker-wyze-bridge#438]
Just got around to (enabling/playing) with the Web-UI... Nice EXCEPT:
I couldn't help but notice the links embedded within the page all default to using "localhost"
If the links were changed to actually use the IP-Address or hostname of the (docker-wyze-brige) Web-UI Server...
The Web-UI would be accessible via: -local LAN & -VPN (tunnels)

**Comment by MapGuy11** [comment]
Yes, I noticed this too. It needs to be set to a variable from the request URL instead of a hardcode for localhost.

**Comment by mrlt8** [comment]
This is a known issue. See #429

**Comment by capncybo** [comment]
Sorry I missed seeing the DOMAIN=
Env Variable
thx
