### ISSUE TITLE
Ran without filter, filtered out cameras won't go awayin WebUI and HomeAssistant

### ISSUE THREAD

**Issue by MarkinBrisbane** [mrlt8/docker-wyze-bridge#439]
Hopefully the subject is meaningful!

I ran this for the first time and as I have elderly parents it pulled in their cameras as well (expected)

So I set up the filter command and the logs show that the filter is working however all cameras are still showing up in the "auto" home assistant view as well as the cool new Web-UI. (unexpected)

I have "removed" the plugin, deleted the folder and reinstalled with filter set correctly on first run which has not fixed this.

The log file in HA Addon/Docker Wyze Bridge does not show the filtered cameras in it.

**Comment by mrlt8** [comment]
The web-ui will list all the cameras on the account, but will not connect to them if they are filtered out.

Maybe we could add a filter on the web-ui to auto hide disabled cams?

**Comment by mrlt8** [comment]
I'm not familiar with HA auto view. Could you post some more info?

**Comment by MarkinBrisbane** [comment]
Home Assistant Lovelace "Auto" basically shows **every single configured entity**, tbh it is a bit of a mess *but* it does help you find things you otherwise can't.  See the image embedded below.
![image](https://user-images.githubusercontent.com/58591328/175214266-aa4d4428-8308-4975-9569-9258c551fc1d.png)

If you run HA, you should be able to see it by your HA URL:
http://homeassistant.local:8123/lovelace-auto

If that doesn't answer your question let me know which part you'd like more info on and I will do my best.

**Comment by mrlt8** [comment]
Got it! The bridge should be able to add an entity over MQTT if you have MQTT enabled, but not sure if add-on's can add entities directly to HA..?  I'll have to look into this.

You should be able to test the latest changes by using https://github.com/mrlt8/edge-repo and installing the edge build.

**Comment by MarkinBrisbane** [comment]
Bravo - this has been addressed really nicely and the fix is applicable to multiple use cases!
