### ISSUE TITLE
Feature Request: Auto Search and Add RTSP Cameras via rtsp-simple-server API

### ISSUE THREAD

**Issue by BeardedTek** [mrlt8/docker-wyze-bridge#441]
I've already begun work on a solution to automatically search for and add rtsp camera feeds and have a mostly working solution: [beardedtek/docker-wyze-bridge](https://github.com/beardedtek/docker-wyze-bridge/)

### CONFIGURATION:
The RTSP Scanner is configured via Environment Variables:
- RTSP_ADD_CAMERAS
  - boolean
  - default: "false"
- RTSP_VERBOSE
  - boolean
  - default: "false"
- RTSP_ADDRESS
  - Can either be a subnet in x.x.x.x/24 format or a single host.
  - default: "192.168.2.0/24"
- RTSP_PORTS
  - comma separated values
  - default: "554,8554"
- RTSP_CREDS
  - comma separated values.  either none or username:pass format
  - default: "admin:admin,none"))
- RTSP_PATHS
  - comma separated values.  must have a starting /
  - default: "/Streaming/Channels/101,/live"

It uses a slightly modified version of [Portscan](https://github.com/BeardedTek/PortScan) forked and PR submitted to [Aperocky/PortScan](https://github.com/Aperocky/PortScan) to:
### HOW IT FUNCTIONS:
1. scan ports defined in RTSP_PORTS
2. attempts to take a snapshot of the stream as defined by rtsp://<creds><host>:<port><path> on the hosts with open ports
3. If a snapshot is taken successfully, it then calls rtsp-simple-server's api to add a new path

### TODO:
1. Add a route to the flask app where we can initiate a scan, name the discovered cameras, and add then add them to rtsp-simple-server
2. More testing to make sure its stable

Any thoughts?

**Comment by BeardedTek** [comment]
As of right now, it is not integrated into the main app and functions as a standalone script inside the docker container.
To test without switching branches you can take the following steps:

### gain a shell inside the docker container:
```
docker-compose exec wyze-bridge
apt-get update && apt-get -y --no-install-recommends install wget
wget https://raw.githubusercontent.com/BeardedTek/docker-wyze-bridge/main/app/rtsp_cameras.py
wget https://raw.githubusercontent.com/BeardedTek/docker-wyze-bridge/main/app/portscan.py
```
### set your environment variables:
```
export RTSP_ADD_CAMERAS=true
export RTSP_VERBOSE=true
export RTSP_ADDRESS=<x.x.x.0/24>
export RTSP_PORTS=554,8554,...
export RTSP_CREDS=user:pass,none
export RTSP_PATHS=/live,/example
```
### execute the script
```
python
>>> from rtsp_cameras import AddRTSPCameras
>>> scan = AddRTSPCameras()
```

**Comment by BeardedTek** [comment]
Another round of hacking away at it...  I must admit, I have the goal of using docker-wyze-bridge in lieu of rtsp-simple server with my pet project [frigate Event Video Recorder](https://github.com/beardedtek-com/fevr) once this PR is merged.

## bugfixes:

#### can't start new thread
- kill off existing threads from Portscan after it finishes running
- allows us to run a scan multiple times without crashing the whole thing down...

## new features

#### ADD: RTSPCameras.delCameras()
- removes rtsp cameras from the path

#### ADD: RTSP_HOSTS
- comma separated ip addresses (1 or more)
- if set, it overrides RTSP_ADDRESS, only running checks and performing actions on the predefined ip addresses.

#### ADD: RTSP_CAMERAS_ENABLE and RTSPCameras.enable
- boolean (default: false)
- RTSPCameras is by default not allowed to execute unless given explicit permission.
- if set to true, it enables execution

#### ADD: RTSP_CAMERAS_ADD and RTSPCameras.addcameras
- boolean (default: false)
- by default we don't want to add cameras, just get the list of cameras for the UI.
- if set to true, it will add all discovered camera paths to rtsp-simple-server through its API

#### ADD: RTSP_CAMERAS_DEL and RTSPCameras.delcameras
- boolean (default: false)
- by default we don't want to delete cameras, just get the list of cameras for the UI.
- if set to true, it will remove all discovered camera paths from rtsp-simple-server through its API

#### ADD: RTSP_WHITESPACE and RTSPCameras.wspace
- string (default: -)
- replaces . and spaces in camera names (should probably make it anything but - or _. I'm sure slashes won't work so well.
- RTSPCameras.wspace sets the default and either can override it.

## Code Cleanup
- Cleaned up a bunch of code.

## Conclusion
This should be ready to interface with flask now. Next step will be writing a route for adding RTSP Cameras.

**Comment by mrlt8** [comment]
Thanks! Just an FYI, we may be able to access and control the RTSP server on the official rtsp firmware over the TUTK protocol.

**Comment by BeardedTek** [comment]
That is essentially what this is doing, leveraging rtsp-simple-server's api.  You can have it search for all on the network with your known credentials, or send it specific hosts to configure one by one.
The interface side I'm working on takes the data this spits out, puts up an snapshot of each camera and allows you to name it and start a path for that camera.  This may be valuable no matter what protocol you're using.

Just a quick question, what license are you using for this project?

**Comment by BeardedTek** [comment]
I'm currently using rtsp-simple-server for my lan where I have a mix of different cameras:
- 3 wyze v3
- Google Nest Hello
- 2 Merkury 1080p bullet cameras "rooted" and rtsp enabled
- Some ESP32 cameras as motion/presence sensors
- A web cam on a raspberry pi transmitting over rtsp
I really don't want to run separate docker containers for my rtsp cameras, my wyze cameras, and my google camera, which is my motivation behind the rtsp discovery.

If this is too far off your project's goal, I wouldn't mind having a fork, but continue to give back where I can to this project, while meeting my own goals as well.

**Comment by BeardedTek** [comment]
I'm going to close this as I've released RTSPScanner which can perform this functionality using rtsp-simple-server's API.

https://pypi.org/project/rtspscanner/

https://github.com/beardedtek-com/RTSPScanner

This allows you to add non-wyze RTSP cameras to docker-wyze-bridge's underlying instance of rtsp-simple-server.

Thanks for all the amazing work!
