### ISSUE TITLE
Blue Iris Issues...

### ISSUE THREAD

**Issue by StoneLegion** [mrlt8/docker-wyze-bridge#442]
I screwed up I use the compose .yml lol

**Comment by KaneHart** [comment]
Example of going via browser.. PS no firewalls, etc enabled...

![image](https://user-images.githubusercontent.com/425853/175109618-6ef34132-cf9d-4d3c-b60d-c74f6888e0ee.png)

**Comment by KaneHart** [comment]
Now here is the remote docker using the same settings working 100% just fine...

![image](https://user-images.githubusercontent.com/425853/175109843-26323b7d-b669-408c-b1a0-8aabc99a0eeb.png)


So strange my new one works in the browser fine but not blue iris with 100% the same settings... No errors in the docker all greenlights.

**Comment by KaneHart** [comment]
So I updated the latest version wiping my old one on the working server and now I have the same issue lol.. Have to figure how long ago / what version worked well lol...
