### ISSUE TITLE
Snapshot "on-demand" from home assistant

### ISSUE THREAD

**Issue by alasso** [mrlt8/docker-wyze-bridge#455]
Hi,

I need to take snapshots on-demand and in versión 1.6.6 there is an updated feature Web-UI: 
":5000/snapshot/cam-name.jpg - Always capture a new snapshot from the rtsp stream. This process may take a couple of seconds."

I tried this feature in my home assistant and it accept the request but does not respond with the image.

Any help will be appreciated
Adrian

**Comment by mrlt8** [comment]
Hmm, I'll have to look into this.

In the meantime, @dsheehan recently added links to the camera info popup in v1.6.9 (hover/click the `i` icon next to the camera name). The snapshot_url should give you the link to the updating snapshot.
<img width="432" alt="url" src="https://user-images.githubusercontent.com/67088095/176702314-40f06f11-ace4-43b1-aab5-f111a1beadc2.png">

**Comment by mrlt8** [comment]
Port 5000 should be available in Home Assistant starting with v1.6.10.
