### ISSUE TITLE
Setting grid columns to 5, produces more than 5 columns

### ISSUE THREAD

**Issue by dsheehan** [mrlt8/docker-wyze-bridge#458]
Precondition: Have more than 5 cameras.
Steps to reproduce: set columns to 5
Expected: grid has 5 columns
Actual: grid does not have 5 columns

![image](https://user-images.githubusercontent.com/71799191/176981850-5170cc2d-5f95-4e44-9564-4eb2d0f757a5.png)

**Comment by mrlt8** [comment]
Noticed this as well. I think `is-2.4` from 12/5 that breaks the css.  `is-one-fifth` seems to  fix it.
