### ISSUE TITLE
Web-UI image refreshing but showing

### ISSUE THREAD

**Issue by bbobrian** [mrlt8/docker-wyze-bridge#460]
wyze-bridge: v1.6.10
I can see the fetch requests happening in dev tools, but the updated image is not being displayed. I am guessing the browser is seeing the same file url being set and not considering it updated. I am seeing the same behavior in Chrome and Edge.

**Comment by mrlt8** [comment]
hmm, it's working for me in safari/chrome, but I do see the same issue in Firefox. 

The first reload from /img to /snapshot works, but it doesn't seem to update the image if the url is the same (i.e. /snapshot to /snapshot).

**Comment by bbobrian** [comment]
I stepped through and manually added '?' + Date.now() to the url and it seemed to work as a cache buster.

**Comment by mrlt8** [comment]
We're using the img src for update_img, so I'm not sure if that would break some of the other stuff..?
@dsheehan Could you take a look?

I wonder if setting the cache-control in the response header would help? `{"Cache-Control": "no-cache, no-store, must-revalidate" }`?

**Comment by dsheehan** [comment]
The current implementation was chosen to try and avoid cache busting. I wanted proper 304 Not Modified responses. Cache busting could waste a ton of bandwidth, so at the very least such an option needs to be on an feature flag to enable/disable.

**Comment by mrlt8** [comment]
Wouldn't bandwidth usage be the same since the images are being generated with each call to /snapshot?

**Comment by dsheehan** [comment]
> Wouldn't bandwidth usage be the same since the images are being generated with each call to /snapshot?

You're right, it should be okay to cache bust on /snapshot
