### ISSUE TITLE
WebUI link urls are homeassistant:port (not homeassistant.local:port)

### ISSUE THREAD

**Issue by r14n** [mrlt8/docker-wyze-bridge#465]
These URLs don't connect 

Is this a config issue on my part (I see nowhere to change this) or is there a bug?

**Comment by mrlt8** [comment]
The HA version is currently using the hostname provided by supervisor, and homeassistant:port should work with/without .local in most cases. However we could change it to use the hostname provided by flask like the standard docker version does.

**Comment by r14n** [comment]
Not sure what flask would provide, but if it gets it working for me that'd be awesome :)

**Comment by mrlt8** [comment]
This should be merged in the latest version.
