### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by Scags104** [mrlt8/docker-wyze-bridge#469]
Whole HA instance is themed dark, Love using your new UI but its very bright. 
Not high priority but would love a dark theme toggle. 

Thanks

**Comment by mrlt8** [comment]
Dark mode should now be available in v1.7.3.

**Comment by Scags104** [comment]
> Dark mode should now be available in v1.7.3.

Fantastic thank you! Looks great
