### ISSUE TITLE
Timed out connecting to Wyze Doorbell (Not Pro)

### ISSUE THREAD

**Issue by naitoshedo** [mrlt8/docker-wyze-bridge#471]
Latest version:
wyze-bridge    | 2022/07/12 03:20:15 [Front Doorbell] IOTC_ER_TIMEOUT
wyze-bridge    | 2022/07/12 03:20:17 [WyzeBridge] ⏰ Timed out connecting to Front Doorbell (20s).
wyze-bridge    | 2022/07/12 03:20:27 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front Doorbell on 192.168.1.110 (1/3)

Every other cam (v2 / v3) work fine.

Mobile app can see the Doorbell without issue.
Have forced a reconnect + reboot of all APs.

Only change was updating via:
docker-compose pull
docker-compose down
docker-compose up --force-recreate --build -d
docker image prune -f

**Comment by mrlt8** [comment]
Hmm. Are the tokens cached? Does setting `- FRESH_DATA=true` help?

**Comment by naitoshedo** [comment]
docker-compose.yml:

version: "2.4"
services:
  wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 5000:5000 # WebUI
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
        environment:
            - NET_MODE=LAN
            - LLHLS=true
            - ROTATE_DOOR=true
            - ENABLE_AUDIO=false
            - RTSP_READTIMEOUT=10s
            - FILTER_NAMES=Misc Cam
            - FILTER_BLOCK=true
            - FPS_FIX=true
            - FRESH_DATA=true
            - SNAPSHOT=RTSP
            - RTSP_PATHS_ALL_READUSER=watcher
            - RTSP_PATHS_ALL_READPASS=watcher
            - WYZE_EMAIL=email
            - WYZE_PASSWORD=password
        volumes:
            - ./tokens:/tokens/
            - ./img:/img/

The above used to work for the Doorbell + 2 Wyze Cams (v3).. Now it's just the v3 Cams. Doorbell is a no go.

**Comment by mrlt8** [comment]
Hmm, that is weird. Any chance you could power cycle the doorbell? 

I've noticed a couple of `IOTC_ER_TIMEOUT` on some of my local builds recently as well with random cameras, so this is something that may need to be investigated further.

**Comment by naitoshedo** [comment]
Yeah restarting the camera from in the app got it to work.

**Comment by mrlt8** [comment]
Awesome! 

I wonder if this might be caused by the bridge not closing the tutk session cleanly on exit? 

@dsheehan can flask pass the exit signal so we can do some cleanup before exit?

**Comment by dsheehan** [comment]
> @dsheehan can flask pass the exit signal so we can do some cleanup before exit?

Try registering an `@app.teardown_appcontext` 
https://flask.palletsprojects.com/en/2.1.x/api/#flask.Flask.teardown_appcontext

**Comment by cheme75** [comment]
FWIW, doorbell has been ok. Maybe off topic, I just added an old beta doorbell (I was a beta tester in 2020) that only live streams in the Wyze app. So far it’s looking ok in the bridge. It fails to get a snapshot at times and repeats, but overall it’s looking ok. Opencv in scrypted is now detecting motion on it which the Wyze app does not. Anyway no db connection issues.
