### ISSUE TITLE
Reverse proxy issues with HA integration

### ISSUE THREAD

**Issue by cmanville** [mrlt8/docker-wyze-bridge#473]
Hello and thank you for all the work that has been put into this project, the web ui was a welcome addition.

I am running wyze-bridge on Home Assistant with Home Assistant behind Nginx Proxy Manager hosted on Docker on a different VM. 
The Home Assistant interface runs on port 8123, which the reverse proxy makes available at "ha.domain.me", so the current way wyze-bridge tries to make the HLS camera streams available by adding port 8888 to it (ha.domain.me:8888/cam-name/) I believe effectively tries to find the stream at 192.168.1.50:8123:8888/cam-name/. 
To my knowledge this makes it impossible for me to play and launch the camera feed from the web interface. I've tried messing with the reverse proxy to somehow make this work, but this is either not possible or beyond my knowledge.

My preferred solution would be for wyze-bridge to be able to use the existing reverse proxy setup to share the camera streams. Would it be possible to make the HLS stream available at "ha.domain.me/7094bb28_docker-wyze-bridge/cam-name/" for example?

Alternatively, if I could manually dictate what domain the wyze-bridge uses (wyze.domain.me instead of using the Home Assistant one for example) I could add a new entry in the reverse proxy for this.

There is much I don't know and I would welcome any suggestions if this is the result of something I have misconfigured.

**Comment by mrlt8** [comment]
Not with the current HA config, but we do have an option to specify the URL the web-ui uses for all the streams in the standard installs. I've added `WB_HLS_URL` to the edge build on the [edge repo](https://github.com/mrlt8/edge-repo), so you could try specifying it there with something like: `http://wyze.domain.me:8888/`

**Comment by cmanville** [comment]
Thank you for the quick response!

I installed the Dev version from the edge repo in Home Assistant, copied my configuration and manually edited the yaml file to add "WB_HLS_URL: https://wyze.domain.me".

The DEV branch web interface still attempts to launch the HLS video stream at "https://ha.domain.me:8888/". Did I misunderstand something, or will I need to wait for a new Dev build before I can test this? (which is fine, I'm not in a hurry)

**Comment by mrlt8** [comment]
Could you try "Docker Wyze Bridge (Edge builds)" that one should have `WB_HLS_URL` enabled. 

Again, this will only change the links in the webUI, you'll still need to config nginx so that you can access the hls streams on `https://ha.domain.me/cam-name`

**Comment by cmanville** [comment]
I added the "edge-repo" to Home Assistant and it's listed as "docker-wyze-bridge-edge" in the Store. This source provides:
- Docker Wyze Bridge (DEV branch)
- Docker Wyze Bridge (nightly branch)
- Docker Wyze Bridge (Previous builds)

Of those I have the DEV branch installed because Edge is not listed as an option. Please let me know where I went wrong if this is not correct.
I also confirmed that the reverse proxy is configured correctly by viewing the camera stream at https://wyze.domain.me/cam-name/

Thank you :-)

**Comment by mrlt8** [comment]
Whoops, had an extra comma in the json! The edge version should show up now.

**Comment by cmanville** [comment]
Great! I was a bit impatient and it wasn't immediately showing up so I removed and added the repo again.
Once I got the Edge build installed (and realized that the url needed to end with a slash) it started working just as I had expected.
Thank you very much for being so responsive and willing to make this work for my configuration!

**Comment by mrlt8** [comment]
Awesome, I'll merge the change into the next official release!

**Comment by mrlt8** [comment]
This should now be available in v1.7.3.

**Comment by pgross41** [comment]
I'm also having issues accessing via my reverse proxy, I'm not sure if the custom URL can solve it or not. I can view the HLS stream in the web-UI if I am on my LAN and use the local IP of home assistant. If I try to access via the internet though I get the following in the console: 

> Mixed Content: The page at 'https://mycustomhassurl.com/7094bb28_docker-wyze-bridge/dashboard' was loaded over HTTPS, but requested an insecure resource 'http://mycustomhassurl.com:8888/my-cam/'. This request has been blocked; the content must be served over HTTPS.

My Nginx proxy is only handling 443 so I tried also forwarding 8888 on the router. That makes that 8888 URL work if I load it in an incognito tab but it doesn't address the issue of being insecure. Is there a way to expose the streams through HA so that it requires auth and is secure?

**Comment by mrlt8** [comment]
You could try enabling `LLHLS=True` or `RTSP_HLSENCRYPTION=yes` to force the https.

No auth at the moment, but you can probably do something in [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) which is what we use underneath to serve the streams.

**Comment by pgross41** [comment]
`LLHLS=True` did make it use https 👍

I was also able to configure basic auth by setting rtsp-simple-server config `paths_all_readuser` and `paths_all_readpass` 👍 
(PS there is a typo [here](https://github.com/mrlt8/docker-wyze-bridge/wiki/Home-Assistant#rtsp-simple-server) it says `readusers` with an `s`)

It still won't load in the UI because it doesn't trust the cert but I can open the link directly and accept the untrusted certificate. This is the error: 
![image](https://user-images.githubusercontent.com/11710621/181168189-812b3d53-9adc-4a91-8d37-575fdc7d3c02.png)
Do I trust the wyze-bridge certificate authority???

Thanks for all the great work on this tool by the way! I see updates available all the time, it's really good stuff!

**Comment by mrlt8** [comment]
Fixed.
The bridge will generate a random certificate, but you can specify the path to your own using `RTSP_HLSSERVERKEY` and `RTSP_HLSSERVERCERT`.

**Comment by pgross41** [comment]
I know this is closed but I finally got around to setting the cert paths and I get the following error: 
```
ERR open /ssl/fullchain.pem: no such file or directory
```

but I can confirm those files are there and are used by other add-ons:
![image](https://user-images.githubusercontent.com/11710621/185236094-a5864ecf-c4f6-4381-9483-664df5cc5d5d.png)

**Comment by mrlt8** [comment]
You may need to volume mount the certificate so that the container can access it?

```yaml
    volumes:
      - /ssl:/ssl
```

**Comment by pgross41** [comment]
That makes sense but I don't think I have access to do that via the HA add-on

**Comment by mrlt8** [comment]
We could try to map the `/ssl/` in the config.
Could you see if the dev build in the [edge-repo](https://github.com/mrlt8/edge-repo) works?

**Comment by pgross41** [comment]
Success! Using the edge repo I have secure access to the streams with the following config: 

UI checkbox: `LLHLS`

rtsp-simple-server config:
```
rtsp_hlsencryption=yes
rtsp_hlsserverkey=/ssl/privkey.pem
rtsp_hlsservercert=/ssl/fullchain.pem
```

Thank you for the swift and helpful responses, this add-on is a work of art

**Comment by mrlt8** [comment]
Should be merged into the main branch now. 
Also added some logic to check if key/cert are in the `/ssl/` dir, so it should automatically use them if available when LLHLS is enabled.
