### ISSUE TITLE
rtsp-simple-server Authentication

### ISSUE THREAD

**Issue by RUHavingFun** [mrlt8/docker-wyze-bridge#48]
I wanted to make my RTSP require authentication.  I tried what I though I understood from the section, but it does nothing.  Also, I do not see rtsp-simple-server when I run [docker container stats].  Not sure what I am doing wrong.

I tried both:

            - RTSP_PUBLISHUSER=***
            - RTSP_PUBLISHPASS=***
and

            - RTSP_READUSER=***
            - RTSP_READPASS=***

with variations of '=', '=:', and ':'

**Comment by mrlt8** [comment]
I believe you are missing the path parameters.
Have you tried something like:
```yaml
- RTSP_PATHS_ALL_PUBLISHUSER=***
- RTSP_PATHS_ALL_PUBLISHPASS=***
```
FYI, you'll probably need to specify a custom ffmpeg command to authenticate:
```yaml
- FFMPEG_CMD=-f h264 -i - -vcodec copy -f rtsp rtsp://***:***@0.0.0.0:8554/
```

**Comment by RUHavingFun** [comment]
Thanks for the info on how to do the proper path syntax.  Makes sense once I see.

So was looking for how to make it so that when I connect via a tool like VLC on my PC I would have to enter a user & pass too.  I made the path changes but it did not seem to matter.  I have not had time to give it a good try yet though.  I am not looking to restrict to just my docker container.

**Comment by mrlt8** [comment]
This works for me
```yaml
- RTSP_PATHS_ALL_READUSER=123
- RTSP_PATHS_ALL_READPASS=asd
```

**Comment by RUHavingFun** [comment]
Thanks!  I forgot to respond and let you know this works perfectly for me.  I am not sure, but I must not have tested with just "=" properly originally.
