### ISSUE TITLE
Video Stream not reliable on 1.7.3

### ISSUE THREAD

**Issue by exiva** [mrlt8/docker-wyze-bridge#480]
The video streams aren't reliable on 1.7.3, i think they aren't reconnecting when going down. I rolled back to `mrlt8/wyze-bridge:1.7.2` and things seem to be properly working again.

**Comment by mrlt8** [comment]
Thanks for the heads up! Will look into this.

**Comment by exiva** [comment]
If you need some testing, let me know. 👍

**Comment by mrlt8** [comment]
I'm not seeing any unusual connection issues on v1.7.3. Could you try running it again to see if the issues are still there?
Most of the changes were related to the web-ui and some cleanup stuff when the bridge is stopped which aren't called till a stop signal is received.

**Comment by exiva** [comment]
Maybe just coincidence. I switched back to latest, will monitor.
