### ISSUE TITLE
Rotate just one camera?

### ISSUE THREAD

**Issue by debsahu** [mrlt8/docker-wyze-bridge#49]
I see the option to edit ffmpeg, but is there a way to rotate the doorbell camera by 90°? From reading the documentation editing ffmpeg will change all cameras.

**Comment by mrlt8** [comment]
Not supported at the moment, but I'll be pushing an update soon!

**Comment by mrlt8** [comment]
v.0.5.2 should now support camera-specific ffmpeg commands:

You might be able to use something like this, but keep in mind this will be re-encoding rather than copying the existing raw h264 stream:
```yaml
- FFMPEG_CMD_FRONT_DOOR=ffmpeg -f h264 -i - -vcodec libx264 -vf transpose=2 -f rtsp rtsp://0.0.0.0:8554/
```

**Comment by debsahu** [comment]
Thank you!
