### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by tammeryousef1006** [mrlt8/docker-wyze-bridge#496]
Many thanks for the great work , is it possible to make the stream run with webrtc

**Comment by mrlt8** [comment]
The bridge has the ability to pull and display the web socket credentials for the webrtc stream direct from the camera if you enable the `WEBRTC=True` env option.

I'm open to any suggestions on how we might be able to integrate that into the bridge/webui.

**Comment by tammeryousef1006** [comment]
thanks for quick reply

i found this docker  ( nibrev/ant-media-server:latest ) on google search
and install to try , but i get this error Please write a valid stream URL
can you help please with the credentials ( name , stream url , stream ID )
i did try them from the printed out after enable webrtc= true , but still
give the error Please write a valid stream URL
