### ISSUE TITLE
Connection issues after 1.8.0 update

### ISSUE THREAD

**Issue by tremfranz** [mrlt8/docker-wyze-bridge#501]
Lost connection to my Wyze video doorbell after 1.8.0 update. Rollback to 1.7.5 solved the issue.

**Comment by mrlt8** [comment]
Could you post some logs from around the time you were having issues?

**Comment by tremfranz** [comment]
Tried to update to 1.8.1 again, same issue:

2022/08/08 22:09:46 [Front door] WARNING: Audio pipe closed
2022/08/08 22:09:46 [Front door] Stream is down.
2022/08/08 22:09:47 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:09:47 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:10:08 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:08] "GET / HTTP/1.1" 200 -
2022/08/08 22:10:08 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:08] "GET /static/site.css HTTP/1.1" 304 -
2022/08/08 22:10:08 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:08] "GET /static/site.js HTTP/1.1" 304 -
2022/08/08 22:10:08 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:08] "GET /img/front-door.jpg HTTP/1.1" 304 -
2022/08/08 22:10:08 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:08] "GET /img/front-door.jpg HTTP/1.1" 304 -
2022/08/08 22:10:08 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:08] "GET /img/front-door.jpg HTTP/1.1" 304 -
2022/08/08 22:10:11 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:10:11] "GET /events/start/front-door HTTP/0.9" 200 -
2022/08/08 22:10:14 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 50%) FW: 4.25.0.267 (2/3)
2022/08/08 22:10:14 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/08/08 22:10:14 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/08/08 22:10:17 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
Output file #0 does not contain any stream
2022/08/08 22:10:17 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:17] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 200 -
2022/08/08 22:10:19 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:19] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 200 -
2022/08/08 22:10:24 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/08/08 22:10:31 [WyzeBridge] Stopping on-demand
2022/08/08 22:10:31 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/08/08 22:10:31 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/08/08 22:10:31 [Front door] WARNING: Audio pipe closed
2022/08/08 22:10:31 [Front door] Stream is down.
2022/08/08 22:10:32 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:10:32 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:10:39 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:10:39] "GET /events/start/front-door HTTP/0.9" 200 -
2022/08/08 22:10:41 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 55%) FW: 4.25.0.267 (2/3)
2022/08/08 22:10:41 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/08/08 22:10:41 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/08/08 22:10:45 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
Output file #0 does not contain any stream
2022/08/08 22:10:45 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:45] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 304 -
2022/08/08 22:10:47 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:10:47] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 200 -
2022/08/08 22:11:00 [WyzeBridge] Stopping on-demand
2022/08/08 22:11:00 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/08/08 22:11:00 [Front door] WARNING: Audio pipe closed
2022/08/08 22:11:00 [Front door] Stream is down.
2022/08/08 22:11:01 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:11:01 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:11:09 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:11:09] "GET /events/start/front-door HTTP/0.9" 200 -
2022/08/08 22:11:12 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 56%) FW: 4.25.0.267 (2/3)
2022/08/08 22:11:12 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/08/08 22:11:13 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/08/08 22:11:17 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
Output file #0 does not contain any stream
2022/08/08 22:11:17 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:11:17] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 304 -
2022/08/08 22:11:19 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:11:19] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 200 -
2022/08/08 22:11:30 [WyzeBridge] Stopping on-demand
2022/08/08 22:11:30 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/08/08 22:11:30 [Front door] WARNING: Audio pipe closed
2022/08/08 22:11:30 [Front door] Stream is down.
2022/08/08 22:11:31 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:11:31 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:11:31 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:11:31] "GET /events/start/front-door HTTP/0.9" 200 -
2022/08/08 22:11:33 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 56%) FW: 4.25.0.267 (2/3)
2022/08/08 22:11:33 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/08/08 22:11:33 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/08/08 22:11:37 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
Output file #0 does not contain any stream
2022/08/08 22:11:37 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:11:37] "GET /snapshot/front-door.jpg?1660011094967= HTTP/1.1" 200 -
2022/08/08 22:11:39 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:11:39] "GET /snapshot/front-door.jpg?1660011094967= HTTP/1.1" 200 -
2022/08/08 22:11:39 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:11:39] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 200 -
2022/08/08 22:11:41 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:11:41] "GET /snapshot/front-door.jpg?1660011012369= HTTP/1.1" 200 -
2022/08/08 22:11:52 [WyzeBridge] Stopping on-demand
2022/08/08 22:11:52 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/08/08 22:11:52 [Front door] WARNING: Audio pipe closed
2022/08/08 22:11:52 [Front door] Stream is down.
2022/08/08 22:11:53 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:11:53 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:12:09 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:12:09] "GET /events/start/front-door HTTP/0.9" 200 -
2022/08/08 22:12:11 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 53%) FW: 4.25.0.267 (2/3)
2022/08/08 22:12:11 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/08/08 22:12:11 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/08/08 22:12:15 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
Output file #0 does not contain any stream
2022/08/08 22:12:15 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:12:15] "GET /snapshot/front-door.jpg?1660011094967= HTTP/1.1" 200 -
2022/08/08 22:12:17 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:12:17] "GET /snapshot/front-door.jpg?1660011094967= HTTP/1.1" 200 -
2022/08/08 22:12:29 [WyzeBridge] Stopping on-demand
2022/08/08 22:12:29 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/08/08 22:12:29 [Front door] WARNING: Audio pipe closed
2022/08/08 22:12:30 [Front door] Stream is down.
2022/08/08 22:12:30 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:12:30 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:12:38 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:12:38] "GET /events/start/front-door HTTP/0.9" 200 -
2022/08/08 22:12:40 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 55%) FW: 4.25.0.267 (2/3)
2022/08/08 22:12:40 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/08/08 22:12:41 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/08/08 22:12:45 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
Output file #0 does not contain any stream
2022/08/08 22:12:45 [WyzeBridge] 172.30.32.2 - - [08/Aug/2022 22:12:45] "GET /snapshot/front-door.jpg?1660011094967= HTTP/1.1" 304 -
2022/08/08 22:12:49 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/08/08 22:12:59 [WyzeBridge] Stopping on-demand
2022/08/08 22:12:59 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/08/08 22:12:59 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/08/08 22:12:59 [Front door] WARNING: Audio pipe closed
2022/08/08 22:13:00 [Front door] Stream is down.
2022/08/08 22:13:00 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 10.0.0.64 (1/3)
2022/08/08 22:13:00 [Front door] ⌛️ Waiting for on-demand connection...
2022/08/08 22:14:19 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 22:14:19] "GET /events/start/front-door HTTP/0.9" 200 -

**Comment by mrlt8** [comment]
Thank you! I can replicate the issue.
