### ISSUE TITLE
code 400, message Bad request version

### ISSUE THREAD

**Issue by z062007vette** [mrlt8/docker-wyze-bridge#507]
This might be related to issue #501, but this is what starts a "Timed out connecting to Front door (20s)." every second. I'm using Docker on Synology to link to Synology Surveillance Station. I did a fresh pull with only the needed settings I use. Logs attached. Not sure what other information you need to debug. 
[mrlt8-wyze-bridge1.csv](https://github.com/mrlt8/docker-wyze-bridge/files/9332451/mrlt8-wyze-bridge1.csv)

**Comment by mrlt8** [comment]
The timeout issue should be fixed in v1.8.3

**Comment by z062007vette** [comment]
That seems to have done it! It auto updated around 2 am and has been stable since. Thank you very much!
