### ISSUE TITLE
Driveway camera has stopped working

### ISSUE THREAD

**Issue by drock1985** [mrlt8/docker-wyze-bridge#508]
Hi,

I have the bridge setup with 4 Wyzecams (3-V3, 1-V1Pan) and was working fine for around 24 hours until the Driveway cam stopped responding in Frigate and can no longer connect. When looking at the console for wyze-cam-bridge this is showing up:

```
2022/08/16 18:21:54 [Driveway] IOTC_ER_TIMEOUT
2022/08/16 18:21:56 [WyzeBridge] ⏰ Timed out connecting to driveway (20s).
2022/08/16 18:22:06 [WyzeBridge] 🎉 Connecting to WyzeCam V3 - driveway on 192.168.1.19 (1/3)
2022/08/16 18:22:22 [LivingRoom] WARNING: Frame not available yet
2022/08/16 18:22:26 [Driveway] IOTC_ER_TIMEOUT
```

So far I have tried rebooting the camera, the bridge, and my router but nothing seems to be working. The other three cameras work fine with no issues. What could I be missing?

-Cheers,

**Comment by exiva** [comment]
I had issues with my doorbell this morning, i had to run `docker images`, and then `docker rmi [image id]` to remove the image and start over. Seems the cache or tokens got fucked up or something. Perhaps add a purge token/cache/data button in the ui @mrlt8 ?

**Comment by drock1985** [comment]
> 

That seems to have done the trick. Thanks for the help. Here's hoping the issue goes away on its own. 

-Cheers,

**Comment by mrlt8** [comment]
It seems like the bridge is able to connect to the camera, but gets stuck waiting for the camera to return a frame, so I don't _think_ it's a token issue or it would fail at the auth part.

Is this with the latest v3 firmware?

**Comment by drock1985** [comment]
> It seems like the bridge is able to connect to the camera, but gets stuck waiting for the camera to return a frame, so I don't _think_ it's a token issue or it would fail at the auth part.
> 
> Is this with the latest v3 firmware?

Sorry I didn't see the reply earlier. Yes; all cameras are running the latest available firmwares. 

I see there is an update to the bridge; i'll re-download the container and see how things go. Thanks.
