### ISSUE TITLE
Updating GUI ports

### ISSUE THREAD

**Issue by tammeryousef1006** [mrlt8/docker-wyze-bridge#514]
when i change the rtmp port from 1935 for example to 1940 , at gui page the link address rtmp doesnt update to the changed port , it remains at 1935

**Comment by tammeryousef1006** [comment]
![1935](https://user-images.githubusercontent.com/62266828/185348607-df6c3e3c-a426-436d-ac98-b9057c6fa134.JPG)
![1940](https://user-images.githubusercontent.com/62266828/185348610-63a30395-68e3-40ff-abaa-88b306f95523.JPG)

**Comment by tammeryousef1006** [comment]
this issue on all the links at gui not getting updated

**Comment by mrlt8** [comment]
Thanks for the report! Unfortunately, changes to the Network settings aren't exposed to the container without some extra scripts.

You can, however, specify a custom RTMP path for the WebUI by setting `WB_RTMP_URL` to `rtmp://my-hostname-or-ip:1940/`

**Comment by tammeryousef1006** [comment]
Thanks for replying  . Yes that's what im doing to solve it currently
