### ISSUE TITLE
2FA Auth Code not working on 1.8.4

### ISSUE THREAD

**Issue by randdusing** [mrlt8/docker-wyze-bridge#518]
Howdy, similar to #83 and #93, my 2 factor authentication code never works and keeps requesting a new one. It doesn't seem to be credential related because if I put the wrong credentials, it fails earlier in the process. Any tips to debug this?

```
2022/08/20 04:06:46 [WyzeBridge] 💬 SMS code requested
2022/08/20 04:06:46 [WyzeBridge] 📝 Add verification code to /tokens/mfa_token.txt
2022/08/20 04:09:50 [WyzeBridge] 🔑 Using “123456” for authentication
2022/08/20 04:09:51 [WyzeBridge] 🚷 Wrong Code?
2022/08/20 04:09:51 [WyzeBridge] Error: 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
```

Thanks for the great work, I'm looking forward to getting this up and running.

**Comment by mrlt8** [comment]
hmm, just tried this myself and it seems to be working:
```
[WyzeBridge] 🔐 MFA Token Required
[WyzeBridge] 💬 SMS code requested
[WyzeBridge] 📝 Add verification code to /tokens/mfa_token.txt
[WyzeBridge] 🔑 Using 471018 for authentication
[WyzeBridge] ✅ Verification code accepted!
```

Are you adding quotes `"` around the token? 

Could potentially be related to #505 where the production api is having some authentication issues.

**Comment by randdusing** [comment]
Oops, the readme was a bit ambiguous, but I should have known to trim quotes. All good now, but your latest commit should be helpful.
