### ISSUE TITLE
Feature Request: Home Assistant Add On or HACS support (ARM64)

### ISSUE THREAD

**Issue by bobloadmire** [mrlt8/docker-wyze-bridge#519]
I would love to be able to install this on my Home Assistant install on rpi4.

https://www.home-assistant.io/

**Comment by mrlt8** [comment]
https://github.com/mrlt8/docker-wyze-bridge/wiki/Home-Assistant

**Comment by bobloadmire** [comment]
How'd I miss that??? Thank you!
