### ISSUE TITLE
Windows Docker Setup

### ISSUE THREAD

**Issue by RUHavingFun** [mrlt8/docker-wyze-bridge#52]
My test of a Windows based Docker setup finally seems to be running.  But I can not connect to any streams.  I have disabled Windows Firewall completely.  Any suggestions?
 
 -----
 
STARTING DOCKER-WYZE-BRIDGE v0.5.1
Could not find local cache for user
Could not find local cache for auth
Fetching auth from wyze api...
Saving auth to local cache...
Fetching user from wyze api...
Saving user to local cache...
Could not find local cache for cameras
Fetching cameras from wyze api...
Saving cameras to local cache...
WHITELIST MODE ON
STARTING 1 OF 23 CAMERAS
2021/08/06 22:59:37 [CAM Front] Starting 1080p 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) in "LAN mode" FW: 4.36.2.5 IP: 192.168.1.111 WiFi: 75%
2021/08/06 22:59:41 I [0/0] [RTSP] [conn 127.0.0.1:42912] opened
2021/08/06 22:59:41 I [0/0] [RTSP] [session 3588204670] opened by 127.0.0.1:42912
2021/08/06 22:59:41 I [1/0] [RTSP] [session 3588204670] is publishing to path 'cam-front', 1 track with UDP

**Comment by mrlt8** [comment]
I don't have access to to a windows machine, but make sure you have the appropriate ports you are trying to access:
https://github.com/mrlt8/docker-wyze-bridge/blob/2b9205403308c55293842cc8e4368efdd1e82146/docker-compose.sample.yml#L6-L9
