### ISSUE TITLE
Add-on not working on mac M1

### ISSUE THREAD

**Issue by jorisrymenants** [mrlt8/docker-wyze-bridge#529]
I am running home assistant with HASSOS AARCH64 image virtualized with UTM.

When the add-on gets started I always receive the following error:

[FATAL tini (6)] exec flask failed: Exec format error

version add-on: 1.8.6
Version hass-os: 8.5
version home assistant: 2022.8.7

**Comment by mrlt8** [comment]
Do you get the same error if you run the container with docker desktop?

**Comment by jorisrymenants** [comment]
Don't have time to test this weekend
Will test beginning of next week.
Thanks

**Comment by jorisrymenants** [comment]
I can confirm that running the container directly with docker desktop from within osx is working.
I hadd to remap port 5000 to a differnt port because port 5000 is already in use.

**Comment by mrlt8** [comment]
Awesome! Not sure why you couldn't get it to work in HA.. Was it by any chance running in x64 mode?

**Comment by jorisrymenants** [comment]
I don't think I can decide anywhere in what mode the addon is running.  
But I can run it directly in docker, at least then I have the camera streams available. I have not found a way to make the UI available home assistant, but I don't really mind about that.
It will probably run better and faster anyway when running directly in docker in osx itself, and not on the virtualised Hassos.

**Comment by rmonst3r** [comment]
Same issue here on M1 Mac, Parallels VM and Portainer/Ubuntu
