### ISSUE TITLE
Question about other rtsp camera's

### ISSUE THREAD

**Issue by tammeryousef1006** [mrlt8/docker-wyze-bridge#531]
is it possible somehow to add an extra camera rtsp to the bridge ? i got tapo c100 which expose onvif and rtsp , i want to add it to the bridge so that i can monitor all camera at one place .

many thanks for the great work

**Comment by mrlt8** [comment]
Potentially in the future. 

See @BeardedTek's https://github.com/beardedtek-com/RTSPScanner

**Comment by BeardedTek** [comment]
RTSPScanner is also available on PyPi

```
python3 -m pip install rtspcanner
```
Add all rtsp cameras found on subnet
```
rtspscanner -m add -a 192.168.0.0/24 -A <wyze-bridge-ip> -t http
```
Add single camera
```
rtspscanner -m add -a 192.168.0.200 -A <wyze-bridge-ip> -t http
```

**Comment by tammeryousef1006** [comment]
Thanks, I'll check it out.

**Comment by tammeryousef1006** [comment]
thanks again , i did install rtspscanner and tried it , the main problem
were with Path , because wyze cams can be viewed on rtsp that ends with
/live , but the tapo cam were detected but not picked since the path was
different ( rtsp**********/stream2
i will try to see if i can add extra path to rtspscanner somehow

**Comment by BeardedTek** [comment]
I thought I added a command line option but looking back at the code I did not.

However, you can prepend a variable before the command to define the paths to look at.
```
RTSP_PATHS="/stream2"
```

**Comment by tammeryousef1006** [comment]
***@***.***:/# rtspscanner -m scan -c admin:admin -a 192.168.68.144
RTSP_PATHS="/stream2"
usage: rtspscanner [-h] [-w WHITESPACE] [-a ADDRESS] [-n NAME] [-p PORTS]
[-c CREDS] -m MODE [-A APIADDR] [-P APIPORT] [-t APITRANSPORT] [-T TIMEOUT]
[-R TIMEOUTRETRIES]
                   [-v]
rtspscanner: error: unrecognized arguments: RTSP_PATHS=/stream2

***@***.***:/# rtspscanner RTSP_PATHS="/stream2" -m scan -c admin:admin -a
192.168.68.144
usage: rtspscanner [-h] [-w WHITESPACE] [-a ADDRESS] [-n NAME] [-p PORTS]
[-c CREDS] -m MODE [-A APIADDR] [-P APIPORT] [-t APITRANSPORT] [-T TIMEOUT]
[-R TIMEOUTRETRIES]
                   [-v]
rtspscanner: error: unrecognized arguments: RTSP_PATHS=/stream2

i tried at end of the command and at start , both gives unrecognized
arguments: RTSP_PATHS=/stream2

did i mess something ?

**Comment by tammeryousef1006** [comment]
this is the response without adding the path

***@***.***:/# rtspscanner -m scan -c admin:admin -a 192.168.68.0/24

4 Potential RTSP Sources:
  192.168.68.85:554
  192.168.68.166:8554
  192.168.68.126:554
  192.168.68.144:554

0 Camera Found:

Credentials Used:
  admin:admin

Paths Used:
  /Streaming/Channels/101
  /live

**Comment by BeardedTek** [comment]
```
RTSP_PATHS="/live2" rtspscanner -m scan -c admin:admin -a 192.168.68.144 -A <wyze_bridge_ip>
```

As it's an environment variable it can be set before the command or exported before you run the command like so:

```
export RTSP_PATHS="/live2"
```
```
rtspscanner -m scan -c admin:admin -a 192.168.68.144 -A <wyze_bridge_ip>
```

**Comment by BeardedTek** [comment]
```
RTSP_PATHS="/live2" rtspscanner -m scan -c admin:admin -a 192.168.68.144 -A <wyze_bridge_ip>
```

As it's an environment variable it can be set before the command or exported before you run the command like so:

```
export RTSP_PATHS="/live2"
```
```
rtspscanner -m scan -c admin:admin -a 192.168.68.144 -A <wyze_bridge_ip>
```
Can you please [file an issue](https://GitHub.com/beardedtek-com/RTSPScanner/issues/) in [RTSPScanner's repo](https://GitHub.com/beardedtek-com/RTSPScanner/)?
I'll have a further look in an hour or so.

**Comment by tammeryousef1006** [comment]
Ok, I will do that.

Many thanks bro 🙏

**Comment by BeardedTek** [comment]
Out of curiosity, do you have the API enabled and the port exposed in your docker-compose file?

You would need have the following added to your compose file:
```
  ports:
    - target: 9997
      published: 9997
      mode: host
  environment:
    - RTSP_APIADDRESS=0.0.0.0:9997
    - RTSP_API=yes
```

**Comment by tammeryousef1006** [comment]
No i didn't enable it sorry . I will update my docker and give it a try.

My bad sorry again

**Comment by BeardedTek** [comment]
If I were to have a dollar for every time I made a mistake I'd be a millionaire.  Mistakes are valuable.  It's how we learn.  I now can add a command line option I missed and add error handling I didn't think to add yet.

Thank you!

**Comment by BeardedTek** [comment]
Version 0.1.4 of rtspscanner is released on pypi.

To upgrade:
```
python3 -m pip install --upgrade rtspscanner
```

## Changelog:

# 0.1.3 > 0.1.4:
- Add `-pp` `--paths` command line option
   - Adds easier way to add custom paths for rtsp streams
- Add RTSP_WHITESPACE environment variable
- Move `cla()` within `if __name__ == "__main":`
- refactor `splitEnvCSV` to `splitCSV` to better reflect its function
- Add error handling on requests.ConnectionError while trying to contact API
  - Thank you @tammeryousef1006 for pointing out this behavior
  - Outputs tips on how to rectify problems and stops further connection attemps
  - Typical output:
```
Cannot reach rtsp-simple-server at http://192.168.2.243:9997.
Possible Causes: API not enabled
                 transport (http/https) not correct: http
                 ip/fqdn not correct: 192.168.2.243
                 port number not correct: 9997

2 Potential RTSP Sources:
  192.168.2.190:8554
  192.168.2.189:8554

2 Cameras Found:
  192.168.2.190: rtsp://*****:*****@192.168.2.190:8554/Streaming/Channels/101
  192.168.2.189: rtsp://*****:*****@192.168.2.189:8554/Streaming/Channels/101

Credentials Used:
  *****:*****

Paths Used:
  /Streaming/Channels/101
  /live
  /live2
```

**Comment by tammeryousef1006** [comment]
many thanks for following up with me


i did upgrade rtspscanner and i update wyze docker bridge with the
mentioned ports and environment , after that i run the  command
rtspscanner -m add -A 192.168.68.166 -c admin:admin -a 192.168.68.144
-pp /stream2

it shows that it did detect and add the new rtsp camera as below


***@***.***:/# rtspscanner -m add -A 192.168.68.166 -c admin:admin -a
192.168.68.144 -pp /stream2
Adding 192.168.68.144 - ***@***.***:554/stream2
| 200 : SUCCESS

1 Potential RTSP Source:
  192.168.68.144:554

1 Camera Found:
  192.168.68.144: ***@***.***:554/stream2

Credentials Used:
  admin:admin

Paths Used:
  /stream2


then i toke a look at wyze bridge and saw this msg below



rtsp://127.0.0.1:8554/192-168-68-144: Server returned 404 Not Found

2022/08/30 20:30:11 [RTSP][192-168-68-144] ✅ '/192-168-68-144' stream
is UP! (3/3)

Output file #0 does not contain any stream


i tried to restart the bridge and to restart rtsp server but still the
new camera not showing up with other cams

the output file #0 does not contain any stream but i do use that
stream already with many other apps such as frigate and ewelink
camsync , but dont have idea what to do to make the stream publish
with the bridge


 i feel im very close to this but got no clue what to do next

**Comment by tammeryousef1006** [comment]
i did try to play the stream despite of all above at vlc and it was running
, the camera name was the same ip address rtsp://
192.168.68.166:8554/192-168-68-144
but the log showing alot as below

2022/08/30 20:43:11 [RTSP][192-168-68-144] 📕 Client stopped reading

Output file #0 does not contain any stream

Traceback (most recent call last):

  File "/app/rtsp_event.py", line 7, in <module>

    from datetime import datetime as dt

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 879, in exec_module

  File "<frozen importlib._bootstrap_external>", line 1012, in get_code

  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode

KeyboardInterrupt

**Comment by BeardedTek** [comment]
Try using the url given by rtspscanner to open up the stream in vlc.  If it does, then the issue lies with rtsp-simple-server

**Comment by tammeryousef1006** [comment]
i did try that , the stream is working but the video rubbish , full of gray and non clear , i guess its related to rtsp simple server config with ffmpeg i guess

![Capture](https://user-images.githubusercontent.com/62266828/187541307-4677d8cf-d5e4-4d72-990d-2a2deaf8ee0c.JPG)

**Comment by BeardedTek** [comment]
This could also be because of poor network conditions to/from the camera.Some cameras can only handle 1 rtsp connection before they get bogged down.

If you have any other source accessing the cameras, I'd recommend stopping that access and trying again.

It would also explain why it would give you `Output file #0 does not contain any stream`

**Comment by tammeryousef1006** [comment]
will try to use it again with wired camera for testing later on

**Comment by tammeryousef1006** [comment]
sorry i forget to mention  , i access the stream from vlc as i mentioned
above but its not showing with the others cams on wyze bridge ui main page
