### ISSUE TITLE
Wyze outdoor camera snapshot not working

### ISSUE THREAD

**Issue by jclark50** [mrlt8/docker-wyze-bridge#532]
I’ve recently been having trouble taking snapshots with my two outdoor Wyze cams (version 1, WVOD1). I am running Docker Wyze Bridge 1.8.6 and home assistant 2022.8.7.

It simply doesn’t save the snapshot images for the outdoor cameras. My routine works by turning on the add-on for 5 minutes every 2 hours to take a few snapshots. I have the configuration set with “RTSP15” as the snapshot mode, and I’ve tried every combination of “allowed net mode” and “img type”, but nothing has worked.

The only time the snapshot with the outdoor cameras will work is if I manually start the add-on and open the web UI to view the cameras (sometimes I have to hit the refresh button). 

Everything continues to work fine with all of my other (wired) Wyze cams.

**Comment by mrlt8** [comment]
Unfortunately, the interval snapshots like `RTSP15` aren't working with the on-demand streams while they are in standby mode (default for the outdoor cams) right now as it only works when the camera is connected to the bridge and streaming.

One workaround would be to access the the snapshot endpoint for the camera (:5000/snapshot/<cam-name>) which will wake the camera and take a snapshot, after which the camera should go back into standby mode.
