### ISSUE TITLE
TOTP stopped working recently

### ISSUE THREAD

**Issue by Drakkim** [mrlt8/docker-wyze-bridge#534]
After updating to the most recent version (Commit #530 ) I am getting an error on starting the container:

2022/09/02 22:29:24 [WyzeBridge] Incorrect padding
2022/09/02 22:29:34 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/09/02 22:29:35 [WyzeBridge] 🔐 MFA Token Required
2022/09/02 22:29:35 [WyzeBridge] Incorrect padding

I've tried rolling back to v1.8.6, 1.8.5, and 1.8.4 with no luck, so I'm guessing it's a server-side change?

**Comment by mrlt8** [comment]
The fix is currently in the edge build, and should get pushed in the next release!

**Comment by mrlt8** [comment]
Should be fixed in v1.8.7.

Also added an option to set the key in your docker-compose with `TOTP_KEY`.
