### ISSUE TITLE
Absent https HLS functionality.

### ISSUE THREAD

**Issue by GloriamSemper** [mrlt8/docker-wyze-bridge#538]
With Home Assistant plugin, using an encrypted (https) HA server. Using a manually entered URL for HLS streaming in browser (ie https://ha.server.com:8888/wyzecam/), an https error is returned:

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by mrlt8** [comment]
I believe you'll need to enable `HLSENCRYPTION` and set the certificates in rtsp-simple-server to enable https access for the HLS stream.

Enabling `LLHLS` in the bridge should enable https and configure the certificates if necessary.

**Comment by GloriamSemper** [comment]
Just enabled the LLHLS switch, restarted the add-on in HA, and worked like normal. Sorry for my ignorance on the subject. Thanks for responding so quickly. Loving the on-demand option btw. Your work is appreciated!
