### ISSUE TITLE
Two factor hangs during login - Home Assistant

### ISSUE THREAD

**Issue by rlust** [mrlt8/docker-wyze-bridge#541]
When I open docker homebridge tab it asks for TFO, I enter code and if just spins and never finishes to login.

Two Factor Authentication Required

**Comment by rlust** [comment]
<img width="561" alt="TFOHang" src="https://user-images.githubusercontent.com/1095910/190414529-f8ccc720-e25d-4652-83ac-5e45aa45a931.png">

**Comment by mrlt8** [comment]
hmm. Anything in the bridge logs? I wonder if it might be a JS issue. Can you post the browser you're using?

**Comment by rlust** [comment]
I am using Safari, the latest release.

**Comment by mrlt8** [comment]
Seems to be working for me on Safari 16.0, are you on Ventura? 

Do you see anything in the docker logs?

**Comment by rlust** [comment]
Thanks for the help. Not sure if this helps but I found  a MFA error listed here.

<img width="549" alt="Screen Shot 2022-09-18 at 9 41 09 AM" src="https://user-images.githubusercontent.com/1095910/190906655-e2bdc04d-4f4a-4ec6-a0d5-651f17c2e78c.png">
<img width="549" alt="Screen Shot 2022-09-18 at 9 41 09 AM" src="https://user-images.githubusercontent.com/1095910/190906725-0e4402cc-cf8d-4d1e-8274-55ecc91bda7f.png">

**Comment by rlust** [comment]
Found this also, agin not sure if this helps.

  sse.addEventListener("mfa", (e) => {
    const alertDiv = document.getElementById("alert")
    if (e.data == "clear") {
      alertDiv.innerHTML = '<div class="columns is-centered"><div class="column is-half-desktop"><article class="message is-success container is-one-third-desktop"><div class="message-body"><span class="icon"><i class="fas fa-check-circle"></i></span><span>Verification code accepted!</div></article></div></div>'
      setTimeout(function () { location.reload(1); }, 5000);
    } else {
      if (alertDiv.classList.contains("is-hidden")) {
        const mfaType = e.data == "PrimaryPhone" ? "SMS" : "TOTP"
        console.error("MFA Required!!!!!")
        alertDiv.classList.toggle("is-hidden");
        alertDiv.innerHTML = '<div class="columns is-centered"><div class="column is-half-desktop"><article class="message is-dark container is-one-third-desktop">\
      <div class="message-header">Two Factor Authentication Required</div>\
      <div class="message-body"><form id="mfa-form" action="#"><div class="field"><label class="label" for="mfa-code">'+ mfaType + ' code required</label><p class="control has-icons-left"><input id="mfa-code" class="input is-dark is-large is-fullwidth" type="tel" placeholder="e.g. 123456" inputmode="numeric" required pattern="\\d{3}\\s?\\d{3}" maxlength="7"><span class="icon is-left"><i class="fas fa-unlock" aria-hidden="true"></i></span></div><div class="field"><div class="control"><button id="mfa-submit" type="submit" class="button is-dark is-fullwidth">Submit</button></div></p></div></form></div>\
      </article></div></div>'
        const mfaForm = document.getElementById("mfa-form")
        const button = document.getElementById("mfa-submit").classList
        mfaForm.addEventListener('submit', (e) => {
          e.preventDefault();
          button.add("is-loading")
          let mfaCode = document.getElementById("mfa-code").value.replace(/\s/g, '')
          fetch("/mfa/" + mfaCode).then(resp => resp.json()).then(data => {
            mfaForm.reset()
            button.remove("is-loading")
          }).catch(console.log("error"))
        })
      }
    }
  })
  sse.addEventListener("message", (e) => {
    Object.entries(JSON.parse(e.data)).forEach(([cam, status]) => {
      const statusIcon = document.querySelector(`#${cam} .status i.fas`);
      const preview = document.querySelector(`#${cam} img.refresh_img`);
      statusIcon.setAttribute("class", "fas")
      statusIcon.parentElement.title = null
      if (preview) { preview.classList.remove("connected") }
      if (status == "connected") {
        statusIcon.classList.add("fa-circle-play", "has-text-success");
        statusIcon.parentElement.title = "Click/tap to pause";
        if (preview) { preview.classList.add("connected") }
        let noPreview = document.querySelector(`#${cam} .no-preview`)
        if (noPreview) {
          let fig = noPreview.parentElement
          let preview = document.createElement("img")
          preview.classList.add("refresh_img", "loading-preview", "connected")
          preview.dataset.cam = cam
          preview.src = "static/loading.svg"
          noPreview.replaceWith(preview)
          loadPreview(fig.querySelector("img"))
        }
      } else if (status == "connecting") {
        statusIcon.classList.add("fa-satellite-dish", "has-text-warning");
        statusIcon.parentElement.title = "Click/tap to pause";
      } else if (status == "standby") {
        statusIcon.classList.add("fa-circle-pause");
        statusIcon.parentElement.title = "Click/tap to play";
      } else if (status == "offline") {
        statusIcon.classList.add("fa-ghost");
      } else {
        statusIcon.setAttribute("class", "fas fa-circle-exclamation")
      }
    });
  });

**Comment by mrlt8** [comment]
Looks like you're running this as a home assistant add-on?

Could you try accessing the web-hi directly on port 5000?

**Comment by rlust** [comment]
I am running this in HA. I can hit port 5000 and it takes my code, but comes back shortly asking again. This is different than in HA. I also keep getting codes texted to me. I can try running it on my Unraid server.

**Comment by rlust** [comment]
Here is the log info from the add-on:

Please try again!
2022/09/18 12:14:29 [WyzeBridge] 192.168.1.110 - - [18/Sep/2022 12:14:29] "GET /mfa/295097 HTTP/1.1" 200 -
2022/09/18 12:14:33 [WyzeBridge] 💬 SMS code requested
2022/09/18 12:14:33 [WyzeBridge] 📝 Enter verification code in the WebUI or add it to /config/wyze-bridge/mfa_token.txt
2022/09/18 12:17:50 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:17:50] "GET / HTTP/1.1" 200 -
2022/09/18 12:17:50 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:17:50] "GET /static/site.css HTTP/1.1" 304 -
2022/09/18 12:17:50 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:17:50] "GET /static/site.js HTTP/1.1" 304 -
2022/09/18 12:17:50 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:17:50] "GET /static/site.js HTTP/1.1" 304 -
2022/09/18 12:17:50 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:17:50] "GET /static/site.css HTTP/1.1" 304 -
2022/09/18 12:17:51 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:17:51] "GET /api/sse_status HTTP/1.1" 200 -
2022/09/18 12:18:33 [WyzeBridge] 🔑 Using 481780 for authentication
2022/09/18 12:18:33 [WyzeBridge] 🚷 Wrong Code?
2022/09/18 12:18:33 [WyzeBridge] Error: 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
Please try again!
2022/09/18 12:18:34 [WyzeBridge] 192.168.1.110 - - [18/Sep/2022 12:18:34] "GET /mfa/481780 HTTP/1.1" 200 -
2022/09/18 12:18:37 [WyzeBridge] 💬 SMS code requested
2022/09/18 12:18:37 [WyzeBridge] 📝 Enter verification code in the WebUI or add it to /config/wyze-bridge/mfa_token.txt
2022/09/18 12:28:05 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:28:05] "GET / HTTP/1.1" 200 -
2022/09/18 12:28:05 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:28:05] "GET /static/site.js HTTP/1.1" 304 -
2022/09/18 12:28:05 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:28:05] "GET /static/site.css HTTP/1.1" 304 -
2022/09/18 12:28:05 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:28:05] "GET /static/site.css HTTP/1.1" 304 -
2022/09/18 12:28:05 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:28:05] "GET /static/site.js HTTP/1.1" 304 -
2022/09/18 12:28:05 [WyzeBridge] 172.30.32.2 - - [18/Sep/2022 12:28:05] "GET /api/sse_status HTTP/1.1" 200 -

**Comment by rlust** [comment]
I stopped the add-on and restarted, and in HA it failed but in Chrome at port 5000 it now worked! Yea!

**Comment by mrlt8** [comment]
Hey @rlust could you see if v1.8.8 fixed the issue for you?
