### ISSUE TITLE
Snapshot 404 error

### ISSUE THREAD

**Issue by RUHavingFun** [mrlt8/docker-wyze-bridge#542]
I just upgraded from 1.6.3 to 1.8.7.  I have also just enabled 2FA and got it working.  But I am getting 404 errors in regards to Snapshots.  The WebUI shows not snapshots but I do get my streams.  Is there something I likely missed in doing the pull and upgrading?

**Comment by mrlt8** [comment]
That's strange. Can you access the snapshot uri directly? 

```

:5000/snapshot/camera-nickname.jpg

Or 

:5000/img/camera-nickname.jpg

```

**Comment by RUHavingFun** [comment]
Nope - neither.  I am running this on a RPi.  Is there a directory I should check exists?

**Comment by RUHavingFun** [comment]
2022/09/15 16:12:39 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:39] "GET /?snapshot HTTP/1.1" 200 -
2022/09/15 16:12:39 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:39] "GET /static/site.css HTTP/1.1" 304 -
2022/09/15 16:12:39 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:39] "GET /static/site.js HTTP/1.1" 304 -
2022/09/15 16:12:39 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:39] "GET /static/loading.svg HTTP/1.1" 304 -
2022/09/15 16:12:40 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:40] "GET /api/sse_status HTTP/1.1" 200 -
2022/09/15 16:12:40 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:40] "GET /snapshot/cam-front.jpg?1663258359944 HTTP/1.1" 404 -
2022/09/15 16:12:40 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:40] "GET /snapshot/cam-driveway-north.jpg?1663258359944 HTTP/1.1" 404 -
2022/09/15 16:12:40 [WyzeBridge] 10.10.10.54 - - [15/Sep/2022 16:12:40] "GET /snapshot/cam-garage.jpg?1663258359945 HTTP/1.1" 404 -

**Comment by mrlt8** [comment]
Hmm, that is strange. You should be getting redirected to the notavailable image if it can't do a snapshot:
```
"GET /snapshot/fake-cam.jpg HTTP/1.1" 307 -
"GET /static/notavailable.svg HTTP/1.1" 200 -
```

Could you try rebuilding your container to see if that helps?

**Comment by RUHavingFun** [comment]
Should I just do a docker-compose pull and prune or docker rebuild?  Also, on my pi where should I be able to find that fake-cam.jpg file?  I see no "snapshot" directory.

**Comment by mrlt8** [comment]
`fake-cam.jpg` doesn't exist, so it should redirect to `notavailable.svg`


Are you running the cameras in "on-demand" mode or volume mapping any of the directories?

Could you try running the container with minimal options to see if the preview works:

```
docker run \
  -e WYZE_EMAIL=you@email.com \
  -e WYZE_PASSWORD=yourpassw0rd \
  -p 1935:1935 -p 8554:8554 -p 8888:8888 -p 5000:5000 \
  mrlt8/wyze-bridge:latest

```

**Comment by RUHavingFun** [comment]
So the above did work.  Starts far too many cams for my little Pi.  But I will try again with a cam list.  Since this did work what do you think the issue is?  Here is may normal YML.

`services:
    wyze-bridge:
        container_name: wyze-bridge
        network_mode: host
        restart: always
        pull_policy: always
        image: mrlt8/wyze-bridge:latest
        environment:
            - NET_MODE=LAN
            - FRESH_DATA=true
            - WYZE_EMAIL=you@email.com
            - WYZE_PASSWORD= yourpassw0rd
            - QUALITY=HD120
            - RTSP_READTIMEOUT=10s
            - RTSP_PATHS_ALL_READUSER=youuser
            - RTSP_PATHS_ALL_READPASS= yourpassw0rd
            - RTSP_PROTOCOLS=tcp
            - FILTER_NAMES=CAM Backyard, CAM Piggies, CAM North Gate, CAM South Gate`

**Comment by mrlt8** [comment]
Ok, I think it's the spaces in the camera name causing this. 
Could you try the dev branch to see if that fixes it?

**Comment by RUHavingFun** [comment]
Thanks.  I tried the DEV branch and it worked.

> image: mrlt8/wyze-bridge:dev

**Comment by mrlt8** [comment]
Awesome! will merge the changes in the next release!
