### ISSUE TITLE
Support for Nvidia GPU?

### ISSUE THREAD

**Issue by mitchross** [mrlt8/docker-wyze-bridge#548]
Any plans for Nvidia gpu support to decode / encode ? Could port and use jellyfin-ffmpeg

https://jellyfin.org/docs/general/administration/hardware-acceleration.html

**Comment by mrlt8** [comment]
Thanks, I will take a look!

FYI, unless you're doing transcoding/rotation in the bridge, it will just copy the raw h264 into an rtsp stream without any decoding/encoding.

**Comment by mitchross** [comment]
You'll also need

https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)

"ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"

**Comment by mitchross** [comment]
@mrlt8 

How does this work?

For all cameras
environment:
    ..
    - FFMPEG_CMD=-f h264 -i - -vcodec copy -f flv rtmp://rtsp-server:1935/{cam_name}
    
    
    is rtsp-server a special keyword that the container knows about? and same for cam_name?

**Comment by mrlt8** [comment]
The bridge should replace it with the uri safe camera name. You can use `{cam_name}` for lowercase or `{CAM_NAME}` for uppercase.

**Comment by mitchross** [comment]
Im super close, might just need some pointers on the ffmpeg commands

nvidia-wyze is just your dockerfile you linked built locally.

`
version: '2.4'
services:
    wyze-bridge2:
        container_name: wyze-bridge2
        restart: unless-stopped
        image: nvidia-wyze
        privileged: true
        devices:
          - /dev:/dev
        ports:
            - 1937:1935 # RTMP
            - 8556:8554 # RTSP
            - 8889:8888 # HLS
            - 5600:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=xxx# Replace with wyze email 
            - WYZE_PASSWORD=xxx # Replace with wyze password
            - FFMPEG_CMD=ffmpeg -f -hwaccel cuvid -c:v h264_cuvid -i rtmp://0.0.0.0:1935/{cam_name}
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]
`

Getting this error

![image](https://user-images.githubusercontent.com/6330506/193375817-a6c85258-188b-4ab5-9143-85e01b374e3b.png)
![image](https://user-images.githubusercontent.com/6330506/193375837-e1383571-a8d6-4f73-800e-6ac7c22e925b.png)


I do know the GPU is attached

![image](https://user-images.githubusercontent.com/6330506/193375878-56ec6029-cd50-43b9-8b5a-e0d6c0c77251.png)

Codecs Working too

![image](https://user-images.githubusercontent.com/6330506/193375899-154592e6-29f1-4c46-9c01-0c2f271a9e3f.png)


Any ideas?

**Comment by mrlt8** [comment]
I think you need to specify that the input is a `pipe:` or `-`. Does something like this work:

```
FFMPEG_CMD=ffmpeg -loglevel verbose -f -hwaccel cuvid -i - -c:v h264_nvenc -force_key_frames expr:gte(t,n_forced*2) -movflags +empty_moov+default_base_moof+frag_keyframe -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554/{cam_name}
```

**Comment by mitchross** [comment]
@mrlt8 

No luck

![image](https://user-images.githubusercontent.com/6330506/193419345-e6e56679-2f45-4d69-9174-8276eceb1898.png)


So then i tried 

            - FFMPEG_CMD=ffmpeg -loglevel verbose -f h264 -hwaccel_output_format cuda -i - -c:v h264_nvenc -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554/{cam_name}


![image](https://user-images.githubusercontent.com/6330506/193419420-3aa2460e-54ad-4e02-b8c9-94525691a5f3.png)
![image](https://user-images.githubusercontent.com/6330506/193419431-7975e403-fe87-4753-a8f4-06972a903421.png)

**Comment by mrlt8** [comment]
Not sure about the OOM error. Does it work with a single camera or two?

**Comment by mitchross** [comment]
@mrlt8  Yea looks like it works with 1 camera. Im trying to see how Frigate works with ffmpeg/nvidia acceleration becausethat lets me do 6 cams without OOM errors.


https://docs.frigate.video/configuration/hardware_acceleration

https://github.com/blakeblackshear/frigate/blob/7c60753ab0a376efdbd834d3cd3900cc029e5158/frigate/video.py

    "hwaccel_args": "-c:v h264_cuvid",
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://192.168.1.13:8554/deck",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],

**Comment by mrlt8** [comment]
Looks like that is outputting `rawvideo`,  so it's only using `h264_cuvid` for decoding?

Does something like this work:

```
ffmpeg -loglevel verbose -f h264 -c:v h264_cuvid -i - -c:v h264_nvenc -rtsp_transport tcp -f rtsp rtsp://0.0.0.0:8554/{cam_name}
```

**Comment by mitchross** [comment]
@mrlt8  Sorry I was away on business travel.

Yes! It looks like that command works now!

![image](https://user-images.githubusercontent.com/6330506/194791951-affd8e6e-4f7f-4d73-b5fb-e9b0636e10aa.png)

**Comment by mitchross** [comment]
@mrlt8  what are next steps, will this merge into main or always be custom build or what?

**Comment by mrlt8** [comment]
Would be great if we can find a static build of ffmpeg with hwaccel enabled that we can include in the container as the jellyfin one is a little messy since we need to install and copy all the required dependencies. 

Another option would be to just compile our own static build of ffmpeg so we could include the stuff we need and keep it compact.

**Comment by mitchross** [comment]
@mrlt8 check out this commit https://github.com/blakeblackshear/frigate/commit/e649a1eb989f9b09848c7c94f76510c000203cf3

**Comment by mrlt8** [comment]
@mitchross I added a new [Dockerfile.hwaccel](https://github.com/mrlt8/docker-wyze-bridge/blob/main/app/Dockerfile.hwaccel). Could you try it out? 

Unfortunately, we only have a 32-bit version of the library for arm and BtbN only has a 64-bit version of ffmpeg for arm, so we can't fully switch for now, but maybe we could configure a new GitHub workflow to build another image for the Dockerfile.hwaccel image.

**Comment by mitchross** [comment]
> @mitchross I added a new [Dockerfile.hwaccel](https://github.com/mrlt8/docker-wyze-bridge/blob/main/app/Dockerfile.hwaccel). Could you try it out?
> 
> Unfortunately, we only have a 32-bit version of the library for arm and BtbN only has a 64-bit version of ffmpeg for arm, so we can't fully switch for now, but maybe we could configure a new GitHub workflow to build another image for the Dockerfile.hwaccel image.

Ill try this out today... Whats the reason for 32 bit only?

**Comment by mrlt8** [comment]
The SDK we're using doesn't have a 64-bit version for arm linux. It does have 64-bit libraries for arm on android/iOS/tvOS but only 32-bit for arm on linux. I wonder if it might be because Raspbian was 32-bit only until recently and the SDK we're using is slightly out of date (still newer than whatever wyze is using).

**Comment by mitchross** [comment]
@mrlt8  Dockerfile.hwaccel works. Wanna add it to docker hub?

**Comment by mrlt8** [comment]
@mitchross docker images with hwaccel should be available with the `latest-hw` tag!
