### ISSUE TITLE
Snapshot not working if streaming disabled (ON_DEMAND: true)

### ISSUE THREAD

**Issue by jrbecart** [mrlt8/docker-wyze-bridge#549]
To lower the CPU and network usage I added:  `ON_DEMAND: true`
but then RSTP snapshot is not working... ( `SNAPSHOT: RTSP30` or `SNAPSHOT: RTSP`)

Do you think is it possible to have a snaphot every 30 seconds without starting the streaming?

**Comment by mrlt8** [comment]
This is a known issue and we need to figure out a way to do snapshots without draining the battery on the outdoor cams that also use `ON_DEMAND`.

You can manually trigger a snapshot via the webui endpoint: `:5000/snapshot/camera-nickname.jpg`

**Comment by jrbecart** [comment]
Excellent, that's all I need!

I think I tried before but I may have used a wrong nickname.

Thanks!
