### ISSUE TITLE
Issue with new RTSP_FW feature

### ISSUE THREAD

**Issue by anderfrank** [mrlt8/docker-wyze-bridge#564]
I have one cam on the latest RTSP firmware from Wyze (4.28.2.51) and when adding the environment variable RTSP_FW=True and enabling the cam on the FILTER_NAMES variable, I get the following after restarting the docker container. If I remove the cam form the filtered cams variable list and restart, everything starts workinga gain for my other non-RTSP cams.

2022/10/17 16:36:09 [WyzeBridge] Checking Office for firmware RTSP on v4.28.4.51
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/wyze_bridge.py", line 67, in run
    self.get_filtered_cams(fresh_data)
  File "/app/wyze_bridge.py", line 452, in get_filtered_cams
    self.add_rtsp_path(cam)
  File "/app/wyze_bridge.py", line 388, in add_rtsp_path
    if rtsp_path := self.check_rtsp_fw(cam):
  File "/app/wyze_bridge.py", line 423, in check_rtsp_fw
    return session.check_native_rtsp()
  File "/app/wyzecam/iotc.py", line 367, in check_native_rtsp
    return decoded_url[1] if len(decoded_url) > 0 else None
IndexError: list index out of range

**Comment by mrlt8** [comment]
Hmm, I'm unable to replicate the issue, but added some checks to prevent that error in the DEV branch.

Do you have RTSP enabled on the the wyze app for that camera? I also added another ENV option so that `RTSP_FW=force` will turn on the native RTSP stream for all supported cameras.

**Comment by anderfrank** [comment]
Yes, I have RTSP enabled in the Wyze app for the camera. Environment variable RTSP_FW=True is currently enabled, the error only shows up when I add the camera with Wyze RTSP firmware to the FILTER_NAMES variable.

**Comment by mrlt8** [comment]
Could you try running the dev branch:
```yaml
image: mrlt8/wyze-bridge:dev
```
You should see something like "Proxying firmware RTSP to path: '/frontfw'", but if you don't, could you try adding the env `DEBUG_LEVEL=debug`? That should print out the response from the camera which _should_ look like this:


`[wyzecam.iotc][DEBUG][WyzeBridge] RTSP=b'\x01\x05admin\x05admin"rtsp://admin:admin@10.0.0.129/live'`

**Comment by anderfrank** [comment]
Switched to dev branch and added the cam to the filtered list. Container comes online without the error and everything seems good. Enabled debug level and found the line you mentioned.

2022/10/21 13:58:48 [wyzecam.iotc][DEBUG][WyzeBridge] RTSP=b'\x01\x05Admin\x05Admin%rtsp://Admin:Admin@192.168.1.231/live'

**Comment by mrlt8** [comment]
Thank you, that's exactly what I needed! 

It _should_ work now.  Would appreciate it if you could pull the new dev image to test out the changes.

**Comment by anderfrank** [comment]
Just updated to latest dev image and all seems to be good. Thanks so much for looking into this!

2022/10/21 18:21:11 [WyzeBridge] Checking Office for firmware RTSP on v4.28.4.51
2022/10/21 18:21:14 [WyzeBridge] Proxying firmware RTSP to path: '/officefw'

**Comment by anderfrank** [comment]
Is it expected behavior that the stream will up and down like this?

2022/10/21 18:27:20 [RTSP][OFFICEFW] ✅ '/officefw' stream is UP! (3/3)
2022/10/21 18:27:21 [RTSP][OFFICEFW] 📖 New client reading 
2022/10/21 18:27:29 [RTSP][OFFICEFW] 📕 Client stopped reading
2022/10/21 18:27:53 [RTSP][OFFICEFW] ❌ '/officefw' stream is down
2022/10/21 18:27:58 [RTSP][OFFICEFW] ✅ '/officefw' stream is UP! (3/3)
2022/10/21 18:27:59 [RTSP][OFFICEFW] 📖 New client reading

**Comment by mrlt8** [comment]
No, it shouldn't. Could you try rebooting the camera to see if that helps clear up the issue?

**Comment by anderfrank** [comment]
Power cycling the camera appears to have resolved this, thanks!

Are there plans for future releases where this proxied stream can be modified to change the resolution, bitrate, audio format, etc...?

**Comment by mrlt8** [comment]
Good question. Not sure if it's possible as the setting for official RTSP stream seems to be hardcoded into the firmware.

**Comment by anderfrank** [comment]
Ah ok, thanks.If I may ask a stupid question, what is the reason to use this proxied RTSP stream over the one direct from  the cam?On Oct 21, 2022, at 11:58 PM, mrlt8 ***@***.***> wrote:﻿
Good question. Not sure if it's possible as the setting for official RTSP stream seems to be hardcoded into the firmware.

**Comment by mrlt8** [comment]
It was a requested feature. 
There are some benefits like giving you a static address for the stream, as well as creating an HLS and RTMP stream.

**Comment by anderfrank** [comment]
Got it, thx for the additional info.
