### ISSUE TITLE
Support for v1 Cams?

### ISSUE THREAD

**Issue by lostage** [mrlt8/docker-wyze-bridge#57]
Hello! Thank you for all of your work, this is amazing.

I have 4 cameras; 1 pan, 1 v2, 2 v1. When I start the container, the logs say "STARTING ALL 4 CAMERAS" but it only actually opens the non-v1 cams. For one of the v1 cams, the logs only mentions it once, with "[Play Room] AV_ER_TIMEOUT". Nothing is ever shown for the other v1 cam. When going to their respective URLs, it shows "Err: no on is publishing to path 'play-room'". Are v1 cams supported? I mean... it does say "all your cams" 😀

**Comment by mrlt8** [comment]
Interesting. 

I don't have a v1 so can't test things out.
Could you run the container with `- FILTER_MODEL=V1` and see if it prints anything else?

**Comment by lostage** [comment]
Sure! I added the flag, recreated the container, nothing useful except:

`Fetching cameras from local cache...,
WHITELIST MODE ON ,
STARTING 2 OF 4 CAMERAS,` 

Thinking maybe it needed to pull the camera list from Wyze again, I added `- FRESH_DATA=True` which produced the following:

`2021/08/08 19:47:58 I [0/0] rtsp-simple-server v0.16.4,
2021/08/08 19:47:58 I [0/0] [RTSP] UDP/RTP listener opened on :8000,
2021/08/08 19:47:58 I [0/0] [RTSP] UDP/RTCP listener opened on :8001,
2021/08/08 19:47:58 I [0/0] [RTSP] TCP listener opened on :8554,
2021/08/08 19:47:58 I [0/0] [RTMP] listener opened on :1935,
2021/08/08 19:47:58 I [0/0] [HLS] listener opened on :8888,
STARTING DOCKER-WYZE-BRIDGE v0.5.2,
Could not find local cache for user,
Could not find local cache for auth,
Fetching auth from wyze api...,
2021/08/08 19:47:59 MFA Token (PrimaryPhone) Required,
Add token to /tokens/mfa_token,
2021/08/08 19:48:00 SMS code requested,
2021/08/08 19:48:46 Using xxxxxx as verification code,
Saving auth to local cache...,
Fetching user from wyze api...,
Saving user to local cache...,
Fetching cameras from local cache...,
WHITELIST MODE ON ,
STARTING 2 OF 4 CAMERAS,`

**Comment by wolfkabal** [comment]
Seeing the same thing as above. 1xPan, 2 x v1 cams.

[ CAM1] Wyze WYZEC1 may not be fully supported yet

**Comment by mrlt8** [comment]
Is the v1 still working in the app now that it's reached end-of-life?

**Comment by jamescochran** [comment]
The v1 is working in the app even though it's reached end of life. I can't access it so I came here looking to see if it was even possible. I am viewing a WYZEC1 feed right now through the app though so it definitely works.

**Comment by mrlt8** [comment]
@jamescochran could you try running https://github.com/mrlt8/docker-wyze-bridge/tree/cam_v1 and post any errors.

**Comment by jamescochran** [comment]
Am I able to just change what I’m pulling in the docker to add :cam_v1 or
do I need to clone it and build it?

**Comment by mrlt8** [comment]
You'd need to clone and build for now.

**Comment by mrlt8** [comment]
Has anyone been able to test the v1 yet?

**Comment by jamescochran** [comment]
I cloned this and built it. I just ran it with the standard docker run command with the docker image I built locally from that branch and I still don't see the cam show up, no errors other than "2022/06/24 22:35:12 [WyzeBridge] 💔 WYZEC1 not supported"
`docker run \
  -e WYZE_EMAIL=you@email.com \
  -e WYZE_PASSWORD=yourpassw0rd \
  -p 8888:8888 cam1
`

**Comment by mrlt8** [comment]
Are you on the v1 branch? `git checkout -b cam_v1`

**Comment by jamescochran** [comment]
Yes this is the output of git branch:

```
* cam_v1
  main
```

Then in went into the app directory and did `docker build -t cam1 .` and then ran it like in said above.

**Comment by jamescochran** [comment]
Let me do some more digging when I get home. It looks like I'm in the right branch but certainly see those warnings in the code you took out that should be gone so I've done something wrong.

**Comment by jamescochran** [comment]
For posterity I ended up wiping everything out and doing this and verifying the changes were there. I'll build and run again now. 
```
104 git clone https://github.com/mrlt8/docker-wyze-bridge
 105 cd docker-wyze-bridge/
 106 git checkout -t origin/cam_v1
 107 nano app/wyze_bridge.py
```

**Comment by jamescochran** [comment]
OK. I can now confirm that it is at least loading a feed. Its doing a lot of buffering but I'm also out at the ballfield and connected over cellular to my home VPN so I'll test more later and throw some more variables at it.

**Comment by Webtron18** [comment]
I just got this image built and running thanks to @jamescochran help above. 
Looks like my V1 is working as it should now:
```
wyze-bridge_camv1 |
wyze-bridge_camv1 |
wyze-bridge_camv1 | =====
wyze-bridge_camv1 | WYZEC1
wyze-bridge_camv1 |
wyze-bridge_camv1 |
wyze-bridge_camv1 | videoParm:
wyze-bridge_camv1 |         bitRate: 120
wyze-bridge_camv1 |      resolution: 1
wyze-bridge_camv1 |             fps: 10
wyze-bridge_camv1 |  horizontalFlip: 1
wyze-bridge_camv1 |    verticalFlip: 1
wyze-bridge_camv1 |            logo: 1
wyze-bridge_camv1 |            time: 1
wyze-bridge_camv1 |
wyze-bridge_camv1 | settingParm:
wyze-bridge_camv1 |     stateVision: 1
wyze-bridge_camv1 |     nightVision: 1
wyze-bridge_camv1 |             osd: 1
wyze-bridge_camv1 |           logSd: 1
wyze-bridge_camv1 |        logUdisk: 1
wyze-bridge_camv1 |          telnet: 2
wyze-bridge_camv1 |              tz: -4
wyze-bridge_camv1 |
wyze-bridge_camv1 | basicInfo:
wyze-bridge_camv1 |        firmware: 3.9.4.16
wyze-bridge_camv1 |            type: Camera
wyze-bridge_camv1 |        hardware: 0.0.0.0
wyze-bridge_camv1 |           model: WYZEC1
wyze-bridge_camv1 |             mac: *******
wyze-bridge_camv1 |          wifidb: 84
wyze-bridge_camv1 |
wyze-bridge_camv1 | channelResquestResult:
wyze-bridge_camv1 |           video: 1
wyze-bridge_camv1 |           audio: 1
wyze-bridge_camv1 |
wyze-bridge_camv1 | recordType:
wyze-bridge_camv1 |            type: 1
wyze-bridge_camv1 |
wyze-bridge_camv1 | sdParm:
wyze-bridge_camv1 |          status: 1
wyze-bridge_camv1 |        capacity: 30431
wyze-bridge_camv1 |            free: 508
wyze-bridge_camv1 |
wyze-bridge_camv1 | uDiskParm:
wyze-bridge_camv1 |          status: 2
wyze-bridge_camv1 |        capacity: 0
wyze-bridge_camv1 |            free: 0
wyze-bridge_camv1 |
wyze-bridge_camv1 | apartalarmParm:
wyze-bridge_camv1 |            type: 1
wyze-bridge_camv1 |          startX: 22
wyze-bridge_camv1 |           longX: 51
wyze-bridge_camv1 |          startY: 26
wyze-bridge_camv1 |         heightY: 72
wyze-bridge_camv1 |
wyze-bridge_camv1 |
wyze-bridge_camv1 |
wyze-bridge_camv1 | 2022/06/25 00:41:49 [oldcam] ? Getting 120kb/s HD stream (10fps) via LAN mode (WiFi: 84%) FW: 3.9.4.16 (2/3)
wyze-bridge_camv1 | 2022/06/25 00:41:49 [RTSP][OLDCAM] ? '/oldcam' stream is UP! (3/3)
```

**Comment by Webtron18** [comment]
Looks like the stream is coming through pretty clear as well. No errors so far.

**Comment by mrlt8** [comment]
Awesome! Thanks @jamescochran @Webtron18 
Is the audio working? I noticed it's not showing any `audioParm` info, so we may have to set the codec and bit rate manually.

**Comment by Webtron18** [comment]
Oh ya, doesn't look like the audio is working on the HLS. Ill try RTSP in a moment. 
![Screen Shot 2022-06-24 at 9 03 35 PM](https://user-images.githubusercontent.com/7501413/175752369-05773dfb-6087-4843-9e5a-e06c5c9131a7.png)

**Comment by Webtron18** [comment]
Ya the RTSP stream is not producing audio either.

**Comment by mrlt8** [comment]
Thanks @Webtron18! I'll have to see if they were using a different method for the audio on the v1.

And just to confirm, do you have `ENABLE_AUDIO=true` in your env?

**Comment by jamescochran** [comment]
> ENABLE_AUDIO=true

Audio is working with this set. However, I'm still getting a ton of buffering. I need to do more testing but it seems like it was bad in the app too so I unplugged it and plugged back in then it was good on the app until I loaded the HLS stream.

**Comment by Webtron18** [comment]
For me when I enable the audio I am unable to see the HLS or RTSP streams. My logs show that its streaming, but the HLS page shows 404 and the RTPS says no connection available. 
As soon as I disable the audio it works fine. Ill keep digging.

**Comment by Webtron18** [comment]
With `ENABLE_AUDIO=True` :
```
wyze-bridge_camv1 | 2022/06/25 01:54:37 [oldcam] ? Getting 120kb/s HD stream (10fps) via RELAY mode (WiFi: 84%) FW: 3.9.4.16 (2/3)
wyze-bridge_camv1 | 2022/06/25 01:54:37 [oldcam] ? Audio Enabled - PCM > AAC/8,000Hz
```

With `ENABLE_AUDIO=False` :
```
wyze-bridge_camv1 |
wyze-bridge_camv1 | 2022/06/25 01:59:41 [oldcam] ? Getting 120kb/s HD stream (10fps) via RELAY mode (WiFi: 85%) FW: 3.9.4.16 (2/3)
wyze-bridge_camv1 | 2022/06/25 01:59:41 [RTSP][OLDCAM] ? '/oldcam' stream is UP! (3/3
```

I dont ever see the RTSP stream go UP.

**Comment by mrlt8** [comment]
Hmm, that is weird.. does it eventually time out when audio is enabled?

**Comment by Webtron18** [comment]
I've left it for about 20 minutes and it hasnt connected or timed out yet. Just stays at the `Audio Enabled - PCM > AAC/8,000Hz` log line.

**Comment by mrlt8** [comment]
hmm, the audio pipe is probably getting blocked for some reason.
Could you run it with `DEBUG_FFMPEG=true` and see if ffmpeg is giving any info?
