### ISSUE TITLE
feature request:  support HA camera integration camera.turn_on and turn_off.

### ISSUE THREAD

**Issue by wystewart** [mrlt8/docker-wyze-bridge#576]
feature request:  support HA camera integration camera.turn_on and turn_off.

I know I can use the switch entities of JoshuaMulliken/ha-wyzeapi, but it would be cleaner if it was supported by this software natively in the HA camera integration.

**Comment by wystewart** [comment]
doesn't seem appropriate here since bridge itself is not really an integration

**Comment by mrlt8** [comment]
Would love to add this, but the cameras don't seem to respond to the ON/OFF commands sent via the TUTK, so we'd probably have to do it over the web api the same way the official app and other wyze integrations do it.
