### ISSUE TITLE
Can't view the streams

### ISSUE THREAD

**Issue by IceDraken** [mrlt8/docker-wyze-bridge#582]
It appears the integration is working to pull in my cameras on version 1.8.12... but I can't view the RTMP, RTSP, or HLC streams.  But the cameras are online and the snapshot seems to update.

**Comment by mrlt8** [comment]
Did it work previously? Can you try opening the streams in VLC?

**Comment by IceDraken** [comment]
It worked at the latest about a week ago, i believe on version 1.8.10
VLC is not reliable.  Sometimes they at least open play for a second and die.  Others won't open at all.
I can however open the stream in the wyze app, and I can get the thumbnail to update via the API.

**Comment by IceDraken** [comment]
This is the error when VLC doesn't play it at all....
satip error: Failed to setup RTSP session
access_realrtsp warning: Cseq mismatch, got 1, assumed 0
access_realrtsp warning: only real/helix rtsp servers supported for now

**Comment by mrlt8** [comment]
hmm, v1.8.12 did bump rtsp-simple-server to v0.20.1, but I'm not seeing any issues with VLC and it seems like your snapshots are still coming through via rtsp.

Anything unusual in the logs?

Do you think you could run the container with an older image which should have the previous build of rtsp-simple-server:
```yaml
image: mrlt8/wyze-bridge:1.8.11
```

**Comment by IceDraken** [comment]
Just that it keeps trying to reconnect to cameras here and there.  So I am going to go out and reboot all my outdoor access points and see if its something with my wifi.

**Comment by IceDraken** [comment]
@mrlt8 I think you can close this.  It has to do with signal strength.  Even though I can view it in the App, it's via the substream.  The signal strength and wireless weren't enough to support the full 1080P stream.  I readjusted all my outdoor AP's and a few indoor ones that feed these cameras and it all seems good.
