### ISSUE TITLE
Custom UI Port: Not Working

### ISSUE THREAD

**Issue by destinybonavita** [mrlt8/docker-wyze-bridge#586]
Hi! I'm using a `docker-compos.yml` file with a custom UI port but its saying it's still using port 5000. I'm not sure if I'm doing something wrong or not but i'm not seeing any errors.

**Comment by destinybonavita** [comment]
I wanted to note i've tried changing `FLASK_RUN_PORT` as well with no luck

**Comment by mrlt8** [comment]
You'll need to change the external port (before the `:`) 
e.g., to have the web-ui use port 8080:
```yaml
ports:
    - 1935:1935 # RTMP
    - 8554:8554 # RTSP
    - 8888:8888 # HLS
    - 8080:5000 # WEB-UI
```

**Comment by destinybonavita** [comment]
> You'll need to change the external port (before the `:`) e.g., to have the web-ui use port 8080:
> 
> ```yaml
> ports:
>     - 1935:1935 # RTMP
>     - 8554:8554 # RTSP
>     - 8888:8888 # HLS
>     - 8080:5000 # WEB-UI
> ```

hm, switched it to `8080` but no luck. i'm running docker on the same pi as my octoprint instance which is already using 80 and 8000 so that's why i want to switch the port

<img width="586" alt="Screenshot 2022-11-02 at 12 31 27 AM" src="https://user-images.githubusercontent.com/24532951/199397512-a8b6b05b-6957-4cb4-8b25-14c47a6a848e.png">

**Comment by destinybonavita** [comment]
I just realized the screenshot shows `4200`, when I try to load `http://www.fisk-tower.local:8080` it just sits loading

**Comment by mrlt8** [comment]
An nothing in the logs when the connection is dropped?

**Comment by destinybonavita** [comment]
where are the logs located? i just updated the log level to debug to make sure i get everything

**Comment by mrlt8** [comment]
Flask logs should get printed to the console on `docker-compose up`. You can view the logs with `docker logs -f wyze-bridge` if you're running the container in detached mode.

Other logging levels are mostly related to tutk and/or ffmpeg.

Can you reach the API endpoints or are those getting dropped too?

```
http://localhost:5000/api
http://localhost:5000/api/<camera-name>
```

**Comment by destinybonavita** [comment]
not seeing any errors, the `/api` endpoint is being dropped as well

**Comment by mrlt8** [comment]
Could it be a firewall issue? Can you try another port?

**Comment by destinybonavita** [comment]
im trying to see how to know what port(s) are blocked and how to open them

**Comment by destinybonavita** [comment]
also wanted to note that `http://fisk-tower.local:5000/snapshot/gwen-cam.jpg` isn't working either

**Comment by destinybonavita** [comment]
weird that streaming is working but none of the other ports

**Comment by destinybonavita** [comment]
(sorry for all the comments), after doing some digging octoprint runs default on port `5000`, so that's probably why that is happening. is it possible to change the IP for the api?

**Comment by mrlt8** [comment]
Something like `sudo netstat -tulpn | grep LISTEN`? 
You may need to make some tweaks if you have a firewall like ufw.

**Comment by mrlt8** [comment]
> (sorry for all the comments), after doing some digging octoprint runs default on port `5000`, so that's probably why that is happening. is it possible to change the IP for the api?

yes, same as above when you changed it to 8080:

```yaml
 - 5001:5000 # WEB-UI
```

**Comment by destinybonavita** [comment]
> > (sorry for all the comments), after doing some digging octoprint runs default on port `5000`, so that's probably why that is happening. is it possible to change the IP for the api?
> 
> yes, same as above when you changed it to 8080:
> 
> ```yaml
>  - 5001:5000 # WEB-UI
> ```

Success! Switching that out fixed it. Thanks for your help!
