### ISSUE TITLE
Not getting latest version

### ISSUE THREAD

**Issue by jplwoodward** [mrlt8/docker-wyze-bridge#590]
Every time I start wyze bridge, I run mrlt8/wyze-bridge:latest, but I do not get the latest version, i get 1.8.10.  How do I upgrade to the latest veraion.  I do not use docker compose, I just run it from my /etc/rc.local.

**Comment by mrlt8** [comment]
Should be able to add `--pull=always` before the image `mrlt8/wyze-bridge:latest`:

```
docker run \
  -e WYZE_EMAIL=you@email.com \
  -e WYZE_PASSWORD=yourpassw0rd \
  -p 1935:1935 -p 8554:8554 -p 8888:8888 -p 5000:5000 \
  --pull=always \
  mrlt8/wyze-bridge:latest
```

**Comment by jplwoodward** [comment]
Thank you!  Your software is terrific!
