### ISSUE TITLE
[FATAL tini (8)] exec flask failed: Exec format error 

### ISSUE THREAD

**Issue by thatdaveguy1** [mrlt8/docker-wyze-bridge#604]
Yes, me again... been enjoying this plugin too much.

Environment:

HASSIO on M1 Mac via UTM Virtualization. aarch64.

I've installed the Add-On, but when starting it it immediately throws an error: [FATAL tini (8)] exec flask failed: Exec format error

**Comment by mrlt8** [comment]
This seems related to https://github.com/mrlt8/docker-wyze-bridge/issues/529.

Not exactly sure what is going on, but I'll try to look into it again.

**Comment by mattfusf** [comment]
Experiencing the same on an M1 Mac Studio, running Debian (aarch64) in UTM virtual machine. If I can provide any details to help find a fix I'm happy to help.
