### ISSUE TITLE
Ability to specify username/password for webUI interface

### ISSUE THREAD

**Issue by ofadam** [mrlt8/docker-wyze-bridge#612]
Would it be possible to include some sort of credentialing for the webUI interface? 

The webUI interface gives away quite a bit of information about each camera – and allows access to all cameras associated with an account. With optional credentials for the dashboard, users would still be able to open the snapshot URL on the same port, but not discover the other cameras unless knowing the names.

**Comment by mrlt8** [comment]
This is probably a good idea, as the next release will include the ability to send commands to the camera. Will look into it!

**Comment by JA16122000** [comment]
Good idea!
So olny specific people, you want, can watch your cams :D

**Comment by mrlt8** [comment]
You can already add authentication to the streams with:

```yaml
- RTSP_PATHS_ALL_READUSER=123
- RTSP_PATHS_ALL_READPASS=asd
```
