### ISSUE TITLE
Preview Not Available

### ISSUE THREAD

**Issue by dmkjr** [mrlt8/docker-wyze-bridge#619]
Evening --
I'm not sure what is going on.  I updated to v1.9.1 this evening and now I've noticed each block shows "Preview not Available" as a snapshot.  I can play the streams, but none of them are appearing.

Any idea?

<img width="1490" alt="Screenshot 2022-11-21 at 9 32 16 PM" src="https://user-images.githubusercontent.com/662675/203206906-b82714aa-9af4-420f-a727-a04afd40b516.png">

**Comment by mrlt8** [comment]
I noticed this as well, and have been looking into it.

**Comment by mrlt8** [comment]
Hey @dmkjr could you see if the dev branch helps?

**Comment by dmkjr** [comment]
That worked. Sorry for the slow update.

**Comment by baonguyengia1308-coder** [comment]
<img width="1896" height="791" alt="Image" src="https://github.com/user-attachments/assets/d3179b82-ab0b-4a4b-9149-9d22ef6a8259" />

It happen with me to, idont know why is not working
