### ISSUE TITLE
Outdoor cam does not work

### ISSUE THREAD

**Issue by pbarone** [mrlt8/docker-wyze-bridge#62]
When trying to stream my outdor cam feed I get this error in the log

Unexpected mode for connect challenge response (10001): 6
2021/08/07 22:59:14 [Front Porch] 'NoneType' object has no attribute 'encode'

and then a lot of these
2021/08/07 22:59:16 [Front Porch] AV_ER_EXCEED_MAX_CHANNEL

**Comment by mrlt8** [comment]
Will take a look, but not sure if having an rtsp stream from the outdoor cam is a great idea.

**Comment by xk42** [comment]
Weird, I just started getting this on one of my v3 camera as well. It was working earlier today.

wyze-bridge    | 2021/08/08 04:07:25 [Front Porch Cam2] AV_ER_EXCEED_MAX_CHANNEL
wyze-bridge    | 2021/08/08 04:07:26 [Front Porch Cam2] AV_ER_EXCEED_MAX_CHANNEL
wyze-bridge    | 2021/08/08 04:07:27 [Front Porch Cam2] AV_ER_EXCEED_MAX_CHANNEL
wyze-bridge    | 2021/08/08 04:07:27 [Front Porch Cam2] AV_ER_EXCEED_MAX_CHANNEL

**Comment by pbarone** [comment]
fair enough, but I think it should ignore it, not fill the log with errors. Maybe output just one line saying Outdoor cams are not supported?
