### ISSUE TITLE
Unable to Save Configuration Entries

### ISSUE THREAD

**Issue by wergeld** [mrlt8/docker-wyze-bridge#627]
Fresh install of v1.9.2 on Home Assistant running on Raspberry Pi 4 8Gb.
Steps taken:
Added the repository via button at https://github.com/mrlt8/docker-wyze-bridge/wiki/Home-Assistant#install.
Opened Add-On store and clicked on the "Docker Wyze Bridge"
Clicked "Install"
Once done I clicked on the Configuration tab and entered in my Wyze user/pw and scrolled down to "Save" button which was "greyed out" and clicked it. Green check-mark appeared by user/pw field was cleared out.
Clicking on "Start" in the Info tab gives popup error:
Missing required option 'WYZE_EMAIL' in Docker Wyze Bridge (7094bb28_docker-wyze-bridge).

Going back and updating other items in Configuration and clicking on "Save" does not actually save but reverts to initial config.

System details:
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20220907.2 - latest

**Comment by cma168** [comment]
Sorry - ignore my issue - user error.  I entered my credentials and scrollled to the bottom to click save.  However, I didn’t notice there was a save button for the first pane.  Clicking on that save button worked.

**Comment by wergeld** [comment]
Correct. User/Interface error. Two save buttons. I scrolled all the way to the bottom and missed the intermediate save.
