### ISSUE TITLE
Minor wiki change

### ISSUE THREAD

**Issue by cameronetchart** [mrlt8/docker-wyze-bridge#634]
Currently the wiki page for [HomeKit Secure Video](https://github.com/mrlt8/docker-wyze-bridge/wiki/HomeKit-Secure-Video), under Setup, has step 1 as "Install [Scrypted](https://github.com/koush/scrypted/wiki/Installation:-Docker-Compose)". This is the incorrect link (it opens the "create new wiki page" page), and it should be the same as the first paragraph on the page, going to https://github.com/koush/scrypted. 

Thanks for the project, enjoying setting it up!

**Comment by mrlt8** [comment]
Thanks! updated the link to point to https://github.com/koush/scrypted#installation
