### ISSUE TITLE
Wyze 2FA popup not showing up in web ui

### ISSUE THREAD

**Issue by MattEllison95** [mrlt8/docker-wyze-bridge#636]
Docker container not detecting two factor authentication.

**Comment by MattEllison95** [comment]
Requests to /mfa/<code> also do not work.

**Comment by mrlt8** [comment]
Will try to see if they changed anything with 2FA in the API.

Are you getting any errors in the docker logs or in the WebUI?

**Comment by joe2k1** [comment]
I had these exact same problems, although I was able to get it to accept the 6 digit 2FA code using environment variables. For reasons I cannot explain I have not been able to reproduce when I get it to work once or twice.

**Comment by mrlt8** [comment]
hmm just tried adding a time-based one-time password to my dummy account and it seems to be detecting it and working in the webUI.


```
[WyzeBridge] 🕵️ Cached email doesn't match 'WYZE_EMAIL'
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] 🔐 MFA Token Required
[WyzeBridge] 📝 Enter verification code in the WebUI or add it to /tokens/mfa_token.txt
[WyzeBridge] 🔑 Using 749357 for authentication
[WyzeBridge] 172.18.0.1 - - [13/Dec/2022 03:33:55] "GET /mfa/749357 HTTP/1.1" 200 -
[WyzeBridge] ✅ Verification code accepted!
[WyzeBridge] 💾 Saving 'auth' to local cache..
```

**Comment by TWG-Matt** [comment]
I'm having the same issue.  I have added my 2FA from 1Password but when I restart the container, it doesn't recognize it at all.  What is the env variable that needs to be added?

**Comment by mrlt8** [comment]
like this?

```yaml
environment:
    - TOTP_KEY=MYSECRETKEY12345
```

**Comment by MattEllison95** [comment]
I ended up figure out why - my Windows Clock was off by like 2 minutes so the 2fa code was invalid. Make sure your clock settings are set correctly on the device you’re getting the code from.
