### ISSUE TITLE
How to get (WEB_AUTH=True) working 

### ISSUE THREAD

**Issue by capncybo** [mrlt8/docker-wyze-bridge#639]
I Added: WEB_AUTH=True  to the bottom of my docker-compose.yml such as...
            - WEB_AUTH=True
And I deleted my old docker raspberry pi containers & images, & rebuilt them a new but when browsing to:
http://192.168.50.150:5000/?columns=4&order=front-door,front-yard,alley,garage
OR even a basic...
http://192.168.50.150:5000/
It still connects as usual without prompting me for a username & password.
WHAT am I doing wrong, or misunderstanding??

**Comment by JA16122000** [comment]
under environment:

- WEB_AUTH=True
- WEB_USERNAME=PutHereYourName
- WEB_PASSWORD=AndHereYourPassword

**Comment by capncybo** [comment]
@JA16122000   I had thought the username & password were supposed to default to the
            - WYZE_EMAIL=mine
            - WYZE_PASSWORD=password
Soooo I just tried adding your suggestion above but even after deleting my docker container & rebuilding...
No Authorization requested.

However I did see a reference of the Authorization being disabled  via mrlt8

**Comment by mrlt8** [comment]
hmm, just tried `docker-compose up` with 
```yaml
    environment:
      - WEB_AUTH=true
```
and 
```yaml
    environment:
      - WEB_AUTH=true
      - WEB_USERNAME=admin
      - WEB_PASSWORD=admin
```
and they both seem to work for me. could you try opening the page in another browser or in private mode to see if something is getting cached in the browser?

**Comment by capncybo** [comment]
Sorry, I'm fairly certain this was an error on my part.
I discovered that I had another separate docker-compose.yml file elsewhere.
Most Likely taking priority over the one inside my ~/docker-wyze-bridge-1.10.1 directory
But I also relocated the new environment variables to a position directly under the...
  environment:
Anyways it's working now, thank you for everything & Merry Christmas
CLOSING
