### ISSUE TITLE
Some cameras not updating-Home Assistant

### ISSUE THREAD

**Issue by sjmotew** [mrlt8/docker-wyze-bridge#647]
I have 6 Wyze cams running, most are doing very well.  Several however fail to update and show snapshots or streams that are days old.  Have tried restarting, resetting cameras, and reloading HA and docker-wyze-bridge.  It does seem to be the same 1 or 2 cameras.  Happy to share any relevant logs if helpful.

**Comment by mrlt8** [comment]
Is that just the snapshot? the default setting will pull the image from the Wyze API once at start up.

**Comment by sjmotew** [comment]
I figured out that the cameras that were not updating had been loaded with older RTSP-enabled firmware.  Updated to the most recent firmware from Wyze-site and fixed issue.  Might want to add to instructions as I suspect users migrating to docker-wyze-bridge may have been using direct RTSP.  Thnk you

**Comment by mrlt8** [comment]
Will need to investigate this further as it should be backwards compatible with all firmware.
