### ISSUE TITLE
How do I record streams to file?

### ISSUE THREAD

**Issue by garrettmueller** [mrlt8/docker-wyze-bridge#648]
After wasting my time trying to install an add on to my docker version of Home Assistant, I ended up here and this Docker works great. I can see my cameras quality is awesome. But how do I record natively in this program? Without using another program? Would really appreciate it I'm sorry I'm not sure what to do with the lines of commands the instructions have.

**Comment by mrlt8** [comment]
Some recording info here https://github.com/mrlt8/docker-wyze-bridge/wiki/Stream-Recording
Cleanup is still missing, so you'll need to manually remove older clips.

**Comment by mclever** [comment]
@mrlt8 any plans to be able to write to Nas instead of local drive only?

**Comment by mrlt8** [comment]
I'll look into it, but I believe it may be possible to mount the path to your NAS in your docker-compose under `volumes`?

**Comment by mrlt8** [comment]
The default path for home assistant is `"RECORD_PATH": "media/wyze/{CAM_NAME}"` which should persist even if the container is restarted. You should be able to specify your own path with `RECORD_PATH`, but keep in mind that the add-on only has the media directory mapped to the container.
