### ISSUE TITLE
v0.5.3 stopped working

### ISSUE THREAD

**Issue by pbarone** [mrlt8/docker-wyze-bridge#65]
When I try to connect to my V3 stream I get this error

2021/08/08 14:05:24 I [1/0] [RTSP] [conn 10.0.0.49:56188] ERR: path must end with a slash (back-yard-cam)

if I add a slash to the path I get this

2021/08/08 14:07:02 I [1/0] [RTSP] [conn 10.0.0.49:49845] ERR: invalid path name: can't end with a slash (back-yard-cam/)

here is the full log session when starting the container

2021/08/08 14:08:53 [Back Yard Cam] Starting 1080p 120kb/s Stream for WyzeCam V3 (WYZE_CAKP2JFUS) in "LAN mode" FW: 4.36.2.5 IP: 10.0.0.59 WiFi: 83%
2021/08/08 14:08:58 I [0/0] [RTSP] [conn 127.0.0.1:49210] opened
2021/08/08 14:08:58 I [0/0] [RTSP] [session 257817575] opened by 127.0.0.1:49210
2021/08/08 14:08:58 I [0/0] [path back_yard_cam] created
2021/08/08 14:08:58 I [1/0] [RTSP] [session 257817575] is publishing to path 'back_yard_cam', 1 track with UDP
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63140] opened
2021/08/08 14:09:03 I [1/0] [path back-yard-cam] created
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63140] ERR: no one is publishing to path 'back-yard-cam'
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63140] closed
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63141] opened
2021/08/08 14:09:03 I [1/0] [RTSP] [session 145956398] opened by 10.0.0.49:63141
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63141] ERR: path must end with a slash (back-yard-cam)
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63141] closed
2021/08/08 14:09:03 I [1/0] [RTSP] [session 145956398] closed
2021/08/08 14:09:03 I [1/0] [RTSP] [conn 10.0.0.49:63142] opened
2021/08/08 14:09:04 I [1/0] [RTSP] [conn 10.0.0.49:63142] closed

**Comment by milkplus27** [comment]
Yup, I'm experiencing something similar since updating. Just keep getting the following error:

```

2021/08/08 14:32:29 I [3/0] [RTSP] [conn 172.21.0.1:43544] ERR: no one is publishing to path 'back-yard-cam'
```

Any way to rollback to the previous version?

**Comment by GabbySF** [comment]
He change the clean_name from replacing " "  with "-" to replacing " " with "_" basically now your camera is called back_yard_cam' instead of back-yard-cam'

**Comment by milkplus27** [comment]
> He change the clean_name from replacing " " with "-" to replacing " " with "_" basically now your camera is called back_yard_cam' instead of back-yard-cam'

ah yup. that sorted it for me, cheers!

**Comment by pbarone** [comment]
Yes that works! Thank you

**Comment by pbarone** [comment]
I would recommend changing the instructions to specify that underscore needs to be used instead of hyphen

**Comment by mrlt8** [comment]
> He change the clean_name from replacing " "  with "-" to replacing " " with "_" basically now your camera is called back_yard_cam' instead of back-yard-cam'

Good catch! I was testing some things out with the updated rtsp-simple-server and forgot to change it back.

Would most of you prefer the `_` or the `-` for the URI?

**Comment by GabbySF** [comment]
Yeah keep it with the _ please I don't wanna go back and change it all again ;) also kick ass job with this project!!

**Comment by mrlt8** [comment]
Thanks! 
It will now default back to `-` but can be changed to `_` with `- URI_SEPARATOR=_`
