### ISSUE TITLE
HA: Putting snapshots in /config/www allows for public access to cameras

### ISSUE THREAD

**Issue by jackrosenthal** [mrlt8/docker-wyze-bridge#660]
The feature to copy snapshots into `/config/www` is not only unnecessary (HA can be pointed at `http://localhost:5000` just fine), but also leaks camera images to the public if the home assistant server is port forwarded to the internet, as `/local/*` can be viewed without authentication.

**Comment by jackrosenthal** [comment]
It looks like users can mitigate this privacy risk by setting `IMG_DIR` in the configuration to something outside of `config/www`.

**Comment by mrlt8** [comment]
Good point. The snapshots in `/config/www` actually predate the the existence of the web UI and can probably be removed now that we have the web UI.
