### ISSUE TITLE
Add ability to change port number for HLS, RTMP, RTSP links on the cameras

### ISSUE THREAD

**Issue by talormanda** [mrlt8/docker-wyze-bridge#667]
For users where the default ports are unable to be used for HLS, RTMP, RTSP, I have to remap them outside my container. Example: Port 8888 is in use by my system for something else, which means I have to map port 8888 on the container to port 8889 outside the container. 

This breaks the button under HLS because when I copy the link, it auto includes port 8888 because that is what the container sees.

Is it possible to add a setting where you can visually specify the URL for HLS, RTMP, RTSP, so we can change the port and have the URL be correct? Currently, I have to copy the link, paste it, then change the port number. Kind of annoying.

**Comment by mrlt8** [comment]
Yes, see https://github.com/mrlt8/docker-wyze-bridge#web-ui

Unfortunately we can't read external port changes from inside the container, but you should be able to remap your HLS with:

```yaml
- WB_HLS_URL=http://my-hostname-or-ip:8889/
```

**Comment by talormanda** [comment]
> Yes, see https://github.com/mrlt8/docker-wyze-bridge#web-ui
> 
> Unfortunately we can't read external port changes from inside the container, but you should be able to remap your HLS with:
> 
> ```yaml
> - WB_HLS_URL=http://my-hostname-or-ip:8889/
> ```

Sorry. I must have scrolled past that. That will do it.

**Comment by mrlt8** [comment]
It should save to a cookie, but you can also force it with something like `http://localhost:5000/?columns=2`

**Comment by VincePimentel** [comment]
Is this possible to do in Home Assistant?

**Comment by mrlt8** [comment]
Yes, you may need to toggle the "Show unused optional configuration options" to display the "Custom HLS URL" options.
