### ISSUE TITLE
Portainer Stack Option 3 - updated Link

### ISSUE THREAD

**Issue by Mkallday** [mrlt8/docker-wyze-bridge#671]
[Portainer Stack Page](https://github.com/mrlt8/docker-wyze-bridge/wiki/Portainer)

- additional info link to Portainer Docs:  404

Updated Portainer Link: 
https://docs.portainer.io/user/docker/stacks/add#option-3-git-repository

**Comment by mrlt8** [comment]
Thank you! Will update the page!
