### ISSUE TITLE
How to use Motion with Wyze?

### ISSUE THREAD

**Issue by asyba** [mrlt8/docker-wyze-bridge#672]
How I can use Motion, I can't find any example.

Im using Cam Wyze V2 with stock firmware latest version.
Using home bridge on rpi 4 with docker-wyze-bridge + homebridge-camera-ffmpeg

```
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Living",
                    "manufacturer": "WyzeCam",
                    "model": "WYZEC1-JZ",
                    "unbridge": true,
                    "debug": true,
                    "motion": true,
                    "videoConfig": {
                        "source": "-i rtsp://xxxx:8554/living-room-cam",
                        "vcodec": "copy"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

homebridge-camera-ffmpeg said that I need to add this and then somehow trigger to this Topic, how I can do that from  docker-wyze-bridge ?

here https://github.com/mrlt8/docker-wyze-bridge#motion-alerts say somethinb about old firwmare , but what old version??

```
"mqtt": {
        "motionTopic": "home/camera",
        "motionMessage": "ON",
        "motionResetTopic": "home/camera",
        "motionResetMessage": "OFF",
        "doorbellTopic": "home/doobell",
        "doorbellMessage": "ON"
      }
```

**Comment by mrlt8** [comment]
Unfortunately, the "boa" http server on the camera that gave access us access to the SD card was gradually removed from all of the cameras starting in March 2022, so anything before that _should_ have still have it enabled.

**Comment by asyba** [comment]
> Unfortunately, the "boa" http server on the camera that gave access us access to the SD card was gradually removed from all of the cameras starting in March 2022, so anything before that _should_ have still have it enabled.

can I downgrade? to 4.9.8.1002 (March 17, 2022)
https://support.wyze.com/hc/en-us/articles/360024852172
but since that date they removed the firmare, do you know other source?

The march version has RTSP? like the last one (December 7, 2022)?

**Comment by mrlt8** [comment]
They're still up. Just not publicly linked:
```
https://s3.us-west-2.amazonaws.com/download.wyzecam.com/firmware/v2/demo_4.9.8.860.zip
https://download.wyzecam.com/firmware/rtsp/demo_4.28.4.51.bin
```
Another alternative is to run the rtsp streams through something like scrypted to get motion alerts in homekit.
