### ISSUE TITLE
Webrtc Audio Disabled

### ISSUE THREAD

**Issue by d4rk50ul1** [mrlt8/docker-wyze-bridge#676]
Hi, i have 4 wyze cam v3 and 1 wyze cam pan v1. i'm trying to hear the cams over WebRTC but it always shows as disabled, not sure how to fix/enable it.
![image](https://user-images.githubusercontent.com/18516091/213021558-7d1b59e6-9271-467e-ae6f-c60697959978.png)

**Comment by mrlt8** [comment]
Do you have audio enabled on the bridge? 
```yaml
- ENABLE_AUDIO=true
```

**Comment by d4rk50ul1** [comment]
Yes i do

**Comment by mrlt8** [comment]
Hmm, does the audio work for the other streams (RTSP/HLS/etc)? I see the same disabled icon if audio is disabled in the bridge, but it is selectable when `ENABLE_AUDIO` is enabled.

**Comment by tlm2021** [comment]
Bit of a newbie here, but I'm having the exact same issue (Wyze Cam v3). None of the streaming options have audio available.

The Docker Wyze Bridge UI shows that audio is enabled:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/4755701/213566489-e8178615-5129-4a85-8a0b-ceecd7f0b0a7.png">

The logs also indicate the audio should be there, though there is a `Output file #0 does not contain any stream` message.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/4755701/213566916-2fe03947-2f74-4653-b6cb-350798bf7a7a.png">

**Comment by mrlt8** [comment]
Hmm, I think WebRTC only supports a limited number of audio codecs. Can you try setting:
```yaml
- AUDIO_CODEC=libopus
```

**Comment by d4rk50ul1** [comment]
I confirm that libopus as audio codec Works. Thanks!!
