### ISSUE TITLE
Bridge not finding new v3 pan

### ISSUE THREAD

**Issue by robmiller1000** [mrlt8/docker-wyze-bridge#686]
I just purchased new v3 cam pan. I have 2 cameras already running on the docker and they work fine. I am trying to add my new cam and it will not show up. I have uninstalled and reinstalled docker and this has not help at all. Any help would be appreciated.

**Comment by mrlt8** [comment]
Does setting `FRESH_DATA` help by any chance?

```yaml
- FRESH_DATA=true
```

**Comment by aflores29** [comment]
I can confirm that the V3 pan works.

**Comment by robmiller1000** [comment]
thank you,
