### ISSUE TITLE
Allow Higher Quality {Enhancement}

### ISSUE THREAD

**Issue by Travisco29** [mrlt8/docker-wyze-bridge#70]
Any way you could allow for a higher bitrate then 240? i notice in the wyze app it uses along the lines of 350kb for streaming.

**Comment by mrlt8** [comment]
I got the 240 value from the upstream [documentation](https://kroo.github.io/wyzecam/reference/tutk/tutk/#wyzecam.tutk.tutk.BITRATE_SUPER_SUPER_HD). 
I think I tried going over 240, but got some errors whenever I went over 256, so decided to hardcode the 240 limit from the documentation.

I'll take a second look and also check the tutk documentation for any limitations.

**Comment by Travisco29** [comment]
ok thanks!

**Comment by mrlt8** [comment]
v0.5.6 should allow up to 255 now, but I noticed a few more frame drops with the higher bitrate. YMMV
Looking into the official app, it seems like it actually has support for 30, 60, 64, 120, 180, and 240.
Either way, I don't think "bitrate" value represents the actual "bitrate".
