### ISSUE TITLE
Snapshot timer not functioning

### ISSUE THREAD

**Issue by ofadam** [mrlt8/docker-wyze-bridge#703]
I can't seem to get this to function as expected – I've tried using the default timer setting and setting 120 seconds, but to no avail. Only the original version of the /img generated at Docker launch continues to be served (cached via 304.)

`SNAPSHOT=RTSP Will run every 180 seconds (configurable) and wll grab a new frame from the RTSP stream every iteration and save it to /img/cam-name.jpg on standard docker installs or /config/www/cam-name.jpg in Home Assistant mode. Can specify a custom interval with SNAPSHOT=RTSP(INT) e.g. SNAPSHOT=RTSP30 to run every 30 seconds`

I should also mention that I'm running this is on-demand mode – would that make this not possible?

**Comment by mrlt8** [comment]
Yes, on-demand mode currently disables the snapshot timer. Still need to look into this as I don't want to drain the battery on the outdoor cams.

However, you can always pull a new snapshot via the webUI at any time using the endpoint: `:5000/snapshot/camera-nickname.jpg`.

**Comment by ofadam** [comment]
I wonder if there's a way to have it skip pulling the snapshot on any camera IDs that match to the outdoor models? I was hoping to pull from the /img endpoint since it's cached and a lot faster than grabbing the snapshot, especially when multiple users are requesting at once.

**Comment by mrlt8** [comment]
As a temporary solution, you could create your own snapshot timer by making a request to the /snapshot/cam.jpg endpoint periodically which should update the snapshots on the /img endpoint that your clients can access.
