### ISSUE TITLE
IOTC_ER_DEVICE_REJECT_BYPORT - no cameras working

### ISSUE THREAD

**Issue by carldanley** [mrlt8/docker-wyze-bridge#708]
![Screen Shot 2023-02-06 at 6 17 17 AM](https://user-images.githubusercontent.com/75226177/216958414-e1d43232-4d0c-4af7-bda8-1755b65c96f4.png)

Hi again! I started getting this a couple of days ago and I'm not sure what's up. All 5x of my Wyze Cam Pro v3's stopped working. Anyone else having this issue?

**Comment by mrlt8** [comment]
does `- FRESH_DATA=true` help?

**Comment by carldanley** [comment]
It didn't - though it seems like it's an actual camera issue. Even the Wyze app itself is having a hard time connecting to the camera. I've checked WiFi strength and everything so will just have to continue trying when I have time again.

**Comment by mrlt8** [comment]
Probably a bug in the firmware. Power cycling the camera may help in some situations.

**Comment by carldanley** [comment]
It's been forever since I made this issue but wanted to follow-up on what was causing this for documentation-sake. It turns out that the root of the cause was my Unifi equipment's "Nightly Channel Optimization" being turned on.

I guess the cameras don't like it when the WiFi changes channels; they don't reconnect very well, if at all. After disabling this feature, my cameras now stay connected and I rarely run into this issue, if at all.

Going to close this out!
