### ISSUE TITLE
Wyze Outdoor Cam Battery Drain

### ISSUE THREAD

**Issue by efloyd** [mrlt8/docker-wyze-bridge#709]
I'm experiencing accelerated battery drain with Wyze Outdoor Cam V2 running on Portainer with Wyze Bridge and Scrypted running on separate containers. 

I'll charge the camera to 100%, and it will be down to 0% in 6-8 hours. I'm hoping that someone here can validate my settings and/or provide guidance. And, I'm not sure if this more of a Wyze-Bridge question, or a Scrypted question. I do have a Ring Outdoor Cam Battery connected using the Ring plugin in Scrypted, and it doesn't drain nearly as fast - I'll get 10-15 days out of that battery, which leads me to believe that it has something to do with the settings I have for the Wyze camera.

For the Wyze Bridge container, I do have the variable ON_DEMAND set to True. It's my understanding that this forces the camera to not stream unless the stream is called, which in my case would be Scrypted and Homekit.

I've attached screenshots of the settings for this Wyze Outdoor V2 cam in Scrypted. 

![Scrypted - 1 RTSP Camera](https://user-images.githubusercontent.com/33038738/217069142-935977ff-5f7c-4833-8540-2ef88f52b37f.png)
![Scrypted - 2 Snapshot](https://user-images.githubusercontent.com/33038738/217069161-4b234fd2-072e-4078-8d2c-916aca471625.png)
![Scrypted - 3 PAM Diff Motion Detection](https://user-images.githubusercontent.com/33038738/217069167-f0896ec4-ae45-4025-90ee-8c001c6603a1.png)
![Scrypted - 4 Streams - Manage](https://user-images.githubusercontent.com/33038738/217069176-7d5ecf0d-1833-44d0-b0bf-5b2b8f283747.png)
![Scrypted - 4 Streams - Stream](https://user-images.githubusercontent.com/33038738/217069186-fc7005cd-1671-4f39-b21e-ae78d666003d.png)
![Scrypted - 5 Transcoding](https://user-images.githubusercontent.com/33038738/217069196-bc3fda8a-2298-42eb-95cd-efaf033302fb.png)
![Scrypted - 6 Extensions](https://user-images.githubusercontent.com/33038738/217069202-52e4c686-6417-4ec2-9850-5c4ea82151d8.png)

Any guidance would be appreciated!

**Comment by mrlt8** [comment]
I believe it's the pre-buffer and motion detection which will keep a connection to the camera open. 

Unfortunately, the bridge tries to keep everything local, so we don't have access to the motion sensor (yet), but you may be able to poll the status using one of the other wyze plug-ins.

**Comment by efloyd** [comment]
I'm now experiencing a completely different issue - when I had 1 Outdoor Cam and 2 V2 cams, things seemed pretty stable. I just added a second Outdoor Cam, and it's become very unstable, and I can't seem to get the cams to load in the Wyze App when the the Wyze-Bridge container is running.

I deleted both the Stack and Container in Portainer, and redployed everything, setting ON_DEMAND to "True" and NET_MODE to "LAN". 

I'm seeing a lot of "Snapshot Unavailable", cams dropping, inability to view cams in Wyze App, cams not refreshing at all in Wyze-Bridge.

**Comment by mrlt8** [comment]
Could be the cameras flooding your wifi if you only experience it when streaming simultaneously.

May need to check your router for IGMP Snooping/IGMP Proxy related settings. 

ubiquiti unifi and tp-link deco seem to have more issues with the wyze cams.

**Comment by jshg46** [comment]
I have 2 outdoor cams myself, this does kill the batteries quick.

**Comment by efloyd** [comment]
Good news is that I think I've stabilized my 2 V2s and 2 Outdoor V2s. Here's what I did:
1. I was running the old RTSP firmware on the V2s, so I upgraded them to the most recent V2 firmware
2. I changed 2.4 GHz channel on my Netgear Orbi Mesh system (RBR850) to channel 11. It was on Auto before.
3. I disabled IGMP proxying on the Netgear Orbi.
4. I unchecked "Enable 20/40 MHz Coexistence" on the Netgear Orbi to disable it.
5. I unchecked "Enable WMM (Wi-Fi multimedia) settings to disable it.

I'm not sure if all of these contributed to the stability, but things seem to be working better. My cams are staying connected, and I'm seeing fewer cam drops in the wyze bridge logs.

The setup is still draining the batteries pretty quick on my Outdoor V2s. I added the solar panels, but they can't keep up. If I can't find a solution for the battery drain, I'm going to have to switch back to the Ring Cam Batteries with solar.

The Ring Battery Cam running with the Scrypted plugin doesn't drain, and the solar panel can keep up.

I was really hoping the Wyze cams would work for me because of their price point, small form factor, and simple-to-use app. I'd prefer to not have to use two camera brands and have to switch back and forth between apps to view recorded events when HSK craps out.

**Comment by mrlt8** [comment]
Unfortunately, the cameras will continue to drain if pre-buffering and/or motion detection are turned on for the battery cameras in scrypted including the [ring](https://www.npmjs.com/package/@scrypted/ring):

> The persistent live stream will drain the battery faster than it can charge.

**Comment by efloyd** [comment]
Is there anyway to disable the persistent stream for the Outdoor Cams and rely on the events triggered by the camera itself?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jshg46** [comment]
I just gave up on it for the time being. I cant just keep on killing the batteries. Maybe a fix for this will be found soon.

**Comment by mrlt8** [comment]
@efloyd you need to disable pre-buffering and any motion detection in scrypted. You may be able to poll the motion status from the web API using one of the other wyze libraries like https://github.com/JoshuaMulliken/wyzeapy or https://github.com/shauntarves/wyze-sdk and use that as a motion sensor in scrypted. Keep in mind that wyze doesn't like people doing this.

@jshg46 This is a design flaw in the camera itself. The bridge already stops streaming when there aren't any clients connected, and there isn't anything that can be done to "fix" the battery.

**Comment by efloyd** [comment]
I decided to give the Ring Cam Battery another try - the standalone cam battery without the solar panel, for now. I installed the Scrypted Ring plugin, which allowed me to add the Ring cam to Homebridge.  Configured motion alerts and recording in the Home app, and I get Homekit notifications on motion and HKSV recording, just like I did with my Wyze Cam Outdoors.

So far, I've been running it for 2 weeks straight and it's taken this long for the batter to get to 29%. If I add the solar panel, I'm sure it will be able to keep up at that rate. And I do check my Home app pretty often which forces the Ring cam to refresh its snapshot. 

I'm not sure sure what the technical/implementation differences are between the Wyze Bridge exposing the cams to Scrypted via RTSP vs the Ring plugin for Scrypted. For the Ring camera, I don't have to enable the Rebroadcast, Snapshot or Motion Detection plugins in Scrypted That functionality seems to be inherently built into the Scrypted Ring plugin?

Unless anyone has any guidance on how to prevent so much battery drain on the Wyze Cam Outdoors with the Wyze Bridge exposing RTSP to Scrypted, I think I'll be switching to Ring cameras. Which is a huge bummer because not only are the Ring cameras so much more expensive, I love everything about the Wyze cameras - the images/video are better, the AI events are better, the Wyze app is better, the form factor is better, the power cables are easier to manage/hide, and I love the new V3 Pan Cam.

Below are screenshots of the Ring camera configuration in Scrypted:

![image](https://user-images.githubusercontent.com/33038738/222474686-724c76d5-1eab-4ccf-8ec9-9bdf3bf4a7d0.png)

![image](https://user-images.githubusercontent.com/33038738/222474726-483d164e-dd39-44c7-a359-f587792a4628.png)

**Comment by tae180** [comment]
I’m having an issue with my wyze outdoor camera battery draining fast.  Can’t go 1 day when I have docker wyze bridge running. Any suggestions?

**Comment by efloyd** [comment]
> I’m having an issue with my wyze outdoor camera battery draining fast. Can’t go 1 day when I have docker wyze bridge running. Any suggestions?

I had the same issue. Couldn’t resolve. I’m switching to Ring cams using the Scrypted plugin. My Ring battery cams take days to run down, and never run down with the solar attachment. 

I love the Wyze cams, but didn’t want to use two different cam brands and juggle 2 different apps.

**Comment by weromemuero** [comment]
> I’m having an issue with my wyze outdoor camera battery draining fast. Can’t go 1 day when I have docker wyze bridge running. Any suggestions?

The only way I'm able to get my streams working without battery drain is without motion detection enabled... This are the plugins i have enabled on scrypted:

![imagen](https://github.com/mrlt8/docker-wyze-bridge/assets/135170924/d2182d66-c3af-49cd-8768-6f380df8d965)

No snapshot from prebuffer and no prebuffered stream.

I can get to stream the camera on the home app but cant use the HKSV options as i'm not activating the motion detection. With this settings my camera battery lasts at least 3+ weeks

**Comment by TheRealWaldo** [comment]
I am not using scripted, just the stock Home Assistant add-on, and I am having the battery drain issue.  Any suggestions?

**Comment by TheRealWaldo** [comment]
I'm using 2.8.3 of the HA add-on and have MOTION_API on, but it is not updating the images on either the wired or wireless cameras.  Not sure if that's the most current?

**Comment by TheRealWaldo** [comment]
I tried moving to the dev version with these settings:

```
NET_MODE: LAN
SNAPSHOT: API
MQTT_DTOPIC: homeassistant
ENABLE_AUDIO: false
MOTION_API: true
ON_DEMAND: false
SUBSTREAM: false
CAM_OPTIONS: []
```

The obvious API and account credentials are hidden. The thumbnail is not updating, and the motion entity for the outdoor cam remains 'unknown'.

I have it plugged into power for testing, so I don't know if it is still draining.

**Comment by TheRealWaldo** [comment]
I took the camera off power and it drained within a few hours using the above settings on the dev branch.

**Comment by mrlt8** [comment]
hmm, is something in HA trying to access the streams that is causing the battery to drain?

**Comment by TheRealWaldo** [comment]
This is a scratch installation of the Wyze addon, none of the cameras were set up previously.  There are no automations or anything else hooked up to it yet.  

Only thing I added was a picture entity for the snapshot to a dashboard.

**Comment by TheRealWaldo** [comment]
Another note: the entity shows that the stream is always on with the above settings.  If I set ON_DEMAND to true, it doesn't stream, but it also doesn't take snapshots, show motion, or allow you to manually take a snapshot on the outdoor cam.

**Comment by TheRealWaldo** [comment]
Another note: the entity shows that the stream is always on with the above settings.  If I set ON_DEMAND to true, it doesn't stream, but it also doesn't take snapshots, show motion, or allow you to manually take a snapshot on the outdoor cam.

**Comment by TheRealWaldo** [comment]
Using the new version, battery is still draining with the settings above.

**Comment by TheRealWaldo** [comment]
I might have a hint as to what is happening with the settings above. On startup, WyzeBridge tries to connect to ALL cameras. If any one camera is unreachable, it retries connecting to ALL cameras every 10 seconds, restarting the stream for ALL cameras every time.

Effectively, this means that if any one camera is unreachable, regardless of whether it is intentional or not, it will quickly deplete the batteries of all battery-operated cameras.

**Comment by TheRealWaldo** [comment]
I tried IGNORE_OFFLINE, which did stop the continuous retry on _ALL_ cameras, but it still continues to reconnect to and stream the battery-operated cam for some reason; also seeing:

```[WyzeBridge] [EVENTS] WyzeAPIError: code='1011' msg='system limit exceeded, please try again later.' method=POST path=/app/v4/device/get_event_list, cooling down.```

A lot.

**Comment by mrlt8** [comment]
Do you have another instance of the bridge running? Default settings shouldn't be exceeding the rate limit.

> Only thing I added was a picture entity for the snapshot to a dashboard.

is this pulling the image from the /media folder?

**Comment by TheRealWaldo** [comment]
There were no other instances.  I was not even attempting to pull images.

All I was doing was moving in front of the camera and watching the logs to see what it was doing.  Occasionally, I would alter the settings to see if I could get it to work, which would cause a restart.

**Comment by TheRealWaldo** [comment]
Re the picture entity; it's just pointing to the snapshot entity created by MQTT

If you view the preview from the entity itself, it throws an error (access denied). When viewed from the dashboard (had to pull this out of the generated HTML), it looks to be pulling the image from /api/camera_proxy which is the same behaviour as any other snapshot in Home Assistant.  

I have not sniffed out the MQTT to do any discovery on the source beyond that, but this would be the same behaviour as other camera sources with snapshots if it was coming from the media folder.
