### ISSUE TITLE
WYZEDB3 Doorbell not recording

### ISSUE THREAD

**Issue by sdleeke** [mrlt8/docker-wyze-bridge#711]
When the container starts a new video file appears, but the size is always zero.  There are no WebRTC or HLS streams for the doorbell, unlike the Waze Cam V3's that work fine, both WebRTC and HLS and recording is also working.

Has anyone seen/solved this problem w/ the Wyze Doorbell?

**Comment by mrlt8** [comment]
Do you have audio enabled? I believe there were some issues with ffmpeg if the audio codec wasn't compatible with the container.

**Comment by mrlt8** [comment]
Can you see the audio code that doorbell uses when audio is enabled? I can try to see if we might be able to use a different video container for the doorbell.

**Comment by sdleeke** [comment]
How would I find that?

**Comment by mrlt8** [comment]
It should show something like `🔊 Audio Enabled - MULAW/8,000Hz` in the logs when audio is enabled.

**Comment by sdleeke** [comment]
Wyze Cam V3's: Audio Enabled - ALAW/16,000Hz
Wyze Doorbell: Audio Enabled - PCM > LIBOPUS/8,000Hz

Thank you for building this; it is very helpful.
