### ISSUE TITLE
[WYZE_CAKP2JFUS] is not supported

### ISSUE THREAD

**Issue by HelpMeWyzePlz** [mrlt8/docker-wyze-bridge#719]
Can someone help me please?

Trying to connect my Wyze v3 cams to Home Assistant via the Docker Wyze Bridge but it says they are not supported.

![image](https://user-images.githubusercontent.com/125322113/218598989-6182ce63-0c22-423b-8b25-fb3b33584de2.png)

Thank You.

**Comment by mrlt8** [comment]
hmm. That is strange. It means that the camera data it received from wyze is missing some information needed to connect.

Is the camera on a beta firmware? Can you run it again with the Fresh Data option enabled?

**Comment by HelpMeWyzePlz** [comment]
Huh, okay that makes me feel a bit better. Just hoping the model i bought is supported.

I added them to the app first, and updated the firmware to 4.36.9.139

Sorry, what should I run again?

Thank You

![image](https://user-images.githubusercontent.com/125322113/218612416-9508478a-7d50-4570-9ead-ef84cb644157.png)

**Comment by HelpMeWyzePlz** [comment]
Oh my, It worked!

I found the Pull Fresh Data From Wyze API (Ignore local cache and pull fresh data from the wyze API.) and selected it.

I can see the camera now =)

Should i leave it enabled?

Thank You

**Comment by mrlt8** [comment]
Not sure why it didn't get the correct data the first time, but you should be able to disable it for now.
