### ISSUE TITLE
Unable to Auth - "Temporary failure in name resolution"

### ISSUE THREAD

**Issue by Mx772** [mrlt8/docker-wyze-bridge#721]
Full error:
```
2023/02/14 21:02:21 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2023/02/14 21:02:31 [WyzeBridge] HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b30239720>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

Not sure why it's getting a DNS error, no other containers are getting this error. 
Was able to ping from other containers. (No ping or curl/nslookup/etc installed on your native docker image to test dns)

It does seem it's not inheriting the DNS from the host for some reason. (I just updated to latest image then saw this error.)
```
root@487fe88230d4:/app# cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```

vs other containers/host:
```
>cat /etc/resolv.conf

nameserver 192.168.1.144
search .
```
Was there any recent changes to anything that would cause it to no longer inherit DNS/resolv.conf?

**Comment by mrlt8** [comment]
I don't think so. I just did a fresh data start on my container and it was able to auth correctly.

Are you still getting the error? I think some people were having this issue in the past with apparmor?

**Comment by Mx772** [comment]
Yeah, still getting it. 

Completely tore the stack down and put it back up. Same result. 

Super bizarre honestly as this is the only container seeing issues.
(Started happening after watchtower updated yesterday) 

Is there any cli cmds to mess with DNS to see if that is the issue? 
Trying to see if anything is actually leaving the container or not. 

I'm inclined to to say it is something DNS related because of the resolv.conf file, but I have no idea why it's not inheriting now.

**Comment by mrlt8** [comment]
Hmm. I believe the connection is getting dropped/block on the host..? 

Can you double check any firewall and/or AppArmor setting on the host?

**Comment by Mx772** [comment]
Looking at #107 it seems super similar. But I haven't touched AppArmor, so it's bizarre that it's throwing an issue. 
I don't see anything listed in AppArmor here:
```
> sudo aa-status | grep wyze

```

Everything else that mentions docker is also working fine (Calling out, etc)
```
> sudo aa-status | grep docker
   docker-default
   /usr/local/bin/python3.10 (460250) docker-default
   /usr/bin/busybox (3742098) docker-default
   /bin/s6-svscan (3742115) docker-default
   /watchtower (3742225) docker-default
   /portainer (3742411) docker-default
   /bin/s6-supervise (3742637) docker-default
   /usr/local/bin/python3.8 (3742779) docker-default
   /bin/s6-supervise (3742999) docker-default
   /bin/s6-supervise (3743000) docker-default
   /usr/bin/bash (3743002) docker-default
   /usr/sbin/nginx (3743003) docker-default
   /usr/bin/node (3743008) docker-default
   /opt/adguardhome/AdGuardHome (3743116) docker-default
   /usr/sbin/nginx (3743211) docker-default
   /usr/sbin/nginx (3743212) docker-default
   /usr/sbin/nginx (3743213) docker-default
   /usr/sbin/nginx (3743214) docker-default
   /usr/sbin/nginx (3743215) docker-default
```

**Comment by Mx772** [comment]
For what it's worth, if I try going to that URL on anything in my network, or even my phone (non-wifi) I get:
![image](https://user-images.githubusercontent.com/9059161/219252379-48045d80-1027-43a8-a60a-5be3e2170557.png)

**Comment by Mx772** [comment]
Disabled UFW, disabled AppArmor. Same error.

**Comment by Mx772** [comment]
So I figured it out....

It was my DNS server. (Broken with both PiHole & AdGuard) 

The issue? While defining the port for DNS in your DNS server, you have to define your IP address. So instead of saying:
```
    ports:
      - 192.168.1.144:53:53/tcp
      - 192.168.1.144:53:53/udp
```

You have to define the IP:PORT

```
    ports:
      - 192.168.1.12:53:53/tcp
      - 192.168.1.12:53:53/udp
```

I started to think it was DNS because I had just updated to 22.04 ubuntu, did a massive apt-get update/upgrade and then it broke. 

Most containers were fine, but a select few had resolution issues. For example, Wyze-bridge and another one being me-tube. 

I could see my DNS server getting the query, and responding. However... the container never got a response. To which I found this [reddit post](https://www.reddit.com/r/Adguard/comments/p5ouqo/adguard_home_dns_not_reachable_from_docker/). 

Sure enough, putting the IP fixed all the containers. 

So while it was semi-specific to wyze-bridge (It only affected a few containers out of about 50) it was actually a DNS server issue at heart. 

Thank you for the help though! Will Close and hope that others may find their resolution here in the future!

**Comment by maxfield-allison** [comment]
I'm having this same issue now except in my case, pihole is running in host networking mode.
