### ISSUE TITLE
x509: cannot validate certificate for [IPADDRESS] because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by blackthroat** [mrlt8/docker-wyze-bridge#725]
This very well may be a question I need to ask in the [Channels](https://community.getchannels.com/) forum, but figured someone could point me in the right direction.

When setting `LLHLS=true` in my Docker compose, I'm able to access the stream through a browser by IP or DNS hostname (https://nas01.lan:8888/living-room/ or https://172.16.0.15:8888/living-room/) after bypassing the certificate warning `(NET::ERR_CERT_AUTHORITY_INVALID)`. I'm able to access the stream through Channels

However, I'm unable to view the [HLS stream](https://getchannels.com/docs/channels-dvr-server/how-to/custom-channels/#supported-streaming-formats) through Channels:

hostname
```
#[ERR] Failed to start stream for ch9340: M3U: Could not fetch playlist: nas01.lan:8888: Get "https://nas01.lan:8888/living-room/stream.m3u8": x509: certificate is not valid for any names, but wanted to match nas01.lan
#[HLS] Couldn't generate stream playlist for ch9340-dANY-ip172.16.0.246: M3U: Could not fetch playlist: nas01.lan:8888: Get "https://nas01.lan:8888/living-room/stream.m3u8": x509: certificate is not valid for any names, but wanted to match nas01.lan
```

IP Address
```
#[ERR] Failed to start stream for ch9340: M3U: Could not fetch playlist: 172.16.0.15:8888: Get "https://172.16.0.15:8888/living-room/stream.m3u8": x509: cannot validate certificate for 172.16.0.15 because it doesn't contain any IP SANs
#[HLS] Couldn't generate stream playlist for ch9340-dANY-ip172.16.0.246: M3U: Could not fetch playlist: 172.16.0.15:8888: Get "https://172.16.0.15:8888/living-room/stream.m3u8": x509: cannot validate certificate for 172.16.0.15 because it doesn't contain any IP SANs
```

It's my understanding that [LLHLS](https://github.com/aler9/rtsp-simple-server#low-latency-variant) requires a certificate, and I believe that it's automatically generated and stored in `/tokens` in the container.

I've tried bridge and host networking in Docker, as well as setting the environment variable `WB_HLS_URL=https://nas01.lan:8888/` (although I don't believe this is the intended use case).

Inside the Channels container:
```
# curl -v https://172.16.0.15:8888/backyard/
*   Trying 172.16.0.15:8888...
* Connected to 172.16.0.15 (172.16.0.15) port 8888 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* [CONN-0-0][CF-SSL] TLSv1.0 (OUT), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Unknown (21):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self-signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Not sure if it is possible, but perhaps disable the certificate validation for the stream in Channels? Or pass the Wyze bridge generated certificates to the Channels app/container?

**Comment by mrlt8** [comment]
How is channels pulling the HLS stream? Does it run as a service that proxies the stream to the app or does the app pull the HLS stream directly?

Either way, you'll probably want the same certificate to persist, so you should probably volume mount the `tokens` directory:
```yaml
volumes:
    - /path/to/save/local/tokens/:/tokens/
```
The bridge should then dump and reuse the certificate and key from there. I believe you should also be able to install and trust the certificate on the device trying to access the LL-HLS stream.


Another alternative would be to generate and pass your own valid certificate to the container with `RTSP_HLSSERVERKEY` and `RTSP_HLSSERVERCERT`.

**Comment by blackthroat** [comment]
Thanks @mrlt8 for the suggestions! I created a feature request on Channels forum, https://community.getchannels.com/t/feature-request-ability-to-add-use-self-signed-certificates-for-hls-streams-in-custom-channels-source/35344

Closing this issue.

**Comment by blackthroat** [comment]
I was able to get the certificate copied and installed on the Channels server, but have a new error:
```
x509: certificate relies on legacy Common Name field, use SANs instead
2023/02/20 00:12:13.795140 [HLS] Couldn't generate stream playlist for ch9340-dANY-ip172.16.0.246: M3U: Could not fetch playlist: wyze-bridge:8888: Get "https://wyze-bridge:8888/living-room/stream.m3u8": x509: certificate relies on legacy Common Name field, use SANs instead
```
@mrlt8 Would it be possible to add an ENV variable to customize and set the SubjectAlternateName (SAN) for when the self-signed certificate is created by the server?

**Comment by blackthroat** [comment]
Pulled the dev branch and verified the ENV variable and subjectAltName both worked as expected:

```
* Server certificate:
*  subject: C=US; ST=WA; L=Kirkland; O=WYZE BRIDGE; CN=wyze-bridge
*  start date: Feb 24 08:38:31 2023 GMT
*  expire date: Feb 21 08:38:31 2033 GMT
*  subjectAltName: host "wyze-bridge" matched cert's "wyze-bridge"
*  issuer: C=US; ST=WA; L=Kirkland; O=WYZE BRIDGE; CN=wyze-bridge
*  SSL certificate verify ok.
```

However, receiving new error in the Channels app:

```
2023/02/24 02:45:07.803644 [ERR] Failed to start stream for ch9416: M3U: Could not fetch playlist: wyze-bridge:8888: Get "https://wyze-bridge:8888/living-room/stream.m3u8": x509: certificate signed by unknown authority
2023/02/24 02:45:07.841480 [HLS] Couldn't generate stream playlist for ch9416-dANY-ip172.16.0.246: M3U: Could not fetch playlist: wyze-bridge:8888: Get "https://wyze-bridge:8888/living-room/stream.m3u8": x509: certificate signed by unknown authority
```

Working with Channels developer now. Going to close this ticket out again. 

Thanks for the quick responses and help with everything!
