### ISSUE TITLE
I think Wyze API went down and caused logs when trying to start container -> ☁️ Fetching 'auth' from the Wyze API -> 🚷 Invalid credentials?

### ISSUE THREAD

**Issue by jamesloper** [mrlt8/docker-wyze-bridge#731]
I've been following the development closely and wanted to try the latest docker image, so after pulling that and killing my existing container, I tried to use the same command but something changed. I was using this command to start:

``` bash
docker run -e WYZE_EMAIL=myemail@gmail.com -e WYZE_PASSWORD=mypassword\$ -p 1935:1935 -p 8554:8554 -p 8888:8888 -p 5000:5000 mrlt8/wyze-bridge:latest
```

The following output was given:

```
2023/03/02 21:10:34 [WyzeBridge] 🚷 Invalid credentials?
2023/03/02 21:10:34 [WyzeBridge] 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
```

Now, hilariously after leaving it on in the background to report this very issue, it just started magically working!

```
2023/03/02 21:13:04 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2023/03/02 21:13:05 [WyzeBridge] 💾 Saving 'auth' to local cache...
2023/03/02 21:13:05 [WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
2023/03/02 21:13:05 [WyzeBridge] 💾 Saving 'user' to local cache...
2023/03/02 21:13:05 [WyzeBridge] 🔍 Could not find local cache for 'cameras'
2023/03/02 21:13:05 [WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
2023/03/02 21:13:06 [WyzeBridge] 💾 Saving 'cameras' to local cache...
```

Now, I was pretty perplexed by this, I think it's possible the Wyze API was simply down. Could there be a preflight check or a HTTP status code check to provide an error message?

**Comment by mrlt8** [comment]
Good point. Should print out the response body on status error now:

`{"description":"Invalid User Name or Password.","requestId":"0000-0000-0000-0000-000","errorCode":1000}`

**Comment by mrlt8** [comment]
Was purposefully using the wrong credentials to test the logic, and noticed that the wyze server now seems to ban your IP after a certain number of failed attempts and will spit out the "Invalid User Name or Password." error even with the correct credentials.

Will get this error when trying to log into `https://auth.wyze.com/` as well:

> Error: This login attempt seems strange. The server has blocked it for security.
