### ISSUE TITLE
Wyze V3 Pan - movement commands take very long (4s) to get response

### ISSUE THREAD

**Issue by csammis** [mrlt8/docker-wyze-bridge#735]
Running v1.11.10 with a Wyze V3 Pan on firmware 4.50.1.3603

When I hit the WebUI's /api/<cameraname>/set_rotary_[up/down/left/right] endpoint the server will take a long time to send the response - usually on the order of four seconds. After the request is sent the camera usually moves right away but the server response doesn't arrive for a while after that. Occasionally the response will return right away with `status: "error"` but then the camera will move anyway. Is this expected behavior? If not, how can I help tune this up? Thanks!

**Comment by mrlt8** [comment]
I believe the set_rotary commands don't actually return any response so most of the time is spent just waiting until it times out.

Will try to see if anything can be done about that.

**Comment by csammis** [comment]
I switched to :dev this evening and tried the set_rotary_* commands, and it's working great! No noticeable delay in any of the commands I sent via Chrome. I'd call this closed 👍
