### ISSUE TITLE
v2.0.0 doesn't start when 2FA is enabled

### ISSUE THREAD

**Issue by benchristian88** [mrlt8/docker-wyze-bridge#741]
Been loving the wyze bridge, and its been working well in portainer, as a stack as per the guides, and upgrading each version using the update stack option.

Attempted the upgrade to version 2.0 and the stack upgrades, pulls new image, containers start, all the env look good, container logs show that the auth can be done with 2fa in the web browser, but there is no UI I can get to.  tried deleting everything, starting again fresh, but nothing. deleted images, pull them again, recreated.  started again. no UI. or no response at all to rtsp either.  like the container is not started, but portainer says it is. 

Using proxmox and portainer running on a lxc.  portainer 2.17.1.  proxmox 7.3-6.  And standard stack script. runing on intel nuc

Any tips on where to look for more logs and what could be wrong.  

rollbacks to 1.11.10 works fine. can access ui on 5000, everything works.

**Comment by dimmanramone** [comment]
I have the same problem. The container seems to be running when I'm looking in the logs, but it seems that the port forwarding stopped working for me. 

Going back to 1.11.10 and works everything as before.

**Comment by JA16122000** [comment]
Same problem overhere ;)
Running in container, but no UI

**Comment by edasque** [comment]
Same here. It seems there is nothing at port 5000 to connect to. The container seems otherwise healthy.

**Comment by terryhonn** [comment]
Chiming in with same issue, thanks for reporting.

**Comment by JEOLeary** [comment]
Same, also cannot connect via console, show "Connecting..." forever.

Logs show the following...
🚀 STARTING DOCKER-WYZE-BRIDGE v2.0.0
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] 🔐 MFA code Required
[WyzeBridge] 💬 SMS code requested
[WyzeBridge] 📝 Enter verification code in the WebUI or add it to /tokens/mfa_token.txt

**Comment by mrlt8** [comment]
Thanks for the heads up. Can confirm. This is not a portainer issue, but a 2FA issue.

The 2FA seems to be blocking Flask from starting up. Will try to get this patched, but you should be able to comoplete the 2FA authentication manually until I can push a fix:
https://github.com/mrlt8/docker-wyze-bridge/wiki/Portainer#two-factor-authentication

**Comment by dimmanramone** [comment]
> Thanks for the heads up. Can confirm. This is not a portainer issue, but a 2FA issue.
> 
> The 2FA seems to be blocking Flask from starting up. Will try to get this patched, but you should be able to comoplete the 2FA authentication manually until I can push a fix: https://github.com/mrlt8/docker-wyze-bridge/wiki/Portainer#two-factor-authentication

Just tried that and didn't work for me

**Comment by terryhonn** [comment]
There's a mistake in the documentation. To copy your 2FA code properly, it needs to be 

`echo "123456" > /tokens/mfa_token.txt`

**Comment by JA16122000** [comment]
i don't use a Portainer whehe

**Comment by mrlt8** [comment]
> There's a mistake in the documentation. To copy your 2FA code properly, it needs to be

Updated - Thanks!

> i don't use a Portainer whehe

https://github.com/mrlt8/docker-wyze-bridge/wiki/Two-Factor-Authentication#docker

**Comment by JA16122000** [comment]
Now Portainer installed.

Al this don't work for me.
https://github.com/mrlt8/docker-wyze-bridge/wiki/Two-Factor-Authentication#docker

Still no UI

**Comment by mrlt8** [comment]
Pushed some changes into v2.0.1 so that the bridge doesn't block Flask from starting if it needs a 2FA code.

Please let me know if you run into any issues!

**Comment by benchristian88** [comment]
can confirm this works now.  thanks very much.   great update!
