### ISSUE TITLE
Upgrade from V3 to V3PRO [Now solved]

### ISSUE THREAD

**Issue by JA16122000** [mrlt8/docker-wyze-bridge#745]
Upgrade from the V3 to the V3PRO

But now i'm getting problems.
"Voortuin" is just a frozen screen
"Achtertuin" won't load at all.

Recording files are now spit out every minute :O 

Any suggestions?
http://j-mulderij.nl:5000/
==
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 5000:5000 # WEB-UI
            - 9997:9997 # Expose port for API
            - 8889:8889 # WebRTC
            - 8189:8189 # WebRTC/ICE
        environment:
            - WYZE_EMAIL=blavlavla
            - WYZE_PASSWORD=Bananana
            - WB_IP=195.240.59.44
            - NET_MODE=ANY
            - FRESH_DATA=True
            - RTSP_API=True
            - TZ=Europe/Amsterdam
            - RECORD_ALL=True
            - RECORD_PATH=/Record/{cam_name}
            - RECORD_FILE_NAME={cam_name}_%Y%m%d_%H_%M_%S
            - RECORD_LENGTH=900
            - LOG_FILE=True
        volumes:
            - /mnt/usbhdd/Record/:/record/
            - ./tokens:/tokens/

==

[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:38] "GET /mfa/873588 HTTP/1.1" 200 -
[WyzeBridge] ✅ Verification code accepted!
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Voortuin [HL_CAM3P]
[WyzeBridge] [+] Adding Achtertuin [HL_CAM3P]
[WyzeBridge] starting rtsp-simple-server v0.21.6
[WyzeBridge] 🎬 2 streams enabled
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Voortuin on 192.168.178.70
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Achtertuin on 192.168.178.69
[voortuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 64%) FW: 4.58.0.3210 🔒 (DTLS) (2/3)
[voortuin] 📹 Will record 900s mp4 clips to /record/voortuin/
[achtertuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.58.0.3210 🔒 (DTLS) (2/3)
[achtertuin] 📹 Will record 900s mp4 clips to /record/achtertuin/
[WyzeBridge] ✅ '/voortuin stream is UP! (3/3)
[achtertuin] WARNING: Wrong resolution (frame_size=4)
Requesting frame_size=3 and bitrate=180
[voortuin] WARNING: Wrong resolution (frame_size=4)
Requesting frame_size=3 and bitrate=180
[achtertuin] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[voortuin] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET / HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /static/site.css HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /static/site.js HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /static/webrtc.js HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /static/loading.svg HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /favicon.ico HTTP/1.1" 404 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /snapshot/achtertuin.jpg?1678962403903 HTTP/1.1" 307 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /static/notavailable.svg HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /snapshot/achtertuin.jpg?1678962403903 HTTP/1.1" 307 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:44] "GET /static/notavailable.svg HTTP/1.1" 200 -
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] ☁️ Pulling "voortuin" thumbnail to /img/voortuin.jpg
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:26:55] "GET /snapshot/voortuin.jpg?1678962403902 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[achtertuin] WARNING: Still waiting for first frame. Updating frame size.
Requesting frame_size=3 and bitrate=180
[voortuin] WARNING: Still waiting for first frame. Updating frame size.
Requesting frame_size=3 and bitrate=180
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] ☁️ Pulling "voortuin" thumbnail to /img/voortuin.jpg
[WyzeBridge] ❌ '/voortuin' stream is down
[voortuin] Stream stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Voortuin on 192.168.178.70
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 195.240.59.44 - - [16/Mar/2023 11:27:04] "GET /snapshot/voortuin.jpg?1678962403902 HTTP/1.1" 200 -
[voortuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 65%) FW: 4.58.0.3210 🔒 (DTLS) (2/3)
[voortuin] 📹 Will record 900s mp4 clips to /record/voortuin/
[voortuin] WARNING: Wrong resolution (frame_size=4)
Requesting frame_size=3 and bitrate=180
[voortuin] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[WyzeBridge] ✅ '/achtertuin stream is UP! (3/3)
[achtertuin] Stream did not receive a frame for over 15s
[WyzeBridge] ❌ '/achtertuin' stream is down
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Achtertuin on 192.168.178.69
[achtertuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.58.0.3210 🔒 (DTLS) (2/3)
[achtertuin] 📹 Will record 900s mp4 clips to /record/achtertuin/
[achtertuin] WARNING: Wrong resolution (frame_size=4)
Requesting frame_size=3 and bitrate=180
[achtertuin] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[voortuin] WARNING: Still waiting for first frame. Updating frame size.
Requesting frame_size=3 and bitrate=180
[achtertuin] WARNING: Still waiting for first frame. Updating frame size.
Requesting frame_size=3 and bitrate=180
[WyzeBridge] ✅ '/voortuin stream is UP! (3/3)
[voortuin] Stream did not receive a frame for over 15s
[WyzeBridge] ❌ '/voortuin' stream is down
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Voortuin on 192.168.178.70
[voortuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 63%) FW: 4.58.0.3210 🔒 (DTLS) (2/3)
[voortuin] 📹 Will record 900s mp4 clips to /record/voortuin/
[voortuin] WARNING: Wrong resolution (frame_size=4)
Requesting frame_size=3 and bitrate=180
[voortuin] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[WyzeBridge] ✅ '/achtertuin stream is UP! (3/3)
[achtertuin] Stream did not receive a frame for over 15s
[WyzeBridge] ❌ '/achtertuin' stream is down
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Achtertuin on 192.168.178.69
[achtertuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.58.0.3210 🔒 (DTLS) (2/3)
[achtertuin] 📹 Will record 900s mp4 clips to /record/achtertuin/
[achtertuin] WARNING: Wrong resolution (frame_size=4)
Requesting frame_size=3 and bitrate=180
[achtertuin] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[voortuin] WARNING: Still waiting for first frame. Updating frame size.
Requesting frame_size=3 and bitrate=180

**Comment by mrlt8** [comment]
hmm, do you mean `IGNORE_RES`? I don't think `FRAME_SIZE=4` would actually do anything..?

Were there any other changes?

**Comment by mrlt8** [comment]
`FRAME_SIZE` is not a valid option, so it shouldn't make a difference if you remove it.

**Comment by JA16122000** [comment]
Damn youre right 🤣

Well, i don't know what i did to get it working.
But, i'm happy now! 😂😉
