### ISSUE TITLE
Wyze Docker Bridge in Home Assistant  - odd error 'ON_DEMAND' does not exist in the schema

### ISSUE THREAD

**Issue by Menz01** [mrlt8/docker-wyze-bridge#748]
i have been seeing this alot in my logs and i am not sure what it means:

 WARNING (MainThread) [supervisor.addons.options] Option 'ON_DEMAND' does not exist in the schema for Docker Wyze Bridge (7094bb28_docker-wyze-bridge)

i have installed this using the addon store in Home Assistant

**Comment by mrlt8** [comment]
ON_DEMAND is on by default now, so the option is no longer needed in the add-on config.

**Comment by Menz01** [comment]
I never configured an add on configured. I just installed the addon from
home assistant addon store and started it

**Comment by mrlt8** [comment]
`ON_DEMAND` was a default option used in previous versions, so may it may have gotten stuck in the configuration for the Wyze Bridge Add-on if you upgraded from a previous version.  You may need to select "Edit in YAML" to remove it if it doesn't go away.
