### ISSUE TITLE
Recordings daytime/nighttime FPS difference

### ISSUE THREAD

**Issue by JA16122000** [mrlt8/docker-wyze-bridge#749]
Hi!

Just upgraded my V3 to the V3 PRO, but now i've got problems with both of my cams.

**Night-time**
Recordings will play in night-time faster (2 seconds, will play fastforward in 1 second)
When i restart the container, it is working fine, till the morning starts.

**Day-time**
Recordings will play slower in day-time (1 second will play slower in 2 seconds)
When i restart the container, it is working fine, till the night starts ....

And so on, and on and on

FPS_FIX=true don't make any difference.

What do i miss?

Allready tried:

FPS_FIX=True
In the wyze-app turn off "night vision mode" so it will not change

Any suggestions what i am missing?

It is only one off the two camera's thats having this problem.
When i recreate the container, it is working fine, till the evening or morning starts.

**Comment by JA16122000** [comment]
It is only one off the two camera's thats having this problem.
When i recreate the container, it is working fine, till the evening or morning starts.

**Comment by mrlt8** [comment]
Hey @JA16122000, I added a couple of commands to adjust the FPS. Could you see if any of these help when the night FPS drops? 
https://github.com/mrlt8/docker-wyze-bridge/blob/0273264fb4c7c96fef46fed665523f9a675bb93a/app/wyzebridge/wyze_control.py#L50-L53

**Comment by JA16122000** [comment]
I will try @mrlt8!

Will this commands, work automatic?
Or do i have, to give this command by hand?

**Comment by mrlt8** [comment]
You'd have to manually send the commands for now. If it works, then we could potentially try to automate the commands if the fps starts to drift.

**Comment by JA16122000** [comment]
How do i do that in portainer?

**Comment by mrlt8** [comment]
https://github.com/mrlt8/docker-wyze-bridge/wiki/Camera-Commands

**Comment by JA16122000** [comment]
FPS are now terrible 🤣 
Even set on 20

**Comment by mrlt8** [comment]
FORCE_ENCODE requires more processing power, so make sure your host can handle the re-encode or utilize a hardware encoder.

Not sure if it would make a difference, but have you tried recording the output from the rtsp stream instead? https://github.com/aler9/mediamtx#save-streams-to-disk

**Comment by JA16122000** [comment]
> FORCE_ENCODE requires more processing power, so make sure your host can handle the re-encode or utilize a hardware encoder.
> 
> Not sure if it would make a difference, but have you tried recording the output from the rtsp stream instead? https://github.com/aler9/mediamtx#save-streams-to-disk

i would love to try that, but i realy don't know how.
Is there someone, hoe can explane to me (in simple language) how to do this in my portainer?

**Comment by mrlt8** [comment]
something like:
```yaml
- MTX_PATHS_CAMNAME_RUNONREADY=ffmpeg -i rtsp://0.0.0.0:8554/camname -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts /record/camname_%Y-%m-%d_%H-%M-%S.ts
```

**Comment by JA16122000** [comment]
> something like:
> 
> ```yaml
> - MTX_PATHS_CAMNAME_RUNONREADY=ffmpeg -i rtsp://0.0.0.0:8554/camname -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts /record/camname_%Y-%m-%d_%H-%M-%S.ts
> ```

![Schermafbeelding 2023-05-14 135929](https://github.com/mrlt8/docker-wyze-bridge/assets/112784196/1d9626c6-9ec4-4d0c-9c6d-c226ecb7a9c1)
 Like this?
 
 It don't get any *.ts file

**Comment by mrlt8** [comment]
You need to specify the CAMNAME in MTX_PATHS_CAMNAME_RUNONREADY with the actual name:
`MTX_PATHS_ACHTERTUIN_RUNONREADY`

**Comment by JA16122000** [comment]
Now the recordings don't mis any frames!
So this is just working fine, except for the switch to nighttime and daytime.
Maybe this is to tweak somehow
