### ISSUE TITLE
Fancy New features BREAKING a Core Function

### ISSUE THREAD

**Issue by capncybo** [mrlt8/docker-wyze-bridge#750]
Been using this project for ages & it's been great.  But IMO the latest release has broken a core function.
Formerly the project could be used to display ALL the Camera snapshots with an adjustable refresh rate in seconds.
The client didn't need any fancy (Built-in) video support whatsoever... it could be a simple browser.
However, latest software seems to require someone manually start each camera individually.
I would assume this was done to minimize bandwidth related complaints.
But some of us used the project for say...
4-5 Cameras to have their snapshots updated every 20-30 seconds.  (Not wanting live streaming, as snapshots are useful enough)
I do understand that streaming codecs are more efficient at transmitting video.
But not every client supports WebRTC or HLS & periodically updated snapshots were actually quite useful.
Is there anyway to replicate the OLD functionality without rolling-back the project version?

**Comment by JA16122000** [comment]
> Note: I re-read the most-recent notes & tried a few things, without success... **Preview refresh interval:** http://localhost:5000/?refresh=30 **NO-LUCK** **autoplay:** http://localhost:5000/?autoplay **NO-LUCK**
> 
> The browser I'm using is: Firefox 110.0 I seem to recall that autoplay may have always broken with this browser. But breaking the Preview interval... is New & Just Plain Sucks ;-( What's the point of logging into something to see (Preview/snapshots) which are... many hrs or even days old? This is what Wyze has always done poorly & what your project "used to do right".

![a](https://user-images.githubusercontent.com/112784196/227014493-d90fec9a-dfeb-435a-9a5b-a85b6f211a7b.png)

Working fine overhere on Firefox

**Comment by terryhonn** [comment]
Yeah, http://wyzebridge:5001/?refresh=30 works fine here for me as well, also on FF:
![image](https://user-images.githubusercontent.com/8404272/227018922-3c3f50a7-c76d-4ed2-acde-eadc9ae84237.png)


Wonder what you're doing wrong?

**Comment by capncybo** [comment]
@JA16122000 & @terryhonn
Unfortunately with v2.0.1 my (Snapshot/Previews) will only download & display on the very 1st launch.
Afterwards, the cameras go offline (Pause symbol) & I have to manually restart them.
But it behaves somewhat erratically, almost like I can only have one snapshot (Play symbol) working at a time.
May I ask:  Which Camera firmware are you people running? (Myself I have been remaining on v4.36.9.139)
 Note: I've been doing so... to keep the following, project working... https://github.com/gtxaspec/wz_mini_hacks
+
I've been compiling the source code locally & running the project on a Raspberry Pi-400
(And doing this has been working on all versions up-to: docker-wyze-bridge-1.11.7 )

I think (perhaps) my-issue resulted from @mrlt8 implementing "ON-Demand ONLY"?
Or perhaps v2.0.1 is finally requiring newer firmware is loaded on the cameras? (But I really don't want to loose wz_mini_hacks)
Any ideas or suggestions?

**Comment by terryhonn** [comment]
Looks like I've got cams that are running 4.28.4.49, 4.36.10.4054, 4.61.0.3, etc.

I wonder if your issues might stem from the code you're compiling yourself. Could you maybe stand up another container with mrlt8's image and see if it makes a difference?
I literally just launch a browser and hit a shortcut to my bridge URL and all my cams show up and refresh automatically like this one:


![chrome_oafQbeE79e](https://user-images.githubusercontent.com/8404272/227284132-a71a4aaa-ba46-4adf-9454-dd1bbe7961bf.gif)

**Comment by capncybo** [comment]
@terryhonn Thank you for your advice. For now (I had to roll-back).  Which works.
But I plan on revisiting this issue with v2.0.1 over the weekend.
Could I please encourage you to share your yaml file? (Obviously first [remove/replace] your email & password)
Unfortunately my yaml config might be what is causing me grief. However I have to keep some advanced ENV variables.
Why? Because my wyze-account actually contains cameras from two different physical locations & networks.
Hence I have to use...
            - FILTER_NAMES=Front Door, Front Yard, alley, garage
Because I  "typically" DO NOT WANT to see my v3-Cams at the Cottage so I was only displaying the three above
And looking at it now... I wonder if perhaps the spaces in the names were causing my issues with v2.0.1?
Hmmm & I also just noticed... 
My default WYZE-account includes a camera which was (**unplugged & offline**), in between
Front Door, Front Yard, alley, garage, **spare**, my CabinCam1 & CabinCam2
As I hinted at above, my set-up might be a little more complex than most

**Comment by mrlt8** [comment]
The issue seems to be caused by the switch to on-demand. 

The WebUI remains mostly unchanged from v1.x, so it will only reload the preview when the bridge has an active connection to the camera (this is to prevent the camera from unnecessarily waking battery cams). 

This shouldn't make a difference for most people since the previews will continue to update as long as you have an active stream.

If you need an image to be generated constantly, one option would be to use the `SNAPSHOT=RTSP` option which can be configured to update the snapshots on an interval.

**Comment by capncybo** [comment]
@mrlt8  I forgot to write back & say thanks for (addressing/resolving) this matter, nice work BTW.
I will be closing this issue.  However I wanted to add the following comment...
-I find the NEW JS-Notifications OVERLY INTRUSIVE, especially on a mobile device
ex) on my cell-phone the (Green/Red) Notifications often Cover-up Half of the Display, & obstruct 1-2 cameras

**SUGGESTION**: Would it be possible for you to add an ENV Variable to Disable the JS-Notifications ?
Otherwise your fix works very well...
I really Like being able to manually specify the refresh time via URL, thanks again.
