### ISSUE TITLE
Substream Quality setting

### ISSUE THREAD

**Issue by mckochan** [mrlt8/docker-wyze-bridge#755]
Would it be possible to add a Quality variable for the sub streams?
SD30 is extremely blocky for me.

I've tried setting QUALITY_CAM_NAME_SUB to SD60 but it didn't work.

Also, sub streams are typically lower fps than main stream. Is it possible to set sub stream to 5fps?

**Comment by mrlt8** [comment]
Been playing around this for a couple of days, and, while we are able to change the FPS on the camera, the changes seems to apply to both the low and high, so having a different FPS on each stream doesn't seem possible, at least with the current firmware.

An interesting side effect is that the changing the FPS seems to affect the overall shutter speed which could potentially be useful to boost the night vision even further.

**Comment by mckochan** [comment]
Awesome, thanks. I could definitely see 10fps being usable to save bandwidth and possibly boost night vision

**Comment by roger-** [comment]
Is there a list of valid quality settings?

**Comment by mrlt8** [comment]
Should be able to go from 1 to 255. I believe the default "SD" option uses 30 on most cams.

**Comment by roger-** [comment]
Thanks. Any pointers on how to set the FPS on substreams to 5?
