### ISSUE TITLE
{Enhancement} Add MQTT siren trigger 

### ISSUE THREAD

**Issue by Travisco29** [mrlt8/docker-wyze-bridge#76]
Would it be possible to add siren functionality for the v3?

**Comment by mrwiwi** [comment]
Would be awesome indeed !

**Comment by Rustymage** [comment]
Did the siren feature ever get exposed for use?

**Comment by mrlt8** [comment]
MQTT still needs a little work, but it should get merged in this pull request: https://github.com/mrlt8/docker-wyze-bridge/pull/593
