### ISSUE TITLE
Unable to see cameras with the same name

### ISSUE THREAD

**Issue by talormanda** [mrlt8/docker-wyze-bridge#760]
I have cameras shared with me that share the same name as my own.

Example: Basement 1, Basement 2. They don't show up in the web UI. Any fix we can add for this? Perhaps having the code automatically rename them upon a fresh install? Basement 1_1 , Basement 2_2?

**Comment by mrlt8** [comment]
Interesting. Will try to take a look into this.

**Comment by talormanda** [comment]
Any idea about this one? Still running into issues.

**Comment by mrlt8** [comment]
This was added in v2.1.5.
