### ISSUE TITLE
What am  I doing wrong?

### ISSUE THREAD

**Issue by lymanc** [mrlt8/docker-wyze-bridge#770]
I have 4 Wyze cams and only cam 1 "Garage Cam" is recognized via docker or home assistant.  The cams listed by model, id, and version are:

  1)  V3, Garage Cam,         4.61.0.3       RTSP = off
  2)  V3. Office Cam 2,         4.36.3.18
  3)  OG, Office Cam,           1.0.63
  4)  V3, Garage Cam SW,   4.36.10.4054 

I have spent numerous hours on this, and can't figure what is wrong.

**Comment by Mr-HaleYa** [comment]
what does your config file look like?

**Comment by lymanc** [comment]
Hum, I am not aware of  any related config file other than docker-compose.yml which works swell for camera 1.  The following is my docker-compose file with email  and password  info removed.

services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935     # RTMP
            - 8554:8554     # RTSP
            - 8888:8888     # HLS
            - 8889:8889     # WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000     # WEB-UI                      
        environment:
            # - WYZE_EMAIL=${WYZE_EMAIL} # Replace with wyze email 
            # - WYZE_PASSWORD=${WYZE_PASSWORD} # Replace with wyze password

**Comment by lymanc** [comment]
Since my last post,  I added another wyze v3 running the same fw as camera 1 in my first post (i.e. 4.61.0.3, rtsp = off) with no joy.  In otherwords, wyze-bridge is not reconizing it along with 3 other cameras.
Also I did a fresh install of wyze-bridge, and again no joy.  Below is my ha-wyze-bridge log file:

[WyzeBridge] 🏠 Home Assistant Mode
🚀 STARTING DOCKER-WYZE-BRIDGE v2.1.0
[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.33.7:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Garage Cam [WYZE_CAKP2JFUS]
[WyzeBridge] starting MediaMTX v0.22.0
[WyzeBridge] 🎬 1 stream enabled
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Garage Cam on 192.168.1.209
[garage-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 64%) FW: 4.61.0.3 (2/3)
[garage-cam] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[WyzeBridge] ✅ '/garage-cam stream is UP! (3/3)

**Comment by mrlt8** [comment]
This is very strange.  Are any of the cams shared or are they all tied to the primary account?

**Comment by lymanc** [comment]
Thank you for responding.  The cams are not shared, and are only tied to my
primary account.  The account is basic i.e. no cam plus addon's.
