### ISSUE TITLE
v2.1.0 - WebRTC stops working

### ISSUE THREAD

**Issue by talormanda** [mrlt8/docker-wyze-bridge#772]
Using docker. After going to v2.1.0, WebRTC stopped working. Not extra changes were made. It just loads endlessly with no picture. HLS seems to be the only feed that works.

I do have ports 8889tcp / 8189udp still added.

![image](https://user-images.githubusercontent.com/10092964/230567386-74e516db-c89d-468d-98dc-94c2415f9132.png)

**Comment by TheMegamind** [comment]
Experiencing this as well.

**Comment by wbarber69** [comment]
same

**Comment by mrlt8** [comment]
Can confirm. Will look into it.

**Comment by mrlt8** [comment]
Seems to be a UDP issue..? switching to TCP seems to work as a temporary solution:
```
    ports:
      - 8189:8189
    environment:
      - MTX_WEBRTCICETCPMUXADDRESS=:8189
```

**Comment by talormanda** [comment]
> environment:
>       - MTX_WEBRTCICETCPMUXADDRESS=:8189

does the documentation mention this anywhere?

**Comment by wbarber69** [comment]
What is that and where do I put it?

Sent from my iPhone

On Apr 9, 2023, at 10:54 PM, mrlt8 ***@***.***> wrote:

﻿

Seems to be a UDP issue..? switching to TCP seems to work as a temporary solution:

    ports:
      - 8189:8189
    environment:
      - MTX_WEBRTCICETCPMUXADDRESS=:8189

**Comment by mrlt8** [comment]
some information here: https://github.com/aler9/mediamtx#usage-inside-a-container-or-behind-a-nat and here: https://github.com/aler9/mediamtx/blob/67741d16dd9256bdcedb43eb207f07d32c199a83/mediamtx.yml#L211-L220

We were previously using the UDP option, but it seems like something changed with the latest version of rtsp-simple-server/mediamtx?

@wbarber69 it would go in your docker-compose.yml for now.

**Comment by wbarber69** [comment]
Using add on so that’s not an option


Sent from my Apple Watch

**Comment by mrlt8** [comment]
Can you try the edge build from the edge repo? https://github.com/mrlt8/edge-repo

**Comment by wbarber69** [comment]
I’ll give it a go when I’m home

Sent from my iPhone

On Apr 10, 2023, at 9:30 AM, mrlt8 ***@***.***> wrote:

﻿

Can you try the edge build from the edge repo? https://github.com/mrlt8/edge-repo

**Comment by talormanda** [comment]
How do I modify the port on the URL of WEBRTC? I am firing up another docker with the edge release, but I need to change the WEBRTC URL because I am already using port 8889 for my main container.

**Comment by talormanda** [comment]
> https://github.com/mrlt8/docker-wyze-bridge/wiki/WebUI#custom-ports
> 
> you'll need to include the hostname or ip as well.

Correct if I'm wrong.

I have WebRTC remapped: 

![image](https://user-images.githubusercontent.com/10092964/231185042-7efca4eb-cfc1-4734-916a-d752c8851842.png)

Then, I have the env variable setup as:

![image](https://user-images.githubusercontent.com/10092964/231185363-aa5f6780-5412-49b2-b03b-8164e5931131.png)

This leads me to:

![image](https://user-images.githubusercontent.com/10092964/231185471-82683748-6556-4169-a98b-cffb1bdb3d2d.png)

**Comment by Menz01** [comment]
i am having the same issues... i go to my WebRTC stream and i get a full screen and a spinning circle but no video. Here's the odd part. i switched to the "Edge" version yesterday and it worked, but today its back to the same thing. i am using the HA Addon so i do not have access to any docker compose entries

**Comment by TheMegamind** [comment]
Any changes to our environment necessary with this release?  Do we remove this now?

`ports:
      - 8189:8189
    environment:
      - MTX_WEBRTCICETCPMUXADDRESS=:8189`

**Comment by talormanda** [comment]
> - MTX_WEBRTCICETCPMUXADDRESS=8189

can someone remind me what this does? i have this set currently.

**Comment by mrlt8** [comment]
https://github.com/aler9/mediamtx/blob/67741d16dd9256bdcedb43eb207f07d32c199a83/mediamtx.yml#L211-L220

> setting this parameter forces usage of the TCP protocol, which is not optimal for WebRTC.

It was a temporary solution until the bug was patched in an upstream dependency.

**Comment by talormanda** [comment]
> https://github.com/aler9/mediamtx/blob/67741d16dd9256bdcedb43eb207f07d32c199a83/mediamtx.yml#L211-L220
> 
> > setting this parameter forces usage of the TCP protocol, which is not optimal for WebRTC.
> 
> It was a temporary solution until the bug was patched in an upstream dependency.

![image](https://user-images.githubusercontent.com/10092964/232096303-e2eb673c-f9c1-4fcb-b2a8-930344aa70d4.png)

this is what happens when I delete MTX_WEBRTCICETCPMUXADDRESS=8189

running v2.1.1

**Comment by mrlt8** [comment]
Do you have the udp port mapped?

`8189:8189/udp`

**Comment by talormanda** [comment]
> Do you have the udp port mapped?
> 
> `8189:8189/udp`

Yup:

![image](https://user-images.githubusercontent.com/10092964/232097850-27d59d6b-4b06-4b76-a5cb-de1e631e1ac5.png)

**Comment by talormanda** [comment]
Correction:

I deleted MTX_WEBRTCICE**UDP**MUXADDRESS = 8189  (note it is UDP).

Do we still leave this one there?

**Comment by mrlt8** [comment]
`MTX_WEBRTCICEUDPMUXADDRESS` is part of the container and gets set during build, so you shouldn't need to set it manually.

**Comment by talormanda** [comment]
> `MTX_WEBRTCICEUDPMUXADDRESS` is part of the container and gets set during build, so you shouldn't need to set it manually.

so it should be in there, and im just getting confused thinking i added it manually?

**Comment by wbarber69** [comment]
My laptop went down recently so I’m waiting for that.  But in my HA app.  Safari on iOS and edge on Xbox I still cannot get webrtc to work.  Only hls.

Sent from my iPhone

On Apr 16, 2023, at 12:06 AM, talormanda ***@***.***> wrote:

﻿

MTX_WEBRTCICEUDPMUXADDRESS is part of the container and gets set during build, so you shouldn't need to set it manually.

so it should be in there, and im just getting confused thinking i added it manually?

**Comment by mrlt8** [comment]
I just installed the Home Assistant app on my iPhone and was able to stream from multiple cameras over WebRTC in the app.

Are you sure you're on the latest version of the bridge?

**Comment by wbarber69** [comment]
The latest version became available 2 minutes after I posted this.  I M able to get my webrtc streams working now.  But they take forever to load.  The video feed acts like it’s starting but then goes blank, extends to the bottom of the page like I long black brick.  Restarts a few times, then tells me it’s playing, but I only see a still image.  Until I click to fulls teen and back.  Then it shows the feed running then after a couple of minutes it’s back to the never ending looping circle if death.

Sent from my iPhone

On Apr 16, 2023, at 9:28 AM, mrlt8 ***@***.***> wrote:

﻿

I just installed the Home Assistant app on my iPhone and was able to stream from multiple cameras over WebRTC in the app.

Are you sure you're on the latest version of the bridge?

**Comment by talormanda** [comment]
WebRTC works but I find at the end of the day, it stops working again and I have to restart the container. @mrlt8

**Comment by wbarber69** [comment]
I’ve tried that too but sadly none of my webrtc feeds are working at all today.

Sent from my iPhone

On Apr 18, 2023, at 1:37 AM, talormanda ***@***.***> wrote:

﻿

WebRTC works but I find at the end of the day, it stops working again and I have to restart the container. @mrlt8<https://github.com/mrlt8>
