### ISSUE TITLE
Cameras starting up in NON-LAN MODE.  Cannot connect

### ISSUE THREAD

**Issue by cryptobrian** [mrlt8/docker-wyze-bridge#78]
Even though I have - LAN_ONLY=True in my docker config, I get the following in the logs with my camera.  

2021/08/15 01:40:04 [Streetview] NON-LAN MODE

Im unable to connect to any cameras.  Removing LAN_ONLY will show the cameras have started up in RELAY mode.   Anyone know what's going on?

**Comment by mrlt8** [comment]
Are the cameras on a separate VLAN?

I've noticed that some cameras will occasionally want to connect in relay mode, but will eventually come back to LAN mode. Have you tried restarting the camera itself?

**Comment by cryptobrian** [comment]
Nope.   Not a separate VLAN.  Have restarted cameras, and router. Still the same.

This didn't happen a few versions ago.  Only noticed this after pulling the latest update. 
Here's some extra info when I try to view the camera w/ on the web

[Sharon Room] NON-LAN MODE
[0/0] [HLS] [remuxer sharon-room] created
[0/0] [HLS] [conn 192.168.0.111:53874] GET /apple-touch-icon-precomposed.png
[0/0] [HLS] [remuxer sharon-room] ERR: no one is publishing to path 'sharon-room'
[0/0] [HLS] [remuxer sharon-room] destroyed

.. I'm also hosting on a Pi, and using the latest Dockerfile.arm 

This is my config file
        build:
            context: ./app
            # Uncomment to build for arm
            dockerfile: Dockerfile.arm
        environment:
            - WYZE_EMAIL=XXXXXXXXXX
            - WYZE_PASSWORD=XXXXXXXXXX
            - LAN_ONLY=True
            - RTSP_PROTOCOLS=tcp
            - RTSP_READTIMEOUT=30s
            - RTSP_READBUFFERCOUNT=8192
            - FRESH_DATA=True

**Comment by cryptobrian** [comment]
RESOLVED.

Renaming, and restarting the camera + docker to pick up the new names seems to have worked.
Very strange.
