### ISSUE TITLE
SSLCertVertification error

### ISSUE THREAD

**Issue by scubieman** [mrlt8/docker-wyze-bridge#781]
Below is error message. Anyways i did run the command "curl -i -X POST https://auth-prod.api.wyze.com/user/login" it said it had 100 tries left. I tried readding integration and restarting HA. Trying different DNS was using cloudflare.  Help please

BB9E Vacuum Kitchen and Back Hallway: Error executing script. Unexpected error for call_service at pos 2: HTTPSConnectionPool(host='[wyze-general-api.wyzecam.com](http://wyze-general-api.wyzecam.com/)', port=443): Max retries exceeded with url: /v1/user/event (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

**Comment by mrlt8** [comment]
I think you're on the wrong repo. This project doesn't use the `wyze-general-api.wyzecam.com` endpoint nor does it support the vacuums.

**Comment by scubieman** [comment]
dangit. Closing lol
