### ISSUE TITLE
Update to v3 of the Wyze API for authentication with Signature2

### ISSUE THREAD

**Issue by mrlt8** [mrlt8/docker-wyze-bridge#793]
Version 2.4x+ of the Wyze app on both Android and iOS seem to have switched the authentication API to v3 which now requires a signature of the request being sent.

The API endpoint we're currently using for authentication (`https://auth-prod.api.wyze.com/user/login`) still seems to be working, but it's probably best if we start switching over to the new one:`https://auth-prod.api.wyze.com/v3/user/login` with the `appid: umgm_78ae6013d158c4a5` and a `Signature2`.

From what I can tell, we need a secret key for the hmac signature, and the secret key seems to be linked to the appid (`umgm_78ae6013d158c4a5` for the v3 login and 2fa).

**Comment by talormanda** [comment]
What can we get for you to assist?

**Comment by chtse53** [comment]
The wyze-bridge cams cannot connect to Wyze cloud server today, even after successful 2fa.  How can we help to make it working again?

**Comment by mrlt8** [comment]
I was able to extract the signing key from the iOS app, so we should be ready to switch to the new api endpoint.

**Comment by MrM-code** [comment]
Wyze has a new security in place to block bots and automation scripts so it is better to use the new API endpoint that they provided in the email.
