### ISSUE TITLE
WYZE_PASSWORD usage

### ISSUE THREAD

**Issue by jslay88** [mrlt8/docker-wyze-bridge#807]
I noticed you are storing the user in a pickle file, and that I am able to still run the container after initial authentication without WYZE_PASSWORD set. 

I also see in the code it uses the refresh token.

Am I right to assume that I no longer need this variable in the container for long term usage, as the refresh token will be used after initial auth?

If so, could the wiki/readme also document this so users can remove the password from the container after initial auth? This would also require mounting a volume to `/tokens` for persistence. 

Or would this just be something all together a use case you would not want to officially support?

**Comment by mrlt8** [comment]
This should be possible starting with v2.2.4
