### ISSUE TITLE
ON_DEMAND w/HA connection timeout

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#809]
@mrlt8 Hello,

Haven't had time to check out the source, so if you have time to answer =D.

Just started using HA, so using that add-on.  When using ON_DEMAND:
 - is the stream started automatically? 
 - is there a timeout, or is the connection held open, forever? ( it seems i have to leave a window open to ensure multiple connections are fast )
 - is there a way to hold a connection to the camera open, indefinitely? 
 - is https for LL-HLS a hard requirement ( for non apple devices )

**Comment by mrlt8** [comment]
- Yes, the streams should auto-start once a client request a stream, however, this can sometimes a few seconds as the bridge needs to establish a connection to the camera which could cause the client to timeout before receiving a frame.
- The default `runOnDemandCloseAfter` is set to 60s, so the bridge will keep the connection open as long as a client is accessing that specific stream and will disconnect from the camera after 60s of inactivity. 
- ON_DEMAND=False will disable the on-demand timer and reconnect if the connection is lost. 
- The `LLHLS` flag will auto enable SSL for maximum compatibility, but you can manually enable LL-HLS in MediaMTX without SSL by adding `hlsVariant=lowLatency` to the `MEDIAMTX` config.

**Comment by gtxaspec** [comment]
thank you!
