### ISSUE TITLE
Add support for different quality sub-streams

### ISSUE THREAD

**Issue by jporter-dev** [mrlt8/docker-wyze-bridge#81]
Aside from defining the quality profile for the bridge to pull from the camera stream, would it be possible to support multiple quality streams per camera? For example, I have `front-door-cam` that is configured to pull the HD stream, but I'd also like to pull the SD or 360p stream for use with a object detection software (it doesn't require the high quality stream, but I'd still like to use the HD stream elsewhere).

Is this currently possible, or feasible to add? I can attempt to dig into the script and add this feature as well.

**Comment by mrlt8** [comment]
Should be possible. I believe you'd need to setup a second av channel for the alternate stream. Not sure how this would affect the stability of the already fragile streams though.

Another option would be to let rtsp-simple-server create a [lower quality stream](https://github.com/aler9/rtsp-simple-server#remuxing-re-encoding-compression).
The benefit of this method, is that you can customize the frame size and rate to meet your needs:
```yaml
- RTSP_PATHS_<MY-CAM-NAME-UPPER>_RUNONPUBLISH=ffmpeg -hide_banner -nostats -i rtsp://0.0.0.0:8554/<my-cam-name-lower> -c:v libx264 -filter:v scale=640:-1,fps=5 -f rtsp rtsp://0.0.0.0:8554/<my-cam-name-lower>-sd
- RTSP_PATHS_<MY-CAM-NAME-UPPER>_RUNONPUBLISHRESTART=yes
```

**Comment by mckochan** [comment]
Above code worked for me, however it maxes out my i5 CPU with 2 cameras resizing. 
If you are using frigate, it is already using ffmpeg to resize any streams and I already have that setup for quicksync hardware acceleration, so it seems like it is easier to just user the HD stream for object detection. Otherwise, you are just passing the buck to this wyze-bridge container and needing to setup hardware acceleration in here.

**Comment by jporter-dev** [comment]
I am using frigate. Is there any additional config needed to set that up for quicksync hardware acceleration? 

I'll go ahead and close this issue since it's a pretty edge use case and probably not suited as a feature for the wyze-bridge container.

**Comment by mckochan** [comment]
See here for quicksync setup (also GPU if you have one)
https://blakeblackshear.github.io/frigate/configuration/optimizing/

My cpu usage definitely goes up in Frigate when switching from SD to HD
streams in wyzebridge, but it is still manageable at ~20% usage.
I am not 100% sure if this is truly the equivalent of having ffpeg resize
within the wyze bridge container, you could try passing the same arguments
on in this container to see if you could get hardware acceleration working.
It would be a nice feature to get both streams coming from the cam if it
can handle it, but yes I agree this is probably not a very popular feature
request.

**Comment by mrlt8** [comment]
Quick update on this.

It seems like this will not be possible with stock firmware and we can only have one type of stream per camera. Adjusting the resolution anywhere seems to change the quality on all the streams - e.g. changing the quality on the app will affect stream we're consuming and vice versa.
