### ISSUE TITLE
pass SUBSTREAM_CAMNAME to homeassistant addon

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#813]
Is it possible to pass the pass SUBSTREAM_CAM_NAME=True to the homeassistant addon to force substreams?

thanks.

**Comment by mrlt8** [comment]
I know it's missing from the documentation, but it should be possible under `Camera Specific Options`:
```
- CAM_NAME: My Camera
  SUBSTREAM: true
```
