### ISSUE TITLE
feature: add support to set rtsp transport to tcp or udp

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#818]
as an ENV variable or to Camera Options in the HA Ui.  

use case:

setting:
```
  - CAM_NAME: cat pod 1
    SUBSTREAM: true
    RTSP_PROTOCOLS: udp
```
`(MainThread) [supervisor.addons.options] Unknown option 'RTSP_PROTOCOLS' for Docker Wyze Bridge (7094bb28_docker-wyze-bridge)`

looks like its not currently supported.

OR 

trying to use a custom ffmpeg command doesnt work in the ha addon ui:

```
- CAM_NAME: cat pod 1
  SUBSTREAM: true
     FFMPEG: >-
    -loglevel fatal -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 64 -analyzeduration 50 -probesize 50 -f H264 -i pipe: -thread_queue_size 96 -f s16le -ar 8000 -i /tmp/{cam_name} -flags +global_header -c:v copy -c:a copy -movflags +empty_moov+default_base_moof+frag_keyframe -muxdelay 0 -muxpreload 0 -map 0:v -map 1:a -async 100 -f tee [f=rtsp:rtsp_transport=udp:bsfs/v=dump_extra=freq=keyframe]rtsp://0.0.0.0:8554/{cam_name}
```
the yaml gets butchered by the UI:

```
    FFMPEG: ""
    "-loglevel fatal -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 64 -analyzeduration 50 -probesize 50 -f H264 -i pipe": >-
      -thread_queue_size 96 -f s16le -ar 8000 -i /tmp/{cam_name} -flags     
      +global_header -c:v copy -c:a copy -movflags     
      +empty_moov+default_base_moof+frag_keyframe -muxdelay 0 -muxpreload 0
      -map     0:v -map 1:a -async 100 -f tee
      [f=rtsp:rtsp_transport=udp:bsfs/v=dump_extra=freq=keyframe]rtsp://0.0.0.0:8554/{cam_name}
```
and then the line is ignored, going back to the tcp transport...

**Comment by mrlt8** [comment]
I don't believe it's possible to switch only one camera to UDP in MTX, so you'll need to use `PROTOCOLS` under the `MEDIAMTX` config in home assistant. 

FYI, The `RTSP_`  has been replaced by `MTX_` a couple of versions ago.

**Comment by gtxaspec** [comment]
ah, got it, this is what i needed.  switching was the preferred solution.

thank you!
