### ISSUE TITLE
Authenication error

### ISSUE THREAD

**Issue by Tech500** [mrlt8/docker-wyze-bridge#820]
I am using my Wyze app account username and password; producing this result:

🚀 STARTING DOCKER-WYZE-BRIDGE v2.1.8

[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.3:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
[WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"37a10caf-f184-43c3-8b59-0fa8bda18dd1","errorCode":1000}
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
[WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"b8864e79-965a-43ee-afa0-320755ca1a6d","errorCode":1000}
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
[WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"5c0e7725-d81a-4dff-a614-8bffa19b535c","errorCode":1000}
[WyzeBridge] Stopping 0 streams
[WyzeBridge] Stopping MediaMTX...
[WyzeBridge] 👋 goodbye!

Do I need two factor authenication turned-on?

Cameras are running Wyse RTSP Firmware.

**Comment by mrlt8** [comment]
Any chance you have a special characters in the username or password? Some characters like `$` may need to be escaped with an extra `$` so `my$ecret` would need to be set as `my$$ecret`.

**Comment by Tech500** [comment]
Yes; special characters was the the issue.  Changed app password to alphanumeric only; worked perfectly.

Thank you; issue resolved.  Please close issue.
