### ISSUE TITLE
Setting Motion Tracking with latest version 2.2.0 does not work with MQTT or API

### ISSUE THREAD

**Issue by crslen** [mrlt8/docker-wyze-bridge#823]
I've tried API and MQTT to set the motion tracking to on or off with no success.  I'm unsure if this is the only one not responding, but I did notice status_light command works when setting the value.

Example command and response:
curl --request POST http://192.168.1.x:5001/api/garage/motion_tracking --data 2
{"command":"motion_tracking","payload":"","response":"1","status":"success","value":"1"}

**Comment by mrlt8** [comment]
Thanks! This should be fixed in v2.2.1
