### ISSUE TITLE
Generic Camera integration - time out...

### ISSUE THREAD

**Issue by airxwing** [mrlt8/docker-wyze-bridge#827]
Hello @mrlt8 , my setup all goes fine until I try to setup the integration using the "Generic Camera" platform.

I have a Wyze Cam v3, not modified (no RTSP firmware).
The bridge Web UI only shows 2 "video streams", WebRTC and HLS. No RTSP or RTMP.
 
<img width="254" alt="image" src="https://github.com/mrlt8/docker-wyze-bridge/assets/75761983/d79c45cb-94c7-4a07-9e7e-89e5036b94a5">

Do I need to flash the rtsp firmware on the Cam v3?

I always get a Time Out error after adding the two URL's for the still image and the stream, in this case I use the HLS because I do not get an RTSP at all.

http://192.168.128.5:5000/img/front-porch-cam.jpg - this one shows no error.
http://192.168.128.5:8888/front-porch-cam/ - **this one show a time out error.**

<img width="266" alt="image" src="https://github.com/mrlt8/docker-wyze-bridge/assets/75761983/61d1c5e8-87d0-4592-bcda-91fb2433c66b">

But, if I use HLS URL http://192.168.128.5:8888/front-porch-cam/ in my browser I can see the live stream with no problems, the WebRTC works as well. So, integration fails...

Any idea what could be wrong? I appreciate the help!

**Comment by mrlt8** [comment]
Hi @airxwing, you'll need to use the RTSP url instead of the HLS url for each camera. e.g., `rtsp://192.168.128.5:8554/front-porch-cam`

**Comment by airxwing** [comment]
> Hi @airxwing, you'll need to use the RTSP url instead of the HLS url for each camera. e.g., `rtsp://192.168.128.5:8554/front-porch-cam`

Thank you, I did that before, funny thing is I use the RTSP url on my browser and did not work, but still use it on the integration and it was timing out, same way as in when using HLS. But, this time it worked!

Thank you again!
