### ISSUE TITLE
Wiki update for MTX options in HA

### ISSUE THREAD

**Issue by CadeMH** [mrlt8/docker-wyze-bridge#829]
[Home-Assistant](https://github.com/mrlt8/docker-wyze-bridge/wiki/Home-Assistant#mediamtx) & [Advanced-Option](https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#mediamtx) need updated under their MediaMTX sections for Home Assistant. They both mention `MEDIA_MTX` instead of `MEDIAMTX`, and neither example has the `mtx_` prefix on the config option.

`Advanced-Option.md` also has an extra `s` at the end of `_readuser` in the HA mention under the MediaMTX section.

Lastly, I think they would benefit from showing an example of the config in YAML mode:

```yaml
MEDIAMTX: 
  - mtx_paths_all_readuser=123
```
---
## Proposed Advanced-Option.md
* 🏠 For Home Assistant:
  Enter each customization into `MEDIAMTX` ("MediaMTX config" on the configuration UI), e.g. use `mtx_paths_all_readuser=123` for `paths: all: readuser:123`.
  
  ```yaml
  MEDIAMTX: 
    - mtx_paths_all_readuser=123
  ```

## Proposed Home-Assistant.md
[MediaMTX](https://github.com/aler9/mediamtx/blob/main/mediamtx.yml) options can be customized by entering each customization into `MEDIAMTX` ("MediaMTX config" on the configuration UI), e.g. use `mtx_paths_all_readuser=123` for `paths: all: readuser:123`.

```yaml
MEDIAMTX: 
  - mtx_paths_all_readuser=123
```

**Comment by mrlt8** [comment]
Thanks. wiki should be updated.
