### ISSUE TITLE
2 factor auth not working

### ISSUE THREAD

**Issue by TristanBrotherton** [mrlt8/docker-wyze-bridge#83]
I have a separate PR for improving the documentation for adding the docker volume. 
however when setting up two factor auth i am getting an error:

```
wyze-bridge    | 2021/08/21 01:40:48 [MainThread] 🔑 Using 63XXX for authentication
wyze-bridge    | 2021/08/21 01:40:48 [MainThread] 🚷 Wrong Code?
wyze-bridge    | 2021/08/21 01:40:48 [MainThread] Error: 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
wyze-bridge    | Please try again!
```

the code shown in the log, is the correct 2FA code.

**Comment by mrlt8** [comment]
Time-based code from an authenticator app? There's a slight delay, so the code may have expired by the time it reached the wyze server.

**Comment by TristanBrotherton** [comment]
It is - I see the code being sent in the log whilst its still valid - I’ll give it 24hrs to see if it was a wyze issue.

**Comment by TristanBrotherton** [comment]
I did some more investigation - it doesn’t appear to be a timing thing, and i verified my credentials didn’t need escaping.  I can setup multiple attempts in the 30s window and it will fail with the same error.

**Comment by mrlt8** [comment]
Can confirm I'm getting the 400 error as well.

Will be looking into this.

**Comment by mrlt8** [comment]
Weird. I just about to debug when it started working again!
```
[MainThread] 🔐 MFA Token (TotpVerificationCode) Required
Add token to /tokens/mfa_token
[MainThread] 🔑 Using 146822 for authentication
[MainThread] 💾 Saving 'auth' to local cache...
```

**Comment by TristanBrotherton** [comment]
I just tried again and same here - working as expected. Must be a Wyze issue? Thanks for looking into it and your work. Super fun project.

**Comment by mrlt8** [comment]
Ok, found the issue! The Wyze API would randomly change the order of the available mfa options, so the script would occasionally send the verification code as `TotpRecoveryCode` instead of the `TotpVerificationCode`. Should be hard coded to use _Verification_ from now on!

**Comment by TycheMoirae** [comment]
Hey there @mrlt8 great work btw. I'm on the latest v0.5.11 but I'm still getting 400 Client Error. It was working two days ago and I didn't change anything since it was working. But I've tried changing network from Bridge to Host and changing LAN only mode. But still receiving invalid credentials error.
