### ISSUE TITLE
Enable timestamps in the log file?

### ISSUE THREAD

**Issue by Gibber** [mrlt8/docker-wyze-bridge#830]
I have Docker Wyze bridge installed as a Home Assistant add-on. I would like to enable timestamps in the log file but I don't see that as an option in the configuration section of the add-on. Is it possible to add timestamps to the log?

**Comment by mrlt8** [comment]
I believe `DEBUG_LEVEL` in the config for the bridge should enable timestamps.

**Comment by Gibber** [comment]
Thanks for the response. 
I enabled the "show unused optional configuration options", scrolled down and clicked the "debug" button and turned on the LOG-FILE switch, and then clicked "save" and accepted the restart but when I went back into the log there are no timestamps and the log shows debug mode off:

[WyzeBridge] 🏠 Home Assistant Mode
🚀 STARTING DOCKER-WYZE-BRIDGE v2.2.2
[WyzeBridge] 📚 Using 'auth' from local cache...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] 📚 Using 'user' from local cache...

If I go back and look at configuration, it is still set to debug mode with LOG-FILE still on.
I also tried  restarting Home Assistant. No change.

**Comment by mrlt8** [comment]
Hmm, you're right. This seems to be broken in the home assistant add-on. 
I believe it's because the logging module gets setup before the config from home assistant. 

Will have to look into this.

**Comment by mrlt8** [comment]
Log related configs in home assistant should be fixed with v2.2.3.

There's also a new `LOG_TIME` option that should enable timestamps without all the additional debug logging.

**Comment by Gibber** [comment]
Works great. Thanks
