### ISSUE TITLE
Stream via RELAY mode

### ISSUE THREAD

**Issue by AndyIsHereBoi** [mrlt8/docker-wyze-bridge#832]
If my logs report "[front-door] 📡 Getting 180kb/s HD stream (H264/15fps) via RELAY mode (WiFi: 94%) FW: 4.9.9.1851 🔒 (DTLS) (2/3)"
does that mean that the camera is connected locally to my server or going over wyze servers? 
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/69745145/0e38e4f6-5f32-4198-997b-df436f23a782)

**Comment by mrlt8** [comment]
Relay and P2P mode go over the internet. Relay mode uses an external server to "relay" the connection whereas P2P and LAN mode connect directly to the camera.
