### ISSUE TITLE
Pterodactyl Panel Egg

### ISSUE THREAD

**Issue by AndyIsHereBoi** [mrlt8/docker-wyze-bridge#844]
I have started to make a Pterodactyl egg for this project, but what is the start command that is initally run within the container to start the server?

**Comment by mrlt8** [comment]
The actual command may change in the future, but can be found in the `Dockerfile`
https://github.com/mrlt8/docker-wyze-bridge/blob/db6cc087f958b0a3918d4e222c049800b175e8b1/app/Dockerfile#L33

**Comment by AndyIsHereBoi** [comment]
thanks
