### ISSUE TITLE
feature reuqest: restart camera via API

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#845]
restart camera via API

I didn't see this in the project yet

i see from https://github.com/mrlt8/docker-wyze-bridge/issues/391#issuecomment-1213675141 that it was determined via the web api not via tutk.  wondering now that api keys are enabled if this is something that can be implemented.

**Comment by mrlt8** [comment]
The new api key only applies to the login endpoint for skipping 2FA and signature checks. 

However, since they are now recognizing third-party API usage, I will definitely look into the possibility of adding some run_actions.

**Comment by gtxaspec** [comment]
Working well,

Thank You!
