### ISSUE TITLE
bug: HA UI still requires email login and password even when using API

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#850]
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/12115272/3bb198e2-bbc4-4be8-8cb9-146929332148)

bug: HA UI still requires email login and password even when using API

**Comment by mrlt8** [comment]
Official documentation seems to indicate that the key and id are an addition to the email and password, not a replacement:
https://support.wyze.com/hc/en-us/articles/16129834216731

**Comment by gtxaspec** [comment]
Ah, I assumed you only needed the API key...
