### ISSUE TITLE
feature request: set quality via api

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#852]
feature request: set quality via api

i see you can set several variables via the API like rotation and fps, etc. 

Perhaps its possible to configure the quality as well.

**Comment by mrlt8** [comment]
Could probably change the "bitrate" or flip the video as they all use the same `K10052` as the FPS, but changing the resolution had some weird side effects in the past.

While it is possible and and used to work, changing the resolution of the stream was causing some issues with certain streams and clients. 

It's part of the reason why the connection take a few extra seconds to start up as the bridge has to wait for the camera to start sending the correct frame size before it can start publishing the h264 stream.

**Comment by gtxaspec** [comment]
working well thank you!
