### ISSUE TITLE
feature request: enable ipv6 support in docker for UDP rtsp connections.

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#855]
currently tcp only:

```
root     2739388  3.7  0.0 1377680 1804 ?        Sl   10:41  16:34 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8554 -container-ip 172.30.33.1 -container-port 8554
root     2739394  0.0  0.0 1377680 1844 ?        Sl   10:41   0:01 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 8554 -container-ip 172.30.33.1 -container-port 8554
```

is it possible to configure the HA add on to support UDP as well for port 8554 via ipv6?

**Comment by mrlt8** [comment]
Does that work?

**Comment by gtxaspec** [comment]
I'll have to do some more digging on this one.  

With the latest update, the docker-proxy process forwarding [::]:8554 to <internal ipv4>:8554 _is_ spawned, but I can't successfully pull an RTSP stream via IPv6.   The client connects, the server responds, and then the connection stalls.

**Comment by mrlt8** [comment]
Hmm, seems like this might be a docker NAT issue which may be resolved using network [host mode](https://github.com/bluenviron/mediamtx#docker-image).

Host mode should be supported in home assistant, but I don't think it's supported on docker-desktop so this option wouldn't work on macOS or windows.

Will try to see if we need to make any tweaks to the container when running in host mode.

**Comment by mrlt8** [comment]
Hey @gtxaspec could you try the `host` build from the [edge-repo](https://github.com/mrlt8/edge-repo) with:

```yaml
MEDIAMTX:
  - MTX_PROTOCOLS=udp
```

**Comment by gtxaspec** [comment]
@mrlt8, confirmed working via ipv6 udp with that edge host build

**Comment by gtxaspec** [comment]
working in latest release! thank you =D
