### ISSUE TITLE
After 2.3.3 Update, webui will not load

### ISSUE THREAD

**Issue by eatonaaron** [mrlt8/docker-wyze-bridge#867]
I just updated to newest version of the bridge and am now getting http 500 errors when trying to load the webui, and pickle errors.
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/55291686/dcc2183d-8340-44a0-9cc8-50b48bcb6e39)

[WyzeBridge] 🏠 Home Assistant Mode
🚀 STARTING DOCKER-WYZE-BRIDGE v2.3.3
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/app/wyze_bridge.py", line 32, in run
    self.api.login(fresh_data=fresh_data)
  File "/app/wyzebridge/wyze_api.py", line 33, in wrapper
    if not (data := pickle.load(pkl_f)):
                    ^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/55291686/34184689-c4df-486c-bf87-22e36f57b64d)

Any ideas on how to fix this?

**Comment by mrlt8** [comment]
Your cached data seems to be corrupt for some reason. The latest version should clear it out if it encounters this error again.

**Comment by eatonaaron** [comment]
perfect thanks!

**Comment by eatonaaron** [comment]
Fixed!
