### ISSUE TITLE
Rtsp/rtmp stream problems 

### ISSUE THREAD

**Issue by wowanco** [mrlt8/docker-wyze-bridge#878]
Using home assistant on pi4 as standalone os and everytime I go to view either rtsp or rtmp streams from my pan cam v2 & pro v3 the connection to wyzebridge either drops or it just block highlights the stream button. ..using default config....any ideas how to fix? Thank you!

**Comment by mrlt8** [comment]
Does setting ON_DEMAND=False help?

**Comment by wowanco** [comment]
temporarily yes it did help...but i was wondering, could it be that my google mini and my alexa both have access to the two cameras and perhaps they are interfering somehow? nevertheless i disconnected them both and the HLS and WebRTC streams work flawlessly but the RTSP & RTMP streams just highlight the button...They all worked when i fist installed the bridge and VLC would open up and would work, so i am somewhat "new" to streaming and "hacking" etc...but ive been a "self-proclaimed" camera/gadget/computer/electronics geek for 40 years or so and, so far, ive yet to fix this minor issue...any other suggestions would be appreciated! Thank you...
