### ISSUE TITLE
Out of range error (email 2FA code related)

### ISSUE THREAD

**Issue by foobarmeow** [mrlt8/docker-wyze-bridge#880]
Using as a Home Assistant Add-on. After upgrading running into this. Have `WYZE_EMAIL` and `WYZE_PASSWORD` set in options. Let me know if I can provide any more info!

```
[WyzeBridge] 🏠 Home Assistant Mode
🚀 DOCKER-WYZE-BRIDGE v2.3.5 
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.33.1:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 🔐 MFA code Required
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/app/wyze_bridge.py", line 31, in run
    self.api.login(fresh_data=fresh_data)
  File "/app/wyzebridge/wyze_api.py", line 46, in wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wyzebridge/wyze_api.py", line 149, in login
    self._mfa_auth()
  File "/app/wyzebridge/wyze_api.py", line 221, in _mfa_auth
    resp = mfa_response(self.auth, TOKEN_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wyzebridge/wyze_api.py", line 310, in mfa_response
    "verification_id": creds.mfa_details["totp_apps"][0]["app_id"],
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by fahaad9** [comment]
I am also facing the same issue. I am running it on docker and then added it on scrypted to be able to view the streams on Homekit.

**Comment by mrlt8** [comment]
Thanks for the report! Looking into this.

Just to confirm, is this for the time-based 2FA?

**Comment by foobarmeow** [comment]
> Just to confirm, is this for the time-based 2FA?

FWIW when I first started using this software (~3 months ago) I didn't need to use any 2FA. Email/pass had worked. 
 
> Was this working in a previous build?

Yeah it only broke after the upgrade. I don't recall which version was the last working. I suspect my working install had the auth information in cache, and the upgrade made that no longer working? 

Thanks for the response!

**Comment by foobarmeow** [comment]
> Do you have your 2FA setup to use email, sms, or an authenticator app?

Email!

**Comment by mrlt8** [comment]
Thanks! We didn't have support for email 2FA so that's what was causing the error!

**Comment by fahaad9** [comment]
> Thanks! We didn't have support for email 2FA so that's what was causing the error!

Thanks @mrlt8 I was able to switch my 2FA to authenticator and bring everything up. good work.

**Comment by mrlt8** [comment]
email 2FA should now be supported in v2.3.6.

FYI, you should be able to skip the 2fa process by using the API_KEY and API_ID from: https://support.wyze.com/hc/en-us/articles/16129834216731

**Comment by fahaad9** [comment]
> email 2FA should now be supported in v2.3.6.
> 
> FYI, you should be able to skip the 2fa process by using the API_KEY and API_ID from: https://support.wyze.com/hc/en-us/articles/16129834216731

Thank you for adding the email 2FA. Unfortunately the api_key and api_id didn’t work for me. The container started and then stopped instantly.

**Comment by mrlt8** [comment]
Can you post any error you see?

**Comment by foobarmeow** [comment]
Thanks so much for the quick fix @mrlt8! 

API_KEY and API_ID also doesn't seem to work for me on HA, FWIW. Don't see any errors in the log. IMO this issue can be closed. 👍

**Comment by mrlt8** [comment]
Looks like API_KEY and API_ID were broken in HA. Should be fixed now!
