### ISSUE TITLE
Unable to update mfa_token.txt

### ISSUE THREAD

**Issue by rutj87** [mrlt8/docker-wyze-bridge#889]
Hi,
I am trying to configure mfa_token.txt to accomodoate 2FA on my Wyze within HA however whenever I update the txt file it gets cleared back to empty.
Any suggestions or rookie mistakes that I might be making?
Thanks in advance

**Comment by mrlt8** [comment]
The verification code gets cleared out on startup to prevent any old codes from accidentally getting submitted. So you'll need to enter the code after initializing the authentication.

Easiest way would be to use the web-ui to submit the code or it can be skipped entirely by creating an API key/id and using that in your config. You can find more details in the wiki: https://github.com/mrlt8/docker-wyze-bridge/wiki/Two-Factor-Authentication#wyze-api-keyid

**Comment by rutj87** [comment]
Thanks - I’ve actually created the api and have been trying to load that in
the mfa_token.txt but that is also what is being cleared.

If I stop the add on, it will hold the details until it starts and then
clears the all the text (api details).

Have followed the steps but clearly missing something given can’t get the
txt file to hold the details

**Comment by mrlt8** [comment]
Again, easiest way to enter the code is to open the web-ui for the bridge where you can enter the code directly.

Are you trying to use the TOTP key to generate a code? You'll need to either set the code in the add-on config or add it to the file `/config/wyze-bridge/totp`

API key/id also need to be set in the add-on configuration. You may need to toggle `Show unused optional configuration options`.

**Comment by melbnz** [comment]
@rutj87 I had the same problem, then came across this issue: By adding the API ID and key to the optional config options i could then see all my cameras!   You don't need to touch the token file
