### ISSUE TITLE
Version 2.3.8 on Unraid 6.12.2 dropped connections

### ISSUE THREAD

**Issue by Nbr1Sniper** [mrlt8/docker-wyze-bridge#890]
Version 2.3.8 on Unraid 6.12.2 is broken. It keeps dropping connection to my cameras. I’ve tried restarting, cache and camera resets within the program. Reinstalling the latest docker container all without a resolution. 

Please help!!!

**Comment by mrlt8** [comment]
Does rolling back to a previous version resolve the issue? 

Most of the recent changes have been related to web authentication, so not sure where the issue might be coming from.

**Comment by Nbr1Sniper** [comment]
> Does rolling back to a previous version resolve the issue?
> 
> Most of the recent changes have been related to web authentication, so not sure where the issue might be coming from.


I haven’t tried to roll back and don’t know how to do it even just I wanted to. Feel like it’s 6.12.2 related but not sure.

**Comment by Nbr1Sniper** [comment]
> Does rolling back to a previous version resolve the issue?
> 
> Most of the recent changes have been related to web authentication, so not sure where the issue might be coming from.

Rolled Unraid back to 6.12.1 and still having issues. Has to be a docker issues or latest bridge update.

**Comment by Nbr1Sniper** [comment]
Suddenly now working…. No idea what is going on…
