### ISSUE TITLE
bug: mqtt invalid value error in logs

### ISSUE THREAD

**Issue by gtxaspec** [mrlt8/docker-wyze-bridge#893]
when res is set to HD255 / SD255,
`Jul 04 01:54:11 haos homeassistant[494]: 2023-07-03 18:54:11.820 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.wyze_cam_test_bitrate: 255 (range 1.0 - 250.0)`

**Comment by mrlt8** [comment]
This should be fixed in the latest version.

**Comment by gtxaspec** [comment]
Working thank you!
