### ISSUE TITLE
Audio possible?

### ISSUE THREAD

**Issue by Alfiegerner** [mrlt8/docker-wyze-bridge#9]
Thanks so much for this. 

Do you know of any way I can get audio to come through?

**Comment by Alfiegerner** [comment]
Here's what I've tried:

Taken a fork of noelhibbard's script and this project, and altered the script as follows:
```
    ffmpeg = subprocess.Popen(['ffmpeg',
        '-f', 'h264',
        '-i', '-',    
        '-acodec', 'copy', 
        '-vcodec', 'copy', 
        '-f','flv', rtmpurl], stdin=subprocess.PIPE)
```
My cloned dockerfile uses the new script where I've tried adding -acodec copy and -acodec aac but no dice.  Tesing using WebRTC of the rtsp stream (in HomeAssitant).

Any suggestions welcome - ffmpeg parameters always manage to throw me off :) .

**Comment by mrlt8** [comment]
@noelhibbard's original script is using [recv_video_data](https://kroo.github.io/wyzecam/reference/iotc_session/#wyzecam.iotc.WyzeIOTCSession.recv_video_data), so you're only going to get raw video out of that.

**Comment by Alfiegerner** [comment]
Thanks @mrlt8, it doesn't look there's any easy way to add that. I'll add a feature request upstream.

**Comment by jplivingston08** [comment]
Awesome container !!! Appreciate all the hard work!  Audio will be a great add if possible. 
thanks !
