### ISSUE TITLE
v2.3.9 throwing errors

### ISSUE THREAD

**Issue by itsamenathan** [mrlt8/docker-wyze-bridge#905]
```
[WyzeBridge] 🏠 Home Assistant Mode
🚀 DOCKER-WYZE-BRIDGE v2.3.9 
 * Serving Flask app 'frontend'
 * Debug mode: off
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.33.8:5000
[WyzeBridge] Press CTRL+C to quit
    self.run()
  File "/app/wyze_bridge.py", line 31, in run
    self.api.login(fresh_data=fresh_data)
  File "/app/wyzebridge/wyze_api.py", line 33, in wrapper
    if not (data := pickle.load(pkl_f)):
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 785, in __setstate__
    _object_setattr(self, '__pydantic_fields_set__', state['__pydantic_fields_set__'])
                                                     ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '__pydantic_fields_set__'
```
I tried adding an api key but that didn't seem to fix it either

**Comment by mrlt8** [comment]
Thanks for the report! 

Could you try running the add-on with the fresh data option set to true?

**Comment by itsamenathan** [comment]
Seems to have worked.  I didn't know that option existed.  Thanks!

**Comment by airsoftsnake** [comment]
had same issue, had to run with fresh data option to get it working...

**Comment by Block141** [comment]
Thanks for the quick solution!

Just doubling down incase anyone might be confused about the fix. 
1.) Stop the add on and go to configuration.
2.) In options click 3 dot menu and select edit in YAML.
3.) Add FRESH_DATA: true to the options.
4.) Click save and then start add on.
You will be prompted to enter your 2FA, but everything should work again.

**Comment by mclever** [comment]
I used the option to pull fresh data from wyze API in configuration of addon and it worked as well

**Comment by mattaran** [comment]
Adding the FRESH_DATA option to configuration worked for me as well. I am not using Waze 2FA in this installation.

**Comment by Dudesky1325** [comment]
Had the exact same issue and the above fix worked instantly. Also mentioned above, delete that line when you're done.
