### ISSUE TITLE
Cannot get audio to work

### ISSUE THREAD

**Issue by dom8925** [mrlt8/docker-wyze-bridge#910]
I have enabled audio in my environment
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/18646706/c0376a6c-11c3-435b-b831-d374a8a96f51)
but I have no audio in any of the different streams and the information for my camera on the WebUI says audio is no 
![image](https://github.com/mrlt8/docker-wyze-bridge/assets/18646706/cb32ba01-8104-422c-a1b7-44cb901dde6b)
What else can I do to get audio from my cameras? I tried without specifying a particular camera and also adding the line for one of my cameras but it did not make a difference.

**Comment by mrlt8** [comment]
That should work. Can you try running `docker-compose down && docker-compose up`

**Comment by dom8925** [comment]
Unrelated to this issue, I rebooted the VM where I have this setup a couple of times today. I still have no audio

**Comment by mrlt8** [comment]
There's a chance docker might be using the old config, so manually restarting the container may help.

**Comment by JA16122000** [comment]
Typo in your environment 

The D and U 
![huh](https://github.com/mrlt8/docker-wyze-bridge/assets/112784196/c3b9bc3a-f119-4dbd-8ca6-324ce9b798f1)

**Comment by dom8925** [comment]
That will eo
