### ISSUE TITLE
LAN mode only (no internet)

### ISSUE THREAD

**Issue by Nirvanatin** [mrlt8/docker-wyze-bridge#917]
Is it possible to access the RTSP feed of Wyze v3 or the pro version cameras in offline modes, where they are connected to a LAN without internet access?

**Comment by mrlt8** [comment]
It may work temporarily, but rebooting the camera seems to require an internet connection. It used to work in the past, but wyze has been making the cameras more cloud dependent and it would require firmware level modification on the camera itself just to get the camera to boot normally. 

See: https://github.com/gtxaspec/wz_mini_hacks/wiki/Configuration-File#self-hosted--isolated-mode

**Comment by Nirvanatin** [comment]
Thank you. Can the camera typically operate without requiring a reboot for at least 30 days, on average? This will help me get a rough estimation of its expected performance.

**Comment by mrlt8** [comment]
I personally haven't done any network isolation tests, so can't really answer. 

As for downgrading to a firmware that can potentially operate without an internet connection, it would probably have to be pre-DTLS encryption? Potentially as far back as the xnor.ai firmware which means pre v3.
