### ISSUE TITLE
Still having 403 Client Errors even when using API_ID and API_KEY

### ISSUE THREAD

**Issue by mnord222** [mrlt8/docker-wyze-bridge#931]
Have generated API_ID and API_KEY from Wyze's website and updated my docker-compose.yml file accordingly, but continue to get the 403 Client Error.  As far as I know, I do not have a VPN running.

**Comment by mrlt8** [comment]
Your IP/ISP is probably blacklisted by the aws/cloudfront firewall. 

See #876 @iamwoz was able to contact wyze support to have them clear the IP from WAF.

**Comment by mnord222** [comment]
Thanks for the help.  Turns out, I had not pulled the proper version.  Dumbsh*t.
