### ISSUE TITLE
bridge no longer works, gives 403 error before shutting down.

### ISSUE THREAD

**Issue by Xeddius** [mrlt8/docker-wyze-bridge#940]
🚀 STARTING DOCKER-WYZE-BRIDGE v2.2.1

[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] Configuring LL-HLS
[WyzeBridge] 🔐 Generating key for LL-HLS
[WyzeBridge] 🔏 Generating certificate for LL-HLS
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.7:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] ⚠️ 403 Client Error: Forbidden for url: https://auth-prod.api.wyze.com/user/login
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] ⚠️ 403 Client Error: Forbidden for url: https://auth-prod.api.wyze.com/user/login
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] ⚠️ 403 Client Error: Forbidden for url: https://auth-prod.api.wyze.com/user/login
[WyzeBridge] Stopping 0 streams
[WyzeBridge] Stopping MediaMTX...
[WyzeBridge] 👋 goodbye!

**Comment by mrlt8** [comment]
Please update your bridge to the latest version. 

Wyze has made some changes to their API which has been patched in v2.3+ of the bridge.

**Comment by Xeddius** [comment]
Did a complete removal and re-install, this fixed it 👍🏻 Thank you.
