### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by drewski56** [mrlt8/docker-wyze-bridge#943]
Hi!
I've been getting a permission error with docker-compose up. I've done sudo apt update and sudo apt upgrade, fully stopped docker, docker rm wyze-bridge, docker-compose down but everything time I try to get this up and running I'm getting the same error. Apologies if this isn't related specifically to wyze-bridge, but both homeassistant and frigate are running fine. 

Thanks!

wyze-bridge    | Traceback (most recent call last):
wyze-bridge    |   File "/usr/local/bin/flask", line 5, in <module>
wyze-bridge    |     from flask.cli import main
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 1, in <module>
wyze-bridge    |     from . import json as json
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/json/__init__.py", line 6, in <module>
wyze-bridge    |     from ..globals import current_app
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/globals.py", line 6, in <module>
wyze-bridge    |     from werkzeug.local import LocalProxy
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/werkzeug/__init__.py", line 1, in <module>
wyze-bridge    |     from .serving import run_simple as run_simple
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 32, in <module>
wyze-bridge    |     from ._internal import _log
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/werkzeug/_internal.py", line 3, in <module>
wyze-bridge    |     import logging
wyze-bridge    |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
wyze-bridge    |     _startTime = time.time()
wyze-bridge    |                  ^^^^^^^^^^^
wyze-bridge    | PermissionError: [Errno 1] Operation not permitted

**Comment by mrlt8** [comment]
hmm, could be related to [libseccomp2](https://github.com/mrlt8/docker-wyze-bridge/wiki/Raspberry-Pi-(armv7-and-arm64)#libseccomp2)? #97 #909

**Comment by drewski56** [comment]
Amazing, thanks. I did have to wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1~bpo10+1_armhf.deb, not the one listed for some reason. Either way, it's working now, thank you so much for the help! Loving this tool and amazed at your quick response on this.
