### ISSUE TITLE
Wyze-Bridge List Detected 6 cameras, but only 5 cameras show up in web interface

### ISSUE THREAD

**Issue by guocity** [mrlt8/docker-wyze-bridge#947]
Wyze-Bridge List Detected 6 cameras, but only 5 cameras show up in web interface

**Comment by guocity** [comment]
I find out why, two cameras have the same name,

**Comment by JA16122000** [comment]
Restarting your bridge, will do the trick ;)

**Comment by guocity** [comment]
ok, now i add 
  - SUBSTREAM=True
 3 cameras have substream, and 3 cameras don't have substream
rebuild, restart don't do the trick :(

**Comment by mrlt8** [comment]
substream is only supported on newer firmware.
