### ISSUE TITLE
v2.3.14 Cameras detected but not shown

### ISSUE THREAD

**Issue by Jazza159** [mrlt8/docker-wyze-bridge#954]
I updated to v2.3.14 this morning and the web interface reports my cameras 8 cameras are detected however they do not load in the web interface and the RTSP and snapshot links do not function.

There is nothing unusual in my logs, the four cameras that I have set up in home assistant are pulling the thumbnails every 10 seconds as expected. However nothing updates in home assistant and they do not display in the web interface,

I have reviewed the logs and tried restarting several times to see if there are any changes.

![image](https://github.com/mrlt8/docker-wyze-bridge/assets/96936843/3045afb4-d8d3-4a9f-b37c-711df12debdc)

```
[WyzeBridge] ☁️ Pulling "street-cam" thumbnail to /img/street-cam.jpg
[WyzeBridge] ☁️ Pulling "garage-cam" thumbnail to /img/garage-cam.jpg
[WyzeBridge] ☁️ Pulling "hangar" thumbnail to /img/hangar.jpg
[WyzeBridge] ☁️ Pulling "driveway-cam" thumbnail to /img/driveway-cam.jpg
[WyzeBridge] 192.168.20.169 - - [08/Aug/2023 09:29:57] "GET /snapshot/street-cam.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.20.169 - - [08/Aug/2023 09:29:57] "GET /snapshot/garage-cam.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.20.169 - - [08/Aug/2023 09:29:57] "GET /snapshot/driveway-cam.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.20.169 - - [08/Aug/2023 09:29:57] "GET /snapshot/hangar.jpg HTTP/1.1" 200 -
```

Thanks!

**Comment by mrlt8** [comment]
Were the cameras working in a previous version? The cameras seem disabled/filtered out for some reason. Can you try hitting restart and clear the cache?

**Comment by Jazza159** [comment]
They were working previoulsy.
Restart and clear the cache worked a charm.
Sorry for wasting your time!
I tried in Firefox and edge before posting here and it displayed the same as chrome so I assumed clearing the browser cache would not make a difference. Restart and clear the cache got them all back.

Thanks for your support 🙏
