### ISSUE TITLE
Dozens of Python processes getting created and maxing out CPU/RAM

### ISSUE THREAD

**Issue by AdamGGeil** [mrlt8/docker-wyze-bridge#962]
When running this image, I'm encountering an issue where dozens and dozens of Python processes are being created over time, and they are maxing out my CPU and RAM. This ultimately ends up crashing my machine.

I'm pretty new to docker, so I'm not sure how to proceed.

**Comment by mrlt8** [comment]
Can you post some more info re: your host and your docker-compose.yml?

**Comment by AdamGGeil** [comment]
@mrlt8 below is my docker-compose.yml (email and pw info removed). My host is a Windows machine, AMD Ryzen 5, 16 GB RAM.

Please let me know if you'd like more info.

`version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLSa
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] (Can be set in the WebUI):
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            # [OPTIONAL] Wyze API credentials:
            # - API_ID=
            # - API_KEY= `

**Comment by mrlt8** [comment]
Everything seems fine. Can you make sure you have the latest version of docker and docker compose? There were some issues with UDP traffic in a couple of older versions.

**Comment by AdamGGeil** [comment]
@mrlt8 looks like there's an update for docker available (4.21.1 > 4.22.0). I'll install the update, let it run overnight, and then report back.

**Comment by AdamGGeil** [comment]
@mrlt8 unfortunately, the issue persists after updating docker.

**Comment by mrlt8** [comment]
can you post which process/thread is using up all the cpu/ram?

**Comment by AdamGGeil** [comment]
It's actually hundreds of Python processes taking up a fraction of a percentage of CPU/RAM that, combined, were taking up all of the CPU/RAM. I'd be happy to provide more info, but I may need more instruction on what specific info you need/would be helpful.

**Comment by mrlt8** [comment]
can you run `docker stats`?

**Comment by AdamGGeil** [comment]
@mrlt8 sorry for the delay getting back to you. I started having other issues with docker after the most recent update. I suspect the issue was with my machine. 

I need to rebuild that machine, so I decided to pivot and buy a raspberry pi to run docker. That's working great, so I'm going to close out this issue.

I appreciate you assisting in investigating the issue. Thank you!
