### ISSUE TITLE
wyzebridge add-on won't start in home assistant

### ISSUE THREAD

**Issue by droidsteve** [mrlt8/docker-wyze-bridge#966]
installed and configured. 2FA not enabled, click start and get the following log entry, the add-on does not start

[WyzeBridge] 🏠 Home Assistant Mode
🚀 DOCKER-WYZE-BRIDGE v2.3.15 
[WyzeBridge] 📚 Using 'auth' from local cache...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] 📚 Using 'user' from local cache...
[WyzeBridge] 📚 Using 'cameras' from local cache...
[WyzeBridge] [+] Adding Garage Cam [WYZEC1-JZ]
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.33.9:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] [+] Adding Living Room Cam [WYZECP1_JEF]
[WyzeBridge] starting MediaMTX 1.0.0
[WyzeBridge] 🎬 2 streams enabled

Home assistant running in VM on Proxmox:
Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.1 - latest

**Comment by mrlt8** [comment]
it seems to be working. Can you visit the `http://<home assistant IP>:5000`?

**Comment by droidsteve** [comment]
wow, that worked, but clicking the link on the HA menu, it does not.

**Comment by mrlt8** [comment]
May need to disable on_demand in the add-on config for the bridge?
