### ISSUE TITLE
Per camera snapshot settings for indoor/outdoor camera mix?

### ISSUE THREAD

**Issue by timnovinger** [mrlt8/docker-wyze-bridge#970]
I have a mixture of outdoor cameras and non-battery cameras in my setup. For the indoor cameras, it's great having them use an RTSP interval setting; however, even the longest available option in the HomeAssistant config (RTSP300) will quickly kill the outdoor cameras within about a day.

Is it possible to have those outdoor cameras pulling the snapshot from the API while having the indoor/wired cameras grabbing their snapshots via RTSP?

Or alternatively, could we get new options to define even longer custom RTSP intervals within the HomeAssistant settings?

**Comment by mrlt8** [comment]
Will look into this.

**Comment by timnovinger** [comment]
> Is it possible to have those outdoor cameras pulling the snapshot from the API while having the indoor/wired cameras grabbing their snapshots via RTSP?

Or, I just realized, as another idea....could the outdoor cameras periodically poll the API for an updated snapshot at the same interval as whatever is set for RTSP? When motion events trigger, if I'm not mistaken, the snapshot on the Wyze end updates. If that's the case, it'd be awesome to poll the API often-ish to so those snapshot images are somewhat current yet not battery draining.

Thanks for looking into this!

**Comment by mrlt8** [comment]
You might want to try out the dev branch which currently has motion events that can be enabled with `MOTION_API=true`.

Will try to see if we can update the snapshot url when an event is detected.

**Comment by TheRealWaldo** [comment]
I have just run into this; the battery was killed on all my outdoor cameras.  Would love to see a solution!

**Comment by mrlt8** [comment]
motion events was added back in v2.4.0: https://github.com/mrlt8/docker-wyze-bridge/wiki/Camera-Motion

**Comment by TheRealWaldo** [comment]
Got that, doesn't seem to matter.  No motion has happened but the battery is dead.

**Comment by TheRealWaldo** [comment]
Settings are snapshot mode: API, and MOTION_API on,  and the battery drained.  I also tried ON_DEMAND on, but this stops snapshots from appearing in Home Assistant entirely.

Also, with snapshot mode to API, I don't get my non-battery cameras updated on a regular interval.

**Comment by mrlt8** [comment]
ON_DEMAND shouldn't affect battery cams, so I believe you can leave it off.

You can trigger a snapshot on demand by using:
```
http://localhost:5001/snapshot/<cam-name>.jpg
```
or use the `thumb` endpoint to grab the latest thumbnail from the API:
```
http://localhost:5001/thumb/<cam-name>.jpg
```
the `thumb` endpoint should update if you have `MOTION_API` on.

**Comment by mrlt8** [comment]
Do you have the motion detection active on the camera? The thumbs should get updated when the camera detects motion and pushes that to the cloud.
