### ISSUE TITLE
unable to recover from going into privacy mode?

### ISSUE THREAD

**Issue by illspirit** [mrlt8/docker-wyze-bridge#971]
Whenever I set privacy mode on the wyze app the wyze-bridge disconnects and it appears I need to restart the container.

Is this a known issue?

**Comment by mrlt8** [comment]
Privacy mode will "power off" the camera. You'll need to power on the camera via the web-ui or the api/mqtt:
```
http://<bridge-ip>:5000/api/<cam-name>/power/on
```

see this page for additional info on sending commands to the camera: https://github.com/mrlt8/docker-wyze-bridge/wiki/Camera-Commands

**Comment by illspirit** [comment]
Thank you!
