### ISSUE TITLE
Camera's are a bit slow I think it's the Bridge being slow.

### ISSUE THREAD

**Issue by KaneHart** [mrlt8/docker-wyze-bridge#978]
So I had just 4 camera's all Lan, but I set another 2 remotely and removed Lan option as it did not seem to work. Since then my Camera's some of them can have a 30 even 60 second delay it's quite insane and those the ones locally... No I'm not eating up my CPU or anything it's just really delayed haha.

**Comment by mrlt8** [comment]
Do you have audio enabled?

**Comment by mrlt8** [comment]
There are some audio related changes in the dev branch which may help.

**Comment by KaneHart** [comment]
Thank you, I will check that out I don't mind testing :)
