### ISSUE TITLE
Wyze Cam v3 stops working after 3 minutes

### ISSUE THREAD

**Issue by VerityNH** [mrlt8/docker-wyze-bridge#99]
Hello,

**Environment** 
![image](https://user-images.githubusercontent.com/51718614/131674513-efa598f0-2960-408d-88c7-fdf628f405d2.png)

**Network:**
- Router: Netgear RAX 120
- WiFi: Dual mode 2.4 and 5 

Wyze Firmware: 4.36.3.19

**Steps to reproduce:**

- Install wyze bridge
- Open a link to any type of stream for Wyze Cam v3

**Actual result:**
You can see the stream, but in about 3-5 minutes it becomes dead.

Expected result: 
Stream is persistent

**Workaround:**
Restart Wyze Cam, this helps for another 3-5 minutes

**Logs:**
```
2021/09/01 13:02:07 I [2/2] [RTMP] [conn 172.17.0.1:56892] opened,
2021/09/01 13:02:11 I [2/2] [RTMP] [conn 172.17.0.1:57388] closed,
2021/09/01 13:02:11 I [2/2] [RTMP] [conn 172.17.0.1:57388] opened,
2021/09/01 13:02:11 I [2/2] [RTMP] [conn 172.17.0.1:57388] ERR: no one is publishing to path 'wyze-cam-3',
2021/09/01 13:02:20 I [2/2] [RTMP] [conn 172.17.0.1:58848] ERR: no one is publishing to path 'wyze-cam-3',
2021/09/01 13:02:20 I [2/2] [RTMP] [conn 172.17.0.1:58848] closed,
2021/09/01 13:02:23 I [2/2] [RTMP] [conn 172.17.0.1:59348] opened,
2021/09/01 13:02:23 I [2/2] [RTMP] [conn 172.17.0.1:59348] ERR: no one is publishing to path 'wyze-cam-3',
2021/09/01 13:02:23 I [2/2] [RTMP] [conn 172.17.0.1:59348] closed,
2021/09/01 13:02:26 I [2/2] [RTMP] [conn 172.17.0.1:59828] closed,
2021/09/01 13:02:35 I [2/2] [RTMP] [conn 172.17.0.1:60884] ERR: no one is publishing to path 'wyze-cam-3',
2021/09/01 13:02:35 I [2/2] [RTMP] [conn 172.17.0.1:60884] closed,
2021/09/01 13:02:35 I [2/2] [RTMP] [conn 172.17.0.1:60884] opened
```

**Comment by mrlt8** [comment]
Is it just the one camera and does the stream eventually come back? 
Your logs show 2 other streams open - are those unaffected?

**Comment by VerityNH** [comment]
Yes, this only happens to v3 camera, two v2 cameras are not affected

**Comment by VerityNH** [comment]
Restarting container also helps for a bit

**Comment by mrlt8** [comment]
Does the stream come back if left alone? It _should_ try to reconnect if the connection is lost.

**Comment by VerityNH** [comment]
No, it never comes back

**Comment by mrlt8** [comment]
I believe rtsp-simple-server is closing the connection while ffmpeg is still active, so the stream never gets restarted..
Could you try editing the ENV on your container and changing the `RTSP_READTIMEOUT` value to `60s` to see if that helps?

**Comment by VerityNH** [comment]
[_wyze-bridge_logs (4).txt](https://github.com/mrlt8/docker-wyze-bridge/files/7092908/_wyze-bridge_logs.4.txt)
Unfortunately this does not help, attaching some debug level logs

**Comment by chimcanhcut1112** [comment]
oops, i have same issue, but i restart wyze v3, it's work again.
lastest firmware/

**Comment by chimcanhcut1112** [comment]
> Does it also drop at 3 min? Could you post your firmware versions and the connection mode? It should say something like Starting ... in "LAN mode" or "Relay mode"

not in 3 minutes, but 10-30 minutes, some time, i use lan-mode, restart wyze in app wyze, work fine. i'm use lastest version.

**Comment by bartekd123** [comment]
I receive this issue too, sometimes after an hour or 2, sometimes after many hours, but only when I block internet from the network that the camera connects to. The camera should continue to work when you have local only set, and turn off internet from the camera, right?

**Comment by mrlt8** [comment]
Theoretically, yes, it should work without internet. BUT, I think the cameras likes to phone home every now and then, as well as to push motion notifications etc, which could cause the camera behave irregularly?

**Comment by bartekd123** [comment]
Yea, figured thats it, thanks. Thought I would mention that just in case others are blocking internet and seeing the same behaviour.

**Comment by mrlt8** [comment]
Have you tried [disabling motion detection](https://github.com/mrlt8/docker-wyze-bridge/issues/2#issuecomment-871847901) on the camera before putting the cams offline? That should reduce some if not most of the connection attempts.

**Comment by bartekd123** [comment]
haven't tried, but thanks for the suggestion, Ill give it a shot.

**Comment by backslashV** [comment]
Having the same issue on both local and non local v3 cams.

**Comment by VerityNH** [comment]
Tried this out - the issue is still there.
Also, potential regression introduced on Wyze V3 cam only - 
![image](https://user-images.githubusercontent.com/51718614/132528410-5381dc89-39a6-4ecb-8a57-13515dd1864b.png)

**Comment by mrlt8** [comment]
could you try with `DEBUG_FRAMES=true`?

**Comment by VerityNH** [comment]
Tested 0.6.4 - regression is gone

**Comment by gleep52** [comment]
I have 4 v3 cams on firmware listed in readme (4.36.3.19 (August 26, 2021)) and do not have a single problem.  I have motion detection, notifications, and anything else disabled.  I stream this to blue iris for deep stack analysis on motion detection and also pulling a second stream for beta testing scrypted.app for HomeKit video.

**Comment by VerityNH** [comment]
Confirmed that when using docker-composer the issue is not reproducible.

Still can easily reproduce when using portainer stack. Updating the issue title

**Comment by VerityNH** [comment]
Spoke too fast.. failed after 7 minutes

**Comment by vabajaa** [comment]
Experiencing this issue right now, all my V3 cams drop offline constantly and require a docker restart to fix for about 10-15min. (If it helps, they sometimes pick up again but after a good 4-5 hours and break again soon after)

**Comment by mrlt8** [comment]
Could be some WiFi interference from a neighboring network. I've noticed some connection issues when a neighbor's AP auto selects an overlapping WiFi channel.

**Comment by VerityNH** [comment]
@gleep52 the other two cameras are v2 cams and yes - they are working without any issues.
I don't see any issues with a network - no package loss

**Comment by gleep52** [comment]
Then that is definitely a problem with wyze-bridge I'd guess.  I would still recommend reflashing the firmware just to be sure - but I guess this confirms the camera is up and wyze-bridge loses connection only.  That's an issue for @mrlt8  to look into.  Sorry :(
