### ISSUE TITLE
wyze-bridge keeps restarting

### ISSUE THREAD

**Issue by sgtstadanko** [mrlt8/docker-wyze-bridge#994]
Using the sample docker-compose.yml, the wyzebridge just keeps restarting and i can never get into the webui - 

Creating network "docker-wyze-bridge_default" with the default driver
Creating wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 
wyze-bridge    | 🚀 DOCKER-WYZE-BRIDGE v2.3.17 
wyze-bridge    | 
wyze-bridge    | Traceback (most recent call last):
wyze-bridge    |   File "/usr/local/bin/flask", line 8, in <module>
wyze-bridge    |     sys.exit(main())
wyze-bridge    |              ^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 1064, in main
wyze-bridge    |     cli.main()
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
wyze-bridge    |     rv = self.invoke(ctx)
wyze-bridge    |          ^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
wyze-bridge    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
wyze-bridge    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
wyze-bridge    |     return ctx.invoke(self.callback, **ctx.params)
wyze-bridge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
wyze-bridge    |     return __callback(*args, **kwargs)
wyze-bridge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
wyze-bridge    |     return ctx.invoke(f, obj, *args, **kwargs)
wyze-bridge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
wyze-bridge    |     return __callback(*args, **kwargs)
wyze-bridge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 912, in run_command
wyze-bridge    |     raise e from None
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 898, in run_command
wyze-bridge    |     app = info.load_app()
wyze-bridge    |           ^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 309, in load_app
wyze-bridge    |     app = locate_app(import_name, name)
wyze-bridge    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 236, in locate_app
wyze-bridge    |     return find_best_app(module)
wyze-bridge    |            ^^^^^^^^^^^^^^^^^^^^^
wyze-bridge    |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 64, in find_best_app
wyze-bridge    |     app = app_factory()
wyze-bridge    |           ^^^^^^^^^^^^^
wyze-bridge    |   File "/app/frontend.py", line 38, in create_app
wyze-bridge    |     wb.start()
wyze-bridge    |   File "/usr/local/lib/python3.11/threading.py", line 957, in start
wyze-bridge    |     _start_new_thread(self._bootstrap, ())
wyze-bridge    | RuntimeError: can't start new thread

**Comment by sgtstadanko** [comment]
I have tried putting wyze email and pass in quotes as well as my api keys

**Comment by mrlt8** [comment]
I believe you need to update docker and/or libseccomp2 on your host. See #909 #959

**Comment by sgtstadanko** [comment]
i am the latest available in the repos. Do you know what version it needs to be?

**Comment by sgtstadanko** [comment]
Ok latest issue solved by searching around here. Issue was special char in password in yaml file.  Even though i tried escaping with quotes and \ to no avail. Changed password in app and then in file and now started.

**Comment by mrlt8** [comment]
hmm, not sure why you're getting an internal error. Is your api key/id correct? Can you try removing the key and ID so that the bridge will use the older auth api?

**Comment by sgtstadanko** [comment]
Thanks!
