### ISSUE TITLE
Garage Door Support

### ISSUE THREAD

**Issue by jfarmer08** [mrlt8/docker-wyze-bridge#997]
@mrlt8 You can add support for opening and closing the garage support if you feel like it would be needed. Using the API you would use the RunAction Cmd with 'garage_door_trigger' as the actionKey. If the door is open it will close it and if closed it will open it. I am still working on detecting the state of the door. 

I could add it, but not sure where to start with this project. 

https://github.com/jfarmer08/wyze-api/blob/main/src/index.js#L777

**Comment by mrlt8** [comment]
Accessories are not supported yet, but will keep this in mind!
